### ISSUE TITLE
[Bug] Check failed: `sampled_index >= 0`

### ISSUE THREAD

**Issue by love-xunmeng** [mlc-ai/mlc-llm#1073]
## 🐛 Bug

Traceback (most recent call last):
  File "examples/python/sample_mlc_chat.py", line 13, in <module>
    output = cm.generate(
  File "/Users/miniconda3/envs/mlc/lib/python3.8/site-packages/mlc_chat/chat_module.py", line 762, in generate
    self._prefill(prompt, generation_config=generation_config)
  File "/Users/miniconda3/envs/mlc/lib/python3.8/site-packages/mlc_chat/chat_module.py", line 940, in _prefill
    self._prefill_func(input, decode_next_token, place_in_prompt.value, generation_config_str)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 277, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/Users/miniconda3/envs/mlc/lib/python3.8/site-packages/tvm/_ffi/base.py", line 476, in raise_last_ffi_error
    raise py_err
ValueError: Traceback (most recent call last):
  File "/Users/runner/work/package/package/tvm/src/runtime/relax_vm/builtin.cc", line 177
ValueError: Check failed: (ptr->dl_tensor.ndim == ndim) is false: ErrorContext(fn=softmax_with_temperature, loc=param[1], param=temperature, annotation=R.Tensor((), dtype="float32"))  expect Tensor with ndim 0 but get 1

## To Reproduce

1. python3 -m mlc_llm.build --model /Users/Work/mlc-llm/dist/models/RedPajama-INCITE-Chat-3B-v1 --target metal(or metal) --quantization q4f16_1(or q4f16_0)
2. python examples/python/sample_mlc_chat.py

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Intel Core i5 + Intel Iris Plus Graphics 655 1536 MB
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):13.5 (22G74)
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): 
 - How you installed MLC-LLM (`conda`, source): condo
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.8.17
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:62c05266986ea6639a9fd16fb87ba75a9ec056a8

**Comment by MasterJH5574** [comment]
Hi @love-xunmeng, could you please force update the mlc_chat package by following instructions here https://llm.mlc.ai/docs/install/mlc_llm.html and then try again? I think this issue is fixed by https://github.com/mlc-ai/mlc-llm/commit/204860b786460247f77717053cd3a4e1e0069b06

**Comment by love-xunmeng** [comment]
I update mlc_chat by "python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly mlc-ai-nightly" then I get the following error:

Traceback (most recent call last):
  File "examples/python/sample_mlc_chat.py", line 13, in <module>
    output = cm.generate(
  File "/Users/miniconda3/envs/mlc/lib/python3.8/site-packages/mlc_chat/chat_module.py", line 773, in generate
    self._decode(generation_config=generation_config)
  File "/Users/miniconda3/envs/mlc/lib/python3.8/site-packages/mlc_chat/chat_module.py", line 1005, in _decode
    self._decode_func(generation_config_str)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/Users/miniconda3/envs/mlc/lib/python3.8/site-packages/tvm/_ffi/base.py", line 476, in raise_last_ffi_error
    raise py_err
tvm.error.InternalError: Traceback (most recent call last):
  File "/Users/runner/work/package/package/tvm/src/runtime/relax_vm/lm_support.cc", line 421
InternalError: Check failed: sampled_index >= 0 (-1 vs. 0) :

**Comment by MasterJH5574** [comment]
Hi @love-xunmeng, this now becomes a different issue. I tried to build and run RedPajama on my end, and it works well. Could you try if other models (like llama) works on your end? If so then we might need to try to reproduce the RedPajama issue first.

**Comment by junrushao** [comment]
Closing as there’s no further updates and the issue seems fixed on our end. Please feel free to open up a new one if it persists.
