### ISSUE TITLE
Unable to install on Mac M1

### ISSUE THREAD

**Issue by songproducer** [mlc-ai/mlc-llm#111]
I run:

 conda install -c mlc-ai -c conda-forge mlc-chat-nightly

```
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/gateways/repodata/__init__.py", line 161, in conda_http_errors
        yield
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/gateways/repodata/__init__.py", line 127, in repodata
        response.raise_for_status()
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/mlc-ai/osx-arm64/current_repodata.json
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/requests/models.py", line 971, in json
        return complexjson.loads(self.text, **kwargs)
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/simplejson/__init__.py", line 514, in loads
        return _default_decoder.decode(s)
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/simplejson/decoder.py", line 386, in decode
        obj, end = self.raw_decode(s)
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/simplejson/decoder.py", line 416, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/notices/core.py", line 121, in wrapper
        return func(*args, **kwargs)
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 264, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 134, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 177, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 282, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 449, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 1064, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/core/index.py", line 267, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 169, in query_all
        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))
      File "/Users/leotreasure/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
        yield fs.pop().result()
      File "/Users/leotreasure/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 444, in result
        return self.__get_result()
      File "/Users/leotreasure/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
        raise self._exception
      File "/Users/leotreasure/miniconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 158, in subdir_query
        return tuple(
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 174, in query
        self.load()
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 264, in load
        _internal_state = self._load()
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 366, in _load
        raw_repodata_str = self._repo.repodata(cache.state)  # type: ignore
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/gateways/repodata/__init__.py", line 127, in repodata
        response.raise_for_status()
      File "/Users/leotreasure/miniconda3/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/gateways/repodata/__init__.py", line 208, in conda_http_errors
        raise RepodataIsEmpty(
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 462, in __init__
        body = response.json()
      File "/Users/leotreasure/miniconda3/lib/python3.8/site-packages/requests/models.py", line 975, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /Users/leotreasure/miniconda3/bin/conda install -c mlc-ai -c conda-forge mlc-chat-nightly`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=mlc-chat
                CONDA_EXE=/Users/leotreasure/miniconda3/bin/conda
             CONDA_PREFIX=/Users/leotreasure/miniconda3/envs/mlc-chat
    CONDA_PROMPT_MODIFIER=(mlc-chat)
         CONDA_PYTHON_EXE=/Users/leotreasure/miniconda3/bin/python
               CONDA_ROOT=/Users/leotreasure/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
               LD_PRELOAD=<not set>
                  MANPATH=/Users/leotreasure/.nvm/versions/node/v18.12.1/share/man:/opt/local/sh
                          are/man:/opt/homebrew/share/man::
                     PATH=/Users/leotreasure/miniconda3/bin:/Users/leotreasure/miniconda3/envs/m
                          lc-chat/bin:/Users/leotreasure/miniconda3/bin:/Users/leotreasure/minic
                          onda3/bin:/Users/leotreasure/miniconda3/bin:/Users/leotreasure/minicon
                          da3/bin:/usr/local/opt/coreutils/libexec/gnubin:/Users/leotreasure/per
                          l5/bin:/Users/leotreasure/.nvm/versions/node/v18.12.1/bin:/Users/leotr
                          easure/miniconda3/condabin:/opt/local/bin:/opt/local/sbin:/opt/homebre
                          w/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:
                          /usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/b
                          in:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/var/r
                          un/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/v
                          ar/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var
                          /run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinter
                          nal/bin:/Users/leotreasure/.cargo/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : mlc-chat
    active env location : /Users/leotreasure/miniconda3/envs/mlc-chat
            shell level : 1
       user config file : /Users/leotreasure/.condarc
 populated config files : 
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.8.11.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.4=0
                          __unix=0=0
       base environment : /Users/leotreasure/miniconda3  (writable)
      conda av data dir : /Users/leotreasure/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/mlc-ai/osx-arm64
                          https://conda.anaconda.org/mlc-ai/noarch
                          https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/leotreasure/miniconda3/pkgs
                          /Users/leotreasure/.conda/pkgs
       envs directories : /Users/leotreasure/miniconda3/envs
                          /Users/leotreasure/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.3.1 requests/2.29.0 CPython/3.8.11 Darwin/22.5.0 OSX/13.4
                UID:GID : 505:20
             netrc file : /Users/leotreasure/.netrc
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: 

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

**Comment by junrushao** [comment]
Looks like you have some internet connection issues. Would you mind trying again with a more stable network?

**Comment by songproducer** [comment]
My internet connection is fine. I tried again on mobile but same error.

**Comment by junrushao** [comment]
I am not 100% sure what's happening because it says:

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/mlc-ai/osx-arm64/current_repodata.json
```

It usually happens when the channel (`mlc-ai`) doesn't actually exist, so I just checked but it is there: https://anaconda.org/mlc-ai/mlc-chat-nightly/files...

Would you mind sharing the output of the following command:

```bash
conda search -f mlc-chat-nightly -c mlc-ai
```

**Comment by junrushao** [comment]
Also CC @tqchen: I pushed another build but CD for osx-arm64 would be great

**Comment by tqchen** [comment]
cc @MasterJH5574 who can help to set it up
