### ISSUE TITLE
[Bug] Warning: BlockBuilder destroyed with remaining blocks!

### ISSUE THREAD

**Issue by bojak83318** [mlc-ai/mlc-llm#1144]
## 🐛 Bug
I followed the guide on blog : https://blog.mlc.ai/2023/10/19/Scalable-Language-Model-Inference-on-Multiple-NVDIA-AMD-GPUs
ran 
```
 python3 -m mlc_llm.build --build-model-only --model ./dist/models/$MODEL/ --quantization q4f16_1 --max-seq-len 4096 --num-shards 2 --target rocm 
```
and got the following error : 
```
 ^C[02:43:59] /workspace/tvm/src/relax/ir/block_builder.cc:64: Warning: BlockBuilder destroyed with remaining blocks!
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/rocm/mlc-llm/mlc_llm/build.py", line 46, in <module>
    main()
  File "/home/rocm/mlc-llm/mlc_llm/build.py", line 42, in main
    core.build_model_from_args(parsed_args)
  File "/home/rocm/mlc-llm/mlc_llm/core.py", line 691, in build_model_from_args
    mod = mod_transform_before_build(mod, param_manager, args, model_config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocm/mlc-llm/mlc_llm/core.py", line 443, in mod_transform_before_build
    mod = fuse_split_rotary_embedding(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocm/mlc-llm/mlc_llm/transform/fuse_split_rotary_embedding.py", line 245, in fuse_split_rotary_embedding
    mod["decode"] = rewrite_bindings(ctx, rewriter, mod["decode"])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocm/anaconda3/envs/mlc-llm-venv/lib/python3.11/site-packages/tvm/relax/dpl/rewrite.py", line 118, in rewrite_bindings
    return ffi.rewrite_bindings(ctx, rewriter, func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/home/rocm/anaconda3/envs/mlc-llm-venv/lib/python3.11/site-packages/tvm/_ffi/base.py", line 419, in raise_last_ffi_error
   c_err_msg = py_str(_LIB.TVMGetLastError())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocm/anaconda3/envs/mlc-llm-venv/lib/python3.11/site-packages/tvm/_ffi/base.py", line 53, in <lambda>
    py_str = lambda x: x.decode("utf-8")
                       ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'decode'
```

## Environment

 - Platform ROCM
 - Operating system Ubuntu 22.04 LTS
 - Device : dual gfx 1100 7900xtx and 7900xt
 - How you installed MLC-LLM (`conda`, source): https://llm.mlc.ai/docs/install/mlc_llm.html
 - Python version : 3.11.6
 - GPU driver version (if applicable): rocm 5.7

**Comment by junrushao** [comment]
@masahi @Lunderberg could you guys take a look? Thanks!

**Comment by Lunderberg** [comment]
Hmm.  From the error message, it looks like an error code was returned, but neither a python exception nor an error message was set inside the function.  That shouldn't be possible, since the three possible types [here](https://github.com/apache/tvm/blob/main/src/runtime/c_runtime_api.cc#L400) require either [TVMGetLastPythonError](https://github.com/apache/tvm/blob/main/src/runtime/c_runtime_api.cc#L421) or [TVMGetLastError](https://github.com/apache/tvm/blob/main/src/runtime/c_runtime_api.cc#L406) to return a non-None value.

What was the git SHA for the version of TVM was this running on?

**Comment by junrushao** [comment]
I'm unable to reproduce this error

**Comment by junrushao** [comment]
I tried again, started from a fresh new environment and follow the exact instructions on the blog post, but still cannot reproduce the bug. Perhaps it could be some legacy issue from an old nightly. Would you mind trying again from scratch? Please feel free to create a new issue if the issue persists

**Comment by junrushao** [comment]
<img width="1560" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/22515877/37fc4ecd-b2b0-4a32-9ef0-4802743e3116">
