### ISSUE TITLE
[iOS] - `dolly-v2-3b` + Mobile Support

### ISSUE THREAD

**Issue by terryworona** [mlc-ai/mlc-llm#116]
## Overview

Hey all, I'm trying to get an alternative model working for mobile (i.e. `dolly-v2-3b`). There have been a few discussions on the topic [here](https://github.com/mlc-ai/mlc-llm/issues/71) and [here](https://github.com/mlc-ai/mlc-llm/issues/104), but nothing mobile-specific. 

I'm admittedly new to the world of LLMs (especially on-the-edge), so any help would be greatly appreciated. 

I also saw the team [alluded](https://github.com/mlc-ai/mlc-llm/issues/71#issuecomment-1533755383) to supporting new models + tutorials in the future - so maybe it's just matter of waiting it out. 

Below are the steps I've taken + my current roadblock.

### Install LLVM

```
$ brew install llvm 
$ echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> ~/.zshrc
```

I also installed _all_ required Python packages via `pip`.

### Clone Relax

```
$ git clone https://github.com/mlc-ai/relax.git --recursive
$ cd relax
$ mkdir build
$ cp cmake/config.cmake build
```

### Make

Working directory is still `/relax`.

```
$ make -j
$ export TVM_HOME=$(pwd)
$ export PYTHONPATH=$PYTHONPATH:$TVM_HOME/python
````

### Download Model

Based on the conversations in [this](https://github.com/mlc-ai/mlc-llm/issues/71) issue, I downloaded the Dolly (3B) model to my `/Desktop` directly from hugging face:

```
$ git lfs install && git clone https://huggingface.co/databricks/dolly-v2-3b
```

### Move Model

Going back to my working directory `/relax`, I soft linked the model:

```
$ mkdir -p dist/models 
$ ln -s /Users/me/Desktop/dolly-v2-3b dist/models/dolly-v2-3b 
```

### Build Model

I now cloned the `mlc-llm` project within the `/relax` directory:

```
$ git clone https://github.com/mlc-ai/mlc-llm.git --recursive
$ cd mlc-llm
```

I then tried to build the `dolly-v2-3b` model /w the configuration supplied for `iphone`:

```
$ python3 build.py --model dolly-v2-3b --dtype float16 --target iphone --quantization-mode int3 --quantization-sym --quantization-storage-nbit 16 --max-seq-len 768
```

### Error

After running the `build.py` command, I was presented with the following trace:

```
Traceback (most recent call last):
  File "/Users/me/Development/llm/relax/mlc-llm/build.py", line 207, in <module>
    mod = mod_transform_before_build(mod, params, ARGS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Development/llm/relax/mlc-llm/build.py", line 124, in mod_transform_before_build
    mod = relax.transform.DeadCodeElimination(model_names)(mod)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Development/llm/relax/python/tvm/ir/transform.py", line 238, in __call__
    return _ffi_transform_api.RunPass(self, mod)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Development/llm/relax/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
ValueError: Traceback (most recent call last):
  File "/Users/me/Development/llm/relax/src/ir/module.cc", line 176
ValueError: Cannot find global var "softmax_with_temperature" in the Module
candidates are: ["full", "decode4", "fused_min_max_triu_te_broadcast_to", "squeeze1", "decode6", "transpose5", "layer_norm1", "slice", "rotary_embedding", "encode", "rotary_embedding1", "fused_transpose4_reshape4", "reshape2", "cast4", "fused_matmul2_add_add2_add2_cast", "transpose2", "fused_decode1_fused_matmul4_add1_gelu", "squeeze", "matmul7", "fused_softmax_cast3", "fused_NT_matmul4_add3", "fused_reshape2_squeeze", "fused_decode3_matmul6", "fused_NT_matmul_divide_maximum_minimum_cast2", "create_kv_cache", "fused_NT_matmul3_add4_gelu1", "transpose3", "matmul3", "cast5", "encoding", "fused_decode_fused_matmul2_add", "reshape7", "reshape5", "fused_NT_matmul1_add3", "decode", "encode4", "layer_norm", "extend_te", "fused_layer_norm1_cast6", "reshape3", "encode3", "fused_NT_matmul2_divide1_maximum1_minimum1_cast7", "encode2", "fused_decode2_fused_matmul5_add", "fused_softmax1_cast8", "encode1", "reshape1", "take_decode", "fused_layer_norm_cast1", "fused_NT_matmul1_add3_add5_add5", "fused_matmul2_add_add2_add2", "reshape", "take_decode1", "reshape8", "decoding", "fused_slice1_cast4", "cast", "fused_NT_matmul1_add3_add5_add5_cast5", "decode5", "reshape6"]

```

I took a peak @ the `build.py` script, and it looks like `softmax_with_temperature` is an additional model being used? I'm not sure where to go from here. 

Any help would be greatly appreciated, thank you!

**Comment by terryworona** [comment]
Thank you for the fix @tqchen and @jeethu - this resolved my issue w.r.t. the `build.py` script + `dolly-v2-3b`. I am however, facing a new roadblock. Steps to reproduce below (continuing from my original post):

### Rebase 

To get the aforementioned [fix](https://github.com/mlc-ai/mlc-llm/pull/121), simply pull the latest (within `/relax`):

```
$ git submodule update --init --recursive
$ git pull
```

### Dependencies

I was missing the [rustup](https://rustup.rs/) dependency, so I fetched it:

```
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

### Build

The following build command now works for `dolly-v2-3b`:

```
python3 build.py --model dolly-v2-3b --dtype float16 --target iphone --quantization-mode int3 --quantization-sym --quantization-storage-nbit 16 --max-seq-len 768
```

Output:

```
/Users/me/Development/llm/relax/src/runtime/metal/metal_device_api.mm:165: Intializing Metal device 0, name=Apple M1 Max
Finish exporting to dist/dolly-v2-3b/float16/dolly-v2-3b_iphone_float16.a
```

### Mobile Integration

As per the [instructions](https://github.com/mlc-ai/mlc-llm/tree/main/ios) in the `ios` repo:

```
$ cd ios
$ ./prepare_libs.sh
```

**Note**: I had to change the last line of `prepare_libs.sh` to point to the dolly model (it was _hardcoded_ for `vicuna-v1-7b`)

```
cp ../dist/dolly-v2-3b/float16/dolly-v2-3b_iphone_float16.a build/lib/libmodel_iphone.a
```

The script seemed to complete successfully, so I ran the next one:

```
$ ./prepare_params.sh
```

**Note**: this script too, has `vicuna-v1-7b` hardcoded, so I went to update it to the point to the `dolly-v2-3b` path, but this is where I got stuck. 

The path `../dist/models/*` does not exist, I'm not sure where to find the `tokenizer.model`? The `params` are available however via `../dist/dolly-v2-3b/float16/params`. Screenshot attached. 

Any help would be appreciated. Thanks! 

![dolly-screenshot](https://github.com/mlc-ai/mlc-llm/assets/358709/fc899792-67e4-49d9-ae1e-04cbf82b086b)
