### ISSUE TITLE
Check failed: (it != type_key2index_.end()) is false: Cannot find type node.PrinterConfig. Did you forget to register the node by TVM_REGISTER_NODE_TYPE

### ISSUE THREAD

**Issue by wenqf11** [mlc-ai/mlc-llm#117]
When I try to build on my computer, run
```python3 build.py --model vicuna213123-v1-7b --dtype float16 --target iphone --quantization-mode int3 --quantization-sym --quantization-storage-nbit 16 --max-seq-len 768```
environment:  CentOS Linux release 8.2.2.2004, NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.0
any advice ?
```Traceback (most recent call last):
  File "build.py", line 7, in <module>
    import tvm
  File "/data/home/vincewen/project/relax/python/tvm/__init__.py", line 33, in <module>
    from .runtime.object import Object
  File "/data/home/vincewen/project/relax/python/tvm/runtime/__init__.py", line 23, in <module>
    from .script_printer import Scriptable
  File "/data/home/vincewen/project/relax/python/tvm/runtime/script_printer.py", line 28, in <module>
    class PrinterConfig(Object):
  File "/data/home/vincewen/project/relax/python/tvm/_ffi/registry.py", line 69, in register
    check_call(_LIB.TVMObjectTypeKey2Index(c_str(object_name), ctypes.byref(tidx)))
  File "/data/home/vincewen/project/relax/python/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  93: 0xffffffffffffffff
  92: _start
  91: __libc_start_main
  90: Py_BytesMain
  89: Py_RunMain
  88: PyRun_SimpleFileExFlags
  87: pyrun_file
  86: run_mod
  85: run_eval_code_obj
  84: PyEval_EvalCode
  83: _PyEval_EvalCodeWithName
  82: _PyEval_EvalFrameDefault
  81: PyImport_ImportModuleLevelObject
  80: _PyObject_CallMethodIdObjArgs
  79: object_vacall
  78: _PyFunction_Vectorcall
  77: _PyEval_EvalFrameDefault
  76: _PyFunction_Vectorcall
  75: _PyEval_EvalFrameDefault
  74: _PyFunction_Vectorcall
  73: _PyEval_EvalFrameDefault
  72: _PyFunction_Vectorcall
  71: _PyEval_EvalFrameDefault
  70: _PyFunction_Vectorcall
  69: _PyEval_EvalCodeWithName
  68: _PyEval_EvalFrameDefault
  67: PyVectorcall_Call
  66: cfunction_vectorcall_FASTCALL
  65: builtin_exec
  64: PyEval_EvalCode
  63: _PyEval_EvalCodeWithName
  62: _PyEval_EvalFrameDefault
  61: PyImport_ImportModuleLevelObject
  60: _PyObject_CallMethodIdObjArgs
  59: object_vacall
  58: _PyFunction_Vectorcall
  57: _PyEval_EvalFrameDefault
  56: _PyFunction_Vectorcall
  55: _PyEval_EvalFrameDefault
  54: _PyFunction_Vectorcall
  53: _PyEval_EvalCodeWithName
  52: _PyEval_EvalFrameDefault
  51: PyCFunction_Call
  50: builtin___import__
  49: PyImport_ImportModuleLevelObject
  48: _PyObject_CallMethodIdObjArgs
  47: object_vacall
  46: _PyFunction_Vectorcall
  45: _PyEval_EvalFrameDefault
  44: _PyFunction_Vectorcall
  43: _PyEval_EvalFrameDefault
  42: _PyFunction_Vectorcall
  41: _PyEval_EvalFrameDefault
  40: _PyFunction_Vectorcall
  39: _PyEval_EvalFrameDefault
  38: _PyFunction_Vectorcall
  37: _PyEval_EvalCodeWithName
  36: _PyEval_EvalFrameDefault
  35: PyVectorcall_Call
  34: cfunction_vectorcall_FASTCALL
  33: builtin_exec
  32: PyEval_EvalCode
  31: _PyEval_EvalCodeWithName
  30: _PyEval_EvalFrameDefault
  29: PyImport_ImportModuleLevelObject
  28: _PyObject_CallMethodIdObjArgs
  27: object_vacall
  26: _PyFunction_Vectorcall
  25: _PyEval_EvalFrameDefault
  24: _PyFunction_Vectorcall
  23: _PyEval_EvalFrameDefault
  22: _PyFunction_Vectorcall
  21: _PyEval_EvalFrameDefault
  20: _PyFunction_Vectorcall
  19: _PyEval_EvalFrameDefault
  18: _PyFunction_Vectorcall
  17: _PyEval_EvalCodeWithName
  16: _PyEval_EvalFrameDefault
  15: PyVectorcall_Call
  14: cfunction_vectorcall_FASTCALL
  13: builtin_exec
  12: PyEval_EvalCode
  11: _PyEval_EvalCodeWithName
  10: _PyEval_EvalFrameDefault
  9: _PyFunction_Vectorcall
  8: _PyEval_EvalCodeWithName
  7: _PyEval_EvalFrameDefault
  6: _PyObject_MakeTpCall
  5: PyCFuncPtr_call
  4: _ctypes_callproc
  3: ffi_call
  2: ffi_call_unix64
  1: TVMObjectTypeKey2Index
  0: tvm::runtime::Object::TypeKey2Index(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  File "/data/home/vincewen/project/tvm/src/runtime/object.cc", line 165
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (it != type_key2index_.end()) is false: Cannot find type node.PrinterConfig. Did you forget to register the node by TVM_REGISTER_NODE_TYPE ?```

**Comment by junrushao** [comment]
Please check this out to install TVM properly: https://mlc.ai/mlc-llm/docs/install/tvm.html
