### ISSUE TITLE
[Bug] error during compiling 4-bit quantized version of RedPajama 3B model on ubuntu for android

### ISSUE THREAD

**Issue by saumbcmu** [mlc-ai/mlc-llm#1194]
## 🐛 Bug

Error when running `python3 -m mlc_llm.build --hf-path togethercomputer/RedPajama-INCITE-Chat-3B-v1 --target android --max-seq-len 768 --quantization q4f16_0`

## Error trace
```
Weights exist at dist/models/RedPajama-INCITE-Chat-3B-v1, skipping download.
Using path "dist/models/RedPajama-INCITE-Chat-3B-v1" for model "RedPajama-INCITE-Chat-3B-v1"
Target configured: opencl -keys=opencl,gpu -max_function_args=128 -max_num_threads=256 -max_shared_memory_per_block=16384 -max_threads_per_block=256 -texture_spatial_limit=16384 -thread_warp_size=1
Traceback (most recent call last):
  File "/home/saumyassd/hdd/miniconda3/envs/mlcenv/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/saumyassd/hdd/miniconda3/envs/mlcenv/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/saumyassd/Desktop/CMU/odml/mlc/mlc-llm/mlc_llm/build.py", line 46, in <module>
    main()
  File "/home/saumyassd/Desktop/CMU/odml/mlc/mlc-llm/mlc_llm/build.py", line 42, in main
    core.build_model_from_args(parsed_args)
  File "/home/saumyassd/Desktop/CMU/odml/mlc/mlc-llm/mlc_llm/core.py", line 667, in build_model_from_args
    new_params = utils.convert_weights(param_manager, params, args)
  File "/home/saumyassd/Desktop/CMU/odml/mlc/mlc-llm/mlc_llm/utils.py", line 234, in convert_weights
    target = detect_local_target()
  File "/home/saumyassd/Desktop/CMU/odml/mlc/mlc-llm/mlc_llm/utils.py", line 438, in detect_local_target
    target = method()
  File "/home/saumyassd/Desktop/CMU/odml/mlc/mlc-llm/mlc_llm/utils.py", line 407, in _detect_local_vulkan
    if not dev.exist:
  File "/home/saumyassd/hdd/miniconda3/envs/mlcenv/lib/python3.10/site-packages/tvm/_ffi/runtime_ctypes.py", line 319, in exist
    return self._GetDeviceAttr(self.device_type, self.device_id, 0) != 0
  File "/home/saumyassd/hdd/miniconda3/envs/mlcenv/lib/python3.10/site-packages/tvm/_ffi/runtime_ctypes.py", line 303, in _GetDeviceAttr
    return tvm.runtime._ffi_api.GetDeviceAttr(device_type, device_id, attr_id)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/home/saumyassd/hdd/miniconda3/envs/mlcenv/lib/python3.10/site-packages/tvm/_ffi/base.py", line 476, in raise_last_ffi_error
    raise py_err
tvm.error.InternalError: Traceback (most recent call last):
  7: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<__mk_TVM1::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, __mk_TVM1, tvm::runtime::TVMRetValue)
  6: tvm::runtime::DeviceAPIManager::GetAPI(int, bool)
  5: tvm::runtime::DeviceAPIManager::GetAPI(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) [clone .isra.0]
  4: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::vulkan::__mk_TVM0::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::vulkan::__mk_TVM0, tvm::runtime::TVMRetValue)
  3: tvm::runtime::vulkan::VulkanDeviceAPI::Global()
  2: tvm::runtime::vulkan::VulkanDeviceAPI::VulkanDeviceAPI()
  1: tvm::runtime::vulkan::VulkanInstance::GetPhysicalDevices() const
  0: _ZN3tvm7runtime6deta
  File "/workspace/tvm/src/runtime/vulkan/vulkan_instance.cc", line 144
InternalError: Check failed: (__e == VK_SUCCESS) is false: Vulkan Error, code=-3: VK_ERROR_INITIALIZATION_FAILED
```
## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): ubuntu
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): dell inspiron laptop
 - How you installed MLC-LLM (`conda`, source): conda
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10): 3.10
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by Hzfengsy** [comment]
`VK_ERROR_INITIALIZATION_FAILED` which means Vulkan is not available on your compilation devices (aka your laptop, PC or server, not your target devices). As we are using GPU to accelerate the quantization step, a GPU (integrated ones are also good) is required to compile models
