### ISSUE TITLE
[Bug] Cannot interact with compiled model

### ISSUE THREAD

**Issue by lynkz-matt-psaltis** [mlc-ai/mlc-llm#1200]
## 🐛 Bug

Using wheels or compilation from source I receive the following error when attempting to use the cli or the mlc_chat rest Python module to interact with my compiled module.

InternalError: Check failed: (func.defined()) is false: Error: Cannot find PackedFunc attention_func in either Relax VM kernel library, or in TVM runtime PackedFunc registry, or in global Relax functions of the VM executable

## To Reproduce

1. Use instructions here: https://llm.mlc.ai/docs/deploy/rest.html
2. As well as https://llm.mlc.ai/docs/install/tvm.html#install-tvm-unity

```
root@lmdeploy-766b99f969-dtrxf:/src/mlc-llm# PYTHONPATH=$(pwd)/python python3 -m mlc_chat.rest --model /mnt/models/Phind-CodeLlama-34B-v2-q4f16_2-alpha/params/
INFO:     Started server process [59831]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/src/mlc-llm/python/mlc_chat/rest.py", line 137, in lifespan
    chat_mod = ChatModule(
  File "/src/mlc-llm/python/mlc_chat/chat_module.py", line 783, in __init__
    self._reload(self.model_lib_path, self.model_path, user_chat_config_json_str)
  File "/src/mlc-llm/python/mlc_chat/chat_module.py", line 993, in _reload
    self._reload_func(lib, model_path, app_config_json)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/src/tvm-unity/python/tvm/_ffi/base.py", line 476, in raise_last_ffi_error
    raise py_err
  File "/src/mlc-llm/cpp/llm_chat.cc", line 1425, in mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetVal
ue*)#1}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
    chat_->Reload(args[0], args[1], args[2]);
  File "/src/mlc-llm/cpp/llm_chat.cc", line 477, in mlc::llm::LLMChat::Reload(tvm::runtime::TVMArgValue, tvm::runtime::String, tvm::runtime::String)
    this->ft_.Init(reload_lib, device_, this->num_shards_);
  File "/src/mlc-llm/cpp/llm_chat.cc", line 159, in Init
    this->local_vm->GetFunction("vm_initialization")(
  File "/src/tvm-unity/src/runtime/relax_vm/vm.cc", line 477, in operator()
    this->Init(devices, alloc_types);
  File "/src/tvm-unity/src/runtime/relax_vm/vm.cc", line 781, in tvm::runtime::relax_vm::VirtualMachineImpl::InitFuncPool()
    ICHECK(func.defined())
tvm.error.InternalError: Traceback (most recent call last):
  4: mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs, tvm::
runtime::TVMRetValue*) const
        at /src/mlc-llm/cpp/llm_chat.cc:1425
  3: mlc::llm::LLMChat::Reload(tvm::runtime::TVMArgValue, tvm::runtime::String, tvm::runtime::String)
        at /src/mlc-llm/cpp/llm_chat.cc:477
  2: Init
        at /src/mlc-llm/cpp/llm_chat.cc:159
  1: operator()
        at /src/tvm-unity/src/runtime/relax_vm/vm.cc:477
  0: tvm::runtime::relax_vm::VirtualMachineImpl::InitFuncPool()
        at /src/tvm-unity/src/runtime/relax_vm/vm.cc:781
  File "/src/tvm-unity/src/runtime/relax_vm/vm.cc", line 781
InternalError: Check failed: (func.defined()) is false: Error: Cannot find PackedFunc attention_func in either Relax VM kernel library, or in TVM runtime PackedFunc registry, or in global Relax functions of the VM executable

ERROR:    Application startup failed. Exiting.
```
## Expected behavior

Model should load and provide inference

## Environment

 - Platform: CUDA
 - Operating system: Ubuntu
 - Device: Virtual Machine
 - How you installed MLC-LLM (`conda`, source): Both
 - How you installed TVM-Unity (`pip`, source): Both
 - Python version: 3.10
 - GPU driver version: NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.2
 - CUDA/cuDNN version (if applicable): 12.2
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): 3001b20b0dd114cad23fccb25cbb055ce80a224e
 - Any other relevant information:

**Comment by Hzfengsy** [comment]
Looks like it's an issue related to CUTLASS. Could you please check if you enable CUTLASS when you build TVM Unity? (As your `mlc-llm-chat` is direct to your unity package

**Comment by lynkz-matt-psaltis** [comment]
Thanks @Hzfengsy I've tried with both CUTLASS enabled and disabled.

Adding these switches seems to be the cause --enable-batching --sep-embed

**Comment by Hzfengsy** [comment]
cc @MasterJH5574 for batching support

**Comment by junrushao** [comment]
Batching is around the corner but not finished yet :(

**Comment by lynkz-matt-psaltis** [comment]
Thanks team appreciate the feedback - Amazing work!
