### ISSUE TITLE
Cannot find `ld.lld` during ROCm Build

### ISSUE THREAD

**Issue by bojak83318** [mlc-ai/mlc-llm#1216]
## 🐛 Bug
Traceback (most recent call last):
```
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/rocm/mlc-llm/mlc_llm/build.py", line 47, in <module>
    main()
  File "/home/rocm/mlc-llm/mlc_llm/build.py", line 43, in main
    core.build_model_from_args(parsed_args)
  File "/home/rocm/mlc-llm/mlc_llm/core.py", line 787, in build_model_from_args
    build(mod, args)
  File "/home/rocm/mlc-llm/mlc_llm/core.py", line 670, in build
    ex = relax.build(mod_deploy, args.target, system_lib=args.system_lib)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocm/anaconda3/envs/mlc-llm-venv/lib/python3.11/site-packages/tvm/relax/vm_build.py", line 343, in build
    return _vmlink(builder, target, tir_mod, ext_libs, params, system_lib=system_lib)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocm/anaconda3/envs/mlc-llm-venv/lib/python3.11/site-packages/tvm/relax/vm_build.py", line 242, in _vmlink
    lib = tvm.build(
          ^^^^^^^^^^
  File "/home/rocm/anaconda3/envs/mlc-llm-venv/lib/python3.11/site-packages/tvm/driver/build_module.py", line 281, in build
    rt_mod_host = _driver_ffi.tir_to_runtime(annotated_mods, target_host)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/home/rocm/anaconda3/envs/mlc-llm-venv/lib/python3.11/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "tvm/_ffi/_cython/./packed_func.pxi", line 56, in tvm._ffi._cy3.core.tvm_callback
  File "/home/rocm/anaconda3/envs/mlc-llm-venv/lib/python3.11/site-packages/tvm/contrib/rocm.py", line 120, in callback_rocm_link
    rocm_link(tmp_obj, tmp_cobj)
  File "/home/rocm/anaconda3/envs/mlc-llm-venv/lib/python3.11/site-packages/tvm/contrib/rocm.py", line 85, in rocm_link
    lld if lld is not None else find_lld()[0],
                                ^^^^^^^^^^
  File "/home/rocm/anaconda3/envs/mlc-llm-venv/lib/python3.11/site-packages/tvm/contrib/rocm.py", line 59, in find_lld
    raise RuntimeError("cannot find ld.lld, candidates are: " + str(lld_list))
RuntimeError: cannot find ld.lld, candidates are: ['ld.lld-17.0', 'ld.lld-17', 'ld.lld']
```

## To Reproduce
Building in pure python as per https://blog.mlc.ai/2023/10/19/Scalable-Language-Model-Inference-on-Multiple-NVDIA-AMD-GPUs#docker
I already downloaded the model so i used symbolic links as detailed under 'Additional Context'

## Environment

 - Platform : ROCM
 - Operating system : Ubuntu
 - Device : 7900xtx
 - How you installed MLC-LLM : python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly-rocm57 mlc-ai-nightly-rocm57
 - Python version : 3.11
- ROCM version : 5.7.1

 - Any other relevant information:

## Additional context
i already downloaded the model in ./llm-perf-bench , so i use symbolic links, i dont think this is the issue
```
ln -s mlc-chat-Llama-2-70b-chat-hf-q4f16_1 ../dist/Llama-2-70b-chat-hf-q4f16_1/params

```

**Comment by junrushao** [comment]
This is a common issue that we probably (I myself, particularly) forgot to set PATH in ROCm. To resolve this, you will have to add ROCm's LLVM to PATH, so that ROCm's lld exists:

```bash
export PATH=/opt/rocm/llvm/bin:$PATH
```

In Dockerfile it is reflected on [this line](https://github.com/mlc-ai/llm-perf-bench/blob/main/docker/Dockerfile.rocm57.mlc#L10C11-L10C48).

**Comment by junrushao** [comment]
@tqchen we may want to enhance TVM's default path finding for ROCm to include `/opt/rocm/llvm/bin` by default

**Comment by tqchen** [comment]
@junrushao agree about the above pt, given rocm path is quite canonical
