### ISSUE TITLE
[Bug] _pickle.UnpicklingError: invalid load key, 'v' when compiling model

### ISSUE THREAD

**Issue by Dolidodzik** [mlc-ai/mlc-llm#1305]
## 🐛 Bug

I am not sure if it's a bug, or if I am the one doing something wrong, but I basically followed the steps, installed mlc-llm as it was [explained in docs](https://llm.mlc.ai/docs/compilation/compile_models.html), and it gives me an error.

## To Reproduce
Follow steps from [here](https://llm.mlc.ai/docs/compilation/compile_models.html).

```
lesiu@pop-os:~/coding/compile_models/redpanjama3b$ python3 -m mlc_llm.build --hf-path togethercomputer/RedPajama-INCITE-Chat-3B-v1 --target webgpu --quantization q4f16_1
Weights exist at dist/models/RedPajama-INCITE-Chat-3B-v1, skipping download.
Using path "dist/models/RedPajama-INCITE-Chat-3B-v1" for model "RedPajama-INCITE-Chat-3B-v1"
Target configured: webgpu -keys=webgpu,gpu -max_num_threads=256
Automatically using target for weight quantization: vulkan -keys=vulkan,gpu -max_num_threads=256 -max_shared_memory_per_block=65536 -max_threads_per_block=1024 -supports_16bit_buffer=1 -supports_float16=1 -supports_float32=1 -supports_int16=1 -supports_int32=1 -supports_int8=1 -thread_warp_size=1
Get old param:   0%|                               | 0/388 [00:00<?, ?tensors/sStart computing and quantizing weights... This may take a while.00<?, ?tensors/s]
Get old param:   0%|                       | 1/388 [00:00<02:09,  2.98tensors/s]Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lesiu/.local/lib/python3.10/site-packages/mlc_llm/build.py", line 47, in <module>
    main()
  File "/home/lesiu/.local/lib/python3.10/site-packages/mlc_llm/build.py", line 43, in main
    core.build_model_from_args(parsed_args)
  File "/home/lesiu/.local/lib/python3.10/site-packages/mlc_llm/core.py", line 866, in build_model_from_args
    params = utils.convert_weights(mod_transform, param_manager, params, args)
  File "/home/lesiu/.local/lib/python3.10/site-packages/mlc_llm/utils.py", line 272, in convert_weights
    vm["transform_params"]()
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/home/lesiu/.local/lib/python3.10/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "tvm/_ffi/_cython/./packed_func.pxi", line 56, in tvm._ffi._cy3.core.tvm_callback
  File "/home/lesiu/.local/lib/python3.10/site-packages/mlc_llm/utils.py", line 37, in inner
    return func(*args, **kwargs)
  File "/home/lesiu/.local/lib/python3.10/site-packages/mlc_llm/relax_model/param_manager.py", line 599, in get_item
    load_torch_params_from_bin(torch_binname)
  File "/home/lesiu/.local/lib/python3.10/site-packages/mlc_llm/relax_model/param_manager.py", line 559, in load_torch_params_from_bin
    torch_params = torch.load(
  File "/home/lesiu/.local/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/lesiu/.local/lib/python3.10/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
lesiu@pop-os:~/coding/compile_models/redpanjama3b$
```

## Expected behavior

I excepted the model to compile to my target (webgpu)

## Environment
Python version: Python 3.10.12
OS: Pop!_OS 22.04

**Comment by junrushao** [comment]
This error is thrown by PyTorch, and is likely because the weights in `dist/models/RedPajama-INCITE-Chat-3B-v1` are non-existent or incomplete

**Comment by junrushao** [comment]
Let me know if it's case

**Comment by Dolidodzik** [comment]
@junrushao 

```
dist/models/RedPajama-INCITE-Chat-3B-v1$ ls
config.json             README.md                tokenizer.json
generation_config.json  special_tokens_map.json
pytorch_model.bin       tokenizer_config.json
```

It seems all the files were downloaded, but indeed they seem to be incomplete - in my case `pytorch_model.bin` is just 135 bytes, when it should be much more.

**Comment by tqchen** [comment]
opened a tracking issue https://github.com/mlc-ai/mlc-llm/issues/1319 on better error message. in the meantime, @Dolidodzik can you try to redownload the files?

**Comment by Dolidodzik** [comment]
Well, sorry for that but for some reason i am getting another issue now completely, and I don't even know why. I am getting `ValueError: Multiple weight shard files without json map is not supported`, I tried adding `--use-safetensors` param but I still couldn't get it to work. 

```
lesiu@pop-os:~/coding/compile_models$ python3 -m mlc_llm.build --hf-path togethercomputer/RedPajama-INCITE-Chat-3B-v1 --target webgpu --quantization q4f16_1 --use-safetensors
Weights exist at dist/models/RedPajama-INCITE-Chat-3B-v1, skipping download.
Using path "dist/models/RedPajama-INCITE-Chat-3B-v1" for model "RedPajama-INCITE-Chat-3B-v1"
Target configured: webgpu -keys=webgpu,gpu -max_num_threads=256
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lesiu/.local/lib/python3.10/site-packages/mlc_llm/build.py", line 47, in <module>
    main()
  File "/home/lesiu/.local/lib/python3.10/site-packages/mlc_llm/build.py", line 43, in main
    core.build_model_from_args(parsed_args)
  File "/home/lesiu/.local/lib/python3.10/site-packages/mlc_llm/core.py", line 833, in build_model_from_args
    param_manager.init_torch_pname_to_bin_name(args.use_safetensors)
  File "/home/lesiu/.local/lib/python3.10/site-packages/mlc_llm/relax_model/param_manager.py", line 292, in init_torch_pname_to_bin_name
    mapping = load_torch_pname2binname_map(
  File "/home/lesiu/.local/lib/python3.10/site-packages/mlc_llm/relax_model/param_manager.py", line 921, in load_torch_pname2binname_map
    raise ValueError("Multiple weight shard files without json map is not supported")
ValueError: Multiple weight shard files without json map is not supported

```

**Comment by Dolidodzik** [comment]
@tqchen @junrushao

**Comment by junrushao** [comment]
Well the input format is not safetensor but plain pytorch. @MasterJH5574 could you take a look as the author of this piece of code?

**Comment by MasterJH5574** [comment]
@Dolidodzik Hi! Do you mind sharing the files you re-downloaded under `dist/models/RedPajama-INCITE-Chat-3B-v1` again here? When you use `--use-safetensors`, the error happens when there are multiple files ended with `.safetensor` while the file `model.safetensors.index.json` does not exist. So I am wondering what the files under your directory are.

**Comment by Dolidodzik** [comment]
The thing is, weather or not I use `--use-safetensors` or not, the output is the same.

Well, actually new thing happened - when I was lsing directory you asked about, I realized that .bin file is missing, so I downloaded it manually from huggingface, and placed it there. And now I again get another issue... (Sorry for being so incompetent with that stuff, but this is my first dealing with such a thing, and it's pretty novel thing so there aren't many tutorials yet, thank you guys for doing great work on that)

ANYWAY, currently where i am at, my files:

```
dist/models/RedPajama-INCITE-Chat-3B-v1$ ls
 config.json             'pytorch_model(1).bin'   special_tokens_map.json   tokenizer.json
 generation_config.json   README.md               tokenizer_config.json
```

My output now after running command:
```

python3 -m mlc_llm.build --hf-path togethercomputer/RedPajama-INCITE-Chat-3B-v1 --target webgpu --quantization q4f16_1
Weights exist at dist/models/RedPajama-INCITE-Chat-3B-v1, skipping download.
Using path "dist/models/RedPajama-INCITE-Chat-3B-v1" for model "RedPajama-INCITE-Chat-3B-v1"
Target configured: webgpu -keys=webgpu,gpu -max_num_threads=256
Automatically using target for weight quantization: vulkan -keys=vulkan,gpu -max_num_threads=256 -max_shared_memory_per_block=65536 -max_threads_per_block=1024 -supports_16bit_buffer=1 -supports_float16=1 -supports_float32=1 -supports_int16=1 -supports_int32=1 -supports_int8=1 -thread_warp_size=1
Get old param:   0%|                               | 0/388 [00:00<?, ?tensors/sStart computing and quantizing weights... This may take a while.00<?, ?tensors/s]
Get old param:  98%|███████████████████▌| 380/388 [00:11<00:00, 153.15tensors/s]Finish computing and quantizing weights.████████████▍| 505/518 [00:11<00:00, 202.97tensors/s]
Total param size: 1.4645195007324219 GB
Start storing to cache dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1/params
[0518/0518] saving param_517
All finished, 51 total shards committed, record saved to dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1/params/ndarray-cache.json
Finish exporting chat config to dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1/params/mlc-chat-config.json
Save a cached module to dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1/mod_cache_before_build.pkl.
Get old param: 100%|████████████████████| 388/388 [00:29<00:00, 153.15tensors/s][22:33:53] /workspace/tvm/src/target/llvm/codegen_llvm.cc:185: Warning: Set native vector bits to be 128 for wasm32
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lesiu/.local/lib/python3.10/site-packages/mlc_llm/build.py", line 47, in <module>
    main()
  File "/home/lesiu/.local/lib/python3.10/site-packages/mlc_llm/build.py", line 43, in main
    core.build_model_from_args(parsed_args)
  File "/home/lesiu/.local/lib/python3.10/site-packages/mlc_llm/core.py", line 923, in build_model_from_args
    build(mod, args)
  File "/home/lesiu/.local/lib/python3.10/site-packages/mlc_llm/core.py", line 762, in build
    ex.export_library(args.lib_path, **args.export_kwargs)
  File "/home/lesiu/.local/lib/python3.10/site-packages/tvm/relax/vm_build.py", line 146, in export_library
    return self.mod.export_library(
  File "/home/lesiu/.local/lib/python3.10/site-packages/tvm/runtime/module.py", line 624, in export_library
    return fcompile(file_name, files, **kwargs)
  File "/home/lesiu/.local/lib/python3.10/site-packages/tvm/contrib/emcc.py", line 60, in create_tvmjs_wasm
    libs += [find_lib_path("wasm_runtime.bc")[0]]
  File "/home/lesiu/.local/lib/python3.10/site-packages/tvm/_ffi/libinfo.py", line 166, in find_lib_path
    raise RuntimeError(message)
RuntimeError: Cannot find libraries: wasm_runtime.bc
List of candidates:
/home/lesiu/.local/bin/wasm_runtime.bc
/usr/local/sbin/wasm_runtime.bc
/usr/local/bin/wasm_runtime.bc
/usr/sbin/wasm_runtime.bc
/usr/bin/wasm_runtime.bc
/usr/sbin/wasm_runtime.bc
/usr/bin/wasm_runtime.bc
/usr/games/wasm_runtime.bc
/usr/local/games/wasm_runtime.bc
/home/lesiu/.local/lib/python3.10/site-packages/tvm/wasm_runtime.bc
/home/lesiu/.local/lib/wasm_runtime.bc


```

**Comment by tqchen** [comment]
Please follow steps here https://llm.mlc.ai/docs/install/emcc.html

**Comment by Dolidodzik** [comment]
Ok, so I tried to. I've setup $TVM_HOME, and installed emcc. 
```

lesiu@pop-os:~/clones/emsdk/scripts$ echo $TVM_HOME
/home/lesiu/TVM_HOME/
lesiu@pop-os:~/clones/emsdk/scripts$ emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.49 (04a0cad4d4c9f5d62876821274d78cd0a52427af)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

lesiu@pop-os:~/clones/emsdk/scripts$ emcc --check
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.49 (04a0cad4d4c9f5d62876821274d78cd0a52427af)
shared:INFO: (Emscripten: Running sanity checks)
```

The problem is `./scripts/prep_emcc_deps.sh` is missing in my install. I found issue discussing similar problem, but I couldn't make much out of it... I would highly appreciate any help here.

```
lesiu@pop-os:~/clones/emsdk/scripts$ ls
create_release.py          update_linux_arm64.sh  update_python.py
update_bazel_workspace.py  update_node.py
```

**Comment by Dolidodzik** [comment]
Okay, so that was the part I was missing. After successfully building TVM on my machine with that script, mlc_llm.build command seems to work. Thank you very much, I appreciate all the help. <3 

```
$ python3 -m mlc_llm.build --hf-path togethercomputer/RedPajama-INCITE-Chat-3B-v1 --target webgpu --quantization q4f16_1
Weights exist at dist/models/RedPajama-INCITE-Chat-3B-v1, skipping download.
Using path "dist/models/RedPajama-INCITE-Chat-3B-v1" for model "RedPajama-INCITE-Chat-3B-v1"
Target configured: webgpu -keys=webgpu,gpu -max_num_threads=256
Load cached module from dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1/mod_cache_before_build.pkl and skip tracing. You can use --use-cache=0 to retrace
[17:31:43] /workspace/tvm/src/target/llvm/codegen_llvm.cc:185: Warning: Set native vector bits to be 128 for wasm32
Finish exporting to dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1/RedPajama-INCITE-Chat-3B-v1-q4f16_1-webgpu.wasm
```

**Comment by Dolidodzik** [comment]
Well, since that works...
May I ask if there's any documentation/example that shows how to use generated .wasm build in WebLLM? Are there any things that I need to keep in mind, or can I just get any model from huggingface, generate .wasm and provide it to webllm AppConfig?

**Comment by tqchen** [comment]
As of now we have limited model familiy support, see https://llm.mlc.ai/docs/prebuilt_models.html
