### ISSUE TITLE
[Bug] H100 Cross Compile from A100: The current thread is not a DiscoWorker thread

### ISSUE THREAD

**Issue by technillogue** [mlc-ai/mlc-llm#1309]
## To Reproduce

1. Run latest cu121 wheel

```
Traceback (most recent call last):
File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/cog/server/worker.py", line 222, in _predict
for r in result:
File "/src/predict.py", line 188, in predict
for decoded_token in self.engine(
File "/src/src/inference_engines/mlc_engine.py", line 158, in __call__
self.cm._prefill(input=prompt, generation_config=generation_config)
File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/mlc_chat/chat_module.py", line 992, in _prefill
self._prefill_func(
File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
File "tvm/_ffi/_cython/./packed_func.pxi", line 277, in tvm._ffi._cy3.core.FuncCall
File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
raise py_err
File "/workspace/mlc-llm/cpp/llm_chat.cc", line 1492, in mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime:
:TVMArgs, tvm::runtime::TVMRetValue*)#5}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
File "/workspace/mlc-llm/cpp/llm_chat.cc", line 847, in mlc::llm::LLMChat::PrefillStep(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool, mlc::llm::PlaceInPr
ompt, tvm::runtime::String)
File "/workspace/mlc-llm/cpp/llm_chat.cc", line 1203, in mlc::llm::LLMChat::ForwardTokens(std::vector<int, std::allocator<int> >, long)
ValueError: Traceback (most recent call last):
12: mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#5}::operator()(
tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
at /workspace/mlc-llm/cpp/llm_chat.cc:1492
11: mlc::llm::LLMChat::PrefillStep(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool, mlc::llm::PlaceInPrompt, tvm::runtime::String)
at /workspace/mlc-llm/cpp/llm_chat.cc:847
10: mlc::llm::LLMChat::ForwardTokens(std::vector<int, std::allocator<int> >, long)
at /workspace/mlc-llm/cpp/llm_chat.cc:1203
9: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
8: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::relax_vm::VirtualMachineImpl::GetClosureInternal(tvm::runtime::String const&, bool)::{lambda(tvm::runtime::TVMAr
gs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
7: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
6: tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
5: tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
4: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<void (tvm::runtime::NDArray, tvm::runtime::NDArray)>::AssignTypedLambda<void (*)(tvm::runtime::N
DArray, tvm::runtime::NDArray)>(void (*)(tvm::runtime::NDArray, tvm::runtime::NDArray), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs
 const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
3: tvm::runtime::BroadcastFromWorker0(tvm::runtime::NDArray, tvm::runtime::NDArray)
2: tvm::runtime::GetCCLFunc(char const*)
1: tvm::runtime::DiscoWorker::ThreadLocal()
0: _ZN3tvm7runtime6deta
File "/workspace/tvm/src/runtime/disco/worker.cc", line 46
ValueError: Check failed: (ret) is false: The current thread is not a DiscoWorker thread
```

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Cuda
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): ubuntu22.04
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): H100, A100
 - How you installed MLC-LLM (`conda`, source): pip wheel
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.11
 - GPU driver version (if applicable): 545.23.08. also happens with 525
 - CUDA/cuDNN version (if applicable): 12.3 or 12.1
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

This started happening recently, older wheels are fine. If we don't set device="cuda", it throws `InternalError: Check failed: (__e == VK_SUCCESS) is false: Vulkan Error, code=-9: VK_ERROR_INCOMPATIBLE_DRIVER` instead

**Comment by junrushao** [comment]
Are you using multiple GPUs?

**Comment by junrushao** [comment]
Would be great if you could share the steps to reproduce this issue so that we could find a fix. Thanks!

**Comment by technillogue** [comment]
No, I tried with only one GPU as well. I'll try to get reproduction code soon

**Comment by technillogue** [comment]
steps to reproduce (mountpoint is optional):
```bash
docker run --gpus all --rm -it  -v /mnt/data/models/70b-chat:/app/models/llama-2-70b-chat-hf-mlc/model_artifacts/default_inference_weights/  technillogue/mlc-disco-error-reproduction:latest
```
code: https://github.com/replicate/cog-llama-template/blob/syl/minimal-disco-error-reproduction/reproduce.py

output:
```
2023-11-23T00:40:32Z | INFO  | [ Metrics ] elapsed_time=0.000s file_count=0 throughput="0 B/s" total_bytes_downloaded="0 B"
Traceback (most recent call last):                                                                                                    File "/app/reproduce.py", line 137, in <module>
    print(next(engine("hi")))
          ^^^^^^^^^^^^^^^^^^                                                                                                                                                File "/app/reproduce.py", line 123, in __call__
    self.cm._prefill(input=prompt, generation_config=generation_config)                                                                                                     File "/usr/local/lib/python3.11/dist-packages/mlc_chat/chat_module.py", line 992, in _prefill
    self._prefill_func(                                                                                                                                                     File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__                                  File "tvm/_ffi/_cython/./packed_func.pxi", line 277, in tvm._ffi._cy3.core.FuncCall                                                                                       File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL                                                      File "/usr/local/lib/python3.11/dist-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err                                                                                                                                                            File "/workspace/mlc-llm/cpp/llm_chat.cc", line 1492, in mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#5}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const                       File "/workspace/mlc-llm/cpp/llm_chat.cc", line 847, in mlc::llm::LLMChat::PrefillStep(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool, mlc::llm::PlaceInPrompt, tvm::runtime::String)                                                                                                         File "/workspace/mlc-llm/cpp/llm_chat.cc", line 1203, in mlc::llm::LLMChat::ForwardTokens(std::vector<int, std::allocator<int> >, long)                                 ValueError: Traceback (most recent call last):                                                                                                                              12: mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#5}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
        at /workspace/mlc-llm/cpp/llm_chat.cc:1492
  11: mlc::llm::LLMChat::PrefillStep(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool, mlc::llm::PlaceInPrompt, tvm::runtime::String)
        at /workspace/mlc-llm/cpp/llm_chat.cc:847                                                                                                                           10: mlc::llm::LLMChat::ForwardTokens(std::vector<int, std::allocator<int> >, long)                                                                                              at /workspace/mlc-llm/cpp/llm_chat.cc:1203                                                                                                                          9: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)                                                  8: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::relax_vm::VirtualMachineImpl::GetClosureInternal(tvm::runtime::String const&, bool)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  7: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
  6: tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
  5: tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
  4: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<void (tvm::runtime::NDArray, tvm::runtime::NDArray)>::AssignTypedLambda<void (*)(tvm::runtime::NDArray, tvm::runtime::NDArray)>(void (*)(tvm::runtime::NDArray, tvm::runtime::NDArray), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)                                   3: tvm::runtime::BroadcastFromWorker0(tvm::runtime::NDArray, tvm::runtime::NDArray)
  2: tvm::runtime::GetCCLFunc(char const*)
  1: tvm::runtime::DiscoWorker::ThreadLocal()
  0: _ZN3tvm7runtime6deta
  File "/workspace/tvm/src/runtime/disco/worker.cc", line 46
```

**Comment by junrushao** [comment]
@LeshengJin could you try out if you can reproduce this issue?

**Comment by technillogue** [comment]
I think this is because we build on A100s but were trying to run on H100. When we do `--target "cuda"` it defaults to something like this:

```
Target configured: cuda -keys=cuda,gpu -arch=sm_80 -max_num_threads=1024 -thread_warp_size=32
```

Specifying `--target 'cuda -arch=sm_90'` that shows the correct configuration but then fails with this error:

```
> python3 -m mlc_llm.build --hf-path dist/models/llama-2-70b-hf --target 'cuda -arch=sm_90' --quantization q4f16_1 --use-cuda-graph
Weights exist at dist/models/llama-2-70b-hf, skipping download.
Using path "dist/models/llama-2-70b-hf" for model "llama-2-70b-hf"
Target configured: cuda -keys=cuda,gpu -arch=sm_90 -max_num_threads=1024 -thread_warp_size=32
Load cached module from dist/llama-2-70b-hf-q4f16_1/mod_cache_before_build.pkl and skip tracing. You can use --use-cache=0 to retrace
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/moin/mlc-llm/mlc_llm/build.py", line 46, in <module>
    main()
  File "/home/moin/mlc-llm/mlc_llm/build.py", line 42, in main
    core.build_model_from_args(parsed_args)
  File "/home/moin/mlc-llm/mlc_llm/core.py", line 705, in build_model_from_args
    build(mod, args)
  File "/home/moin/mlc-llm/mlc_llm/core.py", line 570, in build
    mod_deploy = dl.ApplyDefaultSchedule(  # pylint: disable=not-callable
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/tvm/ir/transform.py", line 238, in __call__
    return _ffi_transform_api.RunPass(self, mod)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "tvm/_ffi/_cython/./packed_func.pxi", line 56, in tvm._ffi._cy3.core.tvm_callback
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/tvm/ir/transform.py", line 307, in _pass_func
    return inst.transform_module(mod, ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/tvm/dlight/base/transform.py", line 64, in transform_module
    sch = _apply_rules(func, target, self.rules, tunable=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/tvm/dlight/base/transform.py", line 80, in _apply_rules
    space = rule.apply(func, target, tunable)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/tvm/dlight/gpu/gemv.py", line 197, in apply
    self.sch_inner_reduction(sch, target, block, vector_input_buffers, epilogue)
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/tvm/dlight/gpu/gemv.py", line 490, in sch_inner_reduction
    return apply(
           ^^^^^^
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/tvm/dlight/gpu/gemv.py", line 269, in apply
    and shared_mem_usage.value <= target.max_shared_memory_per_block
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/tvm/target/target.py", line 217, in max_shared_memory_per_block
    return int(self.attrs["max_shared_memory_per_block"])
               ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/tvm/ir/container.py", line 62, in __getitem__
    return _ffi_api.MapGetItem(self, k)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm.error.InternalError: Traceback (most recent call last):
  1: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::__mk_TVM16::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::__mk_TVM16, tvm::runtime::TVMRetValue)
  0: _ZN3tvm7runtime6deta
  File "/workspace/tvm/src/runtime/container.cc", line 153
InternalError: Check failed: (it != n->end()) is false: cannot find the corresponding key in the Map
```

I can see the targets are configured here, but I'm not sure how to specify a specific cross-compilation target architecture. Do I just need to --target cuda-multiarch? Is there a way to specify, for example, sm_80,sm_86,sm_90 _without_ sm_70,sm_75?

https://github.com/mlc-ai/mlc-llm/blob/da07940e05ba5dd2661168b020aa7908ce699282/mlc_llm/utils.py#L643-L661

**Comment by tqchen** [comment]
try to specify `cuda-multiarch`, the `compute_versions = [70, 72, 75, 80, 86, 87, 89, 90]` should corresponds to the list of the compute we support

**Comment by tqchen** [comment]
@technillogue lmk if things are ok after #1326

**Comment by technillogue** [comment]
I haven't gotten the chance to thoroughly test cross-compilation or multiarch, cuobjdump suggests that cuda-multiarch still builds for the sm of the compiling machine only

I also think that's more of a workaround and there is still some thread local variable that is being misused

**Comment by MasterJH5574** [comment]
Gonna close this issue due to inactivity. Please open new ones if there are any other problems.
