### ISSUE TITLE
[Bug] regression with mistral 7b: "prefill_chunk_size" is false:

### ISSUE THREAD

**Issue by chymian** [mlc-ai/mlc-llm#1316]
## 🐛 Bug

running the benchmark with newly created images from today, the mistral model benchmark trows an error:

## To Reproduce

follow the llm-perf-bench
```log
time python -m mlc_chat.cli.benchmark \
        --model ${PATH_TEST}/params \
        --device "cuda" \
        --prompt "What is the meaning of life?" \
        --generate-length 256
+ python -m mlc_chat.cli.benchmark --model /tmp/test//params --device cuda --prompt 'What is the meaning of life?' --generate-length 256
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/micromamba/envs/python311/lib/python3.11/site-packages/mlc_chat/cli/benchmark.py", line 72, in <module>
    main()
  File "/root/micromamba/envs/python311/lib/python3.11/site-packages/mlc_chat/cli/benchmark.py", line 58, in main
    chat_module = ChatModule(
                  ^^^^^^^^^^^
  File "/root/micromamba/envs/python311/lib/python3.11/site-packages/mlc_chat/chat_module.py", line 710, in __init__
    self._reload(self.model_lib_path, self.model_path, user_chat_config_json_str)
  File "/root/micromamba/envs/python311/lib/python3.11/site-packages/mlc_chat/chat_module.py", line 922, in _reload
    self._reload_func(lib, model_path, app_config_json)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/root/micromamba/envs/python311/lib/python3.11/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 1457, in mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 503, in mlc::llm::LLMChat::Reload(tvm::runtime::TVMArgValue, tvm::runtime::String, tvm::runtime::String)
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 483, in mlc::llm::LLMChat::LoadJSONOverride(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 421, in mlc::llm::LLMChat::LoadJSONOverride(picojson::value const&, bool)
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
        at /workspace/mlc-llm/cpp/llm_chat.cc:1457
  2: mlc::llm::LLMChat::Reload(tvm::runtime::TVMArgValue, tvm::runtime::String, tvm::runtime::String)
        at /workspace/mlc-llm/cpp/llm_chat.cc:503
  1: mlc::llm::LLMChat::LoadJSONOverride(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
        at /workspace/mlc-llm/cpp/llm_chat.cc:483
  0: mlc::llm::LLMChat::LoadJSONOverride(picojson::value const&, bool)
        at /workspace/mlc-llm/cpp/llm_chat.cc:421
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 421
TVMError: Check failed: (config.count("prefill_chunk_size")) is false: Need to specify chunk size if using sliding window attention.
```
## Expected behavior
just work 

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): cuda 
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): ubu 22.04
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): 4 x 3070
 - How you installed MLC-LLM (`conda`, source):
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable): 545.23.08
 - CUDA/cuDNN version (if applicable): 12.1
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by MasterJH5574** [comment]
Hi @chymian thanks for reporting. Yes this issue is likely due to a recently merged PR, after which we missed to update the config accordingly. We will work on a fix soon and report back.

**Comment by CharlieFRuan** [comment]
Fixed on huggingface @chymian; changed from `sliding_window_chunk_size` to `prefill_chunk_size`.
