### ISSUE TITLE
[Bug] Cannot compile CodeLlama-7b-hf because of `wasm-ld: error: initial memory too small`

### ISSUE THREAD

**Issue by ClankPan** [mlc-ai/mlc-llm#1409]
## 🐛 Bug

I tried compile CodeLlama-7b-hf for webgpu with q4f32 quantization. However it failed with `wasm-ld: error: initial memory too small, 269728288 bytes needed`.

## To Reproduce

1. `git clone https://github.com/mlc-ai/web-llm`
1. `cd web-llm`
1. `mkdir -p dist/models`
1. `cd dist/models`
1. `git clone https://huggingface.co/codellama/CodeLlama-7b-hf`
1.  `cd ../..`
1. `python3 -m mlc_llm.build --model CodeLlama-7b-hf --target webgpu --quantization q4f32_1`

This showed following error message.
```
Using path "dist/models/CodeLlama-7b-hf" for model "CodeLlama-7b-hf"
Target configured: webgpu -keys=webgpu,gpu -max_num_threads=256
Load cached module from dist/CodeLlama-7b-hf-q4f32_1/mod_cache_before_build.pkl and skip tracing. You can use --use-cache=0 to retrace
[17:06:44] /Users/catalyst/Workspace/mlc-ai-package-self-runner/_work/package/package/tvm/src/target/llvm/codegen_llvm.cc:185: Warning: Set native vector bits to be 128 for wasm32
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/clankpan/mlc-llm/mlc_llm/build.py", line 47, in <module>
    main()
  File "/Users/clankpan/mlc-llm/mlc_llm/build.py", line 43, in main
    core.build_model_from_args(parsed_args)
  File "/Users/clankpan/mlc-llm/mlc_llm/core.py", line 923, in build_model_from_args
    build(mod, args)
  File "/Users/clankpan/mlc-llm/mlc_llm/core.py", line 762, in build
    ex.export_library(args.lib_path, **args.export_kwargs)
  File "/Users/clankpan/.pyenv/versions/anaconda3-2023.09-0/lib/python3.11/site-packages/tvm/relax/vm_build.py", line 146, in export_library
    return self.mod.export_library(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/clankpan/.pyenv/versions/anaconda3-2023.09-0/lib/python3.11/site-packages/tvm/runtime/module.py", line 624, in export_library
    return fcompile(file_name, files, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/clankpan/.pyenv/versions/anaconda3-2023.09-0/lib/python3.11/site-packages/tvm/contrib/emcc.py", line 79, in create_tvmjs_wasm
    raise RuntimeError(msg)
RuntimeError: Compilation error:
wasm-ld: error: initial memory too small, 269796256 bytes needed
emcc: error: '/opt/homebrew/Cellar/emscripten/3.1.50/libexec/llvm/bin/wasm-ld -o dist/CodeLlama-7b-hf-q4f32_1/CodeLlama-7b-hf-q4f32_1-webgpu.wasm /Users/clankpan/mlc-llm/3rdparty/tvm/web/dist/wasm/wasm_runtime.bc /Users/clankpan/mlc-llm/3rdparty/tvm/web/dist/wasm/tvmjs_support.bc /Users/clankpan/mlc-llm/3rdparty/tvm/web/dist/wasm/webgpu_runtime.bc /var/folders/cj/vx3ycjy53klgp5r3nszk171w0000gn/T/tmp6_xuspag/lib0.o /var/folders/cj/vx3ycjy53klgp5r3nszk171w0000gn/T/tmp6_xuspag/devc.o -L/opt/homebrew/Cellar/emscripten/3.1.50/libexec/cache/sysroot/lib/wasm32-emscripten /opt/homebrew/Cellar/emscripten/3.1.50/libexec/cache/sysroot/lib/wasm32-emscripten/crt1_reactor.o -lGL -lal -lhtml5 -lbulkmemory -lstandalonewasm-nocatch-memgrow -lstubs -lnoexit -lc -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /var/folders/cj/vx3ycjy53klgp5r3nszk171w0000gn/T/tmp7gxkykanlibemscripten_js_symbols.so --import-undefined --strip-debug --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=stackSave --export-if-defined=stackRestore --export-if-defined=stackAlloc --export-if-defined=__errno_location --export-table -z stack-size=65536 --initial-memory=83886080 --max-memory=2147483648 --entry=_initialize --table-base=1 --global-base=1024' failed (returned 1)
```

## Expected behavior

I expected code llama can be build same as [Llama-2-7b-chat-hf-q4f32_1](https://huggingface.co/mlc-ai/mlc-chat-Llama-2-7b-chat-hf-q4f32_1/)

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): WebGPU
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): MacOS 14.1
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): Apple M3 Pro
 - How you installed MLC-LLM (`conda`, source): conda `python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly mlc-ai-nightly`
 - How you installed TVM-Unity (`pip`, source): following this [page](https://llm.mlc.ai/docs/install/tvm.html)
 - Python version (e.g. 3.10): Python 3.11.5
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): `0ed0be0fdf006e9a9ae52f48e1cd25f0cc2c4637`
 - Any other relevant information:

## Additional context

If I increased the initial memory size by editing `tvm/contrib/emcc.py` from 80MiB to 320MiB, the compilation succeed. However chrome shows this error after initializing model.

```
Buffer size (1442840576) exceeds the max buffer size limit (1073741824).
 - While calling [Device].CreateBuffer([BufferDescriptor]).
```

**Comment by tqchen** [comment]
try to limi your max-seq-len to a smaller number, right now the model have a larger max-seq-len that might cause the model to request more than available vram

**Comment by ClankPan** [comment]
Thanks!! It was fixed.

**Comment by ClankPan** [comment]
It seems compilation flow was changed recently. Where can I set `max_seq_len` in `mlc_chat compile` command?

**Comment by tqchen** [comment]
you should be able to specify through mlc_chat gen_config, cc @CharlieFRuan on cross checking docs clarity

**Comment by ClankPan** [comment]
Which option is it? I could not find the option. 
```
❯ mlc_chat gen_config -h
usage: MLC LLM Configuration Generator [-h] --quantization {q0f16,q0f32,q3f16_1,q4f16_1,q4f32_1,q4f16_awq} [--model-type {auto,llama,mistral,gpt2,gpt_neox,gpt_bigcode}] --conv-template
                                       {guanaco,mistral_default,oasst,conv_one_shot,vicuna_v1.1,minigpt,open_hermes_mistral,stablecode_completion,gpt2,codellama_instruct,LM,llama-2,stablelm,glm,wizardlm_7b,stablecode_instruct,gpt_bigcode,stablelm-3b,codellama_completion,redpajama_chat,llama_default,dolly,chatml,wizard_coder_or_math,gorilla,rwkv,rwkv_world,neural_hermes_mistral,moss}
                                       [--context-window-size CONTEXT_WINDOW_SIZE] [--sliding-window-size SLIDING_WINDOW_SIZE] [--prefill-chunk-size PREFILL_CHUNK_SIZE] [--tensor-parallel-shards TENSOR_PARALLEL_SHARDS] --output OUTPUT
                                       config

positional arguments:
  config                1) Path to a HuggingFace model directory that contains a `config.json` or 2) Path to `config.json` in HuggingFace format, or 3) The name of a pre-defined model architecture. A `config.json` file in HuggingFace format defines the
                        model architecture, including the vocabulary size, the number of layers, the hidden size, number of attention heads, etc. Example: https://huggingface.co/codellama/CodeLlama-7b-hf/blob/main/config.json. A HuggingFace directory
                        often contains a `config.json` which defines the model architecture, the non-quantized model weights in PyTorch or SafeTensor format, tokenizer configurations, as well as an optional `generation_config.json` provides additional
                        default configuration for text generation. Example: https://huggingface.co/codellama/CodeLlama-7b-hf/tree/main. Pre-defined model architectures include "llama2_7b", "llama2_13b", "llama2_70b", "codellama_7b", "codellama_13b",
                        "codellama_34b", "mistral_7b", "gpt2", "redpajama_3b_v1". (required)

options:
  -h, --help            show this help message and exit
  --quantization {q0f16,q0f32,q3f16_1,q4f16_1,q4f32_1,q4f16_awq}
                        The quantization mode we use to compile. If unprovided, will infer from `model`. (required, choices: q0f16, q0f32, q3f16_1, q4f16_1, q4f32_1, q4f16_awq)
  --model-type {auto,llama,mistral,gpt2,gpt_neox,gpt_bigcode}
                        Model architecture such as "llama". If not set, it is inferred from `mlc-chat-config.json`. (default: "auto", choices: auto, llama, mistral, gpt2, gpt_neox, gpt_bigcode)
  --conv-template {guanaco,mistral_default,oasst,conv_one_shot,vicuna_v1.1,minigpt,open_hermes_mistral,stablecode_completion,gpt2,codellama_instruct,LM,llama-2,stablelm,glm,wizardlm_7b,stablecode_instruct,gpt_bigcode,stablelm-3b,codellama_completion,redpajama_chat,llama_default,dolly,chatml,wizard_coder_or_math,gorilla,rwkv,rwkv_world,neural_hermes_mistral,moss}
                        Conversation template. It depends on how the model is tuned. Use "LM" for vanilla base model (required, choices: guanaco, mistral_default, oasst, conv_one_shot, vicuna_v1.1, minigpt, open_hermes_mistral, stablecode_completion,
                        gpt2, codellama_instruct, LM, llama-2, stablelm, glm, wizardlm_7b, stablecode_instruct, gpt_bigcode, stablelm-3b, codellama_completion, redpajama_chat, llama_default, dolly, chatml, wizard_coder_or_math, gorilla, rwkv,
                        rwkv_world, neural_hermes_mistral, moss)
  --context-window-size CONTEXT_WINDOW_SIZE
                        Option to provide the maximum sequence length supported by the model. This is usually explicitly shown as context length or context window in the model card. If this option is not set explicitly, by default, it will be determined
                        by `context_window_size` or `max_position_embeddings` in `config.json`, and the latter is usually inaccurate for some models. (default: "None")
  --sliding-window-size SLIDING_WINDOW_SIZE
                        (Experimental) The sliding window size in sliding window attention (SWA). This optional field overrides the `sliding_window_size` in config.json for those models that use SWA. Currently only useful when compiling Mistral. This
                        flag subjects to future refactoring. (default: "None")
  --prefill-chunk-size PREFILL_CHUNK_SIZE
                        (Experimental) The chunk size during prefilling. By default, the chunk size is the same as sliding window or max sequence length. This flag subjects to future refactoring. (default: "None")
  --tensor-parallel-shards TENSOR_PARALLEL_SHARDS
                        Number of shards to split the model into in tensor parallelism multi-gpu inference. (default: "None")
  --output OUTPUT, -o OUTPUT
                        The output directory for generated configurations, including `mlc-chat-config.json` and tokenizer configuration. (required)
```




Just in case I'v changed `position_embedding_base` smaller in `mlc-chat-config.json` but it showed  following error while generating.

```
Generate error, TypeError: Failed to execute 'createBuffer' on 'GPUDevice': Failed to read the 'size' property from 'GPUBufferDescriptor': Value is outside the 'unsigned long long' value range.
```

Current config params are here

```
{
  "model_lib": "CodeLlama-7b-hf-q4f32_1",
  "local_id": "CodeLlama-7b-hf-q4f32_1",
  "model_type": "llama",
  "quantization": "q4f32_1",
  "model_config": {
    "hidden_size": 4096,
    "intermediate_size": 11008,
    "num_attention_heads": 32,
    "num_hidden_layers": 32,
    "rms_norm_eps": 1e-05,
    "vocab_size": 32016,
    "position_embedding_base": 2048,
    "context_window_size": 4096,
    "prefill_chunk_size": 4096,
    "num_key_value_heads": 32,
    "head_dim": 128,
    "tensor_parallel_shards": 1
  },
  "vocab_size": 32016,
  "context_window_size": 4096,
  "sliding_window_size": -1,
  "prefill_chunk_size": 4096,
  "tensor_parallel_shards": 1,
  "mean_gen_len": 512,
  "max_gen_len": 2048,
  "shift_fill_factor": 0.3,
  "temperature": 0.7,
  "repetition_penalty": 1.0,
  "top_p": 0.95,
  "conv_template": "llama-2",
  "pad_token_id": 0,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "tokenizer_files": [
    "tokenizer.model",
    "tokenizer.json",
    "tokenizer_config.json"
  ],
  "version": "0.1.0"
}
```

**Comment by ClankPan** [comment]
> `Generate error, TypeError: Failed to execute 'createBuffer' on 'GPUDevice': Failed to read the 'size' property from 'GPUBufferDescriptor': Value is outside the 'unsigned long long' value range.`

This error was fixed by `--prefill_chunk_size 1024` option!

Thanks!!

**Comment by CharlieFRuan** [comment]
Thanks! For future reference, this error is brought up here in the WebGPU tab https://llm.mlc.ai/docs/compilation/compile_models.html#get-started
