### ISSUE TITLE
[Feature Request]  benchmark 

### ISSUE THREAD

**Issue by lambda7xx** [mlc-ai/mlc-llm#1443]
### lightllm

- `git clone https://huggingface.co/meta-llama/Llama-2-7b-hf `
- 
```cd ~/lightllm/```
open a terminal and run the below command
```
python -m lightllm.server.api_server --model_dir ～/Llama-2-7b-hf    \
                                     --host 0.0.0.0                 \
                                     --port 8080                    \
                                     --tp 4                       \
                                     --max_total_token_num 120000  
```
- ``` cd ~/llmperf ```
open a new terminal and run the below command
```
export OPENAI_API_KEY=secret_abcdefg
export OPENAI_API_BASE="http://127.0.0.1:8080/v1"

python token_benchmark_ray.py \
--model "meta-llama/Llama-2-7b-hf" \
--mean-input-tokens 550 \
--stddev-input-tokens 150 \
--mean-output-tokens 150 \
--stddev-output-tokens 10 \
--max-num-completed-requests 2 \
--timeout 600 \
--num-concurrent-requests 1 \
--results-dir "result_outputs" \
--llm-api openai \
--additional-sampling-params '{}'  
```

**Comment by lambda7xx** [comment]
@MasterJH5574 

I use the command to run benchmark for the mlc, and I found some error
 
- the command  for mlc 
```
python -m mlc_chat.rest --model ~/dist/prebuilt/mlc-chat-Llama-2-7b-chat-hf-q4f16  --host 127.0.0.1 --port 8080
```
- the command for llmperf
```
export OPENAI_API_KEY=secret_abcdefg
export OPENAI_API_BASE="http://0.0.0.0:8080/v1"

python token_benchmark_ray.py \
--model "mlc-chat-Llama-2-7b-chat-hf-q4f16" \
--mean-input-tokens 550 \
--stddev-input-tokens 150 \
--mean-output-tokens 150 \
--stddev-output-tokens 10 \
--max-num-completed-requests 2 \
--timeout 600 \
--num-concurrent-requests 1 \
--results-dir "result_outputs" \
--llm-api openai \
--additional-sampling-params '{}' 
```
- the error log
```
INFO:     Started server process [246182]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "lib/python3.10/site-packages/mlc_chat/rest.py", line 276, in request_chat_completion
    session["chat_mod"].reset_chat()  # Reset previous history, KV cache, etc.
KeyError: 'chat_mod'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
```
it seems the rest.py has some bug

**Comment by lambda7xx** [comment]
new error

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "lib/python3.10/site-packages/mlc_chat/rest.py", line 289, in request_chat_completion
    session["chat_mod"]._prefill(  # pylint: disable=protected-access
  File "lib/python3.10/site-packages/mlc_chat/chat_module.py", line 982, in _prefill
    raise ValueError("Only user and assistant roles are supported.")
ValueError: Only user and assistant roles are supported.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "lib/python3.10/site-packages/mlc_chat/rest.py", line 289, in request_chat_completion
    session["chat_mod"]._prefill(  # pylint: disable=protected-access
  File "lib/python3.10/site-packages/mlc_chat/chat_module.py", line 982, in _prefill
    raise ValueError("Only user and assistant roles are supported.")
ValueError: Only user and assistant roles are supported.


```

**Comment by lambda7xx** [comment]
## run [llmperf](https://github.com/ray-project/llmperf/tree/main) on mlc-llm
- Download pre-quantized weights and Download pre-compiled model library. 
 ```
 git lfs install && mkdir -p dist/prebuilt
git clone https://huggingface.co/mlc-ai/mlc-chat-Llama-2-7b-chat-hf-q4f16_1 \
                          dist/prebuilt/mlc-chat-Llama-2-7b-chat-hf-q4f16_1
```
- start the mlc-llm
```
python -m mlc_chat.rest --model Llama-2-7b-chat-hf-q4f16_1  --host 127.0.0.1 --port 8080 
```
- run the llmperf 
```
export OPENAI_API_KEY=secret_abcdefg
export OPENAI_API_BASE="http://127.0.0.1:8080/v1"

python token_benchmark_ray.py \
--model "mlc-chat-Llama-2-7b-chat-hf-q4f16" \
--mean-input-tokens 550 \
--stddev-input-tokens 150 \
--mean-output-tokens 150 \
--stddev-output-tokens 10 \
--max-num-completed-requests 2 \
--timeout 600 \
--num-concurrent-requests 1 \
--results-dir "result_outputs" \
--llm-api openai \
--additional-sampling-params '{}'
```
