### ISSUE TITLE
[Bug] Model compilation with CUTLASS on Jetson Orin AGX

### ISSUE THREAD

**Issue by stevelaskaridis** [mlc-ai/mlc-llm#1466]
## 🐛 Bug

When compiling a model on jetson orin agx (probably applies to jetson orin nano), there is an issue with on model conversion when compiling CUTLASS kernels. The code is breaking somewhere between 9bf5723945ca6016a50eedffae295390b7c11ac6 and 5dc809efb894640c494066b0c07ff0a69b8ee481.

## To Reproduce

1. Checkout (5dc809efb894640c494066b0c07ff0a69b8ee481)
2. Compile with the flags from [here](https://github.com/dusty-nv/jetson-containers/blob/cbfc31cdb21de96b9adbd114c1df6f607272136e/packages/llm/mlc/Dockerfile#L49-L79)
3. Install tvm python wheel
4. Run build.py for a model (tried with llama-2-7b-chat-hf) `python3 build.py --artifact-path <path_to_models> --model Llama-2-7b-chat-hf --quantization q4f16_1 --max-seq-len 4096 --target cuda --use-cuda-graph --use-flash-attn-mqa --use-cache 0`

**Result:** 

```
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    main()
  File "/tmp/mlc_llm/build.py", line 43, in main
    core.build_model_from_args(parsed_args)
  File "/tmp/mlc_llm/core.py", line 903, in build_model_from_args
    mod = mod_transform_before_build(mod, param_manager, args, model_config)
  File "/tmp/mlc_llm/core.py", line 635, in mod_transform_before_build
    mod = tvm.transform.Sequential(
  File "/usr/local/lib/python3.8/dist-packages/tvm/ir/transform.py", line 238, in __call__
    return _ffi_transform_api.RunPass(self, mod)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/usr/local/lib/python3.8/dist-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "tvm/_ffi/_cython/./packed_func.pxi", line 56, in tvm._ffi._cy3.core.tvm_callback
  File "/usr/local/lib/python3.8/dist-packages/tvm/contrib/cutlass/build.py", line 1050, in compile_cutlass_module
    c_source_module.export_library(lib_path, workspace_dir=tmp_dir, **compile_options)
  File "/usr/local/lib/python3.8/dist-packages/tvm/runtime/module.py", line 624, in export_library
    return fcompile(file_name, files, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tvm/contrib/cc.py", line 87, in create_shared
    _linux_compile(output, objects, options, cc, compile_shared=True)
  File "/usr/local/lib/python3.8/dist-packages/tvm/contrib/cc.py", line 303, in _linux_compile
    raise RuntimeError(msg)
RuntimeError: Compilation error:

# ... some warning and notes on redefinitions of LOG and DCHECK ...

./tmp/lib0.cu(78): error: identifier "$" is undefined

./tmp/lib0.cu(78): error: too few arguments for class template "AttentionKernel"

./tmp/lib0.cu(78): error: expected a ";"

./tmp/lib0.cu(85): warning: parsing restarts here after previous syntax error

./tmp/lib0.cu(87): error: name followed by "::" must be a class or namespace name

./tmp/lib0.cu(87): error: a class or namespace qualified name is required

./tmp/lib0.cu(87): error: global-scope qualifier (leading "::") is not allowed

./tmp/lib0.cu(87): error: expected a ";"

./tmp/lib0.cu(88): error: identifier "p" is undefined

./tmp/lib0.cu(92): error: name followed by "::" must be a class or namespace name

./tmp/lib0.cu(94): error: name followed by "::" must be a class or namespace name

./tmp/lib0.cu(95): error: identifier "$" is undefined

./tmp/lib0.cu(95): error: expected a ")"

./tmp/lib0.cu(96): error: expected a ")"

./tmp/lib0.cu(145): error: cannot deduce "auto" type

./tmp/lib0.cu(146): error: name followed by "::" must be a class or namespace name

./tmp/lib0.cu(146): error: a class or namespace qualified name is required

./tmp/lib0.cu(146): error: expected a ")"

./tmp/lib0.cu(148): warning: variable "once" was declared but never referenced

./tmp/lib0.cu(155): error: name followed by "::" must be a class or namespace name

./tmp/lib0.cu(251): error: identifier "$" is undefined

./tmp/lib0.cu(251): error: too few arguments for class template "AttentionKernel"

./tmp/lib0.cu(251): error: expected a ";"

./tmp/lib0.cu(258): warning: parsing restarts here after previous syntax error

./tmp/lib0.cu(260): error: name followed by "::" must be a class or namespace name

./tmp/lib0.cu(260): error: a class or namespace qualified name is required

./tmp/lib0.cu(260): error: global-scope qualifier (leading "::") is not allowed

./tmp/lib0.cu(260): error: expected a ";"

./tmp/lib0.cu(261): error: identifier "p" is undefined

./tmp/lib0.cu(265): error: name followed by "::" must be a class or namespace name

./tmp/lib0.cu(267): error: name followed by "::" must be a class or namespace name

./tmp/lib0.cu(268): error: identifier "$" is undefined

./tmp/lib0.cu(268): error: expected a ")"

./tmp/lib0.cu(269): error: expected a ")"

./tmp/lib0.cu(318): error: cannot deduce "auto" type

./tmp/lib0.cu(319): error: name followed by "::" must be a class or namespace name

./tmp/lib0.cu(319): error: a class or namespace qualified name is required

./tmp/lib0.cu(319): error: expected a ")"

./tmp/lib0.cu(321): warning: variable "once" was declared but never referenced

./tmp/lib0.cu(328): error: name followed by "::" must be a class or namespace name

36 errors detected in the compilation of "./tmp/lib0.cu".

Command line: nvcc -shared -o ./tmp/cutlass.o ./tmp/lib0.cu -c -DCUTLASS_ENABLE_TENSOR_CORE_MMA=1 -gencode=arch=compute_80,code=[sm_80,compute_80] -DNDEBUG -Xcompiler=-fPIC -Xcompiler=-Wconversion -Xcompiler=-fno-strict-aliasing -Xcompiler=-fvisibility=hidden -O3 -std=c++17 -I/usr/local/lib/python3.8/dist-packages/tvm/contrib/cutlass/../../3rdparty/cutlass/include -I/usr/local/lib/python3.8/dist-packages/tvm/contrib/cutlass/../../3rdparty/cutlass/tools/util/include -I/usr/local/lib/python3.8/dist-packages/tvm/contrib/cutlass/../../3rdparty/cutlass/examples/41_fused_multi_head_attention -I/usr/local/lib/python3.8/dist-packages/tvm/contrib/cutlass/../../3rdparty/cutlass/../cutlass_fpA_intB_gemm -t 12 -I/tmp/mlc-llm3rdparty/tvm/include -I/tmp/mlc-llm3rdparty/tvm/3rdparty/dlpack/include -I/tmp/mlc-llm3rdparty/tvm/3rdparty/dmlc-core/include
```

## Expected behavior

Expected behaviour is that the model compiles with the appropriate cutlass kernels compiled for the .so library.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Linux (5.10.104-tegra)
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) Jetson Orin AGX
 - How you installed MLC-LLM (`conda`, source): no, building from source
 - How you installed TVM-Unity (`pip`, source): no, building from source
 - Python version (e.g. 3.10): Python 3.8.10
 - GPU driver version (if applicable): JETPACK R35.2.1
 - CUDA/cuDNN version (if applicable): Build cuda_11.4.r11.4/compiler.31964100_0
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 ```
 USE_NVTX: OFF
USE_GTEST: OFF
SUMMARIZE: ON
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU:
CUDA_VERSION: 11.4
USE_LIBBACKTRACE: OFF
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: ON
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: OFF
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: ON
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM:
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: ON
USE_GRAPH_EXECUTOR_CUDA_GRAPH: ON
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: /usr/bin/llvm-config --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: OFF
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: NOT-FOUND
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: ON
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: NOT-FOUND
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: ON
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: OFF
USE_NNPACK: OFF
LLVM_VERSION: 10.0.0
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: OFF
USE_BNNS: OFF
USE_CUBLAS: ON
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: OFF
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION:
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: ON
TVM_CXX_COMPILER_PATH: /usr/bin/c++
HIDE_PRIVATE_SYMBOLS: ON
 ```
 - Any other relevant information: Tried inside and outside of [dusty-nv's](https://github.com/dusty-nv/jetson-containers) containers.

**Comment by WangFengtu1996** [comment]
maybe the link could help you.
https://www.jetson-ai-lab.com/tutorial_llava.html
