### ISSUE TITLE
[Bug] Model Compilation issue

### ISSUE THREAD

**Issue by Nick-infinity** [mlc-ai/mlc-llm#1468]
## 🐛 Bug

Model compilation fails , tvm.export() throws error
## To Reproduce
Compile any model with python wheel tvm or with source build tvm

1.
1.
1.

mlc_chat compile params/mlc-chat-config.json --device android -o test.tar --model-type mistral --quantization q4f16_1
[2023-12-20 19:15:42] INFO auto_config.py:68: Found model configuration: params/mlc-chat-config.json
[2023-12-20 19:15:42] WARNING auto_target.py:285: --system-lib-prefix is automatically picked from the filename, mistral_q4f16_1_, this allows us to use the filename as the model_lib in android/iOS builds. Please avoid renaming the .tar file when uploading the prebuilt.
[2023-12-20 19:15:42] INFO mistral_model.py:76: Using sliding window attention, setting context_window_size to -1
Compiling with arguments:
  --config          MistralConfig(hidden_size=4096, intermediate_size=17920, num_attention_heads=32, num_hidden_layers=32, rms_norm_eps=1e-05, vocab_size=32000, position_embedding_base=10000.0, context_window_size=-1, num_key_value_heads=8, head_dim=128, sliding_window_size=1024, prefill_chunk_size=128, attention_sink_size=4, tensor_parallel_shards=1, kwargs={'model_type': 'mistral', 'quantization': 'q4f16_1', 'model_config': {'hidden_size': 4096, 'intermediate_size': 17920, 'num_attention_heads': 32, 'num_hidden_layers': 32, 'rms_norm_eps': 1e-05, 'vocab_size': 32000, 'position_embedding_base': 10000.0, 'context_window_size': -1, 'num_key_value_heads': 8, 'head_dim': 128, 'sliding_window_size': 1024, 'prefill_chunk_size': 128, 'attention_sink_size': 4, 'tensor_parallel_shards': 1}, 'mean_gen_len': 128, 'max_gen_len': 512, 'shift_fill_factor': 0.3, 'temperature': 0.7, 'repetition_penalty': 1.0, 'top_p': 0.95, 'conv_template': 'mistral_default', 'pad_token_id': 2, 'bos_token_id': 1, 'eos_token_id': 2, 'tokenizer_files': ['tokenizer.model', 'tokenizer.json', 'tokenizer_config.json'], 'version': '0.1.0'})
  --quantization    GroupQuantize(name='q4f16_1', kind='group-quant', group_size=32, quantize_dtype='int4', storage_dtype='uint32', model_dtype='float16', num_elem_per_storage=8, num_storage_per_group=4, max_int_value=7)
  --model-type      mistral
  --target          {"thread_warp_size": 1, "host": {"kind": "llvm", "tag": "", "keys": ["arm_cpu", "cpu"], "mtriple": "aarch64-linux-android"}, "texture_spatial_limit": 16384, "max_threads_per_block": 256, "max_function_args": 128, "max_num_threads": 256, "kind": "opencl", "max_shared_memory_per_block": 16384, "tag": "", "keys": ["opencl", "gpu"]}
  --opt             flashinfer=0;cublas_gemm=1;cudagraph=0
  --system-lib-prefix "mistral_q4f16_1_"
  --output          test.tar
  --overrides       context_window_size=None;sliding_window_size=None;prefill_chunk_size=None;attention_sink_size=None;max_batch_size=None;tensor_parallel_shards=None
[2023-12-20 19:15:42] INFO compile.py:108: Creating model from: MistralConfig(hidden_size=4096, intermediate_size=17920, num_attention_heads=32, num_hidden_layers=32, rms_norm_eps=1e-05, vocab_size=32000, position_embedding_base=10000.0, context_window_size=-1, num_key_value_heads=8, head_dim=128, sliding_window_size=1024, prefill_chunk_size=128, attention_sink_size=4, tensor_parallel_shards=1, kwargs={'model_type': 'mistral', 'quantization': 'q4f16_1', 'model_config': {'hidden_size': 4096, 'intermediate_size': 17920, 'num_attention_heads': 32, 'num_hidden_layers': 32, 'rms_norm_eps': 1e-05, 'vocab_size': 32000, 'position_embedding_base': 10000.0, 'context_window_size': -1, 'num_key_value_heads': 8, 'head_dim': 128, 'sliding_window_size': 1024, 'prefill_chunk_size': 128, 'attention_sink_size': 4, 'tensor_parallel_shards': 1}, 'mean_gen_len': 128, 'max_gen_len': 512, 'shift_fill_factor': 0.3, 'temperature': 0.7, 'repetition_penalty': 1.0, 'top_p': 0.95, 'conv_template': 'mistral_default', 'pad_token_id': 2, 'bos_token_id': 1, 'eos_token_id': 2, 'tokenizer_files': ['tokenizer.model', 'tokenizer.json', 'tokenizer_config.json'], 'version': '0.1.0'})
[2023-12-20 19:15:42] INFO compile.py:111: Exporting the model to TVM Unity compiler
Traceback (most recent call last):
  File "/home/azureuser/.local/bin/mlc_chat", line 8, in <module>
    sys.exit(main())
  File "/home/azureuser/.local/lib/python3.8/site-packages/mlc_chat/__main__.py", line 24, in main
    cli.main(sys.argv[2:])
  File "/home/azureuser/.local/lib/python3.8/site-packages/mlc_chat/cli/compile.py", line 114, in main
    compile(
  File "/home/azureuser/.local/lib/python3.8/site-packages/mlc_chat/compiler/compile.py", line 170, in compile
    _compile(args, model_config)
  File "/home/azureuser/.local/lib/python3.8/site-packages/mlc_chat/compiler/compile.py", line 112, in _compile
    mod, named_params, ext_mods = model.export_tvm(
TypeError: export_tvm() got an unexpected keyword argument 'allow_extern'
## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source): conda
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.8
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by junrushao** [comment]
It’s because the pip wheel is a bit behind the mainline TVM Unity branch. @CharlieFRuan will do a sync quickly

**Comment by Nick-infinity** [comment]
@junrushao I have compiled the mlc/relax from source and exported its path. I got the same error

**Comment by Nick-infinity** [comment]
Got it, waiting for the fixed wheel

**Comment by CharlieFRuan** [comment]
Just updated https://github.com/mlc-ai/relax; the pip wheel may take some delay; feel free to build from source for now

**Comment by bethalianovike** [comment]
Hi @CharlieFRuan, I tried to compile rwkv-raven-1b5 using the latest tvm-unity you mentioned (build from source), but it looks like it gave an error when building the model. Does the mlc-llm not support rwkv-raven anymore? 
I also tried to compile RedPajama, it works fine.
```
$ python3 -m mlc_llm.build --model ../dist/models/rwkv-raven-1b5 --target cuda --quantization q4f16_2 --use-cache 0
Using path "../dist/models/rwkv-raven-1b5" for model "rwkv-raven-1b5"
Target configured: cuda -keys=cuda,gpu -arch=sm_86 -max_num_threads=1024 -max_shared_memory_per_block=49152 -max_threads_per_block=1024 -registers_per_block=65536 -thread_warp_size=32
Traceback (most recent call last):
  File "/media/data/home/miniconda3/envs/mlc-chat-venv-310/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/media/data/home/miniconda3/envs/mlc-chat-venv-310/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/media/data/home/mlc-llm-1218/mlc_llm/build.py", line 47, in <module>
    main()
  File "/media/data/home/mlc-llm-1218/mlc_llm/build.py", line 43, in main
    core.build_model_from_args(parsed_args)
  File "/media/data/home/mlc-llm-1218/mlc_llm/core.py", line 834, in build_model_from_args
    mod, param_manager, params, model_config = model_generators[args.model_category].get_model(
  File "/media/data/home/mlc-llm-1218/mlc_llm/relax_model/rwkv.py", line 581, in get_model
    create_func(bb, param_manager, config, args.quantization, "prefill")
  File "/media/data/home/mlc-llm-1218/mlc_llm/relax_model/rwkv.py", line 495, in create_func
    bb.update_func(gv, f)
  File "/media/data/home/tvm-unity-1221/python/tvm/relax/block_builder.py", line 729, in update_func
    return _ffi_api.BlockBuilderUpdateFunction(self, gv, updated_func)  # type: ignore
  File "/media/data/home/tvm-unity-1221/python/tvm/_ffi/_ctypes/packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "/media/data/home/tvm-unity-1221/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/media/data/home/tvm-unity-1221/src/relax/ir/block_builder.cc", line 126, in tvm::relax::BlockBuilderImpl::UpdateFunction(tvm::GlobalVar const&, tvm::BaseFunc)
    context_mod_->Update(gv, function);
  File "/media/data/home/tvm-unity-1221/src/ir/module.cc", line 221, in tvm::IRModuleNode::Add(tvm::GlobalVar const&, tvm::BaseFunc const&, bool)
    AddUnchecked(var, checked_func);
  File "/media/data/home/tvm-unity-1221/src/ir/module.cc", line 229, in tvm::IRModuleNode::AddUnchecked(tvm::GlobalVar const&, tvm::BaseFunc const&)
    ICHECK_EQ((*it).second, var);
tvm.error.InternalError: Traceback (most recent call last):
  2: tvm::relax::BlockBuilderImpl::UpdateFunction(tvm::GlobalVar const&, tvm::BaseFunc)
        at /media/data/home/tvm-unity-1221/src/relax/ir/block_builder.cc:126
  1: tvm::IRModuleNode::Add(tvm::GlobalVar const&, tvm::BaseFunc const&, bool)
        at /media/data/home/tvm-unity-1221/src/ir/module.cc:221
  0: tvm::IRModuleNode::AddUnchecked(tvm::GlobalVar const&, tvm::BaseFunc const&)
        at /media/data/home/tvm-unity-1221/src/ir/module.cc:229
  File "/media/data/home/tvm-unity-1221/src/ir/module.cc", line 229
InternalError: Check failed: (*it).second == var (I.GlobalVar("prefill") vs. I.GlobalVar("prefill")) :
```

**Comment by CharlieFRuan** [comment]
We recently migrated the model building workflow: https://llm.mlc.ai/docs/compilation/compile_models.html

And unfortunately rwkv is not yet migrated (but definitely a TODO for us): https://github.com/mlc-ai/mlc-llm/tree/main/python/mlc_chat/compiler/model

However, rwkv breaking in the old flow is upexpected (probably broke due to some updates in tvm)

**Comment by CharlieFRuan** [comment]
Closing this issue for now. Feel free to open another one if issues persist!
