### ISSUE TITLE
[Question] ChatGLM is no longer supported?

### ISSUE THREAD

**Issue by xunkai55** [mlc-ai/mlc-llm#1512]
## ❓ General Questions

The new path (`convert_weight`) seems no longer support ChatGLM. Is it expected? Thanks!

```
 mlc_chat convert_weight --model ~/Dev/models/chatglm2-tiny \
    --quantization q4f16_1 \
    -o dist/chatglm2-tiny-q4f16_1-MLC
[2023-12-29 18:07:58] INFO auto_config.py:94: Found model configuration: /Users/badpoet/Dev/models/chatglm2-tiny/config.json
[2023-12-29 18:07:59] INFO auto_device.py:84: Not found device: cuda:0
[2023-12-29 18:07:59] INFO auto_device.py:84: Not found device: rocm:0
[2023-12-29 18:07:59] INFO auto_device.py:75: Found device: metal:0
[2023-12-29 18:07:59] INFO auto_device.py:84: Not found device: vulkan:0
[2023-12-29 18:08:00] INFO auto_device.py:84: Not found device: opencl:0
[2023-12-29 18:08:00] INFO auto_device.py:33: Using device: metal:0
[2023-12-29 18:08:00] INFO auto_weight.py:70: Finding weights in: /Users/badpoet/Dev/models/chatglm2-tiny
[2023-12-29 18:08:00] INFO auto_weight.py:129: Found source weight format: huggingface-torch. Source configuration: /Users/badpoet/Dev/models/chatglm2-tiny/pytorch_model.bin
[2023-12-29 18:08:00] INFO auto_weight.py:149: Not found Huggingface Safetensor
[2023-12-29 18:08:00] INFO auto_weight.py:106: Using source weight configuration: /Users/badpoet/Dev/models/chatglm2-tiny/pytorch_model.bin. Use `--source` to override.
[2023-12-29 18:08:00] INFO auto_weight.py:110: Using source weight format: huggingface-torch. Use `--source-format` to override.
[2023-12-29 18:08:00] INFO auto_config.py:131: Found model type: chatglm. Use `--model-type` to override.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlc-llm/bin/mlc_chat", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlc-llm/lib/python3.11/site-packages/mlc_chat/__main__.py", line 28, in main
    cli.main(sys.argv[2:])
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlc-llm/lib/python3.11/site-packages/mlc_chat/cli/convert_weight.py", line 86, in main
    model = detect_model_type(parsed.model_type, parsed.config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlc-llm/lib/python3.11/site-packages/mlc_chat/support/auto_config.py", line 133, in detect_model_type
    raise ValueError(f"Unknown model type: {model_type}. Available ones: {list(MODELS.keys())}")
ValueError: Unknown model type: chatglm. Available ones: ['llama', 'mistral', 'gpt2']

```

**Comment by CharlieFRuan** [comment]
Yea the new workflow (SLM) currently hasn't reached parity with the old one, we aim to support models like `ChatGLM` soon. Apologies for the inconvenience; stay tuned via https://llm.mlc.ai/docs/prebuilt_models.html#level-1-supported-model-architectures-the-all-in-one-table.

You could also try implementing one as well, we recently released a tutorial for adding a model to mlc-llm: https://llm.mlc.ai/docs/compilation/define_new_models.html

**Comment by MrRace** [comment]
any good news？

**Comment by tqchen** [comment]
cc @tlopex

**Comment by tlopex** [comment]
Got it. I'll try to support it in a few days.

**Comment by MasterJH5574** [comment]
Hi folks, just want to give you an update here. ChatGLM support is brought back just now, thanks to @tlopex 🎉
