### ISSUE TITLE
[Bug] Error compiling TinyLlama-Chat-v1.0

### ISSUE THREAD

**Issue by scottorly** [mlc-ai/mlc-llm#1530]
## To Reproduce
```
python3 -m mlc_llm.build --hf-path TinyLlama/TinyLlama-1.1B-Chat-v1.0 --target iphone --quantization q8f16_1 --use-cache 0 --use-safetensors                                                                               ─╯
Updated Git hooks.
Git LFS initialized.
Cloning into 'dist/models/TinyLlama-1.1B-Chat-v1.0'...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 54 (delta 18), reused 0 (delta 0), pack-reused 3
Unpacking objects: 100% (54/54), 517.46 KiB | 3.38 MiB/s, done.
Downloaded weights to dist/models/TinyLlama-1.1B-Chat-v1.0
Using path "dist/models/TinyLlama-1.1B-Chat-v1.0" for model "TinyLlama-1.1B-Chat-v1.0"
Target configured: metal -keys=metal,gpu -libs=iphoneos -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=256 -thread_warp_size=1
Host CPU dection:
  Target triple: arm64-apple-darwin23.0.0
  Process triple: arm64-apple-darwin23.0.0
  Host CPU: apple-m1
Automatically using target for weight quantization: metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32
Get old param:   0%|                                                                                                                                                                                 | 0/137 [00:00<?, ?tensors/sTraceback (most recent call last):                                                                                                                                                                    | 0/227 [00:00<?, ?tensors/s]
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/scott/Developer/mlc-llm/mlc_llm/build.py", line 47, in <module>
    main()
  File "/Users/scott/Developer/mlc-llm/mlc_llm/build.py", line 43, in main
    core.build_model_from_args(parsed_args)
  File "/Users/scott/Developer/mlc-llm/mlc_llm/core.py", line 884, in build_model_from_args
    params = utils.convert_weights(mod_transform, param_manager, params, args)
  File "/Users/scott/Developer/mlc-llm/mlc_llm/utils.py", line 283, in convert_weights
    ex = relax.build(mod_transform, target=target)
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.8/site-packages/tvm/relax/vm_build.py", line 336, in build
    return _vmlink(
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.8/site-packages/tvm/relax/vm_build.py", line 247, in _vmlink
    lib = tvm.build(
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.8/site-packages/tvm/driver/build_module.py", line 294, in build
    rt_mod_host = _driver_ffi.tir_to_runtime(annotated_mods, target_host)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.8/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm._ffi.base.TVMError: Traceback (most recent call last):
  Did you forget to bind?
    Variable `scale` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `A` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `w_gathered` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `w_gathered` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `w_gathered` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `scale` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `A` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
  File "/Users/catalyst/Workspace/mlc-ai-package-self-runner/_work/package/package/tvm/src/tir/analysis/verify_memory.cc", line 205
RuntimeError: Memory verification failed with the following errors:
# from tvm.script import tir as T

@T.prim_func
def encode1(A: T.Buffer((2560, 2048), "float16"), w_gathered: T.Buffer((2560, 512), "uint32"), scale: T.Buffer((2560, 64), "float16")):
    T.func_attr({"target": T.target({"host": {"keys": ["arm_cpu", "cpu"], "kind": "llvm", "mcpu": "apple-m1", "mtriple": "arm64-apple-macos", "tag": ""}, "keys": ["metal", "gpu"], "kind": "metal", "max_function_args": 31, "max_num_threads": 256, "max_shared_memory_per_block": 32768, "max_threads_per_block": 1024, "tag": "", "thread_warp_size": 32}), "tir.is_scheduled": T.bool(True), "tir.noalias": T.bool(True)})
    max_abs_value = T.allocate([163840], "float16", "global")
    max_abs_value_1 = T.Buffer((163840,), "float16", data=max_abs_value)
    A_1 = T.Buffer((5242880,), "float16", data=A.data)
    for i, j, k in T.grid(2560, 64, 32):
        cse_var_1: T.int32 = i * 64 + j
        if k == 0:
            max_abs_value_1[cse_var_1] = T.float16(-65504)
        max_abs_value_1[cse_var_1] = T.max(max_abs_value_1[cse_var_1], T.fabs(A_1[i * 2048 + j * 32 + k]))
    scale_1 = T.Buffer((163840,), "float16", data=scale.data)
    for i, j in T.grid(2560, 64):
        cse_var_2: T.int32 = i * 64 + j
        scale_1[cse_var_2] = T.max(max_abs_value_1[cse_var_2], T.float16(0.0001)) * T.float16(0.007874015748031496)
    for i, j, k in T.grid(2560, 512, 4):
        cse_var_3: T.int32 = i * 512 + j
        w_gathered_1 = T.Buffer((1310720,), "uint32", data=w_gathered.data)
        if k == 0:
            w_gathered_1[cse_var_3] = T.uint32(0)
        w_gathered_1[cse_var_3] = T.bitwise_or(w_gathered_1[cse_var_3], T.shift_left(T.Cast("uint32", T.min(T.max(T.round(A_1[i * 2048 + j * 4 + k] / scale_1[i * 64 + j // 8] + T.float16(127)), T.float16(0)), T.float16(254))), T.Cast("uint32", k) * T.uint32(8)))
```

**Comment by junrushao** [comment]
Interesting. Could you share the URL to TinyLlama so that I could try out? Thanks in advance!

**Comment by junrushao** [comment]
OK I'm actually able to run this via the new flow:

```python
from mlc_chat import ChatConfig, ChatModule, callback
from mlc_chat.support import logging

logging.enable_logging()

MODEL = "HF://junrushao/TinyLlama-1.1B-Chat-v1.0-q4f16_1-MLC"

def main():
    cm = ChatModule(
        MODEL,
        device="metal", # "metal" for MacBook, and "cuda" for NV GPUs
        chat_config=ChatConfig(context_window_size=1024),
    )
    cm.generate(
        "What is the meaning of life?",
        progress_callback=callback.StreamToStdout(callback_interval=2),
    )

if __name__ == "__main__":
    main()
```

**Comment by junrushao** [comment]
Macbook:

<img width="1915" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/22515877/15de0889-9d3a-4db4-ab51-784a64b945c4">

CUDA:

<img width="961" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/22515877/3308ad37-5318-49d8-875e-e54d0e1ca778">

**Comment by scottorly** [comment]
> Interesting. Could you share the URL to TinyLlama so that I could try out? Thanks in advance!
https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0

**Comment by junrushao** [comment]
You may want to follow the tutorial: https://llm.mlc.ai/docs/deploy/ios.html.

**Comment by scottorly** [comment]
> You may want to follow the tutorial: https://llm.mlc.ai/docs/deploy/ios.html.

That doesn't address the compilation issue.

**Comment by junrushao** [comment]
Doing JIT compilation, it actually reveals the commands it uses, such as:

<img width="1512" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/22515877/58fda865-943e-4943-aa61-557cf6f004e4">

You may change the `--device` option from `cuda:0` to `iphone:generic` to obtain the model lib for iOS
