### ISSUE TITLE
[Bug] Model compilation fails with memory verification error on silicon

### ISSUE THREAD

**Issue by scottorly** [mlc-ai/mlc-llm#1541]
## 🐛 Bug
```
python3 -m mlc_llm.build --hf-path TinyLlama/TinyLlama-1.1B-Chat-v0.6 --target iphone --quantization q4f16_1 --use-cache 0 --use-safetensors                                            ─╯
Weights exist at dist/models/TinyLlama-1.1B-Chat-v0.6, skipping download.
Using path "dist/models/TinyLlama-1.1B-Chat-v0.6" for model "TinyLlama-1.1B-Chat-v0.6"
Target configured: metal -keys=metal,gpu -libs=iphoneos -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=256 -thread_warp_size=1
Host CPU dection:
  Target triple: arm64-apple-darwin23.0.0
  Process triple: arm64-apple-darwin23.0.0
  Host CPU: apple-m1
Automatically using target for weight quantization: metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/scott/Developer/mlc-llm/mlc_llm/build.py", line 47, in <module>
    main()
  File "/Users/scott/Developer/mlc-llm/mlc_llm/build.py", line 43, in main
    core.build_model_from_args(parsed_args)
  File "/Users/scott/Developer/mlc-llm/mlc_llm/core.py", line 884, in build_model_from_args
    params = utils.convert_weights(mod_transform, param_manager, params, args)
  File "/Users/scott/Developer/mlc-llm/mlc_llm/utils.py", line 283, in convert_weights
    ex = relax.build(mod_transform, target=target)
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/tvm/relax/vm_build.py", line 336, in build
    return _vmlink(
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/tvm/relax/vm_build.py", line 247, in _vmlink
    lib = tvm.build(
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/tvm/driver/build_module.py", line 294, in build
    rt_mod_host = _driver_ffi.tir_to_runtime(annotated_mods, target_host)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm._ffi.base.TVMError: Traceback (most recent call last):
  Did you forget to bind?
    Variable `scale` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `A` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `w_gathered` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `w_gathered` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `w_gathered` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `scale` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `A` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
  File "/Users/catalyst/Workspace/mlc-ai-package-self-runner/_work/package/package/tvm/src/tir/analysis/verify_memory.cc", line 205
RuntimeError: Memory verification failed with the following errors:
# from tvm.script import tir as T

@T.prim_func
def encode(var_A: T.handle, var_w_gathered: T.handle, var_scale: T.handle):
    T.func_attr({"target": T.target({"host": {"keys": ["arm_cpu", "cpu"], "kind": "llvm", "mcpu": "apple-m1", "mtriple": "arm64-apple-macos", "tag": ""}, "keys": ["metal", "gpu"], "kind": "metal", "max_function_args": 31, "max_num_threads": 256, "max_shared_memory_per_block": 32768, "max_threads_per_block": 1024, "tag": "", "thread_warp_size": 32}), "tir.is_scheduled": T.bool(True), "tir.noalias": T.bool(True)})
    vocab_size = T.int32()
    A = T.match_buffer(var_A, (vocab_size, 2048), "float16")
    w_gathered = T.match_buffer(var_w_gathered, (vocab_size, 256), "uint32")
    scale = T.match_buffer(var_scale, (vocab_size, 64), "float16")
    max_abs_value = T.allocate([vocab_size * 64], "float16", "global")
    max_abs_value_1 = T.Buffer((vocab_size * 64,), "float16", data=max_abs_value)
    A_1 = T.Buffer((vocab_size * 2048,), "float16", data=A.data)
    for i, j, k in T.grid(vocab_size, 64, 32):
        cse_var_1: T.int32 = i * 64 + j
        if k == 0:
            max_abs_value_1[cse_var_1] = T.float16(-65504)
        max_abs_value_1[cse_var_1] = T.max(max_abs_value_1[cse_var_1], T.fabs(A_1[i * 2048 + j * 32 + k]))
    scale_1 = T.Buffer((vocab_size * 64,), "float16", data=scale.data)
    for i, j in T.grid(vocab_size, 64):
        cse_var_2: T.int32 = i * 64 + j
        scale_1[cse_var_2] = T.max(max_abs_value_1[cse_var_2], T.float16(0.0001)) * T.float16(0.14285714285714285)
    for i, j, k in T.grid(vocab_size, 256, 8):
        cse_var_3: T.int32 = i * 256 + j
        w_gathered_1 = T.Buffer((vocab_size * 256,), "uint32", data=w_gathered.data)
        if k == 0:
            w_gathered_1[cse_var_3] = T.uint32(0)
        w_gathered_1[cse_var_3] = T.bitwise_or(w_gathered_1[cse_var_3], T.shift_left(T.Cast("uint32", T.min(T.max(T.round(A_1[i * 2048 + j * 8 + k] / scale_1[i * 64 + j // 4] + T.float16(7)), T.float16(0)), T.float16(14))), T.Cast("uint32", k) * T.uint32(4)))

```

**Comment by junrushao** [comment]
`mlc_llm.build` is the old flow and it's likely less convenient and a bit of buggy. Please switch to the new flow.

If you don't want to quantize TinyLlama yourself, please use our pre-quantized version:

```bash
MODEL_DIR=...
git clone https://huggingface.co/junrushao/TinyLlama-1.1B-Chat-v1.0-q4f16_1-MLC $MODEL_DIR
```

and then compile the model lib using $MODEL_DIR:

```bash
OUTPUT_FILE=mylib.tar
mlc_chat compile --help
mlc_chat compile $MODEL_DIR --opt O2 --overrides="context_window_size=512" --device "iphone:generic" --system-lib-prefix "tinyllama_" -o tinyllama.tar
```
