### ISSUE TITLE
Error! Cannot open libOpenCL! My Android Phone says this:

### ISSUE THREAD

**Issue by Onlineraider** [mlc-ai/mlc-llm#1562]
Error: MLCChat failed

Stack trace:
org.apache.tvm.Base$TVMError: InternalError: Check failed: (m_libHandler != nullptr) is false: Error! Cannot open libOpenCL!
Stack trace:
  File "/Users/kartik/mlc/mlc-llm/3rdparty/tvm/src/runtime/opencl/opencl_wrapper/opencl_wrapper.cc", line 128

	at org.apache.tvm.Base.checkCall(Base.java:173)
	at org.apache.tvm.Function.invoke(Function.java:130)
	at ai.mlc.mlcllm.ChatModule.reload(ChatModule.java:43)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:633)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:631)
	at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:534)
	at ai.mlc.mlcchat.AppViewModel$ChatState.mainReloadChat$lambda$3(AppViewModel.kt:631)
	at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$JJKpoRMMpp77FzXKA0o00i8lgRA(Unknown Source:0)
	at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

Error message:
InternalError: Check failed: (m_libHandler != nullptr) is false: Error! Cannot open libOpenCL!
Stack trace:
  File "/Users/kartik/mlc/mlc-llm/3rdparty/tvm/src/runtime/opencl/opencl_wrapper/opencl_wrapper.cc", line 128

System properties:
Android 11 
1st User 
Realme C21y

![Screenshot_20240108-175637](https://github.com/mlc-ai/mlc-llm/assets/156000465/e362ff4e-ac07-412a-8f5c-0f6dcf01438d)
![Screenshot_20240108-175629](https://github.com/mlc-ai/mlc-llm/assets/156000465/f4c412ef-db10-4166-8264-d45ad3dd7002)
![Screenshot_20240108-175627](https://github.com/mlc-ai/mlc-llm/assets/156000465/11f2392b-120e-43c4-adbc-db30e8ad2be2)

**Comment by madrazzl3** [comment]
@Onlineraider is there any progress on this issue? Have you been able to resolve it?

**Comment by tqchen** [comment]
This is likely opencl was not available on the phone

**Comment by nimbusNova** [comment]
what is the resolution the? how can we make opencl available on the phone?

**Comment by imagination24** [comment]
Is there any solution for this?
