### ISSUE TITLE
[Bug] VK_ERROR_INITIALIZATION_FAILED in Python package but CLI works fine

### ISSUE THREAD

**Issue by EntropyGenerator** [mlc-ai/mlc-llm#1585]
## 🐛 Bug

When using MLC LLM Python package, it fails to initialize vulkan devices. Using MLCChat CLI it works fine.

## To Reproduce

1. Install python package according to [this](url)
2. Run the demo
```Python
from mlc_chat import ChatModule
from mlc_chat.callback import StreamToStdout

cm = ChatModule(
    model="dist/Llama-2-7b-chat-hf-q4f16_1-MLC",
    model_lib_path="dist/prebuilt_libs/Llama-2-7b-chat-hf/Llama-2-7b-chat-hf-q4f16_1-cuda.so"
    # Vulkan on Linux: Llama-2-7b-chat-hf-q4f16_1-vulkan.so
    # Metal on macOS: Llama-2-7b-chat-hf-q4f16_1-metal.so
    # Other platforms: Llama-2-7b-chat-hf-q4f16_1-{backend}.{suffix}
)
cm.generate(prompt="What is the meaning of life?", progress_callback=StreamToStdout(callback_interval=2))
```
3. Error occurred:
```Bash
  File "/home/***/miniconda3/envs/mlc/lib/python3.11/site-packages/mlc_chat/chat_module.py", line 710, in __init__
    device_type = self.device.device_type
                  ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'device_type'
```

## Expected behavior

Correctly initialize: `mlc_chat_cli` works fine.

## Environment

 - Platform : AMD 5900HX using Vulkan
 - Operating system : Debian under PVE
 - Python version : 3.11
 - Vulkaninfo reports fine

## Additional context

When using tvm to initialize device, it fails too:
```Python
import tvm
vk=tvm.device("vulkan",0)
vk.exist()
```
```Bash
  File "/home/***/miniconda3/envs/mlc/lib/python3.11/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm.error.InternalError: Traceback (most recent call last):
  7: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<__mk_TVM1::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, __mk_TVM1, tvm::runtime::TVMRetValue)
  6: tvm::runtime::DeviceAPIManager::GetAPI(int, bool)
  5: tvm::runtime::DeviceAPIManager::GetAPI(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) [clone .isra.0]
  4: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::vulkan::__mk_TVM0::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::vulkan::__mk_TVM0, tvm::runtime::TVMRetValue)
  3: tvm::runtime::vulkan::VulkanDeviceAPI::Global()
  2: tvm::runtime::vulkan::VulkanDeviceAPI::VulkanDeviceAPI()
  1: tvm::runtime::vulkan::VulkanInstance::GetPhysicalDevices() const
  0: _ZN3tvm7runtime6deta
  File "/workspace/tvm/src/runtime/vulkan/vulkan_instance.cc", line 144
InternalError: Check failed: (__e == VK_SUCCESS) is false: Vulkan Error, code=-3: VK_ERROR_INITIALIZATION_FAILED
```

**Comment by dtkettler** [comment]
I am also experiencing the same issue.  Trying to use a vulkan model under Manjaro Linux.  mlc_chat_cli also works for me.

**Comment by EntropyGenerator** [comment]
SOLVED by building from source. Both tvm-unity and mlc_chat.
[How to build tvm unity](https://blog.csdn.net/Zyt2048/article/details/135669792)
After building both, install through python package.
## Verifying
`$ python -c "import tvm; print(tvm.vulkan().exist)"`
`True`

It seems that the issue is caused by prebuilt wheel.

**Comment by EntropyGenerator** [comment]
And the official documentation will lead to some unexpected error. Need some patience. However my build has some strange exceptions which don't break the whole process, here are some Traceback
```Python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/***/mlc-llm/python/mlc_chat/cli/model_metadata.py", line 152, in <module>
    main()
  File "/home/***/mlc-llm/python/mlc_chat/cli/model_metadata.py", line 146, in main
    _report_memory_usage(metadata, cfg)
  File "/home/***/mlc-llm/python/mlc_chat/cli/model_metadata.py", line 82, in _report_memory_usage
    kv_cache_bytes = metadata["kv_cache_bytes"]
                     ~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'kv_cache_bytes'
```
