### ISSUE TITLE
[Bug] Encountered a KeyError: 'kv_cache_bytes' when trying to initialize ChatModule.

### ISSUE THREAD

**Issue by LeoYelton** [mlc-ai/mlc-llm#1587]
---

## 🐛 Bug

Encountered a `KeyError: 'kv_cache_bytes'` when trying to initialize `ChatModule`.

## To Reproduce

1. Import `mlc_chat` and `StreamToStdout`.
2. Create an instance of `ChatModule`, specifying the model and model library path.
3. Error occurs upon the initialization of `ChatModule`.

Code sample:

```python
from mlc_chat import ChatModule
from mlc_chat.callback import StreamToStdout

cm = ChatModule(
    model="dist/Llama-2-7b-chat-hf-q4f16_1-MLC",
    model_lib_path="dist/prebuilt_libs/Llama-2-7b-chat-hf/Llama-2-7b-chat-hf-q4f16_1-vulkan.so"
)
```

Error message:

```
Traceback (most recent call last):
  File "/root/anaconda3/envs/mlc-llm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/mlc-llm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/mlc-llm/lib/python3.10/site-packages/mlc_chat/cli/model_metadata.py", line 102, in <module>
    main()
  File "/root/anaconda3/envs/mlc-llm/lib/python3.10/site-packages/mlc_chat/cli/model_metadata.py", line 96, in main
    _report_memory_usage(metadata)
  File "/root/anaconda3/envs/mlc-llm/lib/python3.10/site-packages/mlc_chat/cli/model_metadata.py", line 52, in _report_memory_usage
    kv_cache_bytes = metadata["kv_cache_bytes"]
KeyError: 'kv_cache_bytes'
```

## Expected behavior

Expected the `ChatModule` to initialize without throwing an error.

## Environment

 - Platform: Vulkan
 - Operating system: Linux (specific version)
 - Device: PC with AMD Radeon RX 7900 XTX GPU
 - How you installed MLC-LLM: `conda`
 - Python version: 3.10.13
 - GPU driver version: (if applicable)
 - Any other relevant information: Using ROCm version of `mlc_chat`

## Additional context

This issue occurs when trying to run `mlc_chat` with the Vulkan backend, which should be a supported configuration according to the documentation.

---

**Comment by MingkangW** [comment]
I also entcounter this bug, how can i fix it

**Comment by oreo-lp** [comment]
> I also entcounter this bug, how can i fix it

I added some code in _compute_memory_usage of python3.10/site-packages/mlc_chat/cli/model_metadata.py
before:
```
def _compute_memory_usage(metadata: Dict[str, Any], config: Union[Dict, ConfigBase]):
    params_bytes = 0.0
    for param in metadata["params"]:
        if all(isinstance(v, int) for v in param["shape"]):
            assert all(v > 0 for v in param["shape"]), "All shapes should be strictly positive."
            param_shape = param["shape"]
        else:
            # Contains dynamic shape; use config to look up concrete values
            param_shape = _read_dynamic_shape(param["shape"], config)
        params_bytes += math.prod(param_shape) * np.dtype(param["dtype"]).itemsize
    temp_func_bytes = 0.0
    for _func_name, func_bytes in metadata["memory_usage"].items():
        temp_func_bytes = max(temp_func_bytes, func_bytes)
    
    kv_cache_bytes = metadata["kv_cache_bytes"]

    return params_bytes, temp_func_bytes, kv_cache_bytes
```

and after:
```
def _compute_memory_usage(metadata: Dict[str, Any], config: Union[Dict, ConfigBase]):
    params_bytes = 0.0
    for param in metadata["params"]:
        if all(isinstance(v, int) for v in param["shape"]):
            assert all(v > 0 for v in param["shape"]), "All shapes should be strictly positive."
            param_shape = param["shape"]
        else:
            # Contains dynamic shape; use config to look up concrete values
            param_shape = _read_dynamic_shape(param["shape"], config)
        params_bytes += math.prod(param_shape) * np.dtype(param["dtype"]).itemsize
    temp_func_bytes = 0.0
    for _func_name, func_bytes in metadata["memory_usage"].items():
        temp_func_bytes = max(temp_func_bytes, func_bytes)
    
    if "kv_cache_bytes" in metadata.keys():
        kv_cache_bytes = metadata["kv_cache_bytes"]
    else:
        kv_cache_bytes = 0

    return params_bytes, temp_func_bytes, kv_cache_bytes
```
