### ISSUE TITLE
[Bug] StableLM model conversion not working

### ISSUE THREAD

**Issue by DavidGOrtega** [mlc-ai/mlc-llm#1616]
## 🐛 Bug

Hi, Im trying to convert my model which is based [on this one](https://huggingface.co/stabilityai/stablelm-3b-4e1t)

However I have an error

```
ValueError: Unknown model type: stablelm_epoch. Available ones: ['llama', 'mistral', 'gpt2', 'mixtral', 'gpt_neox', 'gpt_bigcode', 'phi-msft', 'phi']
```

## To Reproduce

1. git clone  https://huggingface.co/stabilityai/stablelm-3b-4e1t
2. mlc_chat convert_weight ./stablelm-3b-4e1t/  --quantization q0f32 -o ./stablelm-3b-4e1t/MLC

```
[2024-01-17 16:13:04] INFO auto_weight.py:106: Using source weight configuration: stablelm-3b-4e1t/model.safetensors.index.json. Use `--source` to override.
[2024-01-17 16:13:04] INFO auto_weight.py:110: Using source weight format: huggingface-safetensor. Use `--source-format` to override.
[2024-01-17 16:13:04] INFO auto_config.py:153: Found model type: stablelm_epoch. Use `--model-type` to override.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hf/bin/mlc_chat", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hf/lib/python3.9/site-packages/mlc_chat/__main__.py", line 28, in main
    cli.main(sys.argv[2:])
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hf/lib/python3.9/site-packages/mlc_chat/cli/convert_weight.py", line 86, in main
    model = detect_model_type(parsed.model_type, parsed.config)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hf/lib/python3.9/site-packages/mlc_chat/support/auto_config.py", line 155, in detect_model_type
    raise ValueError(f"Unknown model type: {model_type}. Available ones: {list(MODELS.keys())}")
ValueError: Unknown model type: stablelm_epoch. Available ones: ['llama', 'mistral', 'gpt2', 'mixtral', 'gpt_neox', 'gpt_bigcode', 'phi-msft', 'phi']
```

## Expected behavior

StableLM should be supported

## Environment
Python 3.9.18
pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly mlc-ai-nightly

**Comment by DavidGOrtega** [comment]
Should I force gpt_neox?

**Comment by DavidGOrtega** [comment]
I have tried to convert it with `gpt_neox` but I has several errors

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hf/bin/mlc_chat", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hf/lib/python3.9/site-packages/mlc_chat/__main__.py", line 28, in main
    cli.main(sys.argv[2:])
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hf/lib/python3.9/site-packages/mlc_chat/cli/convert_weight.py", line 87, in main
    convert_weight(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hf/lib/python3.9/site-packages/mlc_chat/interface/convert_weight.py", line 156, in convert_weight
    _convert_args(args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hf/lib/python3.9/site-packages/mlc_chat/interface/convert_weight.py", line 66, in _convert_args
    model_config = args.model.config.from_file(args.config)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hf/lib/python3.9/site-packages/mlc_chat/support/config.py", line 69, in from_file
    return cls.from_dict(json.load(in_file))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hf/lib/python3.9/site-packages/mlc_chat/support/config.py", line 49, in from_dict
    return cls(**fields, kwargs=kwargs)  # type: ignore[call-arg]
TypeError: __init__() missing 3 required positional arguments: 'use_parallel_residual', 'layer_norm_eps', and 'rotary_pct'
```

**Comment by dusty-nv** [comment]
+1 for StableLM / StableLM2 support

**Comment by DavidGOrtega** [comment]
@dusty-nv stable [should be supported already](https://github.com/mlc-ai/mlc-llm/pull/1008) however I cant make it work

**Comment by anibohara2000** [comment]
@DavidGOrtega we moved to a different model compilation pipeline than the earlier one. In the new pipeline, StableLM is not yet supported.

**Comment by DavidGOrtega** [comment]
I see, unity right? Im updating myself with unity and relax (getting through the mll_chat code).
Is there any real blocker or just only a matter of working hours? I can give it a try as an exercise.

Offtopic:
> Today I was thinking that the project is fairly difficult to follow. 
Could be reasonable to port litgpt to Unity? It could be more or less straight forward. What I like of litgpt is that the whole model is one file.

**Comment by anibohara2000** [comment]
Sure, you can try and submit a PR. You can take a look at #1669 for some more details

**Comment by CharlieFRuan** [comment]
StableLM is supported via https://github.com/mlc-ai/mlc-llm/pull/1701 and the prebuilt weights are uploaded to https://huggingface.co/mlc-ai.

Closing this issue for now:)
