### ISSUE TITLE
mlc_chat Python package error in Windows build

### ISSUE THREAD

**Issue by brian-pieces** [mlc-ai/mlc-llm#1630]
## 🐛 Bug

I was trying to compile a model with `mlc_chat compile` on Windows but it failed with the following error:

```
[2024-01-18 17:00:29] INFO auto_config.py:69: Found model configuration: dist\NeuralHermes-2.5-Mistral-7B-q4f16_1\params\mlc-chat-config.json
[2024-01-18 17:00:38] INFO auto_device.py:76: Found device: vulkan:0
[2024-01-18 17:00:38] INFO auto_device.py:76: Found device: vulkan:1
[2024-01-18 17:00:38] INFO auto_target.py:62: Found configuration of target device "vulkan:0": {"thread_warp_size": 1, "supports_float32": T.bool(True), "supports_int16": 1, "supports_int32": T.bool(True), "max_threads_per_block": 1024, "supports_int8": 1, "max_num_threads": 256, "kind": "vulkan", "max_shared_memory_per_block": 49152, "supports_16bit_buffer": 1, "tag": "", "keys": ["vulkan", "gpu"], "supports_float16": 1}
[2024-01-18 17:00:38] INFO auto_target.py:94: Found host LLVM triple: x86_64-pc-windows-msvc
[2024-01-18 17:00:38] INFO auto_target.py:95: Found host LLVM CPU: alderlake
[2024-01-18 17:00:38] INFO auto_config.py:153: Found model type: mistral. Use `--model-type` to override.
[2024-01-18 17:00:38] INFO mistral_model.py:62: Overriding prefill_chunk_size from 32768 to 4096 (sliding_window_size)
Compiling with arguments:
  --config          MistralConfig(hidden_size=4096, intermediate_size=14336, num_attention_heads=32, num_hidden_layers=32, rms_norm_eps=1e-05, vocab_size=32002, position_embedding_base=10000.0, num_key_value_heads=8, head_dim=128, sliding_window_size=4096, prefill_chunk_size=4096, attention_sink_size=4, tensor_parallel_shards=1, kwargs={})
  --quantization    GroupQuantize(name='q4f16_1', kind='group-quant', group_size=32, quantize_dtype='int4', storage_dtype='uint32', model_dtype='float16', linear_weight_layout='NK', num_elem_per_storage=8, num_storage_per_group=4, max_int_value=7)
  --model-type      mistral
  --target          {"thread_warp_size": 1, "host": {"mtriple": "x86_64-pc-windows-msvc", "tag": "", "kind": "llvm", "mcpu": "alderlake", "keys": ["cpu"]}, "supports_int16": 1, "supports_float32": T.bool(True), "supports_int32": T.bool(True), "max_threads_per_block": 1024, "supports_int8": 1, "max_num_threads": 256, "kind": "vulkan", "max_shared_memory_per_block": 49152, "supports_16bit_buffer": 1, "tag": "", "keys": ["vulkan", "gpu"], "supports_float16": 1}
  --opt             flashinfer=0;cublas_gemm=0;cudagraph=0
  --system-lib-prefix ""
  --output          dist\NeuralHermes-2.5-Mistral-7B-q4f16_1\NeuralHermes-2.5-Mistral-7B-q4f16_1-vulkan.dll
  --overrides       context_window_size=None;sliding_window_size=None;prefill_chunk_size=None;attention_sink_size=None;max_batch_size=None;tensor_parallel_shards=None
[2024-01-18 17:00:38] INFO compile.py:134: Creating model from: MistralConfig(hidden_size=4096, intermediate_size=14336, num_attention_heads=32, num_hidden_layers=32, rms_norm_eps=1e-05, vocab_size=32002, position_embedding_base=10000.0, num_key_value_heads=8, head_dim=128, sliding_window_size=4096, prefill_chunk_size=4096, attention_sink_size=4, tensor_parallel_shards=1, kwargs={})
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\brian\miniconda3\envs\mlc-compile\Scripts\mlc_chat.exe\__main__.py", line 7, in <module>
  File "C:\Users\brian\miniconda3\envs\mlc-compile\Lib\site-packages\mlc_chat\__main__.py", line 24, in main
    cli.main(sys.argv[2:])
  File "C:\Users\brian\miniconda3\envs\mlc-compile\Lib\site-packages\mlc_chat\cli\compile.py", line 131, in main
    compile(
  File "C:\Users\brian\miniconda3\envs\mlc-compile\Lib\site-packages\mlc_chat\interface\compile.py", line 224, in compile
    _compile(args, model_config)
  File "C:\Users\brian\miniconda3\envs\mlc-compile\Lib\site-packages\mlc_chat\interface\compile.py", line 150, in _compile
    model, _ = args.model.quantize[args.quantization.kind](model_config, args.quantization)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brian\miniconda3\envs\mlc-compile\Lib\site-packages\mlc_chat\model\mistral\mistral_quantization.py", line 18, in group_quant
    model: nn.Module = MistralForCasualLM(model_config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brian\miniconda3\envs\mlc-compile\Lib\site-packages\mlc_chat\model\mistral\mistral_model.py", line 387, in __init__
    self.model = MistralModel(config)
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brian\miniconda3\envs\mlc-compile\Lib\site-packages\mlc_chat\model\mistral\mistral_model.py", line 356, in __init__
    self.embed_tokens = nn.Embedding("vocab_size", config.hidden_size)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brian\miniconda3\envs\mlc-compile\Lib\site-packages\tvm\relax\frontend\nn\modules.py", line 623, in __init__
    self.weight = Parameter((num, dim), dtype=dtype)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brian\miniconda3\envs\mlc-compile\Lib\site-packages\tvm\relax\frontend\nn\core.py", line 232, in __init__
    super().__init__(_expr=Tensor.placeholder(shape, dtype=dtype, name="param")._expr)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brian\miniconda3\envs\mlc-compile\Lib\site-packages\tvm\relax\frontend\nn\core.py", line 147, in placeholder
    raise TypeError(f"Invalid shape: {shape}")
TypeError: Invalid shape: ('vocab_size', 4096)
```

Notice how the first arg in `nn.Embedding()` is a string "vocab_size" rather than `config.vocab_size`. I confirmed this problem by looking at my `mlc_chat` conda package and sure enough "vocab_size" is hardcoded in there. I'm guessing something went wrong during the packaging? I've been able to compile with both Mac and Linux today no problem.

## To Reproduce

1.  Install mlc_chat_nightly
2. Clone pre-converted model files
3. Run mlc_chat compile

## Expected behavior

Compiled model lib for Windows 

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Vulkan
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Windows
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): PC
 - How you installed MLC-LLM (`conda`, source): pip nightly
 - How you installed TVM-Unity (`pip`, source): pip nightly
 - Python version (e.g. 3.10): 3.11
 - GPU driver version (if applicable):  Vulkan Instance Version: 1.3.255
 - CUDA/cuDNN version (if applicable): N/A
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): 5212d143d1084f9ab14384794a21c2ab6e135cb5
 - Any other relevant information:

**Comment by junrushao** [comment]
It's a bug introduced very recently, unfortunately :((( We pushed a commit yesterday to get it fixed, and it should go into the latest wheel now

**Comment by brian-pieces** [comment]
Ah okay, good to know I wasn't going crazy 😅 Thanks for the quick response!

**Comment by brian-pieces** [comment]
@junrushao I downloaded the new wheel this morning and everything's working great. Thanks!
