### ISSUE TITLE
[Question] Is there any operator profiling method?

### ISSUE THREAD

**Issue by Lanssi** [mlc-ai/mlc-llm#1644]
## ❓ General Questions
I've managed to deploy RedPajama and Llama2 on various Android devices. But I'm curious about the performance of the operator. My question is that is there any method to achieve operator-level profiling?
As I've known, we have intrusive and non-intrusive ways. But I don't know exactly how I can achieve that.
Could somebody tell me? Thanks!

**Comment by tqchen** [comment]
https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_llm/testing/debug_chat.py provides tools to instrutment op level profiling

**Comment by tqchen** [comment]
https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_llm/testing/debug_compare.py

**Comment by Lanssi** [comment]
> https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_llm/testing/debug_chat.py provides tools to instrutment op level profiling

I really appreciate your reply! Thank you!

**Comment by bethalianovike** [comment]
Hi @tqchen 
I tried to run debug_chat.py to do op level profiling, but I run into an error message, do you have any solution to this issue? Thank you
Error message:
```
InternalError: Check failed: (e == cudaSuccess || e == cudaErrorCudartUnloading) is false: CUDA: operation not permitted when stream is capturing
terminate called after throwing an instance of 'tvm::runtime::InternalError'
  what():  [17:07:16] /home/betha/tvm-unity-slm-0613/src/runtime/cuda/cuda_device_api.cc:171: InternalError: Check failed: (e == cudaSuccess || e == cudaErrorCudartUnloading) is false: CUDA: operation not permitted when stream is capturing

```
Entire script:
```
$ python3 mlc_llm/testing/debug_chat.py --generate-len 128 --model ../dist/Llama-2-7b-chat-hf-q4f16_1-MLC_SLM_gpu_1 --model-lib ../dist/libs/Llama-2-7b-chat-hf-q4f16_1-MLC_SLM_gpu_1_cuda.so --debug-dir ./debug_chat "what is the difference between a dolphin and a whale?"
[2024-06-28 17:07:01] INFO auto_device.py:79: Found device: cuda:0
[2024-06-28 17:07:01] INFO auto_device.py:79: Found device: cuda:1
[2024-06-28 17:07:01] INFO auto_device.py:79: Found device: cuda:2
[2024-06-28 17:07:01] INFO auto_device.py:79: Found device: cuda:3
[2024-06-28 17:07:02] INFO auto_device.py:88: Not found device: rocm:0
[2024-06-28 17:07:03] INFO auto_device.py:88: Not found device: metal:0
[2024-06-28 17:07:05] INFO auto_device.py:79: Found device: vulkan:0
[2024-06-28 17:07:05] INFO auto_device.py:79: Found device: vulkan:1
[2024-06-28 17:07:05] INFO auto_device.py:79: Found device: vulkan:2
[2024-06-28 17:07:05] INFO auto_device.py:79: Found device: vulkan:3
[2024-06-28 17:07:05] INFO auto_device.py:79: Found device: vulkan:4
[2024-06-28 17:07:07] INFO auto_device.py:79: Found device: opencl:0
[2024-06-28 17:07:07] INFO auto_device.py:79: Found device: opencl:1
[2024-06-28 17:07:07] INFO auto_device.py:79: Found device: opencl:2
[2024-06-28 17:07:07] INFO auto_device.py:79: Found device: opencl:3
[2024-06-28 17:07:07] INFO auto_device.py:35: Using device: cuda:0
======================= Starts Tokenization & Embedding =======================
Parsed prompt using conversation template llama-2: ['[INST] <<SYS>>\nYou are a helpful, respectful and honest assistant.\n<</SYS>>\n\nwhat is the difference between a dolphin and a whale? [/INST] ']
Input tokens: [    1   518 25580 29962  3532 14816 29903  6778    13  3492   526   263
  8444 29892  3390  1319   322 15993 20255 29889    13 29966   829 14816
 29903  6778    13    13  5816   338   278  4328  1546   263  8828   561
   262   322   263   377   744 29973   518 29914 25580 29962 29871]
======================= Starts Prefill =======================
Debug instrument output dumped to debug_chat/prefill
======================= Starts Decode =======================
Traceback (most recent call last):
  File "/mlc-llm-slm-0613/python/mlc_llm/testing/debug_chat.py", line 455, in <module>
    main()
  File "/mlc-llm-slm-0613/python/mlc_llm/testing/debug_chat.py", line 451, in main
    dc.generate(parsed.prompt, parsed.generate_len)
  File "/mlc-llm-slm-0613/python/mlc_llm/testing/debug_chat.py", line 392, in generate
    logits = self._decode(next_token, kv_caches)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mlc-llm-slm-0613/python/mlc_llm/testing/debug_chat.py", line 321, in _decode
    logits, kv_caches = self.decode_func(embedding, kv_caches, self.params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/python/tvm/_ffi/_ctypes/packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "/tvm-unity-slm-0613/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 558, in tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
    clo->impl.CallPacked(TVMArgs(values.data(), tcodes.data(), args.size() + 1), rv);
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 632, in operator()
    *rv = static_cast<VirtualMachineImpl*>(ctx_ptr)->InvokeBytecode(gf_idx, inputs);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 689, in tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
    RunLoop();

  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 814, in tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
    this->RunInstrCall(curr_frame, instr);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 790, in tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
    this->InvokeClosurePacked(func_pool_[instr.func_idx], args, &ret);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/cuda/cuda_graph_builtin.cc", line 208, in operator()
    *rv = extension->RunOrCapture(vm, capture_func, func_args, entry_index, shape_expr);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/cuda/cuda_graph_builtin.cc", line 137, in tvm::runtime::relax_vm::CUDAGraphExtensionNode::RunOrCapture(tvm::runtime::relax_vm::VirtualMachine*, tvm::runtime::ObjectRef const&, tvm::runtime::ObjectRef, long, tvm::runtime::Optional<tvm::runtime::ShapeTuple>)
    vm->InvokeClosurePacked(capture_func, TVMArgs(values.data(), tcodes.data(), nargs),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 558, in tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
    clo->impl.CallPacked(TVMArgs(values.data(), tcodes.data(), args.size() + 1), rv);
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 632, in operator()
    *rv = static_cast<VirtualMachineImpl*>(ctx_ptr)->InvokeBytecode(gf_idx, inputs);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 689, in tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
    RunLoop();

  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 814, in tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
    this->RunInstrCall(curr_frame, instr);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 793, in tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
    instrument_.CallPacked(TVMArgs(values.data(), tcodes.data(), values.size()), &rv);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mlc-llm-slm-0613/python/mlc_llm/testing/debug_chat.py", line 107, in __call__
    num_nans = np.sum(np.isnan(args[-1].numpy()))
                               ^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/python/tvm/runtime/ndarray.py", line 261, in numpy
    check_call(_LIB.TVMArrayCopyToBytes(self.handle, data, nbytes))
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 558, in tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
    clo->impl.CallPacked(TVMArgs(values.data(), tcodes.data(), args.size() + 1), rv);
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 632, in operator()
    *rv = static_cast<VirtualMachineImpl*>(ctx_ptr)->InvokeBytecode(gf_idx, inputs);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 689, in tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
    RunLoop();

  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 814, in tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
    this->RunInstrCall(curr_frame, instr);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 790, in tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
    this->InvokeClosurePacked(func_pool_[instr.func_idx], args, &ret);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/cuda/cuda_graph_builtin.cc", line 208, in operator()
    *rv = extension->RunOrCapture(vm, capture_func, func_args, entry_index, shape_expr);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/cuda/cuda_graph_builtin.cc", line 137, in tvm::runtime::relax_vm::CUDAGraphExtensionNode::RunOrCapture(tvm::runtime::relax_vm::VirtualMachine*, tvm::runtime::ObjectRef const&, tvm::runtime::ObjectRef, long, tvm::runtime::Optional<tvm::runtime::ShapeTuple>)
    vm->InvokeClosurePacked(capture_func, TVMArgs(values.data(), tcodes.data(), nargs),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 558, in tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
    clo->impl.CallPacked(TVMArgs(values.data(), tcodes.data(), args.size() + 1), rv);
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 632, in operator()
    *rv = static_cast<VirtualMachineImpl*>(ctx_ptr)->InvokeBytecode(gf_idx, inputs);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 689, in tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
    RunLoop();

  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 814, in tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
    this->RunInstrCall(curr_frame, instr);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc", line 793, in tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
    instrument_.CallPacked(TVMArgs(values.data(), tcodes.data(), values.size()), &rv);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/ndarray.cc", line 423, in TVMArrayCopyToBytes
    ArrayCopyToBytes(handle, data, nbytes);
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/ndarray.cc", line 94, in tvm::runtime::ArrayCopyToBytes(DLTensor const*, void*, unsigned long)
    DeviceAPI::Get(handle->device)->CopyDataFromTo(const_cast<DLTensor*>(handle), &to, nullptr);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tvm-unity-slm-0613/src/runtime/cuda/cuda_device_api.cc", line 202, in tvm::runtime::CUDADeviceAPI::CopyDataFromTo(void const*, unsigned long, void*, unsigned long, unsigned long, DLDevice, DLDevice, DLDataType, void*)
    CUDA_CALL(cudaSetDevice(dev_from.device_id));
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
tvm.error.InternalError: Traceback (most recent call last):
  16: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
        at /tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc:558
  15: operator()
        at /tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc:632
  14: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
        at /tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc:689
  13: tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
        at /tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc:814
  12: tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
        at /tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc:790
  11: operator()
        at /tvm-unity-slm-0613/src/runtime/relax_vm/cuda/cuda_graph_builtin.cc:208
  10: tvm::runtime::relax_vm::CUDAGraphExtensionNode::RunOrCapture(tvm::runtime::relax_vm::VirtualMachine*, tvm::runtime::ObjectRef const&, tvm::runtime::ObjectRef, long, tvm::runtime::Optional<tvm::runtime::ShapeTuple>)
        at /tvm-unity-slm-0613/src/runtime/relax_vm/cuda/cuda_graph_builtin.cc:137
  9: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
        at /tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc:558
  8: operator()
        at /tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc:632
  7: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
        at /tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc:689
  6: tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
        at /tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc:814
  5: tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
        at /tvm-unity-slm-0613/src/runtime/relax_vm/vm.cc:793
  4: ffi_closure_unix64
  3: ffi_closure_unix64_inner
  2: TVMArrayCopyToBytes
        at /tvm-unity-slm-0613/src/runtime/ndarray.cc:423
  1: tvm::runtime::ArrayCopyToBytes(DLTensor const*, void*, unsigned long)
        at /tvm-unity-slm-0613/src/runtime/ndarray.cc:94
  0: tvm::runtime::CUDADeviceAPI::CopyDataFromTo(void const*, unsigned long, void*, unsigned long, unsigned long, DLDevice, DLDevice, DLDataType, void*)
        at /tvm-unity-slm-0613/src/runtime/cuda/cuda_device_api.cc:202
  File "/tvm-unity-slm-0613/src/runtime/cuda/cuda_device_api.cc", line 275
InternalError: Check failed: (e == cudaSuccess || e == cudaErrorCudartUnloading) is false: CUDA: operation would make the legacy stream depend on a capturing blocking stream
Exception ignored in: <function NDArrayBase.__del__ at 0x7048d92949a0>
Traceback (most recent call last):
  File "/tvm-unity-slm-0613/python/tvm/_ffi/_ctypes/ndarray.py", line 82, in __del__
  File "/tvm-unity-slm-0613/python/tvm/_ffi/base.py", line 496, in check_call
  File "/tvm-unity-slm-0613/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
  File "/tvm-unity-slm-0613/src/runtime/ndarray.cc", line 391, in TVMArrayFree
  File "/tvm-unity-slm-0613/src/runtime/ndarray.cc", line 158, in tvm::runtime::NDArray::Internal::FFIDecRef(DLTensor*)
  File "/tvm-unity-slm-0613/include/tvm/runtime/ndarray.h", line 441, in tvm::runtime::NDArray::FFIDecRef(DLTensor*)
  File "/tvm-unity-slm-0613/include/tvm/runtime/object.h", line 842, in tvm::runtime::Object::DecRef()
  File "/tvm-unity-slm-0613/include/tvm/runtime/object.h", line 846, in tvm::runtime::Object::DecRef()
  File "/tvm-unity-slm-0613/src/runtime/ndarray.cc", line 107, in tvm::runtime::NDArray::Internal::DefaultDeleter(tvm::runtime::Object*)
  File "/tvm-unity-slm-0613/src/runtime/cuda/cuda_device_api.cc", line 171, in tvm::runtime::CUDADeviceAPI::FreeDataSpace(DLDevice, void*)
tvm.error.InternalError: Traceback (most recent call last):
  7: 0x00005f039be5691c
  6: TVMArrayFree
        at /tvm-unity-slm-0613/src/runtime/ndarray.cc:391
  5: tvm::runtime::NDArray::Internal::FFIDecRef(DLTensor*)
        at /tvm-unity-slm-0613/src/runtime/ndarray.cc:158
  4: tvm::runtime::NDArray::FFIDecRef(DLTensor*)
        at /tvm-unity-slm-0613/include/tvm/runtime/ndarray.h:441
  3: tvm::runtime::Object::DecRef()
        at /tvm-unity-slm-0613/include/tvm/runtime/object.h:842
  2: tvm::runtime::Object::DecRef()
        at /tvm-unity-slm-0613/include/tvm/runtime/object.h:846
  1: tvm::runtime::NDArray::Internal::DefaultDeleter(tvm::runtime::Object*)
        at /tvm-unity-slm-0613/src/runtime/ndarray.cc:107
  0: tvm::runtime::CUDADeviceAPI::FreeDataSpace(DLDevice, void*)
        at /tvm-unity-slm-0613/src/runtime/cuda/cuda_device_api.cc:171
  File "/tvm-unity-slm-0613/src/runtime/cuda/cuda_device_api.cc", line 175
InternalError: Check failed: (e == cudaSuccess || e == cudaErrorCudartUnloading) is false: CUDA: operation not permitted when stream is capturing
terminate called after throwing an instance of 'tvm::runtime::InternalError'
  what():  [17:07:16] /tvm-unity-slm-0613/src/runtime/cuda/cuda_device_api.cc:171: InternalError: Check failed: (e == cudaSuccess || e == cudaErrorCudartUnloading) is false: CUDA: operation not permitted when stream is capturing
Stack trace:
  0: tvm::runtime::CUDADeviceAPI::FreeDataSpace(DLDevice, void*)
        at /tvm-unity-slm-0613/src/runtime/cuda/cuda_device_api.cc:171
  1: tvm::runtime::NDArray::Internal::DefaultDeleter(tvm::runtime::Object*)
        at /tvm-unity-slm-0613/src/runtime/ndarray.cc:107
  2: tvm::runtime::ObjectPtr<tvm::runtime::Object>::reset()
        at /tvm-unity-slm-0613/include/tvm/runtime/object.h:455
  3: tvm::runtime::ObjectPtr<tvm::runtime::Object>::~ObjectPtr()
        at /tvm-unity-slm-0613/include/tvm/runtime/object.h:404
  4: tvm::runtime::ObjectRef::~ObjectRef()
        at /tvm-unity-slm-0613/include/tvm/runtime/object.h:519
  5: tvm::runtime::NDArray::~NDArray()
        at /tvm-unity-slm-0613/include/tvm/runtime/ndarray.h:51
  6: tvm::runtime::relax_vm::HostMemoryVector::~HostMemoryVector()
        at /tvm-unity-slm-0613/src/runtime/relax_vm/paged_kv_cache.cc:219
  7: tvm::runtime::relax_vm::PagedAttentionKVCacheObj::~PagedAttentionKVCacheObj()
        at /tvm-unity-slm-0613/src/runtime/relax_vm/paged_kv_cache.cc:1137
  8: tvm::runtime::SimpleObjAllocator::Handler<tvm::runtime::relax_vm::PagedAttentionKVCacheObj>::Deleter_(tvm::runtime::Object*)
        at /tvm-unity-slm-0613/include/tvm/runtime/memory.h:138
  9: tvm::runtime::Object::DecRef()
        at /tvm-unity-slm-0613/include/tvm/runtime/object.h:846
  10: tvm::runtime::Object::DecRef()
        at /tvm-unity-slm-0613/include/tvm/runtime/object.h:842
  11: tvm::runtime::ObjectInternal::ObjectFree(void*)
        at /tvm-unity-slm-0613/src/runtime/object_internal.h:56
  12: TVMObjectFree
        at /tvm-unity-slm-0613/src/runtime/object.cc:255
  13: 0x00005f039be5691c


Aborted (core dumped)
```
