### ISSUE TITLE
[Model Request] google/madlad400-3b-mt

### ISSUE THREAD

**Issue by taeyeonlee** [mlc-ai/mlc-llm#1672]
## ⚙️  Request New Models
Could you support the below model ? 
https://huggingface.co/google/madlad400-3b-mt
When converting weights, the error is following.
ValueError: Unknown model type: t5.

- Link to an existing implementation (e.g. Hugging Face/Github): 
- https://huggingface.co/google/madlad400-3b-mt
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html))  No
## Additional context

/mlc-llm$ mlc_chat convert_weight ./dist/models/madlad400-3b-mt/ --quantization q4f16_1 -o dist/madlad400-3b-mt-q4f16_1-MLC
/home/taeyeon/.local/lib/python3.10/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/taeyeon/.local/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/taeyeon/.local/lib/python3.10/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/taeyeon/.local/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
[2024-01-29 01:44:37] INFO auto_config.py:115: Found model configuration: dist/models/madlad400-3b-mt/config.json
[2024-01-29 01:44:37] INFO auto_device.py:76: Found device: cuda:0
[2024-01-29 01:44:37] INFO auto_device.py:85: Not found device: rocm:0
[2024-01-29 01:44:38] INFO auto_device.py:85: Not found device: metal:0
[2024-01-29 01:44:38] INFO auto_device.py:76: Found device: vulkan:0
[2024-01-29 01:44:38] INFO auto_device.py:76: Found device: vulkan:1
[2024-01-29 01:44:39] INFO auto_device.py:85: Not found device: opencl:0
[2024-01-29 01:44:39] INFO auto_device.py:33: Using device: cuda:0
[2024-01-29 01:44:39] INFO auto_weight.py:70: Finding weights in: dist/models/madlad400-3b-mt
[2024-01-29 01:44:39] INFO auto_weight.py:136: Not found Huggingface PyTorch
[2024-01-29 01:44:40] INFO auto_weight.py:160: Found source weight format: huggingface-safetensor. Source configuration: dist/models/madlad400-3b-mt/model.safetensors.index.json
[2024-01-29 01:44:40] INFO auto_weight.py:106: Using source weight configuration: dist/models/madlad400-3b-mt/model.safetensors.index.json. Use `--source` to override.
[2024-01-29 01:44:40] INFO auto_weight.py:110: Using source weight format: huggingface-safetensor. Use `--source-format` to override.
[2024-01-29 01:44:40] INFO auto_config.py:153: Found model type: t5. Use `--model-type` to override.
Traceback (most recent call last):
  File "/home/taeyeon/.local/bin/mlc_chat", line 8, in <module>
    sys.exit(main())
  File "/home/taeyeon/.local/lib/python3.10/site-packages/mlc_chat/__main__.py", line 28, in main
    cli.main(sys.argv[2:])
  File "/home/taeyeon/.local/lib/python3.10/site-packages/mlc_chat/cli/convert_weight.py", line 86, in main
    model = detect_model_type(parsed.model_type, parsed.config)
  File "/home/taeyeon/.local/lib/python3.10/site-packages/mlc_chat/support/auto_config.py", line 155, in detect_model_type
    raise ValueError(f"Unknown model type: {model_type}. Available ones: {list(MODELS.keys())}")
ValueError: Unknown model type: t5. Available ones: ['llama', 'mistral', 'gpt2', 'mixtral', 'gpt_neox', 'gpt_bigcode', 'phi-msft', 'phi']

**Comment by DiegoCao** [comment]
Received, working on reproducing the error.
