### ISSUE TITLE
[Bug] FAILED to read metadata section in legacy model lib when running Qwen-1_8B-Chat-q4f16_1-MLC

### ISSUE THREAD

**Issue by MingkangW** [mlc-ai/mlc-llm#1674]
## 🐛 Bug

FAILED to read metadata section in legacy model lib when running Qwen-1_8B-Chat-q4f16_1-MLC.

## To Reproduce
`git clone https://github.com/mlc-ai/binary-mlc-llm-libs.git`
`git clone https://huggingface.co/mlc-ai/Qwen-1_8B-Chat-q4f16_1-MLC`
I downloaded the model with the above code and ran it with the python code below, but I got an error.
```
from mlc_chat import ChatModule
from mlc_chat.callback import StreamToStdout

cm = ChatModule(
    model="Qwen-1_8B-Chat-q4f16_1-MLC",
    model_lib_path="binary-mlc-llm-libs/Qwen-1_8B-Chat/Qwen-1_8B-Chat-q4f16_1-cuda.so"
)

cm.generate(prompt="What is the meaning of life?", progress_callback=StreamToStdout(callback_interval=2))
```
# Traceback
```
[2024-01-29 14:28:38] INFO auto_device.py:76: Found device: cuda:0
[2024-01-29 14:28:38] INFO auto_device.py:85: Not found device: rocm:0
[2024-01-29 14:28:39] INFO auto_device.py:85: Not found device: metal:0
[2024-01-29 14:28:39] INFO auto_device.py:85: Not found device: vulkan:0
[2024-01-29 14:28:39] INFO auto_device.py:85: Not found device: opencl:0
[2024-01-29 14:28:39] INFO auto_device.py:33: Using device: cuda:0
[2024-01-29 14:28:39] INFO chat_module.py:370: Using model folder: /home/wmk/workspace/test_mlc_dir/dist/Qwen-1_8B-Chat-q4f16_1-MLC
[2024-01-29 14:28:39] INFO chat_module.py:371: Using mlc chat config: /home/wmk/workspace/test_mlc_dir/dist/Qwen-1_8B-Chat-q4f16_1-MLC/mlc-chat-config.json
[2024-01-29 14:28:39] INFO chat_module.py:513: Using library model: dist/libs/Qwen.so
[2024-01-29 14:28:40] ERROR model_metadata.py:162: FAILED to read metadata section in legacy model lib.
Traceback (most recent call last):
  File "/home/wmk/download/mlc-llm/python/mlc_chat/cli/model_metadata.py", line 160, in main
    metadata = _extract_metadata(parsed.model_lib)
  File "/home/wmk/download/mlc-llm/python/mlc_chat/cli/model_metadata.py", line 26, in _extract_metadata
    return json.loads(VirtualMachine(load_module(model_lib), device("cpu"))["_metadata"]())
  File "/home/wmk/download/tvm-relax/python/tvm/runtime/relax_vm.py", line 97, in __init__
    self._setup_device(device, memory_cfg)
  File "/home/wmk/download/tvm-relax/python/tvm/runtime/relax_vm.py", line 133, in _setup_device
    self.module["vm_initialization"](*init_args)
  File "/home/wmk/download/tvm-relax/python/tvm/_ffi/_ctypes/packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "/home/wmk/download/tvm-relax/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/home/wmk/download/tvm-relax/src/runtime/relax_vm/vm.cc", line 839, in tvm::runtime::relax_vm::VirtualMachineImpl::_Init(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
    this->Init(devices, alloc_types);
  File "/home/wmk/download/tvm-relax/src/runtime/relax_vm/vm.cc", line 676, in tvm::runtime::relax_vm::VirtualMachineImpl::InitFuncPool()
    ICHECK(func.defined())
tvm.error.InternalError: Traceback (most recent call last):
  1: tvm::runtime::relax_vm::VirtualMachineImpl::_Init(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
        at /home/wmk/download/tvm-relax/src/runtime/relax_vm/vm.cc:839
  0: tvm::runtime::relax_vm::VirtualMachineImpl::InitFuncPool()
        at /home/wmk/download/tvm-relax/src/runtime/relax_vm/vm.cc:676
  File "/home/wmk/download/tvm-relax/src/runtime/relax_vm/vm.cc", line 676
InternalError: Check failed: (func.defined()) is false: Error: Cannot find PackedFunc flashinfer.single_decode in either Relax VM kernel library, or in TVM runtime PackedFunc registry, or in global Relax functions of the VM executable
Traceback (most recent call last):
  File "/home/wmk/workspace/test_mlc_dir/test.py", line 4, in <module>
    cm = ChatModule(
  File "/home/wmk/download/mlc-llm/python/mlc_chat/chat_module.py", line 780, in __init__
    self._reload(self.model_lib_path, self.model_path, user_chat_config_json_str)
  File "/home/wmk/download/mlc-llm/python/mlc_chat/chat_module.py", line 994, in _reload
    self._reload_func(lib, model_path, app_config_json)
  File "/home/wmk/download/tvm-relax/python/tvm/_ffi/_ctypes/packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "/home/wmk/download/tvm-relax/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/home/wmk/download/mlc-llm/cpp/llm_chat.cc", line 1549, in mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
    chat_->Reload(args[0], args[1], args[2]);
  File "/home/wmk/download/mlc-llm/cpp/llm_chat.cc", line 567, in mlc::llm::LLMChat::Reload(tvm::runtime::TVMArgValue, tvm::runtime::String, tvm::runtime::String)
    this->ft_.Init(reload_lib, device_, model_config);
  File "/home/wmk/download/mlc-llm/cpp/llm_chat.cc", line 170, in Init
    this->local_vm->GetFunction("vm_initialization")(
  File "/home/wmk/download/tvm-relax/src/runtime/relax_vm/vm.cc", line 839, in tvm::runtime::relax_vm::VirtualMachineImpl::_Init(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
    this->Init(devices, alloc_types);
  File "/home/wmk/download/tvm-relax/src/runtime/relax_vm/vm.cc", line 676, in tvm::runtime::relax_vm::VirtualMachineImpl::InitFuncPool()
    ICHECK(func.defined())
tvm.error.InternalError: Traceback (most recent call last):
  4: mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
        at /home/wmk/download/mlc-llm/cpp/llm_chat.cc:1549
  3: mlc::llm::LLMChat::Reload(tvm::runtime::TVMArgValue, tvm::runtime::String, tvm::runtime::String)
        at /home/wmk/download/mlc-llm/cpp/llm_chat.cc:567
  2: Init
        at /home/wmk/download/mlc-llm/cpp/llm_chat.cc:170
  1: tvm::runtime::relax_vm::VirtualMachineImpl::_Init(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
        at /home/wmk/download/tvm-relax/src/runtime/relax_vm/vm.cc:839
  0: tvm::runtime::relax_vm::VirtualMachineImpl::InitFuncPool()
        at /home/wmk/download/tvm-relax/src/runtime/relax_vm/vm.cc:676
  File "/home/wmk/download/tvm-relax/src/runtime/relax_vm/vm.cc", line 676
InternalError: Check failed: (func.defined()) is false: Error: Cannot find PackedFunc flashinfer.single_decode in either Relax VM kernel library, or in TVM runtime PackedFunc registry, or in global Relax functions of the VM executable
```

## Environment

 - Platform: CUDA
 - Operating system: WSL Ubuntu
 - Device: 4060TI
 - How you installed MLC-LLM: source
 - How you installed TVM-Unity: source
 - Python version: 3.8.12
 - GPU driver version:
 - CUDA/cuDNN version: 11.8
 - TVM Unity Hash Tag: USE_CUDA: ON
 - Any other relevant information:

**Comment by tlopex** [comment]
I have encountered the same problem. Can you tell me how to solve it?

**Comment by MingkangW** [comment]
@tlopex I downloaded the original model of Qwen from Hugging Face and compiled it myself to generate a .so file, solving this problem.
