### ISSUE TITLE
[Speed][Metal] Llama2-7b with q4f16_1 quantization works very slow on MacBook Pro x86

### ISSUE THREAD

**Issue by echuraev** [mlc-ai/mlc-llm#1675]
# 🏎️  Speed Report

Hi! I tried to run Llama-2-7b with q4f16_1 quantization on MacBook Pro with Intel CPU, and it works very slow. 

- The model code: Llama-2-7b

- The model configuration: q4f16_1
- Device: MacBook Pro (2,3 GHz 8-Core Intel Core i9; Intel(R) UHD Graphics 630)
- OS: macOS Ventura
- Encode speed (Token/s): 19.3 tok/s
- Decode speed (Token/s): 0.6 tok/s

The model was compiled by the following commands:
1. Export variables:
    ```
    export QUANTIZATION=q4f16_1 
    export MODEL_NAME=Llama-2-7b-chat-hf
    ```
2. Convert weights:
    ```
    python3 -m mlc_chat convert_weight ./dist/models/$MODEL_NAME/ --quantization $QUANTIZATION -o dist/$MODEL_NAME-$QUANTIZATION-MLC/
    ```
3. Gen config:
    ```
    python3 -m mlc_chat gen_config ./dist/models/$MODEL_NAME/ --quantization $QUANTIZATION --conv-template llama-2 --context-window-size 768 -o dist/${MODEL_NAME}-${QUANTIZATION}-MLC/
    ```
4. Compile the model:
    ```
    python3 -m mlc_chat compile ./dist/${MODEL_NAME}-${QUANTIZATION}-MLC/mlc-chat-config.json --device metal -o ./dist/${MODEL_NAME}-${QUANTIZATION}-MLC/${MODEL_NAME}-${QUANTIZATION}-metal.so
    ````
    
To run the model and measure performance, I used script [sample_mlc_chat.py](https://github.com/mlc-ai/mlc-llm/blob/main/examples/python/sample_mlc_chat.py).

Also, on my MacBook I have another GPU: `AMD Radeon Pro 5500M 4 GB`. I tried to run the same script on this GPU, but got the following error:
```
Traceback (most recent call last):
  File "/Users/echuraev/Workspace/OctoML/mlc-llm/examples/python/sample_mlc_chat.py", line 26, in <module>
    output = cm.generate(
  File "/Users/echuraev/Workspace/OctoML/mlc-llm/python/mlc_chat/chat_module.py", line 847, in generate
    self._prefill(prompt, generation_config=generation_config)
  File "/Users/echuraev/Workspace/OctoML/mlc-llm/python/mlc_chat/chat_module.py", line 1064, in _prefill
    self._prefill_func(
  File "/Users/echuraev/Workspace/OctoML/mlc-llm/3rdparty/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "/Users/echuraev/Workspace/OctoML/mlc-llm/3rdparty/tvm/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm._ffi.base.TVMError: Traceback (most recent call last):
  File "/Users/echuraev/Workspace/OctoML/mlc-llm/3rdparty/tvm/src/runtime/metal/metal_module.mm", line 202
  File "/Users/echuraev/Workspace/OctoML/mlc-llm/3rdparty/tvm/src/runtime/library_module.cc", line 78
TVMError: Check failed: blockSize <= maxTotalThreadsPerThreadgroup (1024 vs. 448) :
```

**Comment by tqchen** [comment]
Unfortunately x86 macbook was not well optimized for now
