### ISSUE TITLE
[Bug] convert weights fails with error: Warning: BlockBuilder destroyed with remaining blocks!

### ISSUE THREAD

**Issue by scottorly** [mlc-ai/mlc-llm#1721]
## 🐛 Bug

```
mlc_chat convert_weight ./dist/models/TinyLlama-1.1B-Chat-v1.0 --quantization q4f16_1 -o dist/TinyLlama-1.1B-Chat-v1.0-q4f16_1                                                 ─╯
[2024-02-06 21:40:51] INFO auto_config.py:115: Found model configuration: dist/models/TinyLlama-1.1B-Chat-v1.0/config.json
[2024-02-06 21:40:52] INFO auto_device.py:85: Not found device: cuda:0
[2024-02-06 21:40:52] INFO auto_device.py:85: Not found device: rocm:0
[2024-02-06 21:40:52] INFO auto_device.py:76: Found device: metal:0
[2024-02-06 21:40:53] INFO auto_device.py:85: Not found device: vulkan:0
[2024-02-06 21:40:53] INFO auto_device.py:85: Not found device: opencl:0
[2024-02-06 21:40:53] INFO auto_device.py:33: Using device: metal:0
[2024-02-06 21:40:53] INFO auto_weight.py:70: Finding weights in: dist/models/TinyLlama-1.1B-Chat-v1.0
[2024-02-06 21:40:53] INFO auto_weight.py:136: Not found Huggingface PyTorch
[2024-02-06 21:40:56] INFO auto_weight.py:160: Found source weight format: huggingface-safetensor. Source configuration: dist/models/TinyLlama-1.1B-Chat-v1.0/model.safetensors.index.json
[2024-02-06 21:40:56] INFO auto_weight.py:106: Using source weight configuration: dist/models/TinyLlama-1.1B-Chat-v1.0/model.safetensors.index.json. Use `--source` to override.
[2024-02-06 21:40:56] INFO auto_weight.py:110: Using source weight format: huggingface-safetensor. Use `--source-format` to override.
[2024-02-06 21:40:56] INFO auto_config.py:153: Found model type: llama. Use `--model-type` to override.
Weight conversion with arguments:
  --config          dist/models/TinyLlama-1.1B-Chat-v1.0/config.json
  --quantization    GroupQuantize(name='q4f16_1', kind='group-quant', group_size=32, quantize_dtype='int4', storage_dtype='uint32', model_dtype='float16', linear_weight_layout='NK', num_elem_per_storage=8, num_storage_per_group=4, max_int_value=7)
  --model-type      llama
  --device          metal:0
  --source          dist/models/TinyLlama-1.1B-Chat-v1.0/model.safetensors.index.json
  --source-format   huggingface-safetensor
  --output          dist/TinyLlama-1.1B-Chat-v1.0-q4f16_1
[2024-02-06 21:40:56] INFO llama_model.py:51: context_window_size not found in config.json. Falling back to max_position_embeddings (2048)
[2024-02-06 21:40:56] INFO llama_model.py:71: prefill_chunk_size defaults to context_window_size (2048)
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/bin/mlc_chat", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/mlc_chat/__main__.py", line 28, in main
    cli.main(sys.argv[2:])
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/mlc_chat/cli/convert_weight.py", line 87, in main
    convert_weight(
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/mlc_chat/interface/convert_weight.py", line 169, in convert_weight
    _convert_args(args)
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/mlc_chat/interface/convert_weight.py", line 71, in _convert_args
    _, _named_params, _ = model.export_tvm(  # type: ignore[misc]
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/tvm/relax/frontend/nn/core.py", line 479, in export_tvm
    mod, params, ext_mods = Exporter(debug=debug).build(spec)
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/tvm/relax/frontend/nn/exporter.py", line 136, in build
    outputs, inputs = _emit_method(self.builder, method_spec, params, effects)
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/tvm/relax/frontend/nn/exporter.py", line 277, in _emit_method
    outputs = spec.method(*explicit_inputs)
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/mlc_chat/model/llama/llama_model.py", line 339, in create_tir_paged_kv_cache
    return TIRPagedKVCache(
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/mlc_chat/nn/kv_cache.py", line 261, in __init__
    bb.add_func(_attention_decode(num_key_value_heads, num_attention_heads, head_dim, dtype), "tir_attention_decode"),
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/mlc_chat/nn/kv_cache.py", line 736, in _attention_decode
    assert bdx == 32
AssertionError
[21:40:57] /Users/catalyst/Workspace/mlc-ai-package-self-runner/_work/package/package/tvm/src/relax/ir/block_builder.cc:65: Warning: BlockBuilder destroyed with remaining blocks!
```

**Comment by jpf888** [comment]
Your problem should be caused by your model head size. If your head size is less than 128, you need to pad it to 128. 

I think the root cause is that the underlying kernel implementation of attention limits the size.

**Comment by kmn1024** [comment]
The `assert bdx == 32` check was added by @MasterJH5574 recently (https://github.com/mlc-ai/mlc-llm/commit/7be883cf282691f1795806463c9a3b3eb91b9f03). Maybe TinyLlama needs an exception?

**Comment by MasterJH5574** [comment]
Sorry folks for the issue. We reexamined a bit and right now the kernel should have no such constraint. Sent a PR to remove this assertion https://github.com/mlc-ai/mlc-llm/pull/1729

Meanwhile, @scottorly you can manually remove this assertion from the file `/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/mlc_chat/nn/kv_cache.py` line 736.

**Comment by Suall1969** [comment]
I manually removed that line and now the model compiles but I get this error when I run it on android:
```
InternalError: Check failed: static_cast<size_t>(gfunc.num_args) == args.size() (4 vs. 0) : ValueError: Invoking function create_tir_paged_kv_cache requires 4 inputs but only 0 inputs are provided.
Stack trace:
  File "/workspaces/mlc-llm/3rdparty/tvm/src/runtime/relax_vm/vm.cc", line 652
```
