### ISSUE TITLE
[Question] Models missing tiktoken file

### ISSUE THREAD

**Issue by tlopex** [mlc-ai/mlc-llm#1727]
## ❓ General Questions

Now I'm trying to add a new model Baichuan, but I find that this model does not have Huggingface tokenizer files like Qwen and StableLM. In addition, it also does not have tiktoken file. What should I do to generate mlc-chat-config.json and process tokenizers successfully?

```
[2024-02-08 16:22:12] INFO auto_config.py:115: Found model configuration: dist/models/Baichuan2-7B-Chat/config.json
[2024-02-08 16:22:12] INFO auto_config.py:153: Found model type: baichuan. Use `--model-type` to override.
[2024-02-08 16:22:12] INFO baichuan_model.py:46: context_window_size not found in config.json. Falling back to max_position_embeddings (4096)
[2024-02-08 16:22:12] INFO baichuan_model.py:60: prefill_chunk_size defaults to context_window_size (4096)
[2024-02-08 16:22:12] WARNING config.py:99: Warning: Cannot override max_batch_size, because BaichuanConfig does not have this field
[2024-02-08 16:22:12] INFO gen_config.py:117: [generation_config.json] Setting pad_token_id: 0
[2024-02-08 16:22:12] INFO gen_config.py:117: [generation_config.json] Setting bos_token_id: 1
[2024-02-08 16:22:12] INFO gen_config.py:117: [generation_config.json] Setting eos_token_id: 2
[2024-02-08 16:22:12] INFO gen_config.py:117: [generation_config.json] Setting temperature: 0.3
[2024-02-08 16:22:12] INFO gen_config.py:117: [generation_config.json] Setting top_p: 0.85
[2024-02-08 16:22:12] INFO gen_config.py:117: [generation_config.json] Setting repetition_penalty: 1.05
[2024-02-08 16:22:12] INFO gen_config.py:129: Found tokenizer config: dist/models/Baichuan2-7B-Chat/tokenizer.model. Copying to dist/Baichuan2-7B-Chat-q4f16_1-MLC/tokenizer.model
[2024-02-08 16:22:12] INFO gen_config.py:131: Not found tokenizer config: dist/models/Baichuan2-7B-Chat/tokenizer.json
[2024-02-08 16:22:12] INFO gen_config.py:131: Not found tokenizer config: dist/models/Baichuan2-7B-Chat/vocab.json
[2024-02-08 16:22:12] INFO gen_config.py:131: Not found tokenizer config: dist/models/Baichuan2-7B-Chat/merges.txt
[2024-02-08 16:22:12] INFO gen_config.py:131: Not found tokenizer config: dist/models/Baichuan2-7B-Chat/added_tokens.json
[2024-02-08 16:22:12] INFO gen_config.py:129: Found tokenizer config: dist/models/Baichuan2-7B-Chat/tokenizer_config.json. Copying to dist/Baichuan2-7B-Chat-q4f16_1-MLC/tokenizer_config.json
[2024-02-08 16:22:12] INFO gen_config.py:137: The model has `tokenizer.model` but not `tokenizer.json`. It is always recommended to prefer JSON instead. Attempting to convert using HuggingFace transformers library
[2024-02-08 16:22:12] ERROR gen_config.py:153: Failed with the exception below. Skipping
Traceback (most recent call last):
  File "/home/tlopex/mlc-llm/python/mlc_chat/interface/gen_config.py", line 148, in gen_config
    fast_tokenizer = AutoTokenizer.from_pretrained(str(config.parent), use_fast=True)
  File "/home/tlopex/.local/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 784, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class BaichuanTokenizer does not exist or is not currently imported.
[2024-02-08 16:22:12] INFO gen_config.py:70: [System default] Setting mean_gen_len: 128
[2024-02-08 16:22:12] INFO gen_config.py:70: [System default] Setting max_gen_len: 512
[2024-02-08 16:22:12] INFO gen_config.py:70: [System default] Setting shift_fill_factor: 0.3
[2024-02-08 16:22:12] INFO gen_config.py:177: Dumping configuration file to: dist/Baichuan2-7B-Chat-q4f16_1-MLC/mlc-chat-config.json
 ```

**Comment by tqchen** [comment]
https://github.com/mlc-ai/mlc-llm/pull/1705 maybe related

**Comment by tqchen** [comment]
@rickzx maybe can followup, i believe `tokenizer.model` might still be fine, but indeed if we convert that would be better.

**Comment by rickzx** [comment]
> @rickzx maybe can followup, i believe `tokenizer.model` might still be fine, but indeed if we convert that would be better.

@tqchen @tlopex I'm able to reproduce. Will take a look today

**Comment by rickzx** [comment]
@tlopex So it seems that Baichuan is not implementing a Fast tokenizer interface. You can see here https://huggingface.co/baichuan-inc/Baichuan-7B/blob/main/tokenization_baichuan.py#L42 that it implements `PreTrainedTokenizer` instead of `PreTrainedTokenizerFast`. In this case, it is not possible to convert the tokenizer to the rust-based fast tokenizer, and therefore, you see the ERROR in your log.

But as @tqchen mentioned, in this case, you can just ignore the error, and directly use `tokenizer.model`. We have logic in MLC chat to handle the case where there is just a single `tokenizer.model` file. See: https://github.com/mlc-ai/mlc-llm/blob/main/cpp/tokenizers.cc#L68

**Comment by tlopex** [comment]
@rickzx Thanks! 
So you mean that I can just ignore the `ValueError`
I found that when I use 
```cm = ChatModule(model="./dist/Baichuan2-7B-Chat-q4f16_1-MLC",model_lib_path="./dist/libs/Baichuan2-7B-Chat-q4f16_1-cuda.so")```   
There will still be warning:
```
Warning: Using `tokenizer.model` since we cannot locate `tokenizer.json`.
It is recommended to use `tokenizer.json` to ensure all token mappings are included, since currently, files like `added_tokens.json`, `tokenizer_config.json` are ignored.
```
However, it seems to work normally.

**Comment by tqchen** [comment]
@rickzx shall we provide a better error message in this case?

**Comment by rickzx** [comment]
@tlopex Awesome, please go ahead and send a PR. I can review it once it's published. Thank you!

@tqchen I agree. Provided a better message in https://github.com/mlc-ai/mlc-llm/pull/1753

**Comment by tlopex** [comment]
@tqchen @rickzx Thanks very much!
