### ISSUE TITLE
[Bug] `mlc_llm.build` stopped working on llama-2 (`TypeError: got an unexpected keyword argument 'args'`)

### ISSUE THREAD

**Issue by dusty-nv** [mlc-ai/mlc-llm#1779]
## 🐛 Bug

Since updating to [`MLC @ 6cf63bb`](https://github.com/mlc-ai/mlc-llm/tree/6cf63bb) from [`MLC @ 3feed05`](https://github.com/mlc-ai/mlc-llm/tree/3feed05) the `mlc_llm.build` model compiler has begun having error while building `llama-2-7b`:

```
python3 -m mlc_llm.build --model Llama-2-7b-chat-hf --target cuda --use-cuda-graph --use-flash-attn-mqa --quantization q4f16_ft  --artifact-path /data/models/mlc/6cf63bb/legacy --max-seq-len 4096'

Using path "/data/models/mlc/6cf63bb/legacy/models/Llama-2-7b-chat-hf" for model "Llama-2-7b-chat-hf"
Target configured: cuda -keys=cuda,gpu -arch=sm_87 -max_num_threads=1024 -max_shared_memory_per_block=49152 -max_threads_per_block=1024 -registers_per_block=65536 -thread_warp_size=32
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/build.py", line 47, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/build.py", line 43, in main
    core.build_model_from_args(parsed_args)
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/core.py", line 859, in build_model_from_args
    mod, param_manager, params, model_config = model_generators[args.model_category].get_model(
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/relax_model/llama.py", line 1462, in get_model
    create_prefill_func_for_single_seq(bb, param_manager, config, args.quantization, sep_embed)
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/relax_model/llama.py", line 934, in create_prefill_func_for_single_seq
    logits, key_value_cache = model(
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/testing/nn.py", line 263, in __call__
    return self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/frontend/nn/subroutine.py", line 87, in new_forward
    return old_forward(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/relax_model/llama.py", line 839, in forward
    hidden_states, key_value_cache = self.model(
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/testing/nn.py", line 263, in __call__
    return self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/frontend/nn/subroutine.py", line 87, in new_forward
    return old_forward(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/relax_model/llama.py", line 755, in forward
    hidden_states, key_value_cache = decoder_layer(
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/testing/nn.py", line 263, in __call__
    return self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/frontend/nn/subroutine.py", line 87, in new_forward
    return old_forward(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/relax_model/llama.py", line 611, in forward
    hidden_states, present_key_value = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/testing/nn.py", line 263, in __call__
    return self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/frontend/nn/subroutine.py", line 87, in new_forward
    return old_forward(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/relax_model/llama.py", line 365, in forward
    attn_output, past_key_values = self.attention_fwd(
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/relax_model/llama.py", line 478, in attention_fwd
    relax.op.call_inplace_packed(
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/utils.py", line 173, in wrapper
    bound = sig.bind(*args, **kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'args'
[18:27:28] /opt/mlc-llm/3rdparty/tvm/src/relax/ir/block_builder.cc:65: Warning: BlockBuilder destroyed with remaining blocks!
```

I am unable to migrate to the newer `mlc_chat compile` SLIM model builder yet, namely due to `sep_embed` support missing in some models (see https://github.com/mlc-ai/mlc-llm/issues/1473 and https://github.com/mlc-ai/mlc-llm/issues/1749) in addition to some performance issues with SLIM that @CharlieFRuan has been working on in https://github.com/mlc-ai/mlc-llm/issues/1723

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):  ARM64+CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):  Ubuntu 22.04
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)  Jetson AGX Orin
 - How you installed MLC-LLM (`conda`, source):  source
 - How you installed TVM-Unity (`pip`, source):  source
 - Python version (e.g. 3.10):  3.10
 - GPU driver version (if applicable):  JetPack 6.0 DP / L4T R36.2.0
 - CUDA/cuDNN version (if applicable):  CUDA 12.2
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):  `f8b2ff1bfea46ddbab905267f782c3fd9482a470`
 - Any other relevant information:

**Comment by MasterJH5574** [comment]
Hi @dusty-nv, I found out that #1536 introduced this build regression. A quick solution to unblock you would be just reverting this commit, if it is unrelated with your workflow.

**Comment by tqchen** [comment]
cc @srkreddy1238 can you take a quick look? I assume it was some unintended change that impacts the cuda flow

**Comment by MasterJH5574** [comment]
Never mind, I have filed a fix here https://github.com/mlc-ai/mlc-llm/pull/1782

**Comment by srkreddy1238** [comment]
Thanks @MasterJH5574

**Comment by dusty-nv** [comment]
Thanks @MasterJH5574, this fixed it for Llama, but getting the same error for StableLM:

```bash
python3 -m mlc_llm.build --model stablelm-3b-4e1t --target cuda --use-cuda-graph --use-flash-attn-mqa --quantization q4f16_ft --use-safetensors --artifact-path /data/models/mlc/a2d9eea/legacy --max-seq-len 4096'

Using path "/data/models/mlc/a2d9eea/legacy/models/stablelm-3b-4e1t" for model "stablelm-3b-4e1t"
Target configured: cuda -keys=cuda,gpu -arch=sm_87 -max_num_threads=1024 -max_shared_memory_per_block=49152 -max_threads_per_block=1024 -registers_per_block=65536 -thread_warp_size=32
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/build.py", line 47, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/build.py", line 43, in main
    core.build_model_from_args(parsed_args)
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/core.py", line 859, in build_model_from_args
    mod, param_manager, params, model_config = model_generators[args.model_category].get_model(
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/relax_model/stablelm_3b.py", line 806, in get_model
    create_encoding_func(bb, param_manager, config, args.quantization, sep_embed)
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/relax_model/stablelm_3b.py", line 645, in create_encoding_func
    logits, key_value_cache = model(
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/testing/nn.py", line 263, in __call__
    return self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/frontend/nn/subroutine.py", line 87, in new_forward
    return old_forward(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/relax_model/stablelm_3b.py", line 558, in forward
    hidden_states, key_value_cache = self.model(
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/testing/nn.py", line 263, in __call__
    return self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/frontend/nn/subroutine.py", line 87, in new_forward
    return old_forward(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/relax_model/stablelm_3b.py", line 529, in forward
    hidden_states, key_value_cache = decoder_layer(
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/testing/nn.py", line 263, in __call__
    return self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/frontend/nn/subroutine.py", line 87, in new_forward
    return old_forward(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/relax_model/stablelm_3b.py", line 374, in forward
    hidden_states, present_key_value = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/testing/nn.py", line 263, in __call__
    return self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/frontend/nn/subroutine.py", line 87, in new_forward
    return old_forward(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/relax_model/stablelm_3b.py", line 270, in forward
    relax.op.call_inplace_packed(
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/utils.py", line 173, in wrapper
    bound = sig.bind(*args, **kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'args'
```

Unlike Llama, I do not see explicit changes to StableLM in https://github.com/mlc-ai/mlc-llm/pull/1536 , is some other reversion needed?

**Comment by MasterJH5574** [comment]
Oh sorry that I indeed only updated llama and didn't update other models. Will do a round of check again for other models and report back then. Most changes needed should be as simple as turning the packed `args` into unpacked as in #1782.
