### ISSUE TITLE
[Bug] StableLM and other models missing `q4f16_ft` quantization support in `mlc_chat compile` SLM builder

### ISSUE THREAD

**Issue by dusty-nv** [mlc-ai/mlc-llm#1780]
## 🐛 Bug

The fastest quantization method (`q4f16_ft`) appears to not be implemented for models like StableLM, Phi-2 (and possibly others) in the new `mlc_chat compile` builder:

```
mlc_chat convert_weight models/stablelm-3b-4e1t  --quantization q4f16_ft --output stablelm-3b-4e1t-q4f16_ft'

[2024-02-18 18:49:57] INFO auto_config.py:115: Found model configuration: models/stablelm-3b-4e1t/config.json
[2024-02-18 18:49:59] INFO auto_device.py:76: Found device: cuda:0
[2024-02-18 18:50:01] INFO auto_device.py:85: Not found device: rocm:0
[2024-02-18 18:50:02] INFO auto_device.py:85: Not found device: metal:0
[2024-02-18 18:50:04] INFO auto_device.py:85: Not found device: vulkan:0
[2024-02-18 18:50:06] INFO auto_device.py:85: Not found device: opencl:0
[2024-02-18 18:50:06] INFO auto_device.py:33: Using device: cuda:0
[2024-02-18 18:50:06] INFO auto_weight.py:70: Finding weights in: models/stablelm-3b-4e1t
[2024-02-18 18:50:06] INFO auto_weight.py:136: Not found Huggingface PyTorch
[2024-02-18 18:50:06] INFO auto_weight.py:143: Found source weight format: huggingface-safetensor. Source configuration: models/stablelm-3b-4e1t/model.safetensors.index.json
[2024-02-18 18:50:06] INFO auto_weight.py:106: Using source weight configuration: models/stablelm-3b-4e1t/model.safetensors.index.json. Use `--source` to override.
[2024-02-18 18:50:06] INFO auto_weight.py:110: Using source weight format: huggingface-safetensor. Use `--source-format` to override.
[2024-02-18 18:50:06] INFO auto_config.py:153: Found model type: stablelm_epoch. Use `--model-type` to override.
Weight conversion with arguments:
  --config          models/stablelm-3b-4e1t/config.json
  --quantization    FTQuantize(name='q4f16_ft', kind='ft-quant', quantize_dtype='int4', storage_dtype='int8', model_dtype='float16', group_size=None, num_elem_per_storage=2, max_int_value=7)
  --model-type      stablelm_epoch
  --device          cuda:0
  --source          models/stablelm-3b-4e1t/model.safetensors.index.json
  --source-format   huggingface-safetensor
  --output          stablelm-3b-4e1t-q4f16_ft
[2024-02-18 18:50:06] INFO stablelm_model.py:45: context_window_size not found in config.json. Falling back to max_position_embeddings (4096)
[2024-02-18 18:50:06] INFO stablelm_model.py:59: prefill_chunk_size defaults to context_window_size (4096)
Traceback (most recent call last):
  File "/usr/local/bin/mlc_chat", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/__main__.py", line 28, in main
    cli.main(sys.argv[2:])
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/cli/convert_weight.py", line 87, in main
    convert_weight(
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/interface/convert_weight.py", line 169, in convert_weight
    _convert_args(args)
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/interface/convert_weight.py", line 68, in _convert_args
    model, quantize_map = args.model.quantize[args.quantization.kind](
KeyError: 'ft-quant'
```

The performance difference between `q4f16_ft` and the other `q4f16_*` methods is very significant:

| Model                         | Tokens/sec |
|-------------------------------|:----------:|
| `stablelm-3b-4e1t-q4f16_0`    |     57     |
| `stablelm-3b-4e1t-q4f16_1`    |     66     |
| `stablelm-3b-4e1t-q4f16_2`    |     63     |
| `stablelm-3b-4e1t-q4f16_ft`*   |     94     |
| `Llama-2-7b-chat-hf-q4f16_1`  |     36     |
| `Llama-2-7b-chat-hf-q4f16_2`  |     35     |
| `Llama-2-7b-chat-hf-q4f16_ft` |     45     |

* `stablelm-3b-4e1t-q4f16_ft` perf was using mlc_llm.build (which does support `q4f16_ft` for stablelm)

Llama architecture does have `q4f16_ft` support in `mlc_chat compile` SLM model builder, but it doesn't seem like the others do.  @tqchen is there a plan to add `q4f16_ft` quantization to the other models before transitioning to SLM?  

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):  ARM64+CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):  Ubuntu 22.04
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)  Jetson AGX Orin
 - How you installed MLC-LLM (`conda`, source):  source
 - How you installed TVM-Unity (`pip`, source):  source
 - Python version (e.g. 3.10):  3.10
 - GPU driver version (if applicable):  JetPack 6.0 DP / L4T R36.2.0
 - CUDA/cuDNN version (if applicable):  CUDA 12.2
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):  `f8b2ff1bfea46ddbab905267f782c3fd9482a470`
 - Any other relevant information:

**Comment by CharlieFRuan** [comment]
All SLM models now support `q4f16_ft` via https://github.com/mlc-ai/mlc-llm/pull/1792 thanks to @rickzx
