### ISSUE TITLE
[Question] Chat is not active after Android build.

### ISSUE THREAD

**Issue by Moon-Ahn** [mlc-ai/mlc-llm#1785]
## ❓ General Questions

I built the mlcchat app according to the Android app build provided by < **https://llm.mlc.ai/docs/deploy/android.html** >.

However, when I downloaded the default **'Llama-2-7b-chat-hf-q4f16_1'** and entered the chat, the following error occurred and the chat did not run.

My device name is "Galaxy tabs8", and it's a device that uses the **Qualcomm Snapdragon 8 Gen 1 SM8450**.

----------------------------------------------

```
MLCChat failed

Stack trace:
org.apache.tvm.Base$TVMError: InternalError: Check failed: static_cast<size_t>(gfunc.num_args) == args.size() (4 vs. 0) : ValueError: Invoking function create_tir_paged_kv_cache requires 4 inputs but only 0 inputs are provided.
Stack trace:
  File "/mnt/f/mlc-llm/3rdparty/tvm/src/runtime/relax_vm/vm.cc", line 652

at org.apache.tvm.Base.checkCall(Base.java:173)
at org.apache.tvm.Function.invoke(Function.java:130)
at ai.mlc.mlcllm.ChatModule.reload(ChatModule.java:43)
at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:642)
at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:640)
at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:543)
at ai.mlc.mlcchat.AppViewModel$ChatState.mainReloadChat$lambda$3(AppViewModel.kt:640)
at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$JJKpoRMMpp77FzXKA0o00i8lgRA(Unknown Source:0)
at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda3.run(Unknown Source:8)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)


Error message:
InternalError: Check failed: static_cast<size_t>(gfunc.num_args) == args.size() (4 vs. 0) : ValueError: Invoking function create_tir_paged_kv_cache requires 4 inputs but only 0 inputs are provided.
Stack trace:
  File "/mnt/f/mlc-llm/3rdparty/tvm/src/runtime/relax_vm/vm.cc", line 652
```

**Comment by MrRace** [comment]
Same error！！！

**Comment by Moon-Ahn** [comment]
Oh! I checked and found that the Llama model experienced this error. I noticed that the same symptom occurred when I built the apk file you provided.

No error occurred when configured with Mistral-7B.
Could you please let me know why this problem is currently happening only in Llama?

**Comment by yuxuanchiadm** [comment]
> Oh! I checked and found that the Llama model experienced this error. I noticed that the same symptom occurred when I built the apk file you provided.
> 
> No error occurred when configured with Mistral-7B. Could you please let me know why this problem is currently happening only in Llama?

Same issue. Only happening in Llama. Not in RedPajama3b q4f16, phi2 q4f16 and Mistral7b q4f16

**Comment by yuxuanchiadm** [comment]
Maybe caused by this? But I have absolutely no idea how this part work right now
https://github.com/mlc-ai/mlc-llm/blob/c30348a10eabff5b27a5f5a40370af9796890a2d/cpp/llm_chat.cc#L625C29-L625C50

**Comment by yuxuanchiadm** [comment]
Related to #1651

**Comment by Kartik14** [comment]
#1798 Should fix this.

**Comment by Moon-Ahn** [comment]
@Kartik14 
Sorry, but a new error is occurring...
Please check the error below.

---------------------
```
MLCChat failed

Stack trace:
org.apache.tvm.Base$TVMError: TVMError: Function vm.builtin.paged_attention_kv_cache_attention_with_fused_qkv(0: relax.vm.PagedAttentionKVCache, 1: int64_t, 2: double, 3: runtime.NDArray, 4: runtime.NDArray) -> void expects 5 arguments, but 4 were provided.
Stack trace:
  File "/mnt/d/mlc-llm/3rdparty/tvm/include/tvm/runtime/packed_func.h", line 1908

at org.apache.tvm.Base.checkCall(Base.java:173)
at org.apache.tvm.Function.invoke(Function.java:130)
at ai.mlc.mlcllm.ChatModule.prefill(ChatModule.java:63)
at ai.mlc.mlcchat.AppViewModel$ChatState$requestGenerate$1$1.invoke(AppViewModel.kt:667)
at ai.mlc.mlcchat.AppViewModel$ChatState$requestGenerate$1$1.invoke(AppViewModel.kt:667)
at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:548)
at ai.mlc.mlcchat.AppViewModel$ChatState.requestGenerate$lambda$4(AppViewModel.kt:667)
at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$lluIrcsPALEW5nCb2tohZYadhTY(Unknown Source:0)
at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda3.run(Unknown Source:6)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)


Error message:
TVMError: Function vm.builtin.paged_attention_kv_cache_attention_with_fused_qkv(0: relax.vm.PagedAttentionKVCache, 1: int64_t, 2: double, 3: runtime.NDArray, 4: runtime.NDArray) -> void expects 5 arguments, but 4 were provided.
Stack trace:
  File "/mnt/d/mlc-llm/3rdparty/tvm/include/tvm/runtime/packed_func.h", line 1908
```

**Comment by MasterJH5574** [comment]
Hi @Moon-Ahn, I feel the latest Android app should have addressed this issue. Could you please try out the latest one?

Also cc @Kartik14 for confirmation.

**Comment by Moon-Ahn** [comment]
Hello @MasterJH5574 ,
I downloaded the new version of apk and tried it, but an error occurred again.
This was also a problem that only occurred in llama, but I'm just watching the situation because other people keep posting issues on my behalf.
I'm currently facing another problem, so I'll check if the error has been corrected later.
However, I would like to inform you that there was still an error when I checked it three days ago.

**Comment by Kartik14** [comment]
@Moon-Ahn Hi, It might be because of an old version of Android model lib. The function signature was recently changed to have 5 arguments. Can you please try downloading the latest model libs (or compile the library again if you are building yourself)

**Comment by Moon-Ahn** [comment]
@Kartik14
I understood it as saying 'Llama-2-7b-chat-hf-q4f16_1-MLC' after changing the 3rdParties to the latest version, is that correct?
I installed apk and proceeded with it, so I installed quantized files on the homepage of huggingface provided through the app.
The route where I installed the apk is as follows.
" https://github.com/mlc-ai/binary-mlc-llm-libs/releases/ "

**Comment by Kartik14** [comment]
ohh, if you are installing via the apk, you shouldn't need anything else. Are you getting error in the released apk?

**Comment by Moon-Ahn** [comment]
@Kartik14 
I'm sorry, the apk file I downloaded seems to be old. Currently, llama works fine in the apk file in the link above. Sorry for the confusion.
I have now re-run and downloaded with **" git clone --recursive https://github.com/mlc-ai/mlc-llm/ "** through the guidance of **https://llm.mlc.ai/docs/deploy/android.htm**l , and then re-quantized the Llama model and ran the app.

However, the error _' "TVMError: Function vm.builtin.paged_attention_kv_cache_attention_with_fused_qkv(0: relax.vm.PagedAttentionKVCache, 1: int64_t, 2: double, 3: runtime.NDArray, 4: runtime.NDArray) -> void expects 5 arguments, but 4 were provided." '_ is still output.

-----------------------

As you mentioned, I think **'try downloading the latest model libs (or compile the library again if you are building yourself)'** could be the right way, but I don't think I understood exactly what it meant.
Can you tell me more accurately?
Does that mean running **git clone --recursive https://github.com/mlc-ai/mlc-llm/** is not enough?

**Comment by Moon-Ahn** [comment]
The problem has been resolved.

The environment variable of tvm was set to the previous version.

**Comment by Vinaysukhesh98** [comment]
> The problem has been resolved.
> 
> The environment variable of tvm was set to the previous version.

could you please share steps how you resolved this issue
