### ISSUE TITLE
[Question] How can I build my own Mistral model?

### ISSUE THREAD

**Issue by Moon-Ahn** [mlc-ai/mlc-llm#1793]
## ❓ General Questions

I made my own Mistral 7B model.
And this < **https://llm.mlc.ai/docs/deploy/android.html** > has even succeeded in building into a .tar file.
After executing the command **'./prepare_libs.sh'**, we succeeded in inserting all files of **'${MODEL_NAME}-${QUANTIZATION}'** into the android device through the 'Incorporate Model Weights' section.

However, it nevertheless doesn't work.

Is there any way to run the myown Mistral 7B model?

**Comment by Moon-Ahn** [comment]
This is my error below

----------------------------------

```
MLCChat failed

Stack trace:
org.apache.tvm.Base$TVMError: InternalError: Check failed: (fload_exec.defined()) is false: TVM runtime cannot find vm_load_executable
Stack trace:
  File "/$HOME/mlc-llm/cpp/llm_chat.cc", line 169

	at org.apache.tvm.Base.checkCall(Base.java:173)
	at org.apache.tvm.Function.invoke(Function.java:130)
	at ai.mlc.mlcllm.ChatModule.reload(ChatModule.java:43)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:642)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:640)
	at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:543)
	at ai.mlc.mlcchat.AppViewModel$ChatState.mainReloadChat$lambda$3(AppViewModel.kt:640)
	at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$JJKpoRMMpp77FzXKA0o00i8lgRA(Unknown Source:0)
	at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


Error message:
InternalError: Check failed: (fload_exec.defined()) is false: TVM runtime cannot find vm_load_executable
Stack trace:
  File "/$HOME/mlc-llm/cpp/llm_chat.cc", line 169
```
