### ISSUE TITLE
[Bug]  error when redownload models on android

### ISSUE THREAD

**Issue by BlindDeveloper** [mlc-ai/mlc-llm#1831]
Hello, after app not responding close it delete Gemma 2b model and download again > start chating get error:
MLCChat failed

Stack trace:
org.apache.tvm.Base$TVMError: InternalError: Check failed: (chat_ != nullptr) is false: Chat is not initialized via reload
Stack trace:
  File "/Users/kartik/mlc/mlc-llm/cpp/llm_chat.cc", line 1756

	at org.apache.tvm.Base.checkCall(Base.java:173)
	at org.apache.tvm.Function.invoke(Function.java:130)
	at ai.mlc.mlcllm.ChatModule.prefill(ChatModule.java:54)
	at ai.mlc.mlcchat.AppViewModel$ChatState$requestGenerate$1$1.invoke(AppViewModel.kt:666)
	at ai.mlc.mlcchat.AppViewModel$ChatState$requestGenerate$1$1.invoke(AppViewModel.kt:666)
	at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:548)
	at ai.mlc.mlcchat.AppViewModel$ChatState.requestGenerate$lambda$4(AppViewModel.kt:666)
	at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$lluIrcsPALEW5nCb2tohZYadhTY(Unknown Source:0)
	at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda3.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

Error message:
InternalError: Check failed: (chat_ != nullptr) is false: Chat is not initialized via reload
Stack trace:
  File "/Users/kartik/mlc/mlc-llm/cpp/llm_chat.cc", line 1756

If restart Chat app all works normally.
Device: Galaxy a34 5g
Android version: Android 14

Steps to get "app not responding"

1. Enable Talkback.
2. Start chating using Gemma.
3. Desable talkback using device buttons.
4. Continiue chatting.

**Comment by WiserZhou** [comment]
I have the same bug,but I don't know how to solve.

**Comment by tqchen** [comment]
closing for now as the android app has been updated in recent cycles please also checkout latest [android sdk](https://llm.mlc.ai/docs/deploy/android.html)
