### ISSUE TITLE
[Bug] Access violation in TVM package when trying to run model converted and compiled for Windows

### ISSUE THREAD

**Issue by justastranger** [mlc-ai/mlc-llm#1834]
## 🐛 Bug

Access violation when attempting to use a converted and compiled model (llama2 uncensored).

## To Reproduce

1. Download from HF and convert model
2. Generate config for model
3. Compile the binary
4. Attempt to execute the code below

```python3
from mlc_chat import ChatModule
from mlc_chat.callback import StreamToStdout

cm = ChatModule(
    model="./dist/llama2_7b_chat_uncensored_mlc",
    model_lib_path="./dist/compiled/llama2_7b_chat_uncensored_mlc_q4f32_1-vulkan.dll",
    device="vulkan"
)
cm.generate(prompt="What is the meaning of life?", progress_callback=StreamToStdout(callback_interval=2))
```

This is the complete output from executing the code in a conda environment
```
(mlc-llm) E:\build\mlc-llm>py mlc-ai.py
[2024-02-24 12:52:52] INFO auto_device.py:76: ←[92mFound←[0m device: vulkan:0
[2024-02-24 12:52:52] INFO chat_module.py:370: Using model folder: E:\build\mlc-llm\dist\llama2_7b_chat_uncensored_mlc
[2024-02-24 12:52:52] INFO chat_module.py:371: Using mlc chat config: E:\build\mlc-llm\dist\llama2_7b_chat_uncensored_mlc\mlc-chat-config.json
[2024-02-24 12:52:52] INFO chat_module.py:513: Using library model: ./dist/compiled/llama2_7b_chat_uncensored_mlc_q4f32_1-vulkan.dll
[2024-02-24 12:52:54] INFO model_metadata.py:95: ←[92mTotal memory usage←[0m: 4372.52 MB (Parameters: 4017.27 MB. KVCache: 0.00 MB. Temporary buffer: 355.25 MB)
[2024-02-24 12:52:54] INFO model_metadata.py:104: To reduce memory usage, tweak `prefill_chunk_size`, `context_window_size` and `sliding_window_size`
Traceback (most recent call last):
  File "E:\build\mlc-llm\mlc-ai.py", line 6, in <module>
    cm = ChatModule(
  File "C:\Python310\lib\site-packages\mlc_chat\chat_module.py", line 780, in __init__
    self._reload(self.model_lib_path, self.model_path, user_chat_config_json_str)
  File "C:\Python310\lib\site-packages\mlc_chat\chat_module.py", line 1008, in _reload
    self._reload_func(lib, model_path, app_config_json, kv_cache_config.asjson())
  File "C:\Python310\lib\site-packages\tvm\_ffi\_ctypes\packed_func.py", line 229, in __call__
    _LIB.TVMFuncCall(
OSError: exception: access violation reading 0x0000000000000010
```

## Expected behavior

As there were no failures converting the model, generating the config, and compiling the binary (aside from errors that produced no output which popped up from me misunderstanding instructions), I expected the model to simply work using the example script and prompt.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Vulkan
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Windows 10
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) PC+RX480 8GB
 - How you installed MLC-LLM (`conda`, source): pip
 - How you installed TVM-Unity (`pip`, source): Came with `mlc-ai-nightly`
 - Python version (e.g. 3.10): 3.10.11
 - GPU driver version (if applicable): 23.10.29.06-230817a-395392C-AMD-Software-Adrenalin-Edition
 - CUDA/cuDNN version (if applicable): N/A
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
```
USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU:
CUDA_VERSION: NOT-FOUND
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM:
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: OFF
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: cef243a113d44b5d991e5993f4eeeca71fb1b27f
USE_VULKAN: ON
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2024-02-02 14:09:23 -0500
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 17.0.6
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: OFF
USE_BNNS: OFF
USE_CUBLAS: OFF
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION:
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/HostX64/x64/cl.exe
HIDE_PRIVATE_SYMBOLS: OFF
```
 - Any other relevant information:

## Additional context

Commands used were as follows:
```bat
mlc_chat convert_weight ./dist/llama2_7b_chat_uncensored/ --quantization q4f32_1 --model-type llama --output ./dist/llama2_7b_chat_uncensored_mlc/
mlc_chat gen_config ./dist/llama2_7b_chat_uncensored/ --quantization q4f32_1 --model-type llama --conv-template llama-2 --context-window-size 4096 --output ./dist/llama2_7b_chat_uncensored_mlc/
mlc_chat compile ./dist/llama2_7b_chat_uncensored_mlc/ --device vulkan --opt O2 --output ./dist/compiled/llama2_7b_chat_uncensored_mlc_q4f32_1-vulkan.dll
```

**Comment by tqchen** [comment]
closing for now as this likely is fixed in latest build
