### ISSUE TITLE
[Bug] Llama model not running properly in Android app

### ISSUE THREAD

**Issue by sherelynyap** [mlc-ai/mlc-llm#1838]
## To Reproduce

1. Follow the guide at https://llm.mlc.ai/docs/deploy/android.html

## Expected behavior

The model should be able to hold a conversation.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):Windows
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): Samsung Z Flip3
 - How you installed MLC-LLM (`conda`, source):  source
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.11
 - GPU driver version (if applicable): 
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

The model was initialized and ready to chat but upon inputting "hi". The below error was given
```
MLCChat failed

Stack trace:

org.apache.tvm.Base$TVMError: [23:32:03] C:/Users/yeoph/mlc-llm/3rdparty/tvm/src/runtime/relax_vm/builtin.cc:241: Check failed: (ptr->dl_tensor.ndim == ndim) is false: ValueError: ErrorContext(fn=prefill, loc=param[0], param=input_ids, annotation=R.Tensor((1, seq_len), dtype="int32"))  expect Tensor with ndim 2 but get 3

Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

	at org.apache.tvm.Base.checkCall(Base.java:173)	at org.apache.tvm.Function.invoke(Function.java:130)

	at ai.mlc.mlcllm.ChatModule.prefill(ChatModule.java:54)

	at ai.mlc.mlcchat.AppViewModel$ChatState$requestGenerate$1$1.invoke(AppViewModel.kt:666)

	at ai.mlc.mlcchat.AppViewModel$ChatState$requestGenerate$1$1.invoke(AppViewModel.kt:666)

	at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:548)

	at ai.mlc.mlcchat.AppViewModel$ChatState.requestGenerate$lambda$4(AppViewModel.kt:666)

	at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$lluIrcsPALEW5nCb2tohZYadhTY(Unknown Source:0)

	at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda3.run(Unknown Source:6)

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)

	at java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)

	at java.lang.Thread.run(Thread.java:1012)

Error message:

[23:32:03] C:/Users/yeoph/mlc-llm/3rdparty/tvm/src/runtime/relax_vm/builtin.cc:241: Check failed: (ptr->dl_tensor.ndim == ndim) is false: ValueError: ErrorContext(fn=prefill, loc=param[0], param=input_ids, annotation=R.Tensor((1, seq_len), dtype="int32"))  expect Tensor with ndim 2 but get 3

Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.
```

**Comment by Kartik14** [comment]
Did you compile the library yourself or use the prebuilt ones [here](https://github.com/mlc-ai/binary-mlc-llm-libs)

**Comment by sherelynyap** [comment]
@Kartik14 I used the prebuilt

**Comment by MrRace** [comment]
same issue

**Comment by MrRace** [comment]
> Did you compile the library yourself or use the prebuilt ones [here](https://github.com/mlc-ai/binary-mlc-llm-libs)
@Kartik14 
I use prebuilt libs, I simply placed the Llama-2-7b-chat-hf-q4f16_1-android.tar file from [binary-mlc-llm-libs ](https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/Llama-2-7b-chat-hf/) into the `dist/libs` directory, and then proceeded with the following steps: running `./prepare_libs.sh`, followed by `./gradlew assembleDebug`. Is this the correct process?
I put the model file like `mv /data/local/tmp/Llama-2-7b-chat-hf-q4f16_1 /storage/emulated/0/Android/data/ai.mlc.mlcchat/files/` it can not find the model files when use app in Android phone. Why? Thanks a lot!

**Comment by Kartik14** [comment]
Unfortunately I am unable to reproduce it on my end. It seems like you might be using an older version of the library. Recently the function signatures were updated to handle batched input (hence getting the 3 dim input). Can you try fetching the latest libs from https://github.com/mlc-ai/binary-mlc-llm-libs and build again? If that doesn't work, maybe try compiling the model libraries yourself. You can find the instructions [here](https://llm.mlc.ai/docs/deploy/android.html)

**Comment by Kartik14** [comment]
Hi, Ideally both should work the same. If compiling by yourself is not working, then you probably need to download the latest wheels or build again from source. Also you should update the tvm wheel(`mlc-ai`) as well

**Comment by sherelynyap** [comment]
I tried redoing and there's a new error 
```
MLCChat failed

Stack trace:

org.apache.tvm.Base$TVMError: [14:05:37] C:/Users/yeoph/mlc-llm/3rdparty/tvm/src/runtime/opencl/opencl_module.cc:90: InternalError: Check failed: (e == CL_SUCCESS) is false: OpenCL Error, code=-54: CL_INVALID_WORK_GROUP_SIZE

Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

	at org.apache.tvm.Base.checkCall(Base.java:173)	at org.apache.tvm.Function.invoke(Function.java:130)

	at ai.mlc.mlcllm.ChatModule.decode(ChatModule.java:74)

	at ai.mlc.mlcchat.AppViewModel$ChatState$requestGenerate$1$2.invoke(AppViewModel.kt:669)

	at ai.mlc.mlcchat.AppViewModel$ChatState$requestGenerate$1$2.invoke(AppViewModel.kt:668)

	at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:548)

	at ai.mlc.mlcchat.AppViewModel$ChatState.requestGenerate$lambda$4(AppViewModel.kt:668)

	at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$lluIrcsPALEW5nCb2tohZYadhTY(Unknown Source:0)

	at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda3.run(Unknown Source:6)

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)

	at java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)

	at java.lang.Thread.run(Thread.java:1012)

Error message:

[14:05:37] C:/Users/yeoph/mlc-llm/3rdparty/tvm/src/runtime/opencl/opencl_module.cc:90: InternalError: Check failed: (e == CL_SUCCESS) is false: OpenCL Error, code=-54: CL_INVALID_WORK_GROUP_SIZE

Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.
```

**Comment by sherelynyap** [comment]
identified the issue, same as #1923
