### ISSUE TITLE
[Bug] Problem compiling llama model

### ISSUE THREAD

**Issue by sherelynyap** [mlc-ai/mlc-llm#1873]
## To Reproduce

1. Follow the guide at https://llm.mlc.ai/docs/deploy/android.html#create-android-project-using-compiled-models
When running command 
```
# 2. compile: compile model library with specification in mlc-chat-config.json
mlc_chat compile ./dist/${MODEL_NAME}-${QUANTIZATION}-MLC/mlc-chat-config.json \
    --device android -o ./dist/${MODEL_NAME}-${QUANTIZATION}-MLC/${MODEL_NAME}-${QUANTIZATION}-android.tar
```

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): 
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Windows
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source): prebuilt
 - How you installed TVM-Unity (`pip`, source): prebuilt
 - Python version (e.g. 3.10): 3.11
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

```
[2024-03-03 15:48:36] INFO auto_config.py:69: Found model configuration: Llama-2-7b-chat-hf-q4f16_1-MLC\mlc-chat-config.json
[2024-03-03 15:48:36] INFO auto_config.py:153: Found model type: llama. Use `--model-type` to override.
[2024-03-03 15:48:36] WARNING auto_target.py:304: --system-lib-prefix is automatically picked from the filename, llama_q4f16_1_, this allows us to use the filename as the model_lib in android/iOS builds. Please avoid renaming the .tar file when uploading the prebuilt.
Compiling with arguments:
  --config          LlamaConfig(hidden_size=4096, intermediate_size=11008, num_attention_heads=32, num_hidden_layers=32, rms_norm_eps=1e-05, vocab_size=32000, position_embedding_base=10000, context_window_size=768, prefill_chunk_size=768, num_key_value_heads=32, head_dim=128, tensor_parallel_shards=1, max_batch_size=80, kwargs={})
  --quantization    GroupQuantize(name='q4f16_1', kind='group-quant', group_size=32, quantize_dtype='int4', storage_dtype='uint32', model_dtype='float16', linear_weight_layout='NK', num_elem_per_storage=8, num_storage_per_group=4, max_int_value=7)
  --model-type      llama
  --target          {"thread_warp_size": 1, "host": {"kind": "llvm", "tag": "", "keys": ["arm_cpu", "cpu"], "mtriple": "aarch64-linux-android"}, "texture_spatial_limit": 16384, "max_threads_per_block": 256, "max_function_args": 128, "max_num_threads": 256, "kind": "opencl", "max_shared_memory_per_block": 16384, "tag": "", "keys": ["opencl", "gpu"]}
  --opt             flashinfer=0;cublas_gemm=0;cudagraph=0
  --system-lib-prefix "llama_q4f16_1_"
  --output          Llama-2-7b-chat-hf-q4f16_1-MLC\Llama-2-7b-chat-hf-q4f16_1-android.tar
  --overrides       context_window_size=None;sliding_window_size=None;prefill_chunk_size=None;attention_sink_size=None;max_batch_size=None;tensor_parallel_shards=None
[2024-03-03 15:48:36] INFO compile.py:135: Creating model from: LlamaConfig(hidden_size=4096, intermediate_size=11008, num_attention_heads=32, num_hidden_layers=32, rms_norm_eps=1e-05, vocab_size=32000, position_embedding_base=10000, context_window_size=768, prefill_chunk_size=768, num_key_value_heads=32, head_dim=128, tensor_parallel_shards=1, max_batch_size=80, kwargs={})
[2024-03-03 15:48:37] INFO compile.py:154: Exporting the model to TVM Unity compiler
[2024-03-03 15:48:39] INFO compile.py:160: Running optimizations using TVM Unity
[2024-03-03 15:48:39] INFO compile.py:173: Registering metadata: {'model_type': 'llama', 'quantization': 'q4f16_1', 'context_window_size': 768, 'sliding_window_size': -1, 'attention_sink_size': -1, 'prefill_chunk_size': 768, 'tensor_parallel_shards': 1, 'kv_cache_bytes': 0}
[2024-03-03 15:48:39] INFO pipeline.py:42: Running TVM Relax graph-level optimizations
[2024-03-03 15:49:37] INFO pipeline.py:42: Lowering to TVM TIR kernels
[2024-03-03 15:49:42] INFO pipeline.py:42: Running TVM TIR-level optimizations
[2024-03-03 15:49:53] INFO pipeline.py:42: Running TVM Dlight low-level optimizations
[15:49:53] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:53] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:53] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:53] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:53] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:53] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:53] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:53] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:54] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:54] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:54] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:54] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:54] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:54] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:54] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:54] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:54] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:54] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:54] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:54] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[2024-03-03 15:49:54] INFO pipeline.py:42: Lowering to VM bytecode
[15:49:55] D:\a\package\package\tvm\src\relax\ir\expr.cc:39: Check failed: (!op->struct_info_.defined() || op->struct_info_->IsInstance<FuncStructInfoNode>()) is false: ValueError: Call expects its operator to have FuncStructInfo, but operator I.GlobalVar("fuse_add_norm_prefill"), which was called with arguments [lv1, input_embeds, model_layers_0_post_attention_layernorm_weight5, alloc4, alloc5], has struct info R.Object
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[15:49:55] D:\a\package\package\tvm\src\relax\ir\block_builder.cc:65: Warning: BlockBuilder destroyed with remaining blocks!
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\yeoph\AppData\Local\Programs\Python\Python311\Scripts\mlc_chat.exe\__main__.py", line 7, in <module>
  File "C:\Users\yeoph\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlc_chat\__main__.py", line 24, in main
    cli.main(sys.argv[2:])
  File "C:\Users\yeoph\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlc_chat\cli\compile.py", line 131, in main
    compile(
  File "C:\Users\yeoph\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlc_chat\interface\compile.py", line 226, in compile
    _compile(args, model_config)
  File "C:\Users\yeoph\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlc_chat\interface\compile.py", line 175, in _compile
    args.build_func(
  File "C:\Users\yeoph\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlc_chat\support\auto_target.py", line 175, in build
    relax.build(
  File "C:\Users\yeoph\AppData\Local\Programs\Python\Python311\Lib\site-packages\tvm\relax\vm_build.py", line 335, in build
    mod = pipeline(mod)
          ^^^^^^^^^^^^^
  File "C:\Users\yeoph\AppData\Local\Programs\Python\Python311\Lib\site-packages\tvm\ir\transform.py", line 238, in __call__
    return _ffi_transform_api.RunPass(self, mod)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeoph\AppData\Local\Programs\Python\Python311\Lib\site-packages\tvm\_ffi\_ctypes\packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "C:\Users\yeoph\AppData\Local\Programs\Python\Python311\Lib\site-packages\tvm\_ffi\base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "C:\Users\yeoph\AppData\Local\Programs\Python\Python311\Lib\site-packages\tvm\_ffi\_ctypes\packed_func.py", line 82, in cfun
    rv = local_pyfunc(*pyargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeoph\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlc_chat\compiler_pass\pipeline.py", line 145, in _pipeline
    mod = seq(mod)
          ^^^^^^^^
  File "C:\Users\yeoph\AppData\Local\Programs\Python\Python311\Lib\site-packages\tvm\ir\transform.py", line 238, in __call__
    return _ffi_transform_api.RunPass(self, mod)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeoph\AppData\Local\Programs\Python\Python311\Lib\site-packages\tvm\_ffi\_ctypes\packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "C:\Users\yeoph\AppData\Local\Programs\Python\Python311\Lib\site-packages\tvm\_ffi\base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm._ffi.base.TVMError: Traceback (most recent call last):
  File "D:\a\package\package\tvm\src\relax\ir\expr.cc", line 39
ValueError: Check failed: (!op->struct_info_.defined() || op->struct_info_->IsInstance<FuncStructInfoNode>()) is false: Call expects its operator to have FuncStructInfo, but operator I.GlobalVar("fuse_add_norm_prefill"), which was called with arguments [lv1, input_embeds, model_layers_0_post_attention_layernorm_weight5, alloc4, alloc5], has struct info R.Object
```

**Comment by MasterJH5574** [comment]
Hey @sherelynyap thanks for reporting. I feel that this issue might have been fixed by this commit https://github.com/mlc-ai/mlc-llm/commit/9037aae1bbda663f1ba41487b2ef073bc908ad50. Could you help confirm if your mlc_chat package is the latest? Or please let me know if the issue persists.

**Comment by zhongzhenluo** [comment]
I was sing the latest package, and still has the same error. "/concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time."

**Comment by sherelynyap** [comment]
hmm i think i was following the old workflow using `mlc_chat` instead of `mlc_llm`. It works with `mlc_llm`

**Comment by sherelynyap** [comment]
It seems to compile successfully? But it still prints the error so i'll leave this issue open for now
```
[14:49:27] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:28] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:28] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:28] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:28] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:28] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:28] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:28] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:28] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:28] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:28] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:28] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:29] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:29] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:29] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:29] D:\a\package\package\tvm\src\tir\schedule\./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:29] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:29] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:29] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:29] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:29] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:29] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:29] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[14:49:29] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false:  Loop variable's dtype (int32) is narrower than that of `min` or `extent` (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[2024-03-16 14:49:29] INFO pipeline.py:48: Lowering to VM bytecode
[2024-03-16 14:49:31] INFO estimate_memory_usage.py:55: [Memory usage] Function `alloc_embedding_tensor`: 6.00 MB
[2024-03-16 14:49:31] INFO estimate_memory_usage.py:55: [Memory usage] Function `batch_decode`: 9.02 MB
[2024-03-16 14:49:31] INFO estimate_memory_usage.py:55: [Memory usage] Function `batch_prefill`: 86.62 MB
[2024-03-16 14:49:31] INFO estimate_memory_usage.py:55: [Memory usage] Function `batch_verify`: 86.62 MB
[2024-03-16 14:49:31] INFO estimate_memory_usage.py:55: [Memory usage] Function `create_tir_paged_kv_cache`: 0.00 MB
[2024-03-16 14:49:32] INFO estimate_memory_usage.py:55: [Memory usage] Function `decode`: 0.11 MB
[2024-03-16 14:49:32] INFO estimate_memory_usage.py:55: [Memory usage] Function `embed`: 6.00 MB
[2024-03-16 14:49:32] INFO estimate_memory_usage.py:55: [Memory usage] Function `prefill`: 86.63 MB
[2024-03-16 14:49:32] INFO estimate_memory_usage.py:55: [Memory usage] Function `softmax_with_temperature`: 0.00 MB
[2024-03-16 14:49:33] INFO pipeline.py:48: Compiling external modules
[2024-03-16 14:49:33] INFO pipeline.py:48: Compilation complete! Exporting to disk
[2024-03-16 14:49:39] INFO model_metadata.py:96: Total memory usage: 3701.77 MB (Parameters: 3615.13 MB. KVCache: 0.00 MB. Temporary buffer: 86.63 MB)
[2024-03-16 14:49:39] INFO model_metadata.py:105: To reduce memory usage, tweak `prefill_chunk_size`, `context_window_size` and `sliding_window_size`
[2024-03-16 14:49:39] INFO compile.py:194: Generated: dist\finllama_chat-q4f16_1-MLC\finllama_chat-q4f16_1-android.tar
```

**Comment by MasterJH5574** [comment]
Hi @sherelynyap, from that msg I cannot directly tell if the compilation succeeded or not, since I didn't see the “error msgs” there before. Do you mind letting us know the followup? Like how the deployment on Android goes.

**Comment by sherelynyap** [comment]
the latest stage i got to was https://github.com/mlc-ai/mlc-llm/issues/1923#issuecomment-2012515615
