### ISSUE TITLE
[Bug] Could I compile and execute LLM model for VTA?

### ISSUE THREAD

**Issue by kmisimn76** [mlc-ai/mlc-llm#1880]
## 🐛 Bug

I'm trying to execute a [Vicuna v1.5 model](https://huggingface.co/lmsys/vicuna-7b-v1.5) in VTA simulator with mlc-llm.
I had produce a compiled Vicuna model without any problem, but I got an error in runtime as follow.
Does MLC-LLM supported executing in VTA?
```
Traceback (most recent call last):
  File "benchmark.py", line 24, in <module>
    app.run(main)
  File "/venv/apache-tvm-py3.8/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/venv/apache-tvm-py3.8/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "benchmark.py", line 15, in main
    cm.benchmark_generate(
  File "/workspace/mlc-llm/python/mlc_chat/chat_module.py", line 977, in benchmark_generate
    self._prefill(prompt)
  File "/workspace/mlc-llm/python/mlc_chat/chat_module.py", line 1078, in _prefill
    self._prefill_func(
  File "/workspace/tvm-unity/python/tvm/_ffi/_ctypes/packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "/workspace/tvm-unity/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/mlc-llm/cpp/llm_chat.cc", line 1650, in mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#5}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  File "/mlc-llm/cpp/llm_chat.cc", line 952, in mlc::llm::LLMChat::PrefillStep(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool, mlc::llm::PlaceInPrompt, tvm::runtime::String)
  File "/mlc-llm/cpp/llm_chat.cc", line 1327, in mlc::llm::LLMChat::ForwardTokens(std::vector<int, std::allocator<int> >, long)
  File "/workspace/tvm-unity/src/runtime/relax_vm/vm.cc", line 935, in operator()
    self->InvokeClosurePacked(clo, args, rv);
  File "/workspace/tvm-unity/src/runtime/relax_vm/vm.cc", line 529, in tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
    clo->impl.CallPacked(TVMArgs(values.data(), tcodes.data(), args.size() + 1), rv);
  File "/workspace/tvm-unity/src/runtime/relax_vm/vm.cc", line 603, in operator()
    *rv = static_cast<VirtualMachineImpl*>(ctx_ptr)->InvokeBytecode(gf_idx, inputs);
  File "/workspace/tvm-unity/src/runtime/relax_vm/vm.cc", line 660, in tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
    RunLoop();
  File "/workspace/tvm-unity/src/runtime/relax_vm/vm.cc", line 785, in tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
    this->RunInstrCall(curr_frame, instr);
  File "/workspace/tvm-unity/src/runtime/relax_vm/vm.cc", line 738, in tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
    this->InvokeClosurePacked(func_pool_[instr.func_idx], args, &ret);
  File "/workspace/tvm-unity/src/runtime/relax_vm/vm.cc", line 511, in tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
    packed->CallPacked(args, rv);
  File "/workspace/tvm-unity/src/runtime/library_module.cc", line 78, in operator()
    LOG(FATAL) << TVMGetLastError();
tvm._ffi.base.TVMError: Traceback (most recent call last):
  10: mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#5}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
        at /mlc-llm/cpp/llm_chat.cc:1650
  9: mlc::llm::LLMChat::PrefillStep(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool, mlc::llm::PlaceInPrompt, tvm::runtime::String)
        at /mlc-llm/cpp/llm_chat.cc:952
  8: mlc::llm::LLMChat::ForwardTokens(std::vector<int, std::allocator<int> >, long)
        at /mlc-llm/cpp/llm_chat.cc:1327
  7: operator()
        at /workspace/tvm-unity/src/runtime/relax_vm/vm.cc:935
  6: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
        at /workspace/tvm-unity/src/runtime/relax_vm/vm.cc:529
  5: operator()
        at /workspace/tvm-unity/src/runtime/relax_vm/vm.cc:603
  4: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
        at /workspace/tvm-unity/src/runtime/relax_vm/vm.cc:660
  3: tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
        at /workspace/tvm-unity/src/runtime/relax_vm/vm.cc:785
  2: tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
        at /workspace/tvm-unity/src/runtime/relax_vm/vm.cc:738
  1: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
        at /workspace/tvm-unity/src/runtime/relax_vm/vm.cc:511
  0: operator()
        at /workspace/tvm-unity/src/runtime/library_module.cc:78
  File "/workspace/tvm-unity/src/runtime/library_module.cc", line 78
TVMError: Assert fail: T.tvm_struct_get(p_lv807, 0, 10, "int32") == 12, Argument fused_fused_decode1_take1.p_lv807.device_type has an unsatisfied constraint: 12 == T.tvm_struct_get(p_lv807, 0, 10, "int32")
```

## To Reproduce

1. I added below code to compile in parse_target() method of mlc_llm/utils.py(line 695), and built a Vicuna model using modified mlc-llm.
  ```python
  def parse_target(args: argparse.Namespace) -> None:
    ...
    elif args.target == "vta":
        import vta
        assert tvm.runtime.enabled("rpc")
        env = vta.get_env()
        device = "vta"
        target = env.target if device == "vta" else env.target_vta_cpu
        args.target = tvm.target.Target(target, host=env.target_host)
        args.target_kind = "vta"
    ...
  ``` 
  ```bash
  TVM_LOG_DEBUG=DEFAULT=2 python mlc_llm/build.py --hf-path /dist/model/vicuna-7b-v1.5 --target vta --quantization q4f16_1
  ```
2. To execute compiled model, I added below code in detect_device() of mlc_chat/support/auto_device.py(line 35)
  ```python
  def detect_device(device_hint: str) -> Optional[Device]:
    ...
    elif device_hint == "vta":
        from vta.testing import simulator
        from tvm import rpc
        assert tvm.runtime.enabled("rpc")
        remote = rpc.LocalSession()
        device = remote.device("ext_dev", 0)
        device.MASK2STR[device.device_type] = 'vta'
        return device
    ...
  ``` 
3. I executed benchmark like a below code, and I got an above error.
  ``` python
  cm = ChatModule(model=model_name, model_lib_path=compiled_model_path, device='vta')
  output = cm.benchmark_generate(
        prompt=FLAGS.prompt,
        generate_length=FLAGS.length,
  )
  ```

## Expected behavior

I expected a Vicuna model was executed in mlc-llm with VTA simulator successfully.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): VTA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu 22.04
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): PC + VTA simulator in TVM-unity
 - How you installed MLC-LLM (`conda`, source): Source
 - How you installed TVM-Unity (`pip`, source): Source
 - Python version (e.g. 3.10): 3.8
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): 
```
USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU: OFF
CUDA_VERSION: 12.3
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: OFF
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: ON
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: OFF
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: NOT-FOUND
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: NOT-FOUND
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: ON
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 15.0.7
USE_MRVL: OFF
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: none
USE_BNNS: OFF
USE_CUBLAS: OFF
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: ON
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION: 
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /opt/sccache/c++
HIDE_PRIVATE_SYMBOLS: ON
```
 - Any other relevant information:
I'd compile TVM-unity with `USE_VTA_FSIM ON` and `CMAKE_BUILD_TYPE Debug` option.

**Comment by Hzfengsy** [comment]
As far as I know, VTA is currently not undergoing maintenance. Meanwhile, Relax does not support VTA backends

**Comment by kmisimn76** [comment]
Thank you.
Could I ask a further question, is this error caused by VTA, not by RPC? Is mlc-llm considered to be working on RPC?
If possible, I would like to modify mlc-llm and tvm to execute an LLM model on VTA. Is it feasible?
