### ISSUE TITLE
[Bug] unknown argument '-fwasm-exception'; did you mean '-fwasm-exceptions'?

### ISSUE THREAD

**Issue by nico-martin** [mlc-ai/mlc-llm#1895]
I am trying to create the wasm runtime for RedPajama-INCITE-Instruct-3B

## To Reproduce
```
mlc_chat compile ./dist/RedPajama-INCITE-Instruct-3B-v1-q4f16_1-MLC/mlc-chat-config.json --device webgpu -o dist/libs/RedPajama-INCITE-Instruct-3B-v1-q4f16_1-webgpu.wasm         
```
I then get the following error message:
```
[22:15:50] /Users/catalyst/Workspace/mlc-ai-package-self-runner/_work/package/package/tvm/src/target/llvm/codegen_llvm.cc:185: Warning: Set native vector bits to be 128 for wasm32
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/bin/mlc_chat", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/mlc_chat/__main__.py", line 24, in main
    cli.main(sys.argv[2:])
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/mlc_chat/cli/compile.py", line 131, in main
    compile(
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/mlc_chat/interface/compile.py", line 230, in compile
    _compile(args, model_config)
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/mlc_chat/interface/compile.py", line 177, in _compile
    args.build_func(
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/mlc_chat/support/auto_target.py", line 198, in build
    ).export_library(
      ^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/tvm/relax/vm_build.py", line 146, in export_library
    return self.mod.export_library(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/tvm/runtime/module.py", line 624, in export_library
    return fcompile(file_name, files, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/tvm/contrib/emcc.py", line 80, in create_tvmjs_wasm
    raise RuntimeError(msg)
RuntimeError: Compilation error:
clang: error: unknown argument '-fwasm-exception'; did you mean '-fwasm-exceptions'?
emcc: error: '/opt/homebrew/Cellar/emscripten/3.1.54/libexec/llvm/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --sysroot=/opt/homebrew/Cellar/emscripten/3.1.54/libexec/cache/sysroot -DEMSCRIPTEN -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -O3 -std=c++17 -fwasm-exception /Users/[...]/mlc-llm/3rdparty/tvm/web/dist/wasm/wasm_runtime.bc -c -o /var/folders/p2/kn6zd3096x74d8d5s4nykw740000gn/T/emscripten_temp_vaosu8jo/wasm_runtime_0.o' failed (returned 1)
```

## Expected behavior

According to the Doc, it should produce the wasm runtime.

## Environment

 - Platform: Vulkan
 - Operating system: MacOS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM: `conda`:
 - Python version: 3.11.8

**Comment by nico-martin** [comment]
same with Python `3.10.13`

**Comment by tqchen** [comment]
Thanks for reporting! confirmed the issue and it should be fixed by https://github.com/apache/tvm/pull/16683, @MasterJH5574 we can report back when nightly reflected the change

**Comment by nico-martin** [comment]
Ah I see. I changed that line locally and now it did compile as expected. Thank you so much!
