### ISSUE TITLE
[Bug] SLM flow python chat crashes on latest nightly : Cannot find function vm.builtin.kv_state_clear

### ISSUE THREAD

**Issue by Sing-Li** [mlc-ai/mlc-llm#1910]
## 🐛 Bug

When running the new flow using the python based chat, the latest nightly crashes with the message:

```
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 176
ValueError: Check failed: (f != nullptr) is false: Cannot find function vm.builtin.kv_state_clear
```

## To Reproduce

1.  Install latest cuda 12.2 nightly with dependencies:
```
python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly-cu122 mlc-ai-nightly-cu122
```
1    run the python chat with the new flow
```
python3 -m mlc_chat chat HF://mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC
```
System crashes ....

## Expected behavior

Chat starts as with prior nightly.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):  CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):  Ubuntu 22.04lts
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...):  RTX 3060 12 GB
 - How you installed MLC-LLM (`conda`, source): conda
 - How you installed TVM-Unity (`pip`, source):  pip 
 - Python version (e.g. 3.10):  3.11
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

Actual invocation and error:

```
$ python3 -m mlc_chat chat HF://mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC
[2024-03-08 19:15:00] INFO auto_device.py:76: Found device: cuda:0
[2024-03-08 19:15:00] INFO auto_device.py:85: Not found device: rocm:0
[2024-03-08 19:15:01] INFO auto_device.py:85: Not found device: metal:0
[2024-03-08 19:15:01] INFO auto_device.py:76: Found device: vulkan:0
[2024-03-08 19:15:02] INFO auto_device.py:85: Not found device: opencl:0
[2024-03-08 19:15:02] INFO auto_device.py:33: Using device: cuda:0
[2024-03-08 19:15:02] INFO chat_module.py:356: Downloading model from HuggingFace: HF://mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC
[2024-03-08 19:15:02] INFO download.py:124: Weights already downloaded: /home/autoqa/.cache/mlc_chat/model_weights/mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC
[2024-03-08 19:15:02] INFO chat_module.py:765: Model lib not found. Now compiling model lib on device...
[2024-03-08 19:15:02] INFO jit.py:34: MLC_JIT_POLICY = ON. Can be one of: ON, OFF, REDO, READONLY
[2024-03-08 19:15:02] INFO jit.py:116: Using cached model lib: /home/autoqa/.cache/mlc_chat/model_lib/f81ab35acc278bfe94378904c4101414.so
[2024-03-08 19:15:03] INFO model_metadata.py:96: Total memory usage: 4077.14 MB (Parameters: 3615.13 MB. KVCache: 0.00 MB. Temporary buffer: 462.01 MB)
[2024-03-08 19:15:03] INFO model_metadata.py:105: To reduce memory usage, tweak `prefill_chunk_size`, `context_window_size` and `sliding_window_size`
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/__main__.py", line 47, in <module>
    main()
  File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/__main__.py", line 36, in main
    cli.main(sys.argv[2:])
  File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/cli/chat.py", line 41, in main
    chat(
  File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/interface/chat.py", line 133, in chat
    cm = ChatModule(model, device, chat_config=config, model_lib_path=model_lib_path)
  File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/chat_module.py", line 783, in __init__
    self._reload(self.model_lib_path, self.model_path, user_chat_config_json_str)
  File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/chat_module.py", line 1002, in _reload
    self._reload_func(lib, model_path, app_config_json)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/home/autoqa/.local/lib/python3.10/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 1653, in mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 629, in mlc::llm::LLMChat::Reload(tvm::runtime::TVMArgValue, tvm::runtime::String, tvm::runtime::String)
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 180, in Init
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 278, in _InitFunctions
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 260, in _TryInitKVState
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 176, in operator()
ValueError: Traceback (most recent call last):
  5: mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
        at /workspace/mlc-llm/cpp/llm_chat.cc:1653
  4: mlc::llm::LLMChat::Reload(tvm::runtime::TVMArgValue, tvm::runtime::String, tvm::runtime::String)
        at /workspace/mlc-llm/cpp/llm_chat.cc:629
  3: Init
        at /workspace/mlc-llm/cpp/llm_chat.cc:180
  2: _InitFunctions
        at /workspace/mlc-llm/cpp/llm_chat.cc:278
  1: _TryInitKVState
        at /workspace/mlc-llm/cpp/llm_chat.cc:260
  0: operator()
        at /workspace/mlc-llm/cpp/llm_chat.cc:176
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 176
ValueError: Check failed: (f != nullptr) is false: Cannot find function vm.builtin.kv_state_clear
```

**Comment by tqchen** [comment]
can you please try to reinstall `mlc-ai-nightly-cu122`?

**Comment by MasterJH5574** [comment]
Thanks for reporting! I just followed the commands and was not able to reproduce. So would you like to reinstall the mlc-ai package? It is likely due to a versioning issue.

<img width="1026" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/45167100/f92f0b23-7350-45bb-8ff8-78719bdcebb0">

**Comment by Sing-Li** [comment]
Thanks @tqchen and @MasterJH5574 :pray: 

I uninstalled and reinstalled mlc-ai-nightly-cu122 and it worked again.  Interesting is that the exact same version was removed and installed. 

```
$ python3 -m pip uninstall  mlc-ai-nightly-cu122
Uninstalling mlc-ai-nightly-cu122-0.15.dev99:
....
$  python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly-cu122 mlc-ai-nightly-cu122
Defaulting to user installation because normal site-packages is not writeable
Looking in links: https://mlc.ai/wheels
Requirement already satisfied: mlc-chat-nightly-cu122 in /home/autoqa/.local/lib/python3.10/site-packages (0.1.dev968)
Collecting mlc-ai-nightly-cu122
....
Installing collected packages: mlc-ai-nightly-cu122
Successfully installed mlc-ai-nightly-cu122-0.15.dev99
```

Closing issue.
