### ISSUE TITLE
[Bug] some Yi-34B based models compatibility test

### ISSUE THREAD

**Issue by alphaarea** [mlc-ai/mlc-llm#1919]
## 🐛 Bug

yi-34b-200k seems like the open source model with longest context. So I tested some yi-34b based model. They have the same error when compile. 

The model I tested is below. I hope it will help mlc-llm to optimize the model compatibility

| Models                            | Date             | Architecture | Template      | Convert | Config | Compile | Inference | Speed(decode) |
|-----------------------------------|------------------|--------------|---------------|---------|--------|---------|-----------|---------------|
| 01-ai/Yi-34B-Chat                 | 20240310, dev973 | llama        | gpt2          | TRUE    | TRUE   | FALSE   |           | N/A           |
| 01-ai/Yi-34B-200K                 | 20240310, dev973 | llama        | gpt2          | TRUE    | TRUE   | FALSE   |           | N/A           |
| abacusai/Smaug-34B-v0.1           | 20240310, dev973 | llama        | llama_default | TRUE    | TRUE   | FALSE   |           | N/A           |
| NousResearch/Nous-Hermes-2-Yi-34B | 20240310, dev973 | llama        | gpt2          | TRUE    | TRUE   | FALSE   |           | N/A           |

all of these models run into trouble when use `mlc_chat compile`. They output the same error message, including numbers in the message: `ValueError: Literal value 8589934591 exceeds maximum of int32`

full error message:

```log
...
[2024-03-10 12:23:36] INFO pipeline.py:47: Running TVM Dlight low-level optimizations
Traceback (most recent call last):
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/bin/mlc_chat", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/mlc_chat/__main__.py", line 24, in main
    cli.main(sys.argv[2:])
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/mlc_chat/cli/compile.py", line 131, in main
    compile(
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/mlc_chat/interface/compile.py", line 230, in compile
    _compile(args, model_config)
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/mlc_chat/interface/compile.py", line 177, in _compile
    args.build_func(
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/mlc_chat/support/auto_target.py", line 242, in build
    relax.build(
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/tvm/relax/vm_build.py", line 335, in build
    mod = pipeline(mod)
          ^^^^^^^^^^^^^
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/tvm/ir/transform.py", line 238, in __call__
    return _ffi_transform_api.RunPass(self, mod)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "tvm/_ffi/_cython/./packed_func.pxi", line 56, in tvm._ffi._cy3.core.tvm_callback
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/mlc_chat/compiler_pass/pipeline.py", line 161, in _pipeline
    mod = seq(mod)
          ^^^^^^^^
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/tvm/ir/transform.py", line 238, in __call__
    return _ffi_transform_api.RunPass(self, mod)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "tvm/_ffi/_cython/./packed_func.pxi", line 56, in tvm._ffi._cy3.core.tvm_callback
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/tvm/ir/transform.py", line 307, in _pass_func
    return inst.transform_module(mod, ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/tvm/dlight/base/transform.py", line 64, in transform_module
    sch = _apply_rules(func, target, self.rules, tunable=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/tvm/dlight/base/transform.py", line 80, in _apply_rules
    space = rule.apply(func, target, tunable)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/tvm/dlight/gpu/fallback.py", line 77, in apply
    bx, tx = sch.split(  # pylint: disable=invalid-name
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/tvm/tir/schedule/_type_checker.py", line 340, in wrap
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/tvm/tir/schedule/schedule.py", line 811, in split
    _ffi_api.ScheduleSplit(  # type: ignore # pylint: disable=no-member
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 277, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/home/alphaarea/.conda/envs/mlc-llm-20240310/lib/python3.11/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm.error.InternalError: Traceback (most recent call last):
  27: _ZN3tvm7runtime13PackedFun
  26: tvm::runtime::TypedPackedFunc<tvm::runtime::Array<tvm::tir::LoopRV, void> (tvm::tir::Schedule, tvm::tir::LoopRV const&, tvm::runtime::Array<tvm::runtime::Optional<tvm::PrimExpr>, void> const&, bool)>::AssignTypedLambda<tvm::runtime::Registry::set_body_method<tvm::tir::Schedule, tvm::tir::ScheduleNode, tvm::runtime::Array<tvm::tir::LoopRV, void>, tvm::tir::LoopRV const&, tvm::runtime::Array<tvm::runtime::Optional<tvm::PrimExpr>, void> const&, bool, void>(tvm::runtime::Array<tvm::tir::LoopRV, void> (tvm::tir::ScheduleNode::*)(tvm::tir::LoopRV const&, tvm::runtime::Array<tvm::runtime::Optional<tvm::PrimExpr>, void> const&, bool))::{lambda(tvm::tir::Schedule, tvm::tir::LoopRV const&, tvm::runtime::Array<tvm::runtime::Optional<tvm::PrimExpr>, void> const&, bool)#1}>(tvm::runtime::Registry::set_body_method<tvm::tir::Schedule, tvm::tir::ScheduleNode, tvm::runtime::Array<tvm::tir::LoopRV, void>, tvm::tir::LoopRV const&, tvm::runtime::Array<tvm::runtime::Optional<tvm::PrimExpr>, void> const&, bool, void>(tvm::runtime::Array<tvm::tir::LoopRV, void> (tvm::tir::ScheduleNode::*)(tvm::tir::LoopRV const&, tvm::runtime::Array<tvm::runtime::Optional<tvm::PrimExpr>, void> const&, bool))::{lambda(tvm::tir::Schedule, tvm::tir::LoopRV const&, tvm::runtime::Array<tvm::runtime::Optional<tvm::PrimExpr>, void> const&, bool)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*) const
  25: tvm::tir::TracedScheduleNode::Split(tvm::tir::LoopRV const&, tvm::runtime::Array<tvm::runtime::Optional<tvm::PrimExpr>, void> const&, bool)
  24: tvm::tir::ConcreteScheduleNode::Split(tvm::tir::LoopRV const&, tvm::runtime::Array<tvm::runtime::Optional<tvm::PrimExpr>, void> const&, bool)
  23: tvm::tir::Split(tvm::tir::ScheduleState, tvm::tir::StmtSRef const&, tvm::runtime::Array<tvm::PrimExpr, void> const&, bool)
  22: tvm::arith::Analyzer::CanProve(tvm::PrimExpr const&, tvm::arith::ProofStrength)
  21: tvm::arith::Analyzer::Simplify(tvm::PrimExpr const&, int)
  20: tvm::arith::CanonicalSimplifier::operator()(tvm::PrimExpr const&)
  19: non-virtual thunk to tvm::arith::CanonicalSimplifier::Impl::VisitExpr(tvm::PrimExpr const&)
  18: tvm::arith::RewriteSimplifier::Impl::VisitExpr(tvm::PrimExpr const&)
  17: _ZZN3tvm3tir11ExprFunctorIFNS
  16: tvm::arith::CanonicalSimplifier::Impl::VisitExpr_(tvm::tir::LTNode const*)
  15: tvm::arith::RewriteSimplifier::Impl::VisitExpr(tvm::PrimExpr const&)
  14: _ZZN3tvm3tir11ExprFunctorIFNS
  13: tvm::arith::CanonicalSimplifier::Impl::VisitExpr_(tvm::tir::LTNode const*)
  12: tvm::arith::RewriteSimplifier::Impl::VisitExpr(tvm::PrimExpr const&)
  11: _ZZN3tvm3tir11ExprFunctorIFNS
  10: tvm::arith::CanonicalSimplifier::Impl::VisitExpr_(tvm::tir::LTNode const*)
  9: tvm::arith::RewriteSimplifier::Impl::VisitExpr_(tvm::tir::LTNode const*)
  8: non-virtual thunk to tvm::arith::CanonicalSimplifier::Impl::VisitExpr(tvm::PrimExpr const&)
  7: tvm::arith::CanonicalSimplifier::Impl::Normalize(tvm::PrimExpr) [clone .constprop.0]
  6: tvm::arith::SumExprNode::Normalize() const
  5: tvm::arith::SumExprNode::Normalize_(tvm::runtime::DataType, std::vector<tvm::arith::SplitExpr, std::allocator<tvm::arith::SplitExpr> > const&, long)
  4: tvm::arith::SplitExprNode::NormalizeWithScale(long) const
  3: tvm::PrimExpr tvm::tir::make_const<long, void>(tvm::runtime::DataType, long, tvm::Span)
  2: tvm::PrimExpr tvm::tir::MakeConstScalar<long>(tvm::runtime::DataType, long, tvm::Span)
  1: tvm::IntImm::IntImm(tvm::runtime::DataType, long, tvm::Span)
  0: _ZN3tvm7runtime6deta
  File "/workspace/tvm/src/ir/expr.cc", line 88
InternalError: Check failed: value < 1LL << (dtype.bits() - 1) (8589934591 vs. 2147483648) : ValueError: Literal value 8589934591 exceeds maximum of int32
```

## To Reproduce

```shell
MODEL_PATH='/home/alphaarea/models/Yi-34B-Chat'
MLC_QUANT='q4f16_1'
MLC_DEV='cuda'
MODEL_ARCH='llama'
MODEL_TEMP='gpt2'
MODEL_NAME=${MODEL_PATH##*/}
MODEL_OUTPUT=$MODEL_PATH'-'$MLC_QUANT
MODEL_LIB=$MODEL_NAME'-'$MLC_QUANT'-'$MLC_DEV'.so'

mlc_chat convert_weight --quantization $MLC_QUANT --model-type $MODEL_ARCH --device $MLC_DEV --output $MODEL_OUTPUT $MODEL_PATH
mlc_chat gen_config --quantization $MLC_QUANT --model-type $MODEL_ARCH --conv-template $MODEL_TEMP --context-window-size 2048 --tensor-parallel-shards 4 --max-batch-size 1 --output $MODEL_OUTPUT $MODEL_PATH
mlc_chat compile --device $MLC_DEV --opt 'O0' --output $MODEL_OUTPUT/$MODEL_LIB $MODEL_OUTPUT/mlc-chat-config.json
mlc_chat bench --generate-length 512 --model-lib-path $MODEL_OUTPUT/$MODEL_LIB $MODEL_OUTPUT
```

## Expected behavior

compile success

## Environment

Platform: CUDA
Operating system: Ubuntu 22.04.3 LTS (5.15.0-91-generic)
Device: Tesla P100 x4
How you installed MLC-LLM: python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly-cu121 mlc-ai-nightly-cu121
How you installed TVM-Unity: python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly-cu121 mlc-ai-nightly-cu121
Python version: 3.11
GPU driver version: 545.23.08
CUDA/cuDNN version: 12.1
TVM Unity Hash Tag:
```text
USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU:
CUDA_VERSION: 12.1
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: ON
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM:
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --ignore-libllvm --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: ON
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: f06d486b4a1a27f0bbb072688a5fc41e7b15323c
USE_VULKAN: ON
USE_RUST_EXT: OFF
USE_CUTLASS: ON
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2024-03-08 02:04:22 -0500
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: ON
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 15.0.7
USE_MRVL: OFF
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: OFF
USE_BNNS: OFF
USE_CUBLAS: ON
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION:
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /opt/rh/gcc-toolset-11/root/usr/bin/c++
HIDE_PRIVATE_SYMBOLS: ON
```
Any other relevant information: no

**Comment by MasterJH5574** [comment]
Closing this one as it duplicates #1911.
