### ISSUE TITLE
[Bug] InternalError: Check failed: embedding_shape[0] > 1 (1 vs. 1) When start chatting with StableLM

### ISSUE THREAD

**Issue by tlopex** [mlc-ai/mlc-llm#1952]
## 🐛 Bug

Today I want to fix some small mistakes of StableLM model I made accidentally last time, but I found that I cannot start it.
## To Reproduce

`1.python -m mlc_llm convert_weight dist/models/stablelm-2-1_6b/ --quantization q4f16_1 --output dist/stablelm-2-1_6b-q4f16_1-MLC `
`2.python -m mlc_llm gen_config ./dist/models/stablelm-2-1_6b/ --quantization q4f16_1 --conv-template stablelm-2 -o dist/stablelm-2-1_6b-q4f16_1-MLC/`
`3.python -m mlc_llm compile ./dist/stablelm-2-1_6b-q4f16_1-MLC/mlc-chat-config.json --device cuda -o dist/libs/stablelm-2-1_6b-q4f16_1-cuda.so`
`4.mlc_llm chat dist/stablelm-zephyr-3b-q4f16_1-MLC --device "cuda:0" --overrides context_window_size=4096 --model-lib-path ./dist/libs/stablelm-zephyr-3b-q4f16_1-cuda.so`

## Traceback
```
tlopex@tlopex-OMEN-by-HP-Laptop-17-ck1xxx:~/mlc-llm$ mlc_llm chat dist/stablelm-zephyr-3b-q4f16_1-MLC \
>              --device "cuda:0" --overrides context_window_size=4096 \
>              --model-lib-path ./dist/libs/stablelm-zephyr-3b-q4f16_1-cuda.so
[2024-03-14 01:38:37] INFO config.py:106: Overriding context_window_size from None to 4096
[2024-03-14 01:38:39] INFO auto_device.py:76: Found device: cuda:0
[2024-03-14 01:38:39] INFO chat_module.py:373: Using model folder: /home/tlopex/mlc-llm/dist/stablelm-zephyr-3b-q4f16_1-MLC
[2024-03-14 01:38:39] INFO chat_module.py:374: Using mlc chat config: /home/tlopex/mlc-llm/dist/stablelm-zephyr-3b-q4f16_1-MLC/mlc-chat-config.json
[2024-03-14 01:38:39] INFO chat_module.py:516: Using library model: ./dist/libs/stablelm-zephyr-3b-q4f16_1-cuda.so
[2024-03-14 01:38:40] INFO model_metadata.py:96: Total memory usage: 2508.05 MB (Parameters: 1500.05 MB. KVCache: 0.00 MB. Temporary buffer: 1008.00 MB)
[2024-03-14 01:38:40] INFO model_metadata.py:105: To reduce memory usage, tweak `prefill_chunk_size`, `context_window_size` and `sliding_window_size`
You can use the following special commands:
  /help               print the special commands
  /exit               quit the cli
  /stats              print out the latest stats (token/sec)
  /reset              restart a fresh chat
  /set [overrides]    override settings in the generation config. For example,
                      `/set temperature=0.5;max_gen_len=100;stop=end,stop`
                      Note: Separate stop words in the `stop` option with commas (,).
  Multi-line input: Use escape+enter to start a new line.

Traceback (most recent call last):
  File "/home/tlopex/.local/bin/mlc_llm", line 11, in <module>
    load_entry_point('mlc-llm', 'console_scripts', 'mlc_llm')()
  File "/home/tlopex/mlc-llm/python/mlc_llm/__main__.py", line 36, in main
    cli.main(sys.argv[2:])
  File "/home/tlopex/mlc-llm/python/mlc_llm/cli/chat.py", line 41, in main
    chat(
  File "/home/tlopex/mlc-llm/python/mlc_llm/interface/chat.py", line 135, in chat
    cm._process_system_prompts()  # pylint: disable=protected-access
  File "/home/tlopex/mlc-llm/python/mlc_llm/chat_module.py", line 1210, in _process_system_prompts
    self._process_system_prompts_func()
  File "/home/tlopex/relax/python/tvm/_ffi/_ctypes/packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "/home/tlopex/relax/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/home/tlopex/mlc-llm/cpp/llm_chat.cc", line 1804, in mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#19}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
    GetChat()->ProcessSystemPrompts();
  File "/home/tlopex/mlc-llm/cpp/llm_chat.cc", line 1545, in mlc::llm::LLMChat::ProcessSystemPrompts()
    this->PrefillStep(/*inp=*/"", /*append_conversation=*/false, /*decode_next_token=*/false);
  File "/home/tlopex/mlc-llm/cpp/llm_chat.cc", line 971, in mlc::llm::LLMChat::PrefillStep(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool, mlc::llm::PlaceInPrompt, tvm::runtime::String)
    logits_on_device = this->ForwardTokens(chunk, new_seq_len);
  File "/home/tlopex/mlc-llm/cpp/llm_chat.cc", line 1407, in mlc::llm::LLMChat::ForwardTokens(std::vector<int, std::allocator<int> >, long)
    ShapeTuple embedding_shape = {1, 1, GetHiddenSizeFromEmbedding(embed)};
  File "/home/tlopex/mlc-llm/cpp/llm_chat.cc", line 1450, in mlc::llm::LLMChat::GetHiddenSizeFromEmbedding(tvm::runtime::ObjectRef)
    ICHECK_GT(embedding_shape[0], 1);
tvm.error.InternalError: Traceback (most recent call last):
  4: mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#19}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
        at /home/tlopex/mlc-llm/cpp/llm_chat.cc:1804
  3: mlc::llm::LLMChat::ProcessSystemPrompts()
        at /home/tlopex/mlc-llm/cpp/llm_chat.cc:1545
  2: mlc::llm::LLMChat::PrefillStep(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool, mlc::llm::PlaceInPrompt, tvm::runtime::String)
        at /home/tlopex/mlc-llm/cpp/llm_chat.cc:971
  1: mlc::llm::LLMChat::ForwardTokens(std::vector<int, std::allocator<int> >, long)
        at /home/tlopex/mlc-llm/cpp/llm_chat.cc:1407
  0: mlc::llm::LLMChat::GetHiddenSizeFromEmbedding(tvm::runtime::ObjectRef)
        at /home/tlopex/mlc-llm/cpp/llm_chat.cc:1450
  File "/home/tlopex/mlc-llm/cpp/llm_chat.cc", line 1450
InternalError: Check failed: embedding_shape[0] > 1 (1 vs. 1) : 
```

## Environment

 - Platform : CUDA
 - Operating system : Ubuntu 20.04
 - Device: RTX3080TI
 - How you installed MLC-LLM : source
 - How you installed TVM-Unity : source
 - Python version : 3.8.10
 - GPU driver version (if applicable): 535.154.05 
 - CUDA/cuDNN version (if applicable):12.2
 - Any other relevant information:

**Comment by MasterJH5574** [comment]
Sorry it's my mistake. I wanted to use `ICHECK_GE` (standing for "greater equal") but typed it as `GT` (standing for "greater than")`. Submitted a fix here https://github.com/mlc-ai/mlc-llm/pull/1953

**Comment by MasterJH5574** [comment]
I merged the fix. You can checkout the latest main to patch it.

**Comment by tlopex** [comment]
Okay, thanks!
