### ISSUE TITLE
[Bug] getting started example cause a bug

### ISSUE THREAD

**Issue by XJY990705** [mlc-ai/mlc-llm#1960]
## 🐛 Bug

 Installation is successfull as the picture shows, but when I tried the getting-started example, I got the problem. Besides, I have checked the Cuda version and the Cuda version in Pytorch, they match. It would be a big help if you can help me find where is the problem.
https://llm.mlc.ai/docs/index.html#getting-started 

## To Reproduce

mlc_llm chat HF://mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC

![image](https://github.com/mlc-ai/mlc-llm/assets/93078647/8c0deafc-7666-423f-bd29-555da445bff5)
(mlc-chat-venv) wangh@zj-MS-7B17:~/mlc-llm$ mlc_llm chat HF://mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC
[2024-03-15 10:31:46] INFO auto_device.py:76: Found device: cuda:0
[2024-03-15 10:31:46] INFO auto_device.py:85: Not found device: rocm:0
[2024-03-15 10:31:46] INFO auto_device.py:85: Not found device: metal:0
[2024-03-15 10:31:47] INFO auto_device.py:85: Not found device: vulkan:0
[2024-03-15 10:31:47] INFO auto_device.py:85: Not found device: opencl:0
[2024-03-15 10:31:47] INFO auto_device.py:33: Using device: cuda:0
[2024-03-15 10:31:47] INFO chat_module.py:356: Downloading model from HuggingFace: HF://mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC
[2024-03-15 10:31:47] INFO download.py:131: Weights already downloaded: /home/wangh/.cache/mlc_llm/model_weights/mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC
[2024-03-15 10:31:47] INFO chat_module.py:765: Model lib not found. Now compiling model lib on device...
/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
[2024-03-15 10:31:48] INFO jit.py:34: MLC_JIT_POLICY = ON. Can be one of: ON, OFF, REDO, READONLY
[2024-03-15 10:31:48] INFO jit.py:93: Compiling using commands below:
[2024-03-15 10:31:48] INFO jit.py:94: /home/wangh/anaconda3/envs/mlc-chat-venv/bin/python3.11 -m mlc_llm compile /home/wangh/.cache/mlc_llm/model_weights/mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC --opt 'flashinfer=1;cublas_gemm=1;faster_transformer=1;cudagraph=0' --overrides 'context_window_size=4096;prefill_chunk_size=4096;tensor_parallel_shards=1' --device cuda:0 --output /tmp/tmpxt_f2ohj/lib.so
/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
[2024-03-15 10:31:49] INFO auto_config.py:69: Found model configuration: /home/wangh/.cache/mlc_llm/model_weights/mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC/mlc-chat-config.json
[2024-03-15 10:31:49] INFO auto_target.py:83: Detecting target device: cuda:0
[2024-03-15 10:31:49] INFO auto_target.py:85: Found target: {"thread_warp_size": 32, "arch": "sm_86", "max_threads_per_block": 1024, "max_num_threads": 1024, "kind": "cuda", "max_shared_memory_per_block": 49152, "tag": "", "keys": ["cuda", "gpu"]}
[2024-03-15 10:31:49] INFO auto_target.py:102: Found host LLVM triple: x86_64-unknown-linux-gnu
[2024-03-15 10:31:49] INFO auto_target.py:103: Found host LLVM CPU: skylake
[2024-03-15 10:31:49] INFO auto_target.py:269: Generating code for CUDA architecture: sm_86
[2024-03-15 10:31:49] INFO auto_target.py:270: To produce multi-arch fatbin, set environment variable MLC_MULTI_ARCH. Example: MLC_MULTI_ARCH=70,72,75,80,86,87,89,90
[2024-03-15 10:31:49] INFO auto_config.py:153: Found model type: llama. Use `--model-type` to override.
Compiling with arguments:
  --config          LlamaConfig(hidden_size=4096, intermediate_size=11008, num_attention_heads=32, num_hidden_layers=32, rms_norm_eps=1e-06, vocab_size=32000, position_embedding_base=10000, context_window_size=4096, prefill_chunk_size=4096, num_key_value_heads=32, head_dim=128, tensor_parallel_shards=1, max_batch_size=1, kwargs={})
  --quantization    GroupQuantize(name='q4f16_1', kind='group-quant', group_size=32, quantize_dtype='int4', storage_dtype='uint32', model_dtype='float16', linear_weight_layout='NK', quantize_embedding=True, quantize_final_fc=True, num_elem_per_storage=8, num_storage_per_group=4, max_int_value=7)
  --model-type      llama
  --target          {"thread_warp_size": 32, "host": {"mtriple": "x86_64-unknown-linux-gnu", "tag": "", "kind": "llvm", "mcpu": "skylake", "keys": ["cpu"]}, "arch": "sm_86", "max_threads_per_block": 1024, "libs": ["thrust"], "max_num_threads": 1024, "kind": "cuda", "max_shared_memory_per_block": 49152, "tag": "", "keys": ["cuda", "gpu"]}
  --opt             flashinfer=1;cublas_gemm=0;faster_transformer=1;cudagraph=0
  --system-lib-prefix ""
  --output          /tmp/tmpxt_f2ohj/lib.so
  --overrides       context_window_size=4096;sliding_window_size=None;prefill_chunk_size=4096;attention_sink_size=None;max_batch_size=None;tensor_parallel_shards=1
[2024-03-15 10:31:49] INFO config.py:106: Overriding context_window_size from 4096 to 4096
[2024-03-15 10:31:49] INFO config.py:106: Overriding prefill_chunk_size from 4096 to 4096
[2024-03-15 10:31:49] INFO config.py:106: Overriding tensor_parallel_shards from 1 to 1
[2024-03-15 10:31:49] INFO compile.py:136: Creating model from: LlamaConfig(hidden_size=4096, intermediate_size=11008, num_attention_heads=32, num_hidden_layers=32, rms_norm_eps=1e-06, vocab_size=32000, position_embedding_base=10000, context_window_size=4096, prefill_chunk_size=4096, num_key_value_heads=32, head_dim=128, tensor_parallel_shards=1, max_batch_size=1, kwargs={})
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/wangh/mlc-llm/python/mlc_llm/__main__.py", line 47, in <module>
    main()
  File "/home/wangh/mlc-llm/python/mlc_llm/__main__.py", line 24, in main
    cli.main(sys.argv[2:])
  File "/home/wangh/mlc-llm/python/mlc_llm/cli/compile.py", line 128, in main
    compile(
  File "/home/wangh/mlc-llm/python/mlc_llm/interface/compile.py", line 230, in compile
    _compile(args, model_config)
  File "/home/wangh/mlc-llm/python/mlc_llm/interface/compile.py", line 152, in _compile
    model, _ = args.model.quantize[args.quantization.kind](model_config, args.quantization)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangh/mlc-llm/python/mlc_llm/model/llama/llama_quantization.py", line 18, in group_quant
    model: nn.Module = LlamaForCasualLM(model_config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangh/mlc-llm/python/mlc_llm/model/llama/llama_model.py", line 199, in __init__
    self.model = LlamaModel(config)
                 ^^^^^^^^^^^^^^^^^^
  File "/home/wangh/mlc-llm/python/mlc_llm/model/llama/llama_model.py", line 183, in __init__
    self.embed_tokens = nn.Embedding("vocab_size", config.hidden_size)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangh/tvm-unity/python/tvm/relax/frontend/nn/modules.py", line 623, in __init__
    self.weight = Parameter((num, dim), dtype=dtype)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangh/tvm-unity/python/tvm/relax/frontend/nn/core.py", line 232, in __init__
    super().__init__(_expr=Tensor.placeholder(shape, dtype=dtype, name="param")._expr)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangh/tvm-unity/python/tvm/relax/frontend/nn/core.py", line 147, in placeholder
    raise TypeError(f"Invalid shape: {shape}")
TypeError: Invalid shape: ('vocab_size', 4096)
Traceback (most recent call last):
  File "/home/wangh/mlc-llm/python/mlc_llm/chat_module.py", line 756, in __init__
    self.model_lib_path = _get_lib_module_path(
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangh/mlc-llm/python/mlc_llm/chat_module.py", line 578, in _get_lib_module_path
    raise FileNotFoundError(err_msg)
FileNotFoundError: Cannot find the model library that corresponds to `None`.
`None` is either provided in the `chat_config` you passed in, or specified in /home/wangh/.cache/mlc_llm/model_weights/mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC/mlc-chat-config.json.
We searched over the following possible paths: 
- None-cuda.so
- dist/prebuilt/lib/None-cuda.so
- dist/HF://mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC/None-cuda.so
- /home/wangh/.cache/mlc_llm/model_weights/mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC/None-cuda.so
- /home/wangh/.cache/mlc_llm/model_weights/mlc-ai/None-cuda.so
If you would like to directly specify the model library path, you may consider passing in the `ChatModule.model_lib_path` parameter.
Please checkout https://github.com/mlc-ai/notebooks/blob/main/mlc-llm/tutorial_chat_module_getting_started.ipynb for an example on how to load a model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wangh/anaconda3/envs/mlc-chat-venv/bin/mlc_llm", line 33, in <module>
    sys.exit(load_entry_point('mlc-llm', 'console_scripts', 'mlc_llm')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangh/mlc-llm/python/mlc_llm/__main__.py", line 36, in main
    cli.main(sys.argv[2:])
  File "/home/wangh/mlc-llm/python/mlc_llm/cli/chat.py", line 41, in main
    chat(
  File "/home/wangh/mlc-llm/python/mlc_llm/interface/chat.py", line 133, in chat
    cm = ChatModule(model, device, chat_config=config, model_lib_path=model_lib_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangh/mlc-llm/python/mlc_llm/chat_module.py", line 769, in __init__
    jit.jit(
  File "/home/wangh/mlc-llm/python/mlc_llm/interface/jit.py", line 122, in jit
    _run_jit(
  File "/home/wangh/mlc-llm/python/mlc_llm/interface/jit.py", line 95, in _run_jit
    subprocess.run(cmd, check=True)
  File "/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/wangh/anaconda3/envs/mlc-chat-venv/bin/python3.11', '-m', 'mlc_llm', 'compile', '/home/wangh/.cache/mlc_llm/model_weights/mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC', '--opt', 'flashinfer=1;cublas_gemm=1;faster_transformer=1;cudagraph=0', '--overrides', 'context_window_size=4096;prefill_chunk_size=4096;tensor_parallel_shards=1', '--device', 'cuda:0', '--output', '/tmp/tmpxt_f2ohj/lib.so']' returned non-zero exit status 1.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):Ubuntu
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)PC+RTX 3080
 - How you installed MLC-LLM (`conda`, source):source
 - How you installed TVM-Unity (`pip`, source):source
 - Python version (e.g. 3.10):3.11
 - GPU driver version (if applicable):535
 - CUDA/cuDNN version (if applicable):CUDA 12.1
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by XJY990705** [comment]
And when I use Python API
![image](https://github.com/mlc-ai/mlc-llm/assets/93078647/d28e241a-1e17-4db0-b296-d11a15dc89b5)

**Comment by MasterJH5574** [comment]
Hey @XJY990705, thanks for asking.

For the first issue you encountered:
```
  File "/home/wangh/mlc-llm/python/mlc_llm/model/llama/llama_model.py", line 183, in __init__
    self.embed_tokens = nn.Embedding("vocab_size", config.hidden_size)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangh/tvm-unity/python/tvm/relax/frontend/nn/modules.py", line 623, in __init__
    self.weight = Parameter((num, dim), dtype=dtype)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangh/tvm-unity/python/tvm/relax/frontend/nn/core.py", line 232, in __init__
    super().__init__(_expr=Tensor.placeholder(shape, dtype=dtype, name="param")._expr)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangh/tvm-unity/python/tvm/relax/frontend/nn/core.py", line 147, in placeholder
    raise TypeError(f"Invalid shape: {shape}")
```
This is because your TVM under `/home/wangh/tvm-unity` is not the latest. The latest TVM should work in this case: https://github.com/apache/tvm/blob/main/python/tvm/relax/frontend/nn/core.py#L139-L165. So, could you please check out to the latest TVM (main branch), re-build TVM and try again?

For the second issue, this is because the prebuilt libraries are not updated after a commit. This is less urgent as long as you can update TVM and then re-try the first example.

**Comment by XJY990705** [comment]
Thank you very much!!! I'll try out this method soon!

**Comment by XJY990705** [comment]
> Hey @XJY990705, thanks for asking.
> 
> For the first issue you encountered:
> 
> ```
>   File "/home/wangh/mlc-llm/python/mlc_llm/model/llama/llama_model.py", line 183, in __init__
>     self.embed_tokens = nn.Embedding("vocab_size", config.hidden_size)
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/wangh/tvm-unity/python/tvm/relax/frontend/nn/modules.py", line 623, in __init__
>     self.weight = Parameter((num, dim), dtype=dtype)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/wangh/tvm-unity/python/tvm/relax/frontend/nn/core.py", line 232, in __init__
>     super().__init__(_expr=Tensor.placeholder(shape, dtype=dtype, name="param")._expr)
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/wangh/tvm-unity/python/tvm/relax/frontend/nn/core.py", line 147, in placeholder
>     raise TypeError(f"Invalid shape: {shape}")
> ```
> 
> This is because your TVM under `/home/wangh/tvm-unity` is not the latest. The latest TVM should work in this case: https://github.com/apache/tvm/blob/main/python/tvm/relax/frontend/nn/core.py#L139-L165. So, could you please check out to the latest TVM (main branch), re-build TVM and try again?
> 
> For the second issue, this is because the prebuilt libraries are not updated after a commit. This is less urgent as long as you can update TVM and then re-try the first example.

Thank you!! I have already solved my problem.
