### ISSUE TITLE
Android app does not run model

### ISSUE THREAD

**Issue by Gul7333** [mlc-ai/mlc-llm#2031]
I downloaded model but when I run any model this error come (Android 10)

M![Screenshot_20240325-234844.png](https://github.com/mlc-ai/mlc-llm/assets/106809902/53f5596f-613b-4f47-ab4a-547a36ba7d1d)

LCChat failed

Stack trace:
org.apache.tvm.Base$TVMError: InternalError: Check failed: (config["conv_template"].is<std::string>()) is false: 
Stack trace:
  File "/Users/kartik/mlc/mlc-llm/cpp/llm_chat.cc", line 540

	at org.apache.tvm.Base.checkCall(Base.java:173)
	at org.apache.tvm.Function.invoke(Function.java:130)
	at ai.mlc.mlcllm.ChatModule.reload(ChatModule.java:46)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:648)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:646)
	at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:548)
	at ai.mlc.mlcchat.AppViewModel$ChatState.mainReloadChat$lambda$3(AppViewModel.kt:646)
	at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$CXL6v4mjTu_Sr5Pk2zFDcus0R-8(Unknown Source:0)
	at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda2.run(Unknown Source:8)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

Error message:
InternalError: Check failed: (config["conv_template"].is<std::string>()) is false: 
Stack trace:
  File "/Users/kartik/mlc/mlc-llm/cpp/llm_chat.cc", line 540

**Comment by zhjygit** [comment]
The same as you. Have you solved it?

**Comment by Gul7333** [comment]
No , I haven't

**Comment by MasterJH5574** [comment]
Copying @Kartik14. Looks like we need to rebuild the android app given the conversation template change in `mlc-chat-config.json` https://github.com/mlc-ai/mlc-llm/commit/994f9289892b0218e3fe7e9df4685d35a8fcdfb5

**Comment by Kartik14** [comment]
Yes, I will update the apk

**Comment by Trickster85** [comment]
Is it fixed? Im having same issue

**Comment by Kartik14** [comment]
I have updated the apk :). Should be hopefully fixed now.

**Comment by BlindDeveloper** [comment]
@Kartik14 
Thank you for fix this isue!
Now working corectly!

**Comment by sygi** [comment]
Can you advise how to fix the error? I got an updated (json obj) mlc-chat-config.json, and ran `./prepare_libs` again, but am still getting the error. Is it possible that [this file](https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/Llama-2-7b-chat-hf/Llama-2-7b-chat-hf-q4f16_1-android.tar) needs to be updated to accommodate the changes in the config file? I haven't seen where the config file is reference otherwise.

Thank you!
