### ISSUE TITLE
[Bug] kv_cache_bytes missing in metadata

### ISSUE THREAD

**Issue by yogeshg** [mlc-ai/mlc-llm#2065]
## 🐛 Bug

I got a bug when trying to host server on macos using metal device and llama-2-7b. Based on reading some code, I suspect that this error occurs during interpretation of `max-total-seq-length`, when I explicitly pass `--max-total-seq-length 1000`, the error goes away (I see a different issue, which is captured in 2059).

```
% python -m mlc_llm.serve.server --model dist/Llama-2-7b-chat-hf-q4f16_1-MLC --model-lib-path dist/prebuilt_libs/Llama-2-7b-chat-hf/Llama-2-7b-chat-hf-q4f16_1-metal.so --device metal                            
[2024-03-31 07:20:56] INFO auto_device.py:76: Found device: metal:0
[2024-03-31 07:20:56] INFO chat_module.py:379: Using model folder: /Users/yo/code/mlc-llm/dist/Llama-2-7b-chat-hf-q4f16_1-MLC
[2024-03-31 07:20:56] INFO chat_module.py:380: Using mlc chat config: /Users/yo/code/mlc-llm/dist/Llama-2-7b-chat-hf-q4f16_1-MLC/mlc-chat-config.json
[2024-03-31 07:20:56] INFO chat_module.py:529: Using library model: dist/prebuilt_libs/Llama-2-7b-chat-hf/Llama-2-7b-chat-hf-q4f16_1-metal.so
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/yo/miniconda3/envs/mlc-llm-dev/lib/python3.11/site-packages/mlc_llm/cli/model_metadata.py", line 194, in <module>
    main()
  File "/Users/yo/miniconda3/envs/mlc-llm-dev/lib/python3.11/site-packages/mlc_llm/cli/model_metadata.py", line 184, in main
    _print_memory_usage_in_json(metadata, cfg)
  File "/Users/yo/miniconda3/envs/mlc-llm-dev/lib/python3.11/site-packages/mlc_llm/cli/model_metadata.py", line 112, in _print_memory_usage_in_json
    params_bytes, temp_func_bytes, kv_cache_bytes = _compute_memory_usage(metadata, config)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yo/miniconda3/envs/mlc-llm-dev/lib/python3.11/site-packages/mlc_llm/cli/model_metadata.py", line 88, in _compute_memory_usage
    kv_cache_bytes = metadata["kv_cache_bytes"]
                     ~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'kv_cache_bytes'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/yo/miniconda3/envs/mlc-llm-dev/lib/python3.11/site-packages/mlc_llm/serve/server/__main__.py", line 57, in <module>
    engine = async_engine.AsyncThreadedEngine(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yo/miniconda3/envs/mlc-llm-dev/lib/python3.11/site-packages/mlc_llm/serve/async_engine.py", line 286, in __init__
    kv_cache_config.max_total_sequence_length = _estimate_max_total_sequence_length(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yo/miniconda3/envs/mlc-llm-dev/lib/python3.11/site-packages/mlc_llm/serve/engine.py", line 165, in _estimate_max_total_sequence_length
    usage_str = subprocess.check_output(cmd, universal_newlines=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yo/miniconda3/envs/mlc-llm-dev/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yo/miniconda3/envs/mlc-llm-dev/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/yo/miniconda3/envs/mlc-llm-dev/bin/python', '-m', 'mlc_llm.cli.model_metadata', 'dist/prebuilt_libs/Llama-2-7b-chat-hf/Llama-2-7b-chat-hf-q4f16_1-metal.so', '--print-memory-usage-in-json', '--mlc-chat-config', 'dist/Llama-2-7b-chat-hf-q4f16_1-MLC/mlc-chat-config.json']' returned non-zero exit status 1.
```

## To Reproduce

1. Setup conda, and install libraries
1. Get repositories etc using this documentation: https://llm.mlc.ai/docs/
1. Host REST API using this tutorial: https://llm.mlc.ai/docs/deploy/rest.html

## Expected behavior
Server should start without any issues

## Environment
- Platform: Metal
- Operating system: Mac OS
- Device: Metal
- How you installed MLC-LLM: Conda
- How you installed TVM-Unity (pip, source):
- Python version (e.g. 3.10): 3.11
- GPU driver version (if applicable): --
- CUDA/cuDNN version (if applicable): --
- TVM Unity Hash Tag (python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))", applicable if you compile models): python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))" | grep HASH GIT_COMMIT_HASH: 6d47d37dfe0e8f7bd079859d2aa744531887dacb

## Additional context

See related issue in 2059.

**Comment by yogeshg** [comment]
command from https://github.com/mlc-ai/mlc-llm/pull/2066 fixes this
