### ISSUE TITLE
[Bug] Check failed: (it != type_key2index_.end()) is false: Cannot find type relax.dpl.StructInfoPattern. Did you forget to register the node by TVM_REGISTER_NODE_TYPE 

### ISSUE THREAD

**Issue by sygi** [mlc-ai/mlc-llm#2093]
## 🐛 Bug

I'm trying to follow the instructions in https://llm.mlc.ai/docs/deploy/android.html (the version with using the prebuilt android.jar).
When reaching the `./prepare_libs.sh`, I'm getting the error as in the title.

## To Reproduce

1. Follow the instructions above, downloading the compiled android.jar.
1. Run ./prepare_libs.sh.
1. You'll get the following stacktrace:
```
Traceback (most recent call last):
  File "/home/sygi/code/mlc-llm2/android/library/prepare_model_lib.py", line 3, in <module>
    from tvm.contrib import ndk
  File "/home/sygi/code/mlc-llm/3rdparty/tvm/python/tvm/__init__.py", line 82, in <module>
    from . import relax
  File "/home/sygi/code/mlc-llm/3rdparty/tvm/python/tvm/relax/__init__.py", line 92, in <module>
    from .pipeline import get_pipeline
  File "/home/sygi/code/mlc-llm/3rdparty/tvm/python/tvm/relax/pipeline.py", line 27, in <module>
    from . import transform, backend
  File "/home/sygi/code/mlc-llm/3rdparty/tvm/python/tvm/relax/transform/__init__.py", line 19, in <module>
    from .transform import (
  File "/home/sygi/code/mlc-llm/3rdparty/tvm/python/tvm/relax/transform/transform.py", line 28, in <module>
    from tvm.relax.dpl import DFPattern
  File "/home/sygi/code/mlc-llm/3rdparty/tvm/python/tvm/relax/dpl/__init__.py", line 20, in <module>
    from .pattern import *
  File "/home/sygi/code/mlc-llm/3rdparty/tvm/python/tvm/relax/dpl/pattern.py", line 582, in <module>
    class StructInfoPattern(DFPattern):
  File "/home/sygi/code/mlc-llm/3rdparty/tvm/python/tvm/relax/dpl/pattern.py", line 48, in register_df_node
    return tvm_ffi.register_object("relax.dpl." + type_key.__name__)(type_key)
  File "/home/sygi/code/mlc-llm/3rdparty/tvm/python/tvm/_ffi/registry.py", line 69, in register
    check_call(_LIB.TVMObjectTypeKey2Index(c_str(object_name), ctypes.byref(tidx)))
  File "/home/sygi/code/mlc-llm/3rdparty/tvm/python/tvm/_ffi/base.py", line 496, in check_call
    raise_last_ffi_error()
  File "/home/sygi/code/mlc-llm/3rdparty/tvm/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm.error.InternalError: Traceback (most recent call last):
  68: 0xffffffffffffffff
  67: _start
  66: Py_BytesMain
  65: Py_RunMain
  64: 0x0000653cfb02ee54
  63: 0x0000653cfb0289ca
  62: 0x0000653cfb02f107
  61: PyEval_EvalCode
  60: 0x0000653cfaf0e9c5
  59: PyImport_ImportModuleLevelObject
  58: 0x0000653cfaf28dc8
  57: 0x0000653cfaf2910d
  56: 0x0000653cfaf4db67
  55: PyImport_ImportModuleLevelObject
  54: 0x0000653cfaf28dc8
  53: 0x0000653cfaf29c58
  52: 0x0000653cfb009e2c
  51: PyEval_EvalCode
  50: 0x0000653cfaf0e9c5
  49: PyImport_ImportModuleLevelObject
  48: 0x0000653cfaf28dc8
  47: 0x0000653cfaf2910d
  46: 0x0000653cfaf4db67
  45: PyImport_ImportModuleLevelObject
  44: 0x0000653cfaf28dc8
  43: 0x0000653cfaf29c58
  42: 0x0000653cfb009e2c
  41: PyEval_EvalCode
  40: 0x0000653cfaf0e9c5
  39: PyImport_ImportModuleLevelObject
  38: 0x0000653cfaf28dc8
  37: 0x0000653cfaf29c58
  36: 0x0000653cfb009e2c
  35: PyEval_EvalCode
  34: 0x0000653cfaf0e9c5
  33: PyImport_ImportModuleLevelObject
  32: 0x0000653cfaf28dc8
  31: 0x0000653cfaf2910d
  30: 0x0000653cfaf4db67
  29: PyImport_ImportModuleLevelObject
  28: 0x0000653cfaf28dc8
  27: 0x0000653cfaf29c58
  26: 0x0000653cfb009e2c
  25: PyEval_EvalCode
  24: 0x0000653cfaf0e9c5
  23: PyImport_ImportModuleLevelObject
  22: 0x0000653cfaf28dc8
  21: 0x0000653cfaf29c58
  20: 0x0000653cfb009e2c
  19: PyEval_EvalCode
  18: 0x0000653cfaf0e9c5
  17: PyImport_ImportModuleLevelObject
  16: 0x0000653cfaf28dc8
  15: 0x0000653cfaf29c58
  14: 0x0000653cfb009e2c
  13: PyEval_EvalCode
  12: 0x0000653cfaf0e9c5
  11: PyImport_ImportModuleLevelObject
  10: 0x0000653cfaf28dc8
  9: 0x0000653cfaf29c58
  8: 0x0000653cfb009e2c
  7: PyEval_EvalCode
  6: 0x0000653cfaf0e9c5
  5: 0x000075593f9c79ff
  4: 0x000075593f9c83e8
  3: 0x000075593fc32492
  2: 0x000075593fc35e2d
  1: TVMObjectTypeKey2Index
  0: tvm::runtime::Object::TypeKey2Index(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  File "/home/sygi/code/mlc-llm/3rdparty/tvm/src/runtime/object.cc", line 165
InternalError: Check failed: (it != type_key2index_.end()) is false: Cannot find type relax.dpl.StructInfoPattern. Did you forget to register the node by TVM_REGISTER_NODE_TYPE ?
```

## Expected behavior

This should build the libraries to attach.

## Environment

 - Platform: Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu 22.04 LTS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): this is before getting to the device
 - How you installed MLC-LLM (`conda`, source): no, using the sources
 - How you installed TVM-Unity (`pip`, source): from the 3rd party sources
 - Python version (e.g. 3.10): 3.10.12
 - GPU driver version (if applicable): not applicable
 - CUDA/cuDNN version (if applicable): not applicable
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): gives the same error as the above.
 - Any other relevant information:

## Additional context

I was able to progress further with a code version from the last month but there were some other incompatibilities so I recreated the project from scratch to make sure everything is clean (this means any dependencies should be there).

**Comment by sygi** [comment]
Nevermind, I found my error (not refreshing the venv). I am still getting some new errors, let me report them :P
