### ISSUE TITLE
[Bug] prebuilt pip models don't detect vulkan on Steamdeck

### ISSUE THREAD

**Issue by Zant12** [mlc-ai/mlc-llm#2094]
## 🐛 Bug

latest prebuilt pip module do not detect vulkan drivers.

### python

```py
(deck@steamdeck mlc2024)$ python 1.py 
[2024-04-05 17:37:04] INFO auto_device.py:85: Not found device: cuda:0
[2024-04-05 17:37:05] INFO auto_device.py:85: Not found device: rocm:0
[2024-04-05 17:37:06] INFO auto_device.py:85: Not found device: metal:0
[2024-04-05 17:37:08] INFO auto_device.py:85: Not found device: vulkan:0
[2024-04-05 17:37:09] INFO auto_device.py:85: Not found device: opencl:0
[2024-04-05 17:37:09] INFO auto_device.py:31: Not found: No available device detected
Traceback (most recent call last):
  File "/home/deck/mlc2024/1.py", line 4, in <module>
    cm = ChatModule(
         ^^^^^^^^^^^
  File "/home/deck/miniconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/chat_module.py", line 735, in __init__
    device_type = self.device.device_type
                  ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'device_type'
(1)(deck@steamdeck mlc2024)$
```

### commandline:

```
(130)(deck@steamdeck mlc2024)$ mlc_llm
------------------------- Usage -------------------------
usage: MLC LLM Command Line Interface. [-h] {compile,convert_weight,gen_config,chat,serve,bench}

positional arguments:
  {compile,convert_weight,gen_config,chat,serve,bench}
                        Subcommand to to run. (choices: compile, convert_weight, gen_config, chat,
                        serve, bench)

options:
  -h, --help            show this help message and exit
------------------------- Error -------------------------
the following arguments are required: subcommand
(2)(deck@steamdeck mlc2024)$ mlc_llm -h
usage: MLC LLM Command Line Interface. [-h] {compile,convert_weight,gen_config,chat,serve,bench}

positional arguments:
  {compile,convert_weight,gen_config,chat,serve,bench}
                        Subcommand to to run. (choices: compile, convert_weight, gen_config, chat,
                        serve, bench)

options:
  -h, --help            show this help message and exit
(deck@steamdeck mlc2024)$ mlc_llm chat dist/Llama-2-7b-chat-hf-q4f16_1-MLC/
[2024-04-05 17:43:08] INFO auto_device.py:85: Not found device: cuda:0
[2024-04-05 17:43:09] INFO auto_device.py:85: Not found device: rocm:0
[2024-04-05 17:43:10] INFO auto_device.py:85: Not found device: metal:0
[2024-04-05 17:43:11] INFO auto_device.py:85: Not found device: vulkan:0
[2024-04-05 17:43:12] INFO auto_device.py:85: Not found device: opencl:0
[2024-04-05 17:43:12] INFO auto_device.py:31: Not found: No available device detected
Traceback (most recent call last):
  File "/home/deck/miniconda3/envs/mlc-prebuilt/bin/mlc_llm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/deck/miniconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/__main__.py", line 37, in main
    cli.main(sys.argv[2:])
  File "/home/deck/miniconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/cli/chat.py", line 41, in main
    chat(
  File "/home/deck/miniconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/interface/chat.py", line 133, in chat
    cm = ChatModule(model, device, chat_config=config, model_lib_path=model_lib_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/miniconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/chat_module.py", line 735, in __init__
    device_type = self.device.device_type
                  ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'device_type'
(1)(deck@steamdeck mlc2024)$
```

## To Reproduce

```
conda install -c conda-forge libgcc-ng
conda create --name mlc-prebuilt  python=3.11
conda activate mlc-prebuilt
pip install llm-mlc
python -c "import mlc_llm; print(mlc_llm)" # success
download prequantizeld llama q4f16_1 to dist as shown in documentation and try running with python and cli command, (logs below)


## Expected behavior

I have a previous version of mlc in a different conda enviorment that I was able to install.


The command is: 

mlc_chat_cli --local-id Llama-2-13b-chat-hf-q416_1

with this older binary, the gpu is detected properly and runs with my gpu.

## Environment

 - Platform Vulkan
 - Operating system SteamOS
 - Device Steamdeck
 - How you installed: MLC-LLM create python3.11 conda enviorment, install cpu version via pip install

 - Any other relevant information:

## Additional context

<!-- Add any other context about the problem here. -->

**Comment by tqchen** [comment]
please try out the latest instructions in https://github.com/mlc-ai/mlc-llm/pull/2095 Specifically you need to conda install gcc and libvulkan-loader in your env

**Comment by Zant12** [comment]
thanks, works now!
