### ISSUE TITLE
[Bug] phi-2-q4f16_1-MLC  crashes with nightly  JIT lib build  on cuda 12.2

### ISSUE THREAD

**Issue by Sing-Li** [mlc-ai/mlc-llm#2120]
## 🐛 Bug

Using nightly cuda builds trying to chat or serve with the phi-2-q4f16_1-MLC  model, the JIT lib build workflow crashes.

## To Reproduce

1. install nightly cuda 12.2
1. try `mlc_llm chat HF://mlc-ai/phi-2-q0f16-MLC`
1. see crash before library complete building (trace below)

```
[2024-04-10 16:30:04] INFO auto_device.py:76: Found device: cuda:0
[2024-04-10 16:30:04] INFO auto_device.py:85: Not found device: rocm:0
[2024-04-10 16:30:05] INFO auto_device.py:85: Not found device: metal:0
[2024-04-10 16:30:06] INFO auto_device.py:85: Not found device: vulkan:0
[2024-04-10 16:30:07] INFO auto_device.py:85: Not found device: opencl:0
[2024-04-10 16:30:07] INFO auto_device.py:33: Using device: cuda:0
[2024-04-10 16:30:07] INFO chat_module.py:362: Downloading model from HuggingFace: HF://mlc-ai/phi-2-q4f16_1-MLC
[2024-04-10 16:30:07] INFO download.py:40: [Git] Cloning https://huggingface.co/mlc-ai/phi-2-q4f16_1-MLC.git to /tmp/tmpsok931by/tmp
[2024-04-10 16:30:07] INFO download.py:76: [Git LFS] Downloading 0 files with Git LFS: []
0it [00:00, ?it/s]
[2024-04-10 16:30:09] INFO download.py:152: Downloaded https://huggingface.co/mlc-ai/phi-2-q4f16_1-MLC/resolve/main/params_shard_1.bin to /tmp/tmpsok931by/tmp/params_shard_1.bin
[2024-04-10 16:30:09] INFO download.py:152: Downloaded https://huggingface.co/mlc-ai/phi-2-q4f16_1-MLC/resolve/main/params
...
ms_shard_50.bin to /tmp/tmpsok931by/tmp/params_shard_50.bin
[2024-04-10 16:30:22] INFO download.py:152: Downloaded https://huggingface.co/mlc-ai/phi-2-q4f16_1-MLC/resolve/main/params_shard_49.bin to /tmp/tmpsok931by/tmp/params_shard_49.bin
100%|███████████████████████████████████████████████████████████████████████████████████| 51/51 [00:14<00:00,  3.41it/s]
[2024-04-10 16:30:22] INFO download.py:153: Moving /tmp/tmpsok931by/tmp to /root/.cache/mlc_llm/model_weights/mlc-ai/phi-2-q4f16_1-MLC
[2024-04-10 16:30:24] INFO chat_module.py:781: Model lib not found. Now compiling model lib on device...
[2024-04-10 16:30:24] INFO jit.py:35: MLC_JIT_POLICY = ON. Can be one of: ON, OFF, REDO, READONLY
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/chat_module.py", line 772, in __init__
    self.model_lib_path = _get_lib_module_path(
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/chat_module.py", line 591, in _get_lib_module_path
    raise FileNotFoundError(err_msg)
FileNotFoundError: Cannot find the model library that corresponds to `None`.
`None` is either provided in the `chat_config` you passed in, or specified in /root/.cache/mlc_llm/model_weights/mlc-ai/phi-2-q4f16_1-MLC/mlc-chat-config.json.
We searched over the following possible paths:
- None-cuda.so
- dist/prebuilt/lib/None-cuda.so
- dist/HF://mlc-ai/phi-2-q4f16_1-MLC/None-cuda.so
- /root/.cache/mlc_llm/model_weights/mlc-ai/phi-2-q4f16_1-MLC/None-cuda.so
- /root/.cache/mlc_llm/model_weights/mlc-ai/None-cuda.so
If you would like to directly specify the model library path, you may consider passing in the `ChatModule.model_lib_path` parameter.
Please checkout https://github.com/mlc-ai/notebooks/blob/main/mlc-llm/tutorial_chat_module_getting_started.ipynb for an example on how to load a model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mlc_llm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/__main__.py", line 37, in main
    cli.main(sys.argv[2:])
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/cli/chat.py", line 41, in main
    chat(
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/interface/chat.py", line 133, in chat
    cm = ChatModule(model, device, chat_config=config, model_lib_path=model_lib_path)
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/chat_module.py", line 785, in __init__
    jit.jit(
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/interface/jit.py", line 101, in jit
    "model_config": _get_model_config(),
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/interface/jit.py", line 74, in _get_model_config
    return MODELS[model_type].config.from_dict(model_config).asdict()
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/support/config.py", line 50, in from_dict
    return cls(**fields, kwargs=kwargs)  # type: ignore[call-arg]
TypeError: PhiConfig.__init__() missing 1 required positional argument: 'model_type'
```

## Expected behavior

Should build lib and start chatting as with Llama, Mistral, Gemma, Gorilla Functions, etc.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):  CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):  Ubuntu 22.04lts
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)   3060 12GB
 - How you installed MLC-LLM (`conda`, source):    nightly
 - How you installed TVM-Unity (`pip`, source):    nightly
 - Python version (e.g. 3.10):  3.11
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by Sing-Li** [comment]
Thanks for fixing this @MasterJH5574      Verified working and at 89 tokens / second on the 3060 12GB !   Awesome.
