### ISSUE TITLE
[Bug] kv_cache_bytes missing in metadata(use Python API)

### ISSUE THREAD

**Issue by XJY990705** [mlc-ai/mlc-llm#2121]
## To Reproduce

run as the get started page
https://llm.mlc.ai/docs/index.html

I have checked the issue #2065, but now I want to run in Python API, could you please help me solve this problem?
I have downloaded the latest version of mlc-llm and tvm-unity.
![image](https://github.com/mlc-ai/mlc-llm/assets/93078647/16220953-345e-4127-95d9-5b74685863f2)
## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):Ubuntu
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)PC+ RTX3080
 - How you installed MLC-LLM (`conda`, source):source
 - How you installed TVM-Unity (`pip`, source):pip
 - Python version (e.g. 3.10):3.11
 - GPU driver version (if applicable):535
 - CUDA/cuDNN version (if applicable):12.1
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
TVM_DEBUG_WITH_ABI_CHANGE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU: 
CUDA_VERSION: 12.1
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: ON
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: 
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --ignore-libllvm --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: ON
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: 6ce8430b7f8b894789e9d6a12e5fe3231290cd9c
USE_VULKAN: ON
USE_RUST_EXT: OFF
USE_CUTLASS: ON
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2024-04-08 13:06:17 -0700
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: ON
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 15.0.7
USE_MRVL: OFF
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: OFF
USE_BNNS: OFF
USE_FLASHINFER: ON
USE_CUBLAS: ON
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION: 
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /opt/rh/gcc-toolset-11/root/usr/bin/c++
HIDE_PRIVATE_SYMBOLS: ON

 - Any other relevant information:

**Comment by XJY990705** [comment]
and i got another error using command line
![image](https://github.com/mlc-ai/mlc-llm/assets/93078647/de232c89-bb34-45ab-afce-e31f84796279)

**Comment by XJY990705** [comment]
And today I got another problem, and upgrade numpy came out no difference
![image](https://github.com/mlc-ai/mlc-llm/assets/93078647/a6f3fb0a-53c5-4b97-81c2-a038cf088158)

**Comment by MasterJH5574** [comment]
Thank you @XJY990705 for reporting.

The first error is because the prebuilt library under path `dist/prebuilt_libs/Llama-2-7b-chat-hf/Llama-2-7b-chat-hf-q4f16_1-cuda.so` is outdated and does not contain the latest changes. We will update our documents to remove the incorrect examples. And meanwhile, could you just try the following for constructing the ChatModule?
```python
cm = ChatModule(model="HF://mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC")
```

I feel after trying construct ChatModule as above, you might again encounter the same issue you just report (`Unsupported layout: 0`). I don't have idea on top of my mind. Will discuss with others, see if we can address this, and report back.

**Comment by XJY990705** [comment]
@MasterJH5574 I got this problem though
![image](https://github.com/mlc-ai/mlc-llm/assets/93078647/e8443794-e8ae-4b8e-86e9-a8f9d862dba3)

**Comment by XJY990705** [comment]
And when I try to convert weight according to the document https://llm.mlc.ai/docs/compilation/convert_weights.html
I got the problem as below, and upgrading numpy did not work

(mlc-chat-venv) wangh@zj-MS-7B17:~/mlc-llm$ mlc_llm convert_weight ./dist/models/RedPajama-INCITE-Instruct-3B-v1/ \
    --quantization q4f16_1 \
    -o dist/RedPajama-INCITE-Instruct-3B-v1-q4f16_1-MLC
[2024-04-16 09:43:25] INFO auto_config.py:115: Found model configuration: dist/models/RedPajama-INCITE-Instruct-3B-v1/config.json
[2024-04-16 09:43:26] INFO auto_device.py:76: Found device: cuda:0
[2024-04-16 09:43:27] INFO auto_device.py:85: Not found device: rocm:0
[2024-04-16 09:43:28] INFO auto_device.py:85: Not found device: metal:0
[2024-04-16 09:43:29] INFO auto_device.py:76: Found device: vulkan:0
[2024-04-16 09:43:29] INFO auto_device.py:76: Found device: vulkan:1
[2024-04-16 09:43:30] INFO auto_device.py:85: Not found device: opencl:0
[2024-04-16 09:43:30] INFO auto_device.py:33: Using device: cuda:0
[2024-04-16 09:43:30] INFO auto_weight.py:70: Finding weights in: dist/models/RedPajama-INCITE-Instruct-3B-v1
[2024-04-16 09:43:30] INFO auto_weight.py:129: Found source weight format: huggingface-torch. Source configuration: dist/models/RedPajama-INCITE-Instruct-3B-v1/pytorch_model.bin
[2024-04-16 09:43:30] INFO auto_weight.py:167: Not found Huggingface Safetensor
[2024-04-16 09:43:30] INFO auto_weight.py:106: Using source weight configuration: dist/models/RedPajama-INCITE-Instruct-3B-v1/pytorch_model.bin. Use `--source` to override.
[2024-04-16 09:43:30] INFO auto_weight.py:110: Using source weight format: huggingface-torch. Use `--source-format` to override.
[2024-04-16 09:43:30] INFO auto_config.py:153: Found model type: gpt_neox. Use `--model-type` to override.
Weight conversion with arguments:
  --config          dist/models/RedPajama-INCITE-Instruct-3B-v1/config.json
  --quantization    GroupQuantize(name='q4f16_1', kind='group-quant', group_size=32, quantize_dtype='int4', storage_dtype='uint32', model_dtype='float16', linear_weight_layout='NK', quantize_embedding=True, quantize_final_fc=True, num_elem_per_storage=8, num_storage_per_group=4, max_int_value=7)
  --model-type      gpt_neox
  --device          cuda:0
  --source          dist/models/RedPajama-INCITE-Instruct-3B-v1/pytorch_model.bin
  --source-format   huggingface-torch
  --output          dist/RedPajama-INCITE-Instruct-3B-v1-q4f16_1-MLC
[2024-04-16 09:43:30] INFO gpt_neox_model.py:49: context_window_size not found in config.json. Falling back to max_position_embeddings (2048)
[2024-04-16 09:43:30] INFO gpt_neox_model.py:72: prefill_chunk_size defaults to context_window_size (2048)
Start storing to cache dist/RedPajama-INCITE-Instruct-3B-v1-q4f16_1-MLC
[2024-04-16 09:43:33] INFO huggingface_loader.py:184: Loading HF parameters from: dist/models/RedPajama-INCITE-Instruct-3B-v1/pytorch_model.bin

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0rc1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/wangh/anaconda3/envs/mlc-chat-venv/bin/mlc_llm", line 33, in <module>
    sys.exit(load_entry_point('mlc-llm', 'console_scripts', 'mlc_llm')())
  File "/home/wangh/mlc-llm/python/mlc_llm/__main__.py", line 29, in main
    cli.main(sys.argv[2:])
  File "/home/wangh/mlc-llm/python/mlc_llm/cli/convert_weight.py", line 87, in main
    convert_weight(
  File "/home/wangh/mlc-llm/python/mlc_llm/interface/convert_weight.py", line 182, in convert_weight
    _convert_args(args)
  File "/home/wangh/mlc-llm/python/mlc_llm/interface/convert_weight.py", line 146, in _convert_args
    tvmjs.dump_ndarray_cache(
  File "/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/tvm/contrib/tvmjs.py", line 210, in dump_ndarray_cache
    for k, origin_v in param_generator:
  File "/home/wangh/mlc-llm/python/mlc_llm/interface/convert_weight.py", line 123, in _param_generator
    loader = LOADER[args.source_format](
  File "/home/wangh/mlc-llm/python/mlc_llm/loader/huggingface_loader.py", line 88, in __init__
    self._load_file(path)
  File "/home/wangh/mlc-llm/python/mlc_llm/loader/huggingface_loader.py", line 188, in _load_file
    for name, param in load_func(path):
  File "/home/wangh/mlc-llm/python/mlc_llm/loader/utils.py", line 40, in load_torch_shard
    import torch  # pylint: disable=import-outside-toplevel
  File "/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
Traceback (most recent call last):
  File "/home/wangh/anaconda3/envs/mlc-chat-venv/bin/mlc_llm", line 33, in <module>
    sys.exit(load_entry_point('mlc-llm', 'console_scripts', 'mlc_llm')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangh/mlc-llm/python/mlc_llm/__main__.py", line 29, in main
    cli.main(sys.argv[2:])
  File "/home/wangh/mlc-llm/python/mlc_llm/cli/convert_weight.py", line 87, in main
    convert_weight(
  File "/home/wangh/mlc-llm/python/mlc_llm/interface/convert_weight.py", line 182, in convert_weight
    _convert_args(args)
  File "/home/wangh/mlc-llm/python/mlc_llm/interface/convert_weight.py", line 146, in _convert_args
    tvmjs.dump_ndarray_cache(
  File "/home/wangh/anaconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/tvm/contrib/tvmjs.py", line 210, in dump_ndarray_cache
    for k, origin_v in param_generator:
  File "/home/wangh/mlc-llm/python/mlc_llm/interface/convert_weight.py", line 123, in _param_generator
    loader = LOADER[args.source_format](
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangh/mlc-llm/python/mlc_llm/loader/huggingface_loader.py", line 88, in __init__
    self._load_file(path)
  File "/home/wangh/mlc-llm/python/mlc_llm/loader/huggingface_loader.py", line 188, in _load_file
    for name, param in load_func(path):
  File "/home/wangh/mlc-llm/python/mlc_llm/loader/utils.py", line 50, in load_torch_shard
    param = param.numpy()
            ^^^^^^^^^^^^^
RuntimeError: Numpy is not available

**Comment by 0xDEADFED5** [comment]
i had similar issues before. i think i fixed with `pip install numpy==1.26.4`

**Comment by XJY990705** [comment]
@0xDEADFED5 thank you !!! I tried and it works well

**Comment by XJY990705** [comment]
@MasterJH5574 
I encountered the same issue when I use llava to run in chat module. After I successfully convert weights of llava and generate chat config, I got result as below, I feel it may concerned with the version of TVM, I install the latest version of TVM Unity using pip, and I will try to install earlier version from source and see if it works well.
![image](https://github.com/mlc-ai/mlc-llm/assets/93078647/ba837605-dd1e-4cac-afe3-70484fdda901)

**Comment by MasterJH5574** [comment]
Hi @XJY990705, we have fixed this. Please update the pip package and try again :-) and also please let me know how things go.

**Comment by XJY990705** [comment]
@MasterJH5574  I tried to install TVM-Unity using pip and it works well, thank you very much!!
