### ISSUE TITLE
[Bug] Cannot read total GPU global memory from device.

### ISSUE THREAD

**Issue by hpxiong** [mlc-ai/mlc-llm#2140]
## 🐛 Bug

When running mlc_llm serve, it crashed with the above error

## To Reproduce

1. Follow Compile instruction to compile weight and libs for RedPajama-INCITE-Chat-3B-v1 with Vulkan on MTL Windows.  
2. Run mlc_llm serve with following command:
```shell
mlc_llm serve ./path/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC \
--model-lib-path ./path/RedPajama-INCITE-Chat-3B-v1-q4f16_1-vulkan.dll 
```
Then the following error will be thrown:

```shell
[2024-04-15 15:48:32] INFO auto_device.py:85: Not found device: cuda:0
[2024-04-15 15:48:34] INFO auto_device.py:85: Not found device: rocm:0
[2024-04-15 15:48:35] INFO auto_device.py:85: Not found device: metal:0
[2024-04-15 15:48:38] INFO auto_device.py:76: Found device: vulkan:0
[2024-04-15 15:48:38] INFO auto_device.py:76: Found device: vulkan:1
[2024-04-15 15:48:40] INFO auto_device.py:85: Not found device: opencl:0
[2024-04-15 15:48:40] INFO auto_device.py:33: Using device: vulkan:0
[2024-04-15 15:48:40] INFO chat_module.py:379: Using model folder: c:\llm\models\mlc\dist\weights\RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC
[2024-04-15 15:48:40] INFO chat_module.py:380: Using mlc chat config: c:\llm\models\mlc\dist\weights\RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC\mlc-chat-config.json
[2024-04-15 15:48:40] INFO chat_module.py:529: Using library model: C:\\llm\\models\\mlc\\dist\\libs_compile\\RedPajama-INCITE-Chat-3B-v1-q4f16_1-vulkan.dll
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\me\.conda\envs\llm\Scripts\mlc_llm.exe\__main__.py", line 7, in <module>
  File "C:\Users\me\.conda\envs\llm\Lib\site-packages\mlc_llm\__main__.py", line 41, in main
    cli.main(sys.argv[2:])
  File "C:\Users\me\.conda\envs\llm\Lib\site-packages\mlc_llm\cli\serve.py", line 89, in main
    serve(
  File "C:\Users\me\.conda\envs\llm\Lib\site-packages\mlc_llm\interface\serve.py", line 37, in serve
    async_engine = engine.AsyncEngine(
                   ^^^^^^^^^^^^^^^^^^^
57, in __init__
    kv_cache_config, max_single_sequence_length = _infer_kv_cache_config(
                                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\.conda\envs\llm\Lib\site-packages\mlc_llm\serve\engine_base.py", line 411, in _infer_kv_cache_config    
    local_kv_cache_config, local_mem_usage_list = infer_args_under_mode(
                                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\.conda\envs\llm\Lib\site-packages\mlc_llm\serve\engine_base.py", line 342, in infer_args_under_mode     
    ) = _estimate_mem_usage_and_max_total_sequence_length(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\.conda\envs\llm\Lib\site-packages\mlc_llm\serve\engine_base.py", line 202, in _estimate_mem_usage_and_max_total_sequence_length
    raise ValueError("Cannot read total GPU global memory from device.")
ValueError: Cannot read total GPU global memory from device.
```

## Expected behavior
mlc_llm serve should work.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Vulkan
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Windows
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) iGPU of Intel Core Ultra 7 155H 
 - How you installed MLC-LLM (`conda`, source): conda 
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.11
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

Running mlc_llm ChatModule works fine.

**Comment by tqchen** [comment]
Thanks for reporting, this should be fixed by https://github.com/apache/tvm/pull/16890

**Comment by dapengsmith** [comment]
I  met the same issue. I  manually modify the value of gpu_size_bytes in serve/engine_base.py and it can work well now.
#Line 199 
    # Get single-card GPU size.
    gpu_size_bytes = 1024*1024*1024*5#device.total_global_memory

**Comment by hpxiong** [comment]
> Thanks for reporting, this should be fixed by [apache/tvm#16890](https://github.com/apache/tvm/pull/16890)

It ran into another error

```shell
[2024-04-16 16:13:34] INFO chat_module.py:529: Using library model: C:\\llm\\models\\mlc\\dist\\prebuilt_libs\\Llama-2-7b-chat-hf\\Llama-2-7b-chat-hf-q4f16_1-vulkan.so
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\me\.conda\envs\llm\Scripts\mlc_llm.exe\__main__.py", line 7, in <module>
  File "C:\Users\me\.conda\envs\llm\Lib\site-packages\mlc_llm\__main__.py", line 41, in main
    cli.main(sys.argv[2:])
  File "C:\Users\me\.conda\envs\llm\Lib\site-packages\mlc_llm\cli\serve.py", line 89, in main
    serve(
  File "C:\Users\me\.conda\envs\llm\Lib\site-packages\mlc_llm\interface\serve.py", line 37, in serve
    async_engine = engine.AsyncEngine(
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\.conda\envs\llm\Lib\site-packages\mlc_llm\serve\engine.py", line 853, in __init__
    super().__init__(
  File "C:\Users\me\.conda\envs\llm\Lib\site-packages\mlc_llm\serve\engine_base.py", line 757, in __init__
    kv_cache_config, max_single_sequence_length = _infer_kv_cache_config(
                                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\.conda\envs\llm\Lib\site-packages\mlc_llm\serve\engine_base.py", line 315, in _infer_kv_cache_config
    ) = _get_model_config_limit(model_config_dicts)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\.conda\envs\llm\Lib\site-packages\mlc_llm\serve\engine_base.py", line 292, in _get_model_config_limit
    model_max_batch_size = min(model_max_batch_size, config["model_config"]["max_batch_size"])
                                                     ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'max_batch_size'
```

**Comment by hpxiong** [comment]
> I met the same issue. I manually modify the value of gpu_size_bytes in serve/engine_base.py and it can work well now. #Line 199 # Get single-card GPU size. gpu_size_bytes = 1024_1024_1024*5#device.total_global_memory

Thanks! This worked for me as well.

**Comment by MasterJH5574** [comment]
Hey @hpxiong, would you like to check if there is a field `max_batch_size` in your local RedPajama config at `c:\llm\models\mlc\dist\weights\RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC\mlc-chat-config.json`? It was missing in the our Hugging Face repo, but I added the RedPajama config with the `max_batch_size` field two days ago, so now it is supposed to be good. https://huggingface.co/mlc-ai/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC/blob/main/mlc-chat-config.json#L19

If you can confirm that this field does not exist in `c:\llm\models\mlc\dist\weights\RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC\mlc-chat-config.json`, the way to fix should be either remove this directory `c:\llm\models\mlc\dist\weights\RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC` and re-download the weights again, or just manually add the `max_batch_size` field into that config.

Please let me know if this can help, thanks!

**Comment by hpxiong** [comment]
> max_batch_size

@MasterJH5574 

It looks like the key indeed exists

![image](https://github.com/mlc-ai/mlc-llm/assets/17347604/95ee0b3a-b247-4912-af96-92d84c1c9149)

**Comment by hpxiong** [comment]
Actually the below line shows I must have used wrong model.  

Though I didn't have success with vulkan branch of tvm. But I will close this ticket for now since there is a workaround.  Thanks!


```shell
[2024-04-16 16:13:34] INFO chat_module.py:529: Using library model: C:\\llm\\models\\mlc\\dist\\prebuilt_libs\\Llama-2-7b-chat-hf\\Llama-2-7b-chat-hf-q4f16_1-vulkan.so
```
