### ISSUE TITLE
[Bug] OSError: libmlc_llm_module.so: undefined symbol: _ZNK3tvm7runtime8relax...

### ISSUE THREAD

**Issue by walker-ai** [mlc-ai/mlc-llm#2157]
## To Reproduce

I followed the official tutorial about [Install MLC LLM Python Package](https://llm.mlc.ai/docs/install/mlc_llm.html#install-mlc-packages).

```shell
mlc_llm chat

# or

python -c "import mlc_llm; print(mlc_llm)"

# it shows
Traceback (most recent call last):
  File "/home/walker/anaconda3/envs/mlc-llm/bin/mlc_llm", line 5, in <module>
    from mlc_llm.__main__ import main
  File "/home/walker/workspace/mlc-llm/python/mlc_llm/__init__.py", line 6, in <module>
    from . import protocol, serve
  File "/home/walker/workspace/mlc-llm/python/mlc_llm/serve/__init__.py", line 4, in <module>
    from .. import base
  File "/home/walker/workspace/mlc-llm/python/mlc_llm/base.py", line 28, in <module>
    _LIB, _LIB_PATH = _load_mlc_llm_lib()
                      ^^^^^^^^^^^^^^^^^^^
  File "/home/walker/workspace/mlc-llm/python/mlc_llm/base.py", line 23, in _load_mlc_llm_lib
    return ctypes.CDLL(lib_path[0]), lib_path[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walker/anaconda3/envs/mlc-llm/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/walker/workspace/mlc-llm/python/mlc_llm/libmlc_llm_module.so: undefined symbol: 
_ZNK3tvm7runtime8relax_vm20NDArrayCacheMetadata10FileRecord11ParamRecord4LoadE8DLDevice
PKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS0_8OptionalINS0_7NDArrayEEE
```

I have tried the 2 options (1. Prebuilt Package 2. Build from source), but the same error was encountered.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):Ubuntu 20.04
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)PC+RTX2060
 - How you installed MLC-LLM (`conda`, source):conda
 - How you installed TVM-Unity (`pip`, source):build from source
 - Python version (e.g. 3.10):3.11
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):11.4/8
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
```
### 
I have 2 envs, one is 'tvm' (TVM Unity), another is 'mlc-llm' (MLC-LLM).
And when I tried option 2(build from source), step 'python gen_cmake_config.py', 
I chose the DEFAULT TVM Unity package, which is located in 'mlc-llm/3rdparty/tvm'.
This is because when I add the previous TVM path in, it cannot be compiled correctly.
###

USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
USE_ETHOSU: OFF
CUDA_VERSION: 11.4
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: OFF
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: /home/walker/tools/llvm11.0.0/bin/llvm-config
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: OFF
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: a9065043897dda7a60c55e287701eec407cfd61e
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2023-12-23 12:43:26 +0800
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 11.0.0
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: none
USE_BNNS: OFF
USE_CUBLAS: OFF
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION: 
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /usr/bin/c++
HIDE_PRIVATE_SYMBOLS: OFF
```
 - Any other relevant information:

## Additional context

```shell
Traceback (most recent call last):
  File "/home/walker/anaconda3/envs/mlc-llm/bin/mlc_llm", line 5, in <module>
    from mlc_llm.__main__ import main
  File "/home/walker/workspace/mlc-llm/python/mlc_llm/__init__.py", line 6, in <module>
    from . import protocol, serve
  File "/home/walker/workspace/mlc-llm/python/mlc_llm/serve/__init__.py", line 4, in <module>
    from .. import base
  File "/home/walker/workspace/mlc-llm/python/mlc_llm/base.py", line 28, in <module>
    _LIB, _LIB_PATH = _load_mlc_llm_lib()
                      ^^^^^^^^^^^^^^^^^^^
  File "/home/walker/workspace/mlc-llm/python/mlc_llm/base.py", line 23, in _load_mlc_llm_lib
    return ctypes.CDLL(lib_path[0]), lib_path[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walker/anaconda3/envs/mlc-llm/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/walker/workspace/mlc-llm/python/mlc_llm/libmlc_llm_module.so: undefined symbol: 
_ZNK3tvm7runtime8relax_vm20NDArrayCacheMetadata10FileRecord11ParamRecord4LoadE8DLDevice
PKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS0_8OptionalINS0_7NDArrayEEE
```

**Comment by shreygupta2809** [comment]
Hi, Could you try building `tvm` from source again directly using [main branch of tvm](https://github.com/apache/tvm)?
Please also ensure that you pull the latest changes from the repo and also update its subdirectories using `git submodule update --recursive`.

**Comment by MasterJH5574** [comment]
The issue is simply because version mismatch. So by pinging down a preference we can make them match.

**Comment by walker-ai** [comment]
Thank you for your replies，I will try that :)

**Comment by Single430** [comment]
@MasterJH5574 Hello. I also encountered the same problem. I am currently compiling based on the latest tvm source code. How can I solve this problem？

**Comment by MasterJH5574** [comment]
@Single430 this is due to version mismatch. Would you mind sharing the detailed mlc-llm commit and tvm commit you are currently at?

**Comment by lindingyang** [comment]
have you solved the problem? @walker-ai
