### ISSUE TITLE
[Bug] Unexpected Error: The model weight size may be larger than GPU memory size 

### ISSUE THREAD

**Issue by ahz-r3v** [mlc-ai/mlc-llm#2239]
## 🐛 Bug

mlc_llm reports unexpective error "The model weight size may be larger than GPU memory size.", but the fact is that there is enough memory.  I met with the same problem when trying to run Qwen1.5-1.8B-Chat-q4f16_1-MLC and Qwen-14B-Chat-q4f32_1-MLC on my Orangepi 5 pro. 

## To Reproduce

1. git clone https://huggingface.co/mlc-ai/Qwen1.5-1.8B-Chat-q4f16_1-MLC to ./dist
2. mlc_llm compile ./dist/Qwen1.5-1.8B-Chat-q4f16_1-MLC/mlc-chat-config.json \
              --device opencl -o ./dist/Qwen1.5-1.8B-Chat-q4f16_1-MLC/Qwen1.5-1.8B-Chat-q4f16_1-opencl.so
3. mlc_llm serve ./dist/Qwen1.5-1.8B-Chat-q4f16_1-MLC/ --device opencl \
              --model-lib-path /home/Allin/mlc-llm-new/dist/Qwen1.5-1.8B-Chat-q4f16_1-MLC/Qwen1.5-1.8B-Chat-q4f16_1-opencl.so 

and the error message:
```
[2024-04-28 02:40:09] INFO auto_device.py:76: Found device: opencl:0
[2024-04-28 02:40:09] INFO chat_module.py:379: Using model folder: /home/Allin/mlc-llm-new/dist/Qwen1.5-1.8B-Chat-q4f16_1-MLC
[2024-04-28 02:40:09] INFO chat_module.py:380: Using mlc chat config: /home/Allin/mlc-llm-new/dist/Qwen1.5-1.8B-Chat-q4f16_1-MLC/mlc-chat-config.json
[2024-04-28 02:40:09] INFO chat_module.py:529: Using library model: /home/Allin/mlc-llm-new/dist/Qwen1.5-1.8B-Chat-q4f16_1-MLC/Qwen1.5-1.8B-Chat-q4f16_1-opencl.so
arm_release_ver of this libmali is 'g6p0-01eac0', rk_so_ver is '7'.
Traceback (most recent call last):
  File "/root/miniforge3/bin/mlc_llm", line 33, in <module>
    sys.exit(load_entry_point('mlc-llm', 'console_scripts', 'mlc_llm')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Allin/mlc-llm-new/python/mlc_llm/__main__.py", line 41, in main
    cli.main(sys.argv[2:])
  File "/home/Allin/mlc-llm-new/python/mlc_llm/cli/serve.py", line 75, in main
    serve(
  File "/home/Allin/mlc-llm-new/python/mlc_llm/interface/serve.py", line 43, in serve
    async_engine = engine.AsyncEngine(model_info, kv_cache_config, enable_tracing=enable_tracing)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Allin/mlc-llm-new/python/mlc_llm/serve/engine.py", line 780, in __init__
    super().__init__("async", models, kv_cache_config, engine_mode, enable_tracing)
  File "/home/Allin/mlc-llm-new/python/mlc_llm/serve/engine_base.py", line 558, in __init__
    kv_cache_config.max_total_sequence_length = _estimate_max_total_sequence_length(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Allin/mlc-llm-new/python/mlc_llm/serve/engine_base.py", line 223, in _estimate_max_total_sequence_length
    assert max_total_sequence_length > 0, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Cannot estimate KV cache capacity. The model weight size 1033572352.0 may be larger than GPU memory size 16739180544
```
But 1033572352.0 is  much smaller than 16739180544.
## Expected behavior

Not reporting any error :)

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): OpenCL
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): Orangepi5Pro(RK3588S) with 16GB ram
 - How you installed MLC-LLM (`conda`, source): from source code
 - How you installed TVM-Unity (`pip`, source): from source code
 - Python version (e.g. 3.10): 3.11.5
 - GPU driver version (if applicable): none
 - CUDA/cuDNN version (if applicable): none
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
TVM_DEBUG_WITH_ABI_CHANGE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU: OFF
CUDA_VERSION: NOT-FOUND
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: OFF
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: /home/Allin/clang+llvm-17.0.2-aarch64-linux-gnu/bin/llvm-config
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: OFF
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: 0f67508236158e5c7eb7c906df068e4ed95190f9
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2024-04-10 18:33:09 -0700
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 17.0.2
USE_MRVL: OFF
USE_OPENCL: ON
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: none
USE_BNNS: OFF
USE_FLASHINFER: 
USE_CUBLAS: OFF
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION: 
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /usr/bin/c++
HIDE_PRIVATE_SYMBOLS: ON
 - Any other relevant information: none

When trying to run Qwen-14B-Chat-q4f32_1-MLC server, the error message shows:
```
:$ mlc_llm serve Qwen-14B-Chat-q4f32_1-MLC --model-lib-path /home/Allin/mlc-llm-new/dist/Qwen-14B-Chat-q4f32_1-MLC/Qwen-14B-Chat-q4f32_1-opencl.so 
[2024-04-28 01:44:31] INFO auto_device.py:85: Not found device: cuda:0
[2024-04-28 01:44:34] INFO auto_device.py:85: Not found device: rocm:0
[2024-04-28 01:44:36] INFO auto_device.py:85: Not found device: metal:0
[2024-04-28 01:44:38] INFO auto_device.py:85: Not found device: vulkan:0
[2024-04-28 01:44:42] INFO auto_device.py:76: Found device: opencl:0
[2024-04-28 01:44:42] INFO auto_device.py:33: Using device: opencl:0
[2024-04-28 01:44:42] INFO chat_module.py:379: Using model folder: /home/Allin/mlc-llm-new/Qwen-14B-Chat-q4f32_1-MLC
[2024-04-28 01:44:42] INFO chat_module.py:380: Using mlc chat config: /home/Allin/mlc-llm-new/Qwen-14B-Chat-q4f32_1-MLC/mlc-chat-config.json
[2024-04-28 01:44:42] INFO chat_module.py:529: Using library model: /home/Allin/mlc-llm-new/dist/Qwen-14B-Chat-q4f32_1-MLC/Qwen-14B-Chat-q4f32_1-opencl.so
arm_release_ver of this libmali is 'g6p0-01eac0', rk_so_ver is '7'.
Traceback (most recent call last):
  File "/root/miniforge3/bin/mlc_llm", line 33, in <module>
    sys.exit(load_entry_point('mlc-llm', 'console_scripts', 'mlc_llm')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Allin/mlc-llm-new/python/mlc_llm/__main__.py", line 41, in main
    cli.main(sys.argv[2:])
  File "/home/Allin/mlc-llm-new/python/mlc_llm/cli/serve.py", line 75, in main
    serve(
  File "/home/Allin/mlc-llm-new/python/mlc_llm/interface/serve.py", line 43, in serve
    async_engine = engine.AsyncEngine(model_info, kv_cache_config, enable_tracing=enable_tracing)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Allin/mlc-llm-new/python/mlc_llm/serve/engine.py", line 780, in __init__
    super().__init__("async", models, kv_cache_config, engine_mode, enable_tracing)
  File "/home/Allin/mlc-llm-new/python/mlc_llm/serve/engine_base.py", line 558, in __init__
    kv_cache_config.max_total_sequence_length = _estimate_max_total_sequence_length(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Allin/mlc-llm-new/python/mlc_llm/serve/engine_base.py", line 223, in _estimate_max_total_sequence_length
    assert max_total_sequence_length > 0, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Cannot estimate KV cache capacity. The model weight size 8858030080.0 may be larger than GPU memory size 16739180544
```

**Comment by ahz-r3v** [comment]
in case these can be useful:
I added some prints in engine_base.py:
```
max_total_sequence_length = int(
        (
            int(gpu_size_bytes) * 0.90
            - params_bytes
            - temp_func_bytes
            - kv_aux_workspace_bytes
            - model_workspace_bytes
            - logit_processor_workspace_bytes
        )
        / kv_bytes_per_token
    )
    print("temp_func_bytes: {}".format(temp_func_bytes))
    print("kv_aux_workspace_bytes: {}".format(kv_aux_workspace_bytes))
    print("model_workspace_bytes: {}".format(model_workspace_bytes))
    print("logit_processor_workspace_bytes: {}".format(logit_processor_workspace_bytes))
    print("kv_bytes_per_token: {}".format(kv_bytes_per_token))
    assert max_total_sequence_length > 0, (
        "Cannot estimate KV cache capacity. "
        f"The model weight size {params_bytes} may be larger than GPU memory size {gpu_size_bytes}"
    )
```
and here's outputs:
```
temp_func_bytes: 21852323840
kv_aux_workspace_bytes: 591666136
model_workspace_bytes: 268894528
logit_processor_workspace_bytes: 195999040.0
kv_bytes_per_token: 196609.25
```

**Comment by tqchen** [comment]
Thanks for reporting. As a temp measure. Reduce the prefill chunk size might help. We should followup by auto limit this number when we run gen config

**Comment by Hzfengsy** [comment]
cc @MasterJH5574 to see if we can enhance the error message

**Comment by ahz-r3v** [comment]
> Thanks for reporting. As a temp measure. Reduce the prefill chunk size might help. We should followup by auto limit this number when we run gen config

Thanks for the solution. After reducing prefill chunk size and context_window_size to 4096, it runs properly.

**Comment by ahz-r3v** [comment]
> Thanks for reporting. As a temp measure. Reduce the prefill chunk size might help. We should followup by auto limit this number when we run gen config

Thanks for the solution. But after reducing prefill chunk size to 4096, `mlc_llm serve` still gets the same error running  Qwen1.5-1.8B-Chat-q4f16_1-MLC: 
```
(base) root@orangepi5pro:/home/Allin/mlc-llm-new# mlc_llm serve ./dist/Qwen1.5-1.8B-Chat-q4f16_1-MLC/ --device opencl --model-lib-path /home/Allin/mlc-llm-new/dist/Qwen1.5-1.8B-Chat-q4f16_1-MLC/Qwen1.5-1.8B-Chat-q4f16_1-opencl.so 
[2024-04-28 23:11:54] INFO auto_device.py:76: Found device: opencl:0
[2024-04-28 23:11:54] INFO chat_module.py:379: Using model folder: /home/Allin/mlc-llm-new/dist/Qwen1.5-1.8B-Chat-q4f16_1-MLC
[2024-04-28 23:11:54] INFO chat_module.py:380: Using mlc chat config: /home/Allin/mlc-llm-new/dist/Qwen1.5-1.8B-Chat-q4f16_1-MLC/mlc-chat-config.json
[2024-04-28 23:11:54] INFO chat_module.py:529: Using library model: /home/Allin/mlc-llm-new/dist/Qwen1.5-1.8B-Chat-q4f16_1-MLC/Qwen1.5-1.8B-Chat-q4f16_1-opencl.so
arm_release_ver of this libmali is 'g6p0-01eac0', rk_so_ver is '7'.
gpu_size_bytes: 16739180544
params_bytes: 1033572352.0
temp_func_bytes: 21852323840
kv_aux_workspace_bytes: 118004696
model_workspace_bytes: 33898816
logit_processor_workspace_bytes: 195999040.0
kv_bytes_per_token: 196609.25
Traceback (most recent call last):
  File "/root/miniforge3/bin/mlc_llm", line 33, in <module>
    sys.exit(load_entry_point('mlc-llm', 'console_scripts', 'mlc_llm')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Allin/mlc-llm-new/python/mlc_llm/__main__.py", line 41, in main
    cli.main(sys.argv[2:])
  File "/home/Allin/mlc-llm-new/python/mlc_llm/cli/serve.py", line 75, in main
    serve(
  File "/home/Allin/mlc-llm-new/python/mlc_llm/interface/serve.py", line 43, in serve
    async_engine = engine.AsyncEngine(model_info, kv_cache_config, enable_tracing=enable_tracing)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Allin/mlc-llm-new/python/mlc_llm/serve/engine.py", line 780, in __init__
    super().__init__("async", models, kv_cache_config, engine_mode, enable_tracing)
  File "/home/Allin/mlc-llm-new/python/mlc_llm/serve/engine_base.py", line 565, in __init__
    kv_cache_config.max_total_sequence_length = _estimate_max_total_sequence_length(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Allin/mlc-llm-new/python/mlc_llm/serve/engine_base.py", line 230, in _estimate_max_total_sequence_length
    assert max_total_sequence_length > 0, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Cannot estimate KV cache capacity. The model weight size 1033572352.0 may be larger than GPU memory size 16739180544
```

Here's my mlc-chat-config.json after changing `prefill_chunk_size` and `context_window_size` to 4096:
```
{
  "model_type": "qwen2",
  "quantization": "q4f16_1",
  "model_config": {
    "hidden_act": "silu",
    "hidden_size": 2048,
    "intermediate_size": 5504,
    "num_attention_heads": 16,
    "num_hidden_layers": 24,
    "num_key_value_heads": 16,
    "rms_norm_eps": 1e-06,
    "rope_theta": 1000000.0,
    "vocab_size": 151936,
    "context_window_size": 4096,
    "prefill_chunk_size": 4096,
    "tensor_parallel_shards": 1,
    "head_dim": 128,
    "dtype": "float32"
  },
  "vocab_size": 151936,
  "context_window_size": 4096,
  "sliding_window_size": -1,
  "prefill_chunk_size": 4096,
  "attention_sink_size": -1,
  "tensor_parallel_shards": 1,
  "mean_gen_len": 128,
  "max_gen_len": 512,
  "shift_fill_factor": 0.3,
  "temperature": 0.7,
  "presence_penalty": 0.0,
  "freq_uency_penalty": 0.0,
  "repetition_penalty": 1.1,
  "top_p": 0.8,
  "conv_template": {
    "name": "mistral_default",
    "system_template": "[INST] {system_message}",
    "system_message": "Always assist with care, respect, and truth. Respond with utmost utility yet securely. Avoid harmful, unethical, prejudiced, or negative content. Ensure replies promote fairness and positivity.",
    "system_prefix_token_ids": [
      1
    ],
    "add_role_after_system_message": true,
    "roles": {
      "user": "<|im_start|>user",
      "assistant": "<|im_start|>assistant"
    },
    "role_templates": {
      "user": "{user_message}",
      "assistant": "{assistant_message}",
      "tool": "{tool_message}"
    },
    "messages": [],
    "seps": [
      "<|im_end|>\n"
    ],
    "role_content_sep": "\n",
    "role_empty_sep": "\n",
    "stop_str": [
      "<|im_end|>"
    ],
    "stop_token_ids": [
      151643
    ],
    "function_string": "",
    "use_function_calling": false
  },
  "pad_token_id": 151643,
  "bos_token_id": 151643,
  "eos_token_id": [
    151645,
    151643
  ],
  "tokenizer_files": [
    "tokenizer.json",
    "vocab.json",
    "merges.txt",
    "tokenizer_config.json",
    "added_tokens.json"
  ],
  "version": "0.1.0"
}
```
And I also tried Qwen-7B-Chat-q4f16_1-MLC(https://huggingface.co/mlc-ai/Qwen-7B-Chat-q4f16_1-MLC), this model works fine both on `mlc_llm chat` and `mlc_llm serve`.

**Comment by tqchen** [comment]
@ahz-r3v you might need to cross check if you have recompiled the lib
