### ISSUE TITLE
[Bug] TVMError: Check failed: (result) is false: Failed to allocate 99121664 bytes with alignment 16 bytes

### ISSUE THREAD

**Issue by zhjunqin** [mlc-ai/mlc-llm#2243]
## 🐛 Bug

mlc_ai_nightly_cu121-0.15.dev315-cp310-cp310-manylinux_2_28_x86_64.whl
mlc_llm_nightly_cu121-0.1.dev1166-cp310-cp310-manylinux_2_28_x86_64.whl

benchmark with llama3 model, got following error:

INFO:     127.0.0.1:57104 - "POST /v1/chat/completions HTTP/1.1" 200 OK
Exception in thread Thread-1 (_background_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mlc_llm/serve/engine_base.py", line 1096, in _background_loop
    self._ffi["run_background_loop"]()
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/opt/conda/lib/python3.10/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::contrib::__mk_TVM0::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::contrib::__mk_TVM0, tvm::runtime::TVMRetValue)
  2: void tvm::contrib::thrust_sort<float, int>(DLTensor*, DLTensor*, DLTensor*, bool, int, DLTensor*) [clone .isra.0]
  1: thrust::detail::temporary_allocator<unsigned char, thrust::detail::execute_with_allocator<thrust::mr::allocator<max_align_t, tvm::contrib::WorkspaceMemoryResource>, thrust::cuda_cub::execute_on_stream_nosync_base> >::allocate(unsigned long)
  0: _ZN3tvm7runtime6deta
  File "/workspace/tvm/src/runtime/contrib/thrust/thrust.cu", line 66
TVMError: Check failed: (result) is false: Failed to allocate 99121664 bytes with alignment 16 bytes.

## To Reproduce

1.
1.
1.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
- CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):
 - Ubuntu
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - RTX3090
 - How you installed MLC-LLM (`conda`, source):
 - PIP
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by tqchen** [comment]
Thanks for reporting, this could relates to the thrust size estimation and maximum batch size, if there are more details, feel free to post it. as of now it is hard to reproduce the example, as a result, closing this issue for now as likely latest gpu sampler might addressed this issue, feel free to open new ones
