### ISSUE TITLE
Android MLCChat failed ,[Bug] 

### ISSUE THREAD

**Issue by View999888** [mlc-ai/mlc-llm#2302]
![1d61b3b81f3a81ff1e3399f529ac703](https://github.com/mlc-ai/mlc-llm/assets/64066249/9b8a5741-110f-4a1b-8e9c-291e3c4fe622)

How can this error be resolved?

Stack trace:
org.apache.tvm.Base$TVMError: InternalError: Check failed: (chat_ != nullptr) is false: Chat is not initialized via reload
Stack trace:
  File "/Users/rageshantonyd/Documents/working_prj/mlc-llm/cpp/llm_chat.cc", line 1744

	at org.apache.tvm.Base.checkCall(Base.java:173)
	at org.apache.tvm.Function.invoke(Function.java:130)
	at ai.mlc.mlcllm.ChatModule.prefill(ChatModule.java:54)
	at ai.mlc.mlcchat.AppViewModel$ChatState$requestGenerate$1$1.invoke(AppViewModel.kt:666)
	at ai.mlc.mlcchat.AppViewModel$ChatState$requestGenerate$1$1.invoke(AppViewModel.kt:666)
	at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:548)
	at ai.mlc.mlcchat.AppViewModel$ChatState.requestGenerate$lambda$4(AppViewModel.kt:666)
	at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$lluIrcsPALEW5nCb2tohZYadhTY(Unknown Source:0)
	at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda3.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

Error message:
InternalError: Check failed: (chat_ != nullptr) is false: Chat is not initialized via reload
Stack trace:
  File "/Users/rageshantonyd/Documents/working_prj/mlc-llm/cpp/llm_chat.cc", line 1744

**Comment by View999888** [comment]
问题 1 :如何获取到app_config.json 中的model_lib_path_for_prepare_libs中的模型文件
问题 2 :apk 怎么和模型文件相互联系的

**Comment by abhishekdewan101** [comment]
I had the same issue running on both emulator and device.

**Comment by BlindDeveloper** [comment]
@View999888
Good day, if you try 7 or 8b models you need 8 gb ram.
@abhishekdewan101
Mlc llm working on device only.

**Comment by View999888** [comment]
ERROR:  No module named ‘tvm’

![tvm](https://github.com/mlc-ai/mlc-llm/assets/64066249/fa32b52c-fdbf-49d1-adb7-3faf732e0042)


How to generate 'tvm' ? 
Please have a workaround address

**Comment by MasterJH5574** [comment]
Hi folks, we just did an android build flow refactor yesterday. The new android build flow requires fewer steps. The documentation has been revamped to the new flow https://llm.mlc.ai/docs/deploy/android.html. Could you check out and try again?

Before doing that, please also upgrade your mlc-llm and tvm to use the latest nightly by following instructions in https://llm.mlc.ai/docs/install/mlc_llm.html.

**Comment by MasterJH5574** [comment]
> ERROR: No module named ‘tvm’
> 
> ![tvm](https://private-user-images.githubusercontent.com/64066249/329184735-fa32b52c-fdbf-49d1-adb7-3faf732e0042.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNTE2MDMsIm5iZiI6MTcxNTM1MTMwMywicGF0aCI6Ii82NDA2NjI0OS8zMjkxODQ3MzUtZmEzMmI1MmMtZmRiZi00OWQxLWFkYjctM2ZhZjczMmUwMDQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDE0MjgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNWZjZjVhYzM0NmMyMGZhNzdhZDg4Njk4ODBkMTIxNWZmODIxZTIzZjRjNjVhMTg0NzExZDVhZTdhNzYzZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._WWNXXK4Ka9QNRWbkOqxmzw78JQ3_G6WDsi5FK9oLNc)
> 
> How to generate 'tvm' ? Please have a workaround address

@View999888 You need to install tvm by following https://llm.mlc.ai/docs/install/mlc_llm.html.

**Comment by lengjing606** [comment]
@View999888 你的已经ok了吗 我发现demo apk都有问题
