### ISSUE TITLE
libmodel_android.a error when build android sdk

### ISSUE THREAD

**Issue by lengjing606** [mlc-ai/mlc-llm#2317]
I'm trying build android sdk but got an error with error: (nm: invalid argument to -U/--unicode: dist/lib/libmodel_android.a)
when excuting: mlc_llm package --device android --output dist mlc-package-config.json
Whats wrong and how to fix it?

colab code:
!source $HOME/.cargo/env && \
export PATH=$PATH:/content/androidSdk/cmake/3.22.1/bin && \
export ANDROID_NDK=/content/androidSdk/ndk/26.2.11394342 && \
export TVM_NDK_CC=/content/androidSdk/ndk/26.2.11394342/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang && \
export TVM_HOME=/content/mlc-llm/3rdparty/tvm && \
export MLC_LLM_HOME=/content/mlc-llm && \
mlc_llm package --device android --output dist mlc-package-config.json

error:
[2024-05-10 09:21:39] INFO package.py:142: Clean up all directories under "dist/bundle"
[2024-05-10 09:21:39] INFO jit.py:43: MLC_JIT_POLICY = ON. Can be one of: ON, OFF, REDO, READONLY
[2024-05-10 09:21:39] INFO chat_module.py:379: Using model folder: /content/mlc-llm/dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC
[2024-05-10 09:21:39] INFO chat_module.py:380: Using mlc chat config: /content/mlc-llm/dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC/mlc-chat-config.json
[2024-05-10 09:21:39] INFO package.py:198: Model lib is not specified for model "RedPajama-INCITE-Chat-3B-v1-q4f16_1". Now jit compile the model library.
[2024-05-10 09:21:39] INFO jit.py:120: Compiling using commands below:
[2024-05-10 09:21:39] INFO jit.py:121: /usr/bin/python3 -m mlc_llm compile /content/mlc-llm/dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC --opt 'flashinfer=1;cublas_gemm=1;faster_transformer=1;cudagraph=0;cutlass=1;ipc_allreduce_strategy=NONE' --overrides 'context_window_size=768;prefill_chunk_size=768;tensor_parallel_shards=1' --device android --output /tmp/tmpr7nwf6ja/lib.tar --system-lib-prefix gpt_neox_q4f16_1_74594e3964d8e2a2df0222b930ea2162_
[2024-05-10 09:21:43] INFO auto_config.py:69: Found model configuration: /content/mlc-llm/dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC/mlc-chat-config.json
[2024-05-10 09:21:43] INFO auto_config.py:153: Found model type: gpt_neox. Use `--model-type` to override.
Compiling with arguments:
  --config          GPTNeoXConfig(use_parallel_residual=False, hidden_size=2560, intermediate_size=10240, num_attention_heads=32, num_hidden_layers=32, layer_norm_eps=1e-05, vocab_size=50432, rotary_pct=1.0, position_embedding_base=10000, context_window_size=768, head_dim=80, prefill_chunk_size=768, tensor_parallel_shards=1, ffn_out_dtype='float32', max_batch_size=80, kwargs={})
  --quantization    GroupQuantize(name='q4f16_1', kind='group-quant', group_size=32, quantize_dtype='int4', storage_dtype='uint32', model_dtype='float16', linear_weight_layout='NK', quantize_embedding=True, quantize_final_fc=True, num_elem_per_storage=8, num_storage_per_group=4, max_int_value=7)
  --model-type      gpt_neox
  --target          {"thread_warp_size": 1, "host": {"kind": "llvm", "tag": "", "keys": ["arm_cpu", "cpu"], "mtriple": "aarch64-linux-android"}, "texture_spatial_limit": 16384, "max_threads_per_block": 256, "max_function_args": 128, "max_num_threads": 256, "kind": "opencl", "max_shared_memory_per_block": 16384, "tag": "", "keys": ["opencl", "gpu"]}
  --opt             flashinfer=0;cublas_gemm=0;faster_transformer=0;cudagraph=0;cutlass=0;ipc_allreduce_strategy=NONE
  --system-lib-prefix "gpt_neox_q4f16_1_74594e3964d8e2a2df0222b930ea2162_"
  --output          /tmp/tmpr7nwf6ja/lib.tar
  --overrides       context_window_size=768;sliding_window_size=None;prefill_chunk_size=768;attention_sink_size=None;max_batch_size=None;tensor_parallel_shards=1
[2024-05-10 09:21:43] INFO config.py:106: Overriding context_window_size from 768 to 768
[2024-05-10 09:21:43] INFO config.py:106: Overriding prefill_chunk_size from 768 to 768
[2024-05-10 09:21:43] INFO config.py:106: Overriding tensor_parallel_shards from 1 to 1
[2024-05-10 09:21:43] INFO compile.py:138: Creating model from: GPTNeoXConfig(use_parallel_residual=False, hidden_size=2560, intermediate_size=10240, num_attention_heads=32, num_hidden_layers=32, layer_norm_eps=1e-05, vocab_size=50432, rotary_pct=1.0, position_embedding_base=10000, context_window_size=768, head_dim=80, prefill_chunk_size=768, tensor_parallel_shards=1, ffn_out_dtype='float32', max_batch_size=80, kwargs={})
[2024-05-10 09:21:43] INFO compile.py:157: Exporting the model to TVM Unity compiler
[2024-05-10 09:21:47] INFO compile.py:163: Running optimizations using TVM Unity
[2024-05-10 09:21:47] INFO compile.py:181: Registering metadata: {'model_type': 'gpt_neox', 'quantization': 'q4f16_1', 'context_window_size': 768, 'sliding_window_size': -1, 'attention_sink_size': -1, 'prefill_chunk_size': 768, 'tensor_parallel_shards': 1, 'kv_cache_bytes': 0}
[2024-05-10 09:21:50] INFO pipeline.py:52: Running TVM Relax graph-level optimizations
[2024-05-10 09:21:58] INFO pipeline.py:52: Lowering to TVM TIR kernels
[2024-05-10 09:22:18] INFO pipeline.py:52: Running TVM TIR-level optimizations
[2024-05-10 09:22:59] INFO pipeline.py:52: Running TVM Dlight low-level optimizations
[2024-05-10 09:23:03] INFO pipeline.py:52: Lowering to VM bytecode
[2024-05-10 09:23:09] INFO estimate_memory_usage.py:57: [Memory usage] Function `alloc_embedding_tensor`: 3.75 MB
[2024-05-10 09:23:10] INFO estimate_memory_usage.py:57: [Memory usage] Function `batch_decode`: 3.52 MB
[2024-05-10 09:23:10] INFO estimate_memory_usage.py:57: [Memory usage] Function `batch_prefill`: 33.75 MB
[2024-05-10 09:23:10] INFO estimate_memory_usage.py:57: [Memory usage] Function `batch_verify`: 33.75 MB
[2024-05-10 09:23:10] INFO estimate_memory_usage.py:57: [Memory usage] Function `create_tir_paged_kv_cache`: 0.00 MB
[2024-05-10 09:23:10] INFO estimate_memory_usage.py:57: [Memory usage] Function `decode`: 0.04 MB
[2024-05-10 09:23:10] INFO estimate_memory_usage.py:57: [Memory usage] Function `embed`: 3.75 MB
[2024-05-10 09:23:10] INFO estimate_memory_usage.py:57: [Memory usage] Function `prefill`: 33.75 MB
[2024-05-10 09:23:10] INFO estimate_memory_usage.py:57: [Memory usage] Function `softmax_with_temperature`: 0.00 MB
[2024-05-10 09:23:13] INFO pipeline.py:52: Compiling external modules
[2024-05-10 09:23:13] INFO pipeline.py:52: Compilation complete! Exporting to disk
[2024-05-10 09:23:24] INFO model_metadata.py:96: Total memory usage: 1525.09 MB (Parameters: 1491.34 MB. KVCache: 0.00 MB. Temporary buffer: 33.75 MB)
[2024-05-10 09:23:24] INFO model_metadata.py:105: To reduce memory usage, tweak `prefill_chunk_size`, `context_window_size` and `sliding_window_size`
[2024-05-10 09:23:24] INFO compile.py:203: Generated: /tmp/tmpr7nwf6ja/lib.tar
[2024-05-10 09:23:25] INFO jit.py:128: Using compiled model lib: /root/.cache/mlc_llm/model_lib/b48ad1fec028c53c0957452e4c5f9694.tar
[2024-05-10 09:23:25] INFO package.py:246: Bundle weight for RedPajama-INCITE-Chat-3B-v1-q4f16_1, copy into dist/bundle/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC
[2024-05-10 09:23:39] INFO package.py:271: Dump the app config below to "dist/bundle/mlc-app-config.json":
{
  "model_list": [
    {
      "model_id": "RedPajama-INCITE-Chat-3B-v1-q4f16_1",
      "model_lib": "gpt_neox_q4f16_1_74594e3964d8e2a2df0222b930ea2162",
      "model_path": "RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC",
      "estimated_vram_bytes": 1948348579
    }
  ]
}
Traceback (most recent call last):
  File "/usr/local/bin/mlc_llm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/__main__.py", line 49, in main
    cli.main(sys.argv[2:])
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/cli/package.py", line 51, in main
    package(
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/interface/package.py", line 277, in package
    validate_model_lib(
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/interface/package.py", line 71, in validate_model_lib
    available_model_libs = _get_model_libs(lib_path)
  File "/usr/local/lib/python3.10/dist-packages/mlc_llm/interface/package.py", line 24, in _get_model_libs
    global_symbol_map = cc.get_global_symbol_section_map(lib_path)
  File "/usr/local/lib/python3.10/dist-packages/tvm/contrib/cc.py", line 215, in get_global_symbol_section_map
    raise RuntimeError(msg)
RuntimeError: Runtime error:
nm: invalid argument to -U/--unicode: dist/lib/libmodel_android.a

**Comment by tqchen** [comment]
Can you cross check the nm command in your system, this might due to some differencs in behavior of nm

**Comment by tqchen** [comment]
https://www.man7.org/linux/man-pages/man1/nm.1.html

**Comment by tqchen** [comment]
You can try confirm with which nm

**Comment by tqchen** [comment]
You can try to run conda install nm

**Comment by MasterJH5574** [comment]
Hi @lengjing606, we've updated the android flow again. The latest documentation introduces the new flow https://llm.mlc.ai/docs/deploy/android.html. Could you please update the mlc-llm pip package and try again?

To summarize the new flow, first we need to make sure that `"device": "android"` exists in `mlc-package-config.json`, and then the command
```
mlc_llm package
```
does everything, without needing additional arguments.

**Comment by lengjing606** [comment]
@MasterJH5574 it work fine now,thanks

**Comment by zw0241** [comment]
> @MasterJH5574 it work fine now,thanks
I have updated the latest code, but I'm still getting the same error. How did you solve it? Did you install mlc_llm and TVM based on source code, or  install pre-built binaries? The mlc_llm I installed is from: mlc_llm_nightly_cu122-0.1.dev1213-cp311-cp311-manylinux_2_28_x86_64.whl and mlc_ai_nightly_cu122-0.15.dev315-cp311-cp311-manylinux_2_28_x86_64.whl.

**Comment by MasterJH5574** [comment]
@zw0241 Please update your mlc_llm package and mlc_ai package by following https://llm.mlc.ai/docs/install/mlc_llm.html and try again. The latest wheel is `dev1224` for mlc_llm.

**Comment by zw0241** [comment]
> @zw0241 Please update your mlc_llm package and mlc_ai package by following https://llm.mlc.ai/docs/install/mlc_llm.html and try again. The latest wheel (as of this moment) is `dev1224` for mlc_llm.

yes. It's resolved now. Thank you.

**Comment by MasterJH5574** [comment]
@lengjing606 @zw0241 thank you for getting back. Glad that the new flow works smoothly.
