### ISSUE TITLE
Build.py iOS missing 1 required positional argument: 'target'

### ISSUE THREAD

**Issue by VnykBabyshki** [mlc-ai/mlc-llm#233]
```
(nvnew) vnykbabyshki@vnyks-mbp mlc-llm % python3 build.py            \
    --model vicuna-v1-7b    \
    --quantization q3f16_0  \
    --target iphone         \
    --max-seq-len 768
Using path "dist/models/vicuna-v1-7b" for model "vicuna-v1-7b"
Database paths: ['log_db/redpajama-3b-q4f16', 'log_db/redpajama-3b-q4f32', 'log_db/dolly-v2-3b', 'log_db/vicuna-v1-7b']
Target configured: metal -keys=metal,gpu -libs=iphoneos -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=256 -thread_warp_size=1
Loading checkpoint shards: 100%|█████████████████████████████████████████████| 4/4 [01:17<00:00, 19.34s/it]
[22:03:25] /Users/catalyst/Workspace/wheel-build/tvm/src/runtime/metal/metal_device_api.mm:165: Intializing Metal device 0, name=Apple M1
Automatically using target for weight quantization: metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32
Traceback (most recent call last):
  File "/Users/vnykbabyshki/Downloads/mlc-llm/build.py", line 390, in <module>
    main()
  File "/Users/vnykbabyshki/Downloads/mlc-llm/build.py", line 368, in main
    mod = mod_transform_before_build(mod, params, ARGS)
  File "/Users/vnykbabyshki/Downloads/mlc-llm/build.py", line 254, in mod_transform_before_build
    new_params = utils.transform_params(mod_transform, model_params)
  File "/Users/vnykbabyshki/Downloads/mlc-llm/mlc_llm/utils.py", line 151, in transform_params
    ex = relax.build(mod_transform, target=target)
  File "/Users/vnykbabyshki/Downloads/nvnew/lib/python3.10/site-packages/tvm/relax/vm_build.py", line 338, in build
    return _vmlink(builder, target, tir_mod, ext_libs, params, system_lib=system_lib)
  File "/Users/vnykbabyshki/Downloads/nvnew/lib/python3.10/site-packages/tvm/relax/vm_build.py", line 242, in _vmlink
    lib = tvm.build(
  File "/Users/vnykbabyshki/Downloads/nvnew/lib/python3.10/site-packages/tvm/driver/build_module.py", line 281, in build
    rt_mod_host = _driver_ffi.tir_to_runtime(annotated_mods, target_host)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
TypeError: Traceback (most recent call last):
  File "tvm/_ffi/_cython/./packed_func.pxi", line 56, in tvm._ffi._cy3.core.tvm_callback
TypeError: parse_target.<locals>.compile_metal() missing 1 required positional argument: 'target'
```

**Comment by rapidlugo** [comment]
@VnykBabyshki  This was just solved a little while ago. In order to get this fixed, pull down the latest TVM nightlies (rebuild if you've done it manually), **AND** pull down the latest code from this repo. There were some fixes added that synced up these usages.

**Comment by dongqihouse** [comment]
I encountered the same problem. [#226](https://github.com/mlc-ai/mlc-llm/issues/226#issuecomment-1562388609) is not worked for me.

**Comment by VnykBabyshki** [comment]
@rapidlugo you were right, I just `git pull` the mlc-llm, got few updates and it worked. Thank you!
