### ISSUE TITLE
[Question] Can not get chat CLI working, throwing error after cloning model

### ISSUE THREAD

**Issue by BeytoA** [mlc-ai/mlc-llm#2339]
## ❓ General Questions

Windows 10 64-bit
Intel Xeon W2123 3.60GHz
24,0GB 2666MHz
NVIDIA Quadro P2000

I just installed conda and created a new environment. According to the quick start guide the installation is successful. But when I try to launch chat CLI, and get below error.

```
(base) C:\Users\mypc>conda activate llmENV

(llmENV) C:\Users\mypc>python -c "import mlc_llm; print(mlc_llm)"

<module 'mlc_llm' from 'C:\\Users\\mypc\\AppData\\Local\\miniconda3\\envs\\llmENV\\Lib\\site-packages\\mlc_llm\\__init__.py'>

(llmENV) C:\Users\mypc>mlc_llm chat HF://mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC
[2024-05-14 13:42:58] INFO auto_device.py:88: ←[91mNot found←[0m device: cuda:0
[2024-05-14 13:43:00] INFO auto_device.py:88: ←[91mNot found←[0m device: rocm:0
[2024-05-14 13:43:03] INFO auto_device.py:88: ←[91mNot found←[0m device: metal:0
[2024-05-14 13:43:08] INFO auto_device.py:79: ←[92mFound←[0m device: vulkan:0
[2024-05-14 13:43:10] INFO auto_device.py:88: ←[91mNot found←[0m device: opencl:0
[2024-05-14 13:43:10] INFO auto_device.py:35: Using device: ←[1mvulkan:0←[0m
[2024-05-14 13:43:10] INFO chat_module.py:362: Downloading model from HuggingFace: HF://mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC
[2024-05-14 13:43:10] INFO download.py:42: [Git] Cloning https://huggingface.co/mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC.git to C:\Users\mypc\AppData\Local\Temp\tmpd999_qpt\tmp
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mypc\AppData\Local\miniconda3\envs\llmENV\Scripts\mlc_llm.exe\__main__.py", line 7, in <module>
  File "C:\Users\mypc\AppData\Local\miniconda3\envs\llmENV\Lib\site-packages\mlc_llm\__main__.py", line 37, in main
    cli.main(sys.argv[2:])
  File "C:\Users\mypc\AppData\Local\miniconda3\envs\llmENV\Lib\site-packages\mlc_llm\cli\chat.py", line 42, in main
    chat(
  File "C:\Users\mypc\AppData\Local\miniconda3\envs\llmENV\Lib\site-packages\mlc_llm\interface\chat.py", line 134, in chat
    cm = ChatModule(model, device, chat_config=config, model_lib=model_lib)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mypc\AppData\Local\miniconda3\envs\llmENV\Lib\site-packages\mlc_llm\chat_module.py", line 765, in __init__
    self.model_path, self.config_file_path = _get_model_path(model)
                                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mypc\AppData\Local\miniconda3\envs\llmENV\Lib\site-packages\mlc_llm\chat_module.py", line 363, in _get_model_path
    mlc_dir = download_mlc_weights(model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mypc\AppData\Local\miniconda3\envs\llmENV\Lib\site-packages\mlc_llm\support\download.py", line 138, in download_mlc_weights
    git_clone(git_url, tmp_dir, ignore_lfs=True)
  File "C:\Users\mypc\AppData\Local\miniconda3\envs\llmENV\Lib\site-packages\mlc_llm\support\download.py", line 43, in git_clone
    subprocess.run(
  File "C:\Users\mypc\AppData\Local\miniconda3\envs\llmENV\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mypc\AppData\Local\miniconda3\envs\llmENV\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\mypc\AppData\Local\miniconda3\envs\llmENV\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

(llmENV) C:\Users\mypc>
```

**Comment by tqchen** [comment]
error message said you do not support f16, so please try to use a q4f32 variant of the model

**Comment by tqchen** [comment]
```
mlc_llm chat HF://mlc-ai/Llama-3-8B-Instruct-q4f32_1-MLC
```
