### ISSUE TITLE
m2 mac is not supported

### ISSUE THREAD

**Issue by li2109** [mlc-ai/mlc-llm#236]
I was trying the following command: 
`python3 build.py --hf-path databricks/dolly-v2-3b --quantization q3f16_0 --max-seq-len 768`
but it didn't work:

```
Weights exist at dist/models/dolly-v2-3b, skipping download.
Using path "dist/models/dolly-v2-3b" for model "dolly-v2-3b"
Database paths: ['log_db/redpajama-3b-q4f16', 'log_db/redpajama-3b-q4f32', 'log_db/dolly-v2-3b', 'log_db/vicuna-v1-7b']
[18:36:54] /Users/runner/work/package/package/tvm/src/runtime/metal/metal_device_api.mm:165: Intializing Metal device 0, name=Apple M2 Pro
Target configured: metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32
Target: Namespace(model='dolly-v2-3b', hf_path='databricks/dolly-v2-3b', quantization='q3f16_0', max_seq_len=768, target=metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32, db_path=['log_db/redpajama-3b-q4f16', 'log_db/redpajama-3b-q4f32', 'log_db/dolly-v2-3b', 'log_db/vicuna-v1-7b'], reuse_lib=None, artifact_path='dist', use_cache=1, debug_dump=False, debug_load_script=False, llvm_mingw='', system_lib=False, export_kwargs={}, lib_format='so', system_lib_prefix=None, model_path='dist/models/dolly-v2-3b', target_kind='metal')
^CTraceback (most recent call last):
  File "/Users/testuser/Desktop/mlc-llm-data/mlc-llm/build.py", line 391, in <module>
    main()
  File "/Users/testuser/Desktop/mlc-llm-data/mlc-llm/build.py", line 364, in main
    mod, params = gpt_neox.get_model(ARGS, config)
  File "/Users/testuser/Desktop/mlc-llm-data/mlc-llm/mlc_llm/relax_model/gpt_neox.py", line 624, in get_model
    for name, param in transformers.get_model(
  File "/Users/testuser/Desktop/mlc-llm-data/mlc-llm/mlc_llm/transformers.py", line 54, in get_model
    result = pool.map(
  File "/Users/testuser/opt/anaconda3/envs/mlc-chat/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/testuser/opt/anaconda3/envs/mlc-chat/lib/python3.10/multiprocessing/pool.py", line 768, in get
    self.wait(timeout)
  File "/Users/testuser/opt/anaconda3/envs/mlc-chat/lib/python3.10/multiprocessing/pool.py", line 765, in wait
    self._event.wait(timeout)
  File "/Users/testuser/opt/anaconda3/envs/mlc-chat/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/testuser/opt/anaconda3/envs/mlc-chat/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt
```

It seems the bug is on the TVM side.
and here's another person encountering similar issue that LLVM target and host mismatch on M2 mac: 
https://discuss.tvm.apache.org/t/the-llvmtarget-detection-is-too-strict/14335

**Comment by junrushao** [comment]
To clarify, the issue has nothing to do with M2 or TVM. In fact I'm developing on an M2.

The separate process is loading model from disk, which takes some time, and will be particularly long if you have limited RAM, in this case model loading will use swap.

Please check two things:
- If you are using a conda distro built for ARM macbook by `conda info | grep platform`. Its output should be `osx-arm64` instead of `osx-64`
- If there is any file under `./dist/dolly-something/raw_params/`

**Comment by li2109** [comment]
Thanks for the reply.

I am actually using mac min with m2 pro chip.
```
conda info | grep platform
               platform : osx-64
```          

Yes, there are raw_params after i ran the command

```
python build.py --hf-path=databricks/dolly-v2-3b --target metal
Updated git hooks.
Git LFS initialized.
Cloning into 'dist/models/dolly-v2-3b'...
remote: Enumerating objects: 65, done.
remote: Total 65 (delta 0), reused 0 (delta 0), pack-reused 65
Unpacking objects: 100% (65/65), 604.13 KiB | 2.70 MiB/s, done.
Encountered 1 file(s) that may not have been copied correctly on Windows:
	pytorch_model.bin

See: `git lfs help smudge` for more details.
Downloaded weights to dist/models/dolly-v2-3b
Using path "dist/models/dolly-v2-3b" for model "dolly-v2-3b"
Database paths: ['log_db/redpajama-3b-q4f16', 'log_db/redpajama-3b-q4f32', 'log_db/dolly-v2-3b', 'log_db/vicuna-v1-7b']
[20:11:34] /Users/runner/work/package/package/tvm/src/runtime/metal/metal_device_api.mm:165: Intializing Metal device 0, name=Apple M2 Pro
Target configured: metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32
Target: Namespace(model='dolly-v2-3b', hf_path='databricks/dolly-v2-3b', quantization='q3f16_0', max_seq_len=-1, target=metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32, db_path=['log_db/redpajama-3b-q4f16', 'log_db/redpajama-3b-q4f32', 'log_db/dolly-v2-3b', 'log_db/vicuna-v1-7b'], reuse_lib=None, artifact_path='dist', use_cache=1, debug_dump=False, debug_load_script=False, llvm_mingw='', system_lib=False, export_kwargs={}, lib_format='so', system_lib_prefix=None, model_path='dist/models/dolly-v2-3b', target_kind='metal')
Extracting weights for model: dist/models/dolly-v2-3b
Model weights dumped to: dist/dolly-v2-3b-q3f16_0/raw_params
Loading model weights from: dist/dolly-v2-3b-q3f16_0/raw_params
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 388/388 [00:06<00:00, 60.64it/s]
Loading done
Automatically using target for weight quantization: metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32
device using: metal(0)
[20:16:14] /Users/runner/work/package/package/tvm/src/target/llvm/llvm_module.cc:415: Architecture mismatch: module=arm64-apple-macos host=x86_64-apple-darwin22.4.0
Traceback (most recent call last):
  File "/Users/testuser/Desktop/mlc-llm-data/mlc-llm/build.py", line 391, in <module>
    main()
  File "/Users/testuser/Desktop/mlc-llm-data/mlc-llm/build.py", line 369, in main
    mod = mod_transform_before_build(mod, params, ARGS)
  File "/Users/testuser/Desktop/mlc-llm-data/mlc-llm/build.py", line 255, in mod_transform_before_build
    new_params = utils.transform_params(mod_transform, model_params)
  File "/Users/testuser/Desktop/mlc-llm-data/mlc-llm/mlc_llm/utils.py", line 153, in transform_params
    vm = relax.vm.VirtualMachine(ex, device)
  File "/Users/testuser/opt/anaconda3/envs/mlc-chat/lib/python3.10/site-packages/tvm/runtime/relax_vm.py", line 96, in __init__
    self._setup_device(device, memory_cfg)
  File "/Users/testuser/opt/anaconda3/envs/mlc-chat/lib/python3.10/site-packages/tvm/runtime/relax_vm.py", line 137, in _setup_device
    self.module["vm_initialization"](*init_args)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 276, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  File "/Users/runner/work/package/package/tvm/src/target/llvm/llvm_module.cc", line 386
TVMError: Cannot run module, architecture mismatch
```

I tried with and without --target meta, neither worked.

i also tried deleting the everything inside dist folder and it still didn't work.

```
python build.py --hf-path=databricks/dolly-v2-3b
Updated git hooks.
Git LFS initialized.
Cloning into 'dist/models/dolly-v2-3b'...
remote: Enumerating objects: 65, done.
remote: Total 65 (delta 0), reused 0 (delta 0), pack-reused 65
Unpacking objects: 100% (65/65), 604.13 KiB | 2.78 MiB/s, done.
Encountered 1 file(s) that may not have been copied correctly on Windows:
	pytorch_model.bin

See: `git lfs help smudge` for more details.
Downloaded weights to dist/models/dolly-v2-3b
Using path "dist/models/dolly-v2-3b" for model "dolly-v2-3b"
Database paths: ['log_db/redpajama-3b-q4f16', 'log_db/redpajama-3b-q4f32', 'log_db/dolly-v2-3b', 'log_db/vicuna-v1-7b']
[20:26:25] /Users/runner/work/package/package/tvm/src/runtime/metal/metal_device_api.mm:165: Intializing Metal device 0, name=Apple M2 Pro
Target configured: metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32
Target: Namespace(model='dolly-v2-3b', hf_path='databricks/dolly-v2-3b', quantization='q3f16_0', max_seq_len=-1, target=metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32, db_path=['log_db/redpajama-3b-q4f16', 'log_db/redpajama-3b-q4f32', 'log_db/dolly-v2-3b', 'log_db/vicuna-v1-7b'], reuse_lib=None, artifact_path='dist', use_cache=1, debug_dump=False, debug_load_script=False, llvm_mingw='', system_lib=False, export_kwargs={}, lib_format='so', system_lib_prefix=None, model_path='dist/models/dolly-v2-3b', target_kind='metal')
Extracting weights for model: dist/models/dolly-v2-3b
Model weights dumped to: dist/dolly-v2-3b-q3f16_0/raw_params
Loading model weights from: dist/dolly-v2-3b-q3f16_0/raw_params
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 388/388 [00:07<00:00, 54.47it/s]
Loading done
Automatically using target for weight quantization: metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32
device using: metal(0)
[20:30:22] /Users/runner/work/package/package/tvm/src/target/llvm/llvm_module.cc:415: Architecture mismatch: module=arm64-apple-macos host=x86_64-apple-darwin22.4.0
Traceback (most recent call last):
  File "/Users/testuser/Desktop/mlc-llm-data/mlc-llm/build.py", line 391, in <module>
    main()
  File "/Users/testuser/Desktop/mlc-llm-data/mlc-llm/build.py", line 369, in main
    mod = mod_transform_before_build(mod, params, ARGS)
  File "/Users/testuser/Desktop/mlc-llm-data/mlc-llm/build.py", line 255, in mod_transform_before_build
    new_params = utils.transform_params(mod_transform, model_params)
  File "/Users/testuser/Desktop/mlc-llm-data/mlc-llm/mlc_llm/utils.py", line 153, in transform_params
    vm = relax.vm.VirtualMachine(ex, device)
  File "/Users/testuser/opt/anaconda3/envs/mlc-chat/lib/python3.10/site-packages/tvm/runtime/relax_vm.py", line 96, in __init__
    self._setup_device(device, memory_cfg)
  File "/Users/testuser/opt/anaconda3/envs/mlc-chat/lib/python3.10/site-packages/tvm/runtime/relax_vm.py", line 137, in _setup_device
    self.module["vm_initialization"](*init_args)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 276, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  File "/Users/runner/work/package/package/tvm/src/target/llvm/llvm_module.cc", line 386
TVMError: Cannot run module, architecture mismatch
```

some other info:
Python 3.10.11
mlc-chat-nightly   mlc-ai/osx-64::mlc-chat-nightly-0.1.dev80-80_g1bd6786_h1234567_0

**Comment by li2109** [comment]
conda info:

```
conda info

     active environment : mlc-chat
    active env location : /Users/testuser/opt/anaconda3/envs/mlc-chat
            shell level : 2
       user config file : /Users/testuser/.condarc
 populated config files : /Users/testuser/.condarc
          conda version : 23.1.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=10.16=0
                          __unix=0=0
       base environment : /Users/testuser/opt/anaconda3  (writable)
      conda av data dir : /Users/testuser/opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/testuser/opt/anaconda3/pkgs
                          /Users/testuser/.conda/pkgs
       envs directories : /Users/testuser/opt/anaconda3/envs
                          /Users/testuser/.conda/envs
               platform : osx-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.9.13 Darwin/22.4.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by li2109** [comment]
I realized that i probably having the intel version of anaconda. trying again.

**Comment by li2109** [comment]
Mark as fixed after reinstalling the conda(arm version). @junrushao Thank you for the hint.
