### ISSUE TITLE
[Bug] AttributeError: 'Namespace' object has no attribute 'mlc_source_dir'

### ISSUE THREAD

**Issue by changye-chen** [mlc-ai/mlc-llm#2393]
## 🐛 Bug
After execute ```mlc_llm package```, I passed compile but failed at "Building mlc4j"

## To Reproduce

1. I used the following env:
![image](https://github.com/mlc-ai/mlc-llm/assets/67987954/0913463f-0fff-4278-88d4-05b73465146e)
2. I convert Phi3-mini-4k to q4f16_1 weight in /home/chen/mlc/DIST/Phi3
3. I rewrite the /home/chen/mlc/mlc-llm/android/MLCChat/mlc-package-config.json with 
![image](https://github.com/mlc-ai/mlc-llm/assets/67987954/4aa705e8-0a53-48f2-a600-3eee81e73722)
4. I ```cd /home/chen/mlc/mlc-llm/android/MLCChat/``` and run ```mlc_llm package```

5. I get following outputs:
```
 mlc_llm package                                                                               ─╯
[2024-05-24 01:16:35] INFO package.py:330: MLC LLM HOME: "/home/chen/mlc/mlc-llm"
[2024-05-24 01:16:35] INFO package.py:30: Clean up all directories under "dist/bundle"
[2024-05-24 01:16:35] INFO jit.py:43: MLC_JIT_POLICY = ON. Can be one of: ON, OFF, REDO, READONLY
[2024-05-24 01:16:35] INFO chat_module.py:379: Using model folder: /home/chen/mlc/DIST/Phi3
[2024-05-24 01:16:35] INFO chat_module.py:380: Using mlc chat config: /home/chen/mlc/DIST/Phi3/mlc-chat-config.json
[2024-05-24 01:16:35] INFO package.py:86: Model lib is not specified for model "Phi3-mini-4k". Now jit compile the model library.
[2024-05-24 01:16:35] INFO jit.py:160: Using cached model lib: /home/chen/.cache/mlc_llm/model_lib/975f62b4b6aa7816ecf731d04ed5d01b.tar
[2024-05-24 01:16:35] INFO package.py:134: Bundle weight for Phi3-mini-4k, copy into dist/bundle/Phi3-mini-4k
[2024-05-24 01:16:36] INFO package.py:159: Dump the app config below to "dist/bundle/mlc-app-config.json":
{
  "model_list": [
    {
      "model_id": "Phi3-mini-4k",
      "model_lib": "phi3_q4f16_1_b705f2b6ceb04f6357a2410b43ed6146",
      "model_url": "/home/chen/mlc/DIST/Phi3",
      "estimated_vram_bytes": 2152140180
    }
  ]
}
[2024-05-24 01:16:36] INFO package.py:216: Creating lib from ['/home/chen/.cache/mlc_llm/model_lib/975f62b4b6aa7816ecf731d04ed5d01b.tar']
[2024-05-24 01:16:36] INFO package.py:217: Validating the library dist/lib/libmodel_android.a
[2024-05-24 01:16:36] INFO package.py:218: List of available model libs packaged: ['phi3_q4f16_1_b705f2b6ceb04f6357a2410b43ed6146'], if we have '-' in the model_lib string, it will be turned into '_'
[2024-05-24 01:16:36] INFO package.py:261: Validation pass
[2024-05-24 01:16:36] INFO package.py:275: Moving "dist/lib/libmodel_android.a" to "build/lib/libmodel_android.a"
[2024-05-24 01:16:36] INFO package.py:279: Building mlc4j
Traceback (most recent call last):
  File "/home/chen/mlc/mlc-llm/android/mlc4j/prepare_libs.py", line 105, in <module>
    if parsed.mlc_source_dir is None:
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'mlc_source_dir'
Traceback (most recent call last):
  File "/home/chen/miniconda3/envs/mlcllm/bin/mlc_llm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/chen/miniconda3/envs/mlcllm/lib/python3.12/site-packages/mlc_llm/__main__.py", line 49, in main
    cli.main(sys.argv[2:])
  File "/home/chen/miniconda3/envs/mlcllm/lib/python3.12/site-packages/mlc_llm/cli/package.py", line 63, in main
    package(
  File "/home/chen/miniconda3/envs/mlcllm/lib/python3.12/site-packages/mlc_llm/interface/package.py", line 364, in package
    build_android_binding(mlc_llm_home, output)
  File "/home/chen/miniconda3/envs/mlcllm/lib/python3.12/site-packages/mlc_llm/interface/package.py", line 280, in build_android_binding
    subprocess.run([sys.executable, mlc4j_path / "prepare_libs.py"], check=True, env=os.environ)
  File "/home/chen/miniconda3/envs/mlcllm/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/chen/miniconda3/envs/mlcllm/bin/python', PosixPath('/home/chen/mlc/mlc-llm/android/mlc4j/prepare_libs.py')]' returned non-zero exit status 1.
```
## Expected behavior
expect package the model as document showed

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu(WSL)
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source): pip
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.12
 - GPU driver version (if applicable): 12.1
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by tqchen** [comment]
Thanks for reporting, this should be fixed by https://github.com/mlc-ai/mlc-llm/pull/2394
