### ISSUE TITLE
qwen1.5-0.5B-chat :   lm_head.weight

### ISSUE THREAD

**Issue by viaowp** [mlc-ai/mlc-llm#2458]
## ❓ General Questions

When converting the fine-tuned qwen1.5-0.5B-chat model through MLC-llm, the following error occurs. The same error does not occur when converting the fine-tuned qwen1.5-1.8B-chat model.

[2024-05-29 15:47:50] INFO qwen2_model.py:65: prefill_chunk_size defaults to context_window_size (32768)
Start storing to cache /home/111/models/Qwen1.5-0.5B-Chat-111-q0f16-MLC
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
Traceback (most recent call last):
  File "/home/111/miniconda3/envs/mlc-llm/bin/mlc_llm", line 8, in <module>
    sys.exit(main())
  File "/home/111/miniconda3/envs/mlc-llm/lib/python3.10/site-packages/mlc_llm/__main__.py", line 29, in main
    cli.main(sys.argv[2:])
  File "/home/111/miniconda3/envs/mlc-llm/lib/python3.10/site-packages/mlc_llm/cli/convert_weight.py", line 87, in main
    convert_weight(
  File "/home/111/miniconda3/envs/mlc-llm/lib/python3.10/site-packages/mlc_llm/interface/convert_weight.py", line 181, in convert_weight
    _convert_args(args)
  File "/home/111/miniconda3/envs/mlc-llm/lib/python3.10/site-packages/mlc_llm/interface/convert_weight.py", line 145, in _convert_args
    tvmjs.dump_ndarray_cache(
  File "/home/111/miniconda3/envs/mlc-llm/lib/python3.10/site-packages/tvm/contrib/tvmjs.py", line 215, in dump_ndarray_cache
    for k, origin_v in param_generator:
  File "/home/111/miniconda3/envs/mlc-llm/lib/python3.10/site-packages/mlc_llm/interface/convert_weight.py", line 122, in _param_generator
    loader = LOADER[args.source_format](
  File "/home/111/miniconda3/envs/mlc-llm/lib/python3.10/site-packages/mlc_llm/loader/huggingface_loader.py", line 98, in __init__
    check_parameter_usage(extern_param_map, set(self.torch_to_path.keys()))
  File "/home/111/miniconda3/envs/mlc-llm/lib/python3.10/site-packages/mlc_llm/loader/utils.py", line 32, in check_parameter_usage
    raise ValueError(
ValueError: The following extern parameters do not exist in the weight files:
  lm_head.weight

**Comment by canluhuang** [comment]
I'm having the same issue

`[2024-05-29 17:50:56] INFO qwen2_model.py:48: context_window_size not found in config.json. Falling back to max_position_embeddings (32768)
[2024-05-29 17:50:56] INFO qwen2_model.py:65: prefill_chunk_size defaults to 2048
Start storing to cache dist/qwen_20240523_051550--q4f16_1-MLC
Traceback (most recent call last):
  File "/opt/miniconda3/envs/py3_8/bin/mlc_llm", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/py3_8/lib/python3.8/site-packages/mlc_llm/__main__.py", line 29, in main
    cli.main(sys.argv[2:])
  File "/opt/miniconda3/envs/py3_8/lib/python3.8/site-packages/mlc_llm/cli/convert_weight.py", line 87, in main
    convert_weight(
  File "/opt/miniconda3/envs/py3_8/lib/python3.8/site-packages/mlc_llm/interface/convert_weight.py", line 181, in convert_weight
    _convert_args(args)
  File "/opt/miniconda3/envs/py3_8/lib/python3.8/site-packages/mlc_llm/interface/convert_weight.py", line 145, in _convert_args
    tvmjs.dump_ndarray_cache(
  File "/opt/miniconda3/envs/py3_8/lib/python3.8/site-packages/tvm/contrib/tvmjs.py", line 215, in dump_ndarray_cache
    for k, origin_v in param_generator:
  File "/opt/miniconda3/envs/py3_8/lib/python3.8/site-packages/mlc_llm/interface/convert_weight.py", line 122, in _param_generator
    loader = LOADER[args.source_format](
  File "/opt/miniconda3/envs/py3_8/lib/python3.8/site-packages/mlc_llm/loader/huggingface_loader.py", line 98, in __init__
    check_parameter_usage(extern_param_map, set(self.torch_to_path.keys()))
  File "/opt/miniconda3/envs/py3_8/lib/python3.8/site-packages/mlc_llm/loader/utils.py", line 32, in check_parameter_usage
    raise ValueError(
ValueError: The following extern parameters do not exist in the weight files:
  lm_head.weight
`

**Comment by tqchen** [comment]
seems the error was due to the missing of lm_head.weight, do you mind check yuor weight set and see if there were a different name? cc @tlopex do you mind cross check out `qwen1.5-0.5B-chat ` support?

**Comment by tlopex** [comment]
Got it. I'll check soon.

**Comment by tlopex** [comment]
Hi @viaowp @canluhuang, thanks for your issue!
From your traceback I thought you built mlc-llm from source, right?
I downloaded the latest version model [Qwen1.5-0.5B-Chat](https://huggingface.co/Qwen/Qwen1.5-0.5B-Chat) and converted it with q0f16:
```
tlopex@tlopex-OMEN-by-HP-Laptop-17-ck1xxx:~/mlc-llm$ python -m mlc_llm convert_weight ./dist/models/Qwen1.5-0.5B-Chat/ --quantization q0f16 -o dist/Qwen1.5-0.5B-Chat-q0f16-MLC
[2024-05-29 23:35:17] INFO auto_config.py:115: Found model configuration: dist/models/Qwen1.5-0.5B-Chat/config.json
[2024-05-29 23:35:20] INFO auto_device.py:79: Found device: cuda:0
[2024-05-29 23:35:21] INFO auto_device.py:88: Not found device: rocm:0
[2024-05-29 23:35:22] INFO auto_device.py:88: Not found device: metal:0
[2024-05-29 23:35:22] INFO auto_device.py:88: Not found device: vulkan:0
[2024-05-29 23:35:23] INFO auto_device.py:88: Not found device: opencl:0
[2024-05-29 23:35:23] INFO auto_device.py:35: Using device: cuda:0
[2024-05-29 23:35:23] INFO auto_weight.py:70: Finding weights in: dist/models/Qwen1.5-0.5B-Chat
[2024-05-29 23:35:23] INFO auto_weight.py:136: Not found Huggingface PyTorch
[2024-05-29 23:35:23] INFO auto_weight.py:143: Found source weight format: huggingface-safetensor. Source configuration: dist/models/Qwen1.5-0.5B-Chat/model.safetensors.index.json
[2024-05-29 23:35:23] INFO auto_weight.py:106: Using source weight configuration: dist/models/Qwen1.5-0.5B-Chat/model.safetensors.index.json. Use `--source` to override.
[2024-05-29 23:35:23] INFO auto_weight.py:110: Using source weight format: huggingface-safetensor. Use `--source-format` to override.
[2024-05-29 23:35:23] INFO auto_config.py:153: Found model type: qwen2. Use `--model-type` to override.
Weight conversion with arguments:
  --config          dist/models/Qwen1.5-0.5B-Chat/config.json
  --quantization    NoQuantize(name='q0f16', kind='no-quant', model_dtype='float16')
  --model-type      qwen2
  --device          cuda:0
  --source          dist/models/Qwen1.5-0.5B-Chat/model.safetensors.index.json
  --source-format   huggingface-safetensor
  --output          dist/Qwen1.5-0.5B-Chat-q0f16-MLC
[2024-05-29 23:35:23] INFO qwen2_model.py:48: context_window_size not found in config.json. Falling back to max_position_embeddings (32768)
[2024-05-29 23:35:23] INFO qwen2_model.py:65: prefill_chunk_size defaults to 2048
Start storing to cache dist/Qwen1.5-0.5B-Chat-q0f16-MLC
[2024-05-29 23:35:25] INFO huggingface_loader.py:184: Loading HF parameters from: dist/models/Qwen1.5-0.5B-Chat/model.safetensors
[2024-05-29 23:35:27] INFO huggingface_loader.py:174: [Not quantized] Parameter: "lm_head.weight", shape: (151936, 1024), dtype: float16
[2024-05-29 23:35:30] INFO huggingface_loader.py:174: [Not quantized] Parameter: "model.embed_tokens.weight", shape: (151936, 1024), dtype: float16
[2024-05-29 23:35:32] INFO huggingface_loader.py:174: [Not quantized] Parameter: "model.layers.0.input_layernorm.weight", shape: (1024,), dtype: float16
[2024-05-29 23:35:32] INFO huggingface_loader.py:174: [Not quantized] Parameter: "model.layers.0.mlp.down_proj.weight", shape: (1024, 2816), dtype: float16
[2024-05-29 23:35:32] INFO huggingface_loader.py:174: [Not quantized] Parameter: "model.layers.0.mlp.gate_up_proj.weight", shape: (5632, 1024), dtype: float16
[2024-05-29 23:35:32] INFO huggingface_loader.py:174: [Not quantized] Parameter: "model.layers.0.post_attention_layernorm.weight", shape: (1024,), dtype: float16
```
Above is just part of it which shows that weight can be converted successfully and the parameter `lm_head.weight` do exist. So I think you'd better to download the model from huggingface and try it again.

Besides, we indeed do not upload `Qwen1.5-0.5B-chat` model to our mlc-ai huggingface repository. Therefore I uploaded the model with four distinct quantized version. So I think that's another way if you want to try this model.

**Comment by canluhuang** [comment]
> Hi @viaowp @canluhuang, thanks for your issue! From your traceback I thought you built mlc-llm from source, right? I downloaded the latest version model [Qwen1.5-0.5B-Chat](https://huggingface.co/Qwen/Qwen1.5-0.5B-Chat) and converted it with q0f16:
> 
> ```
> tlopex@tlopex-OMEN-by-HP-Laptop-17-ck1xxx:~/mlc-llm$ python -m mlc_llm convert_weight ./dist/models/Qwen1.5-0.5B-Chat/ --quantization q0f16 -o dist/Qwen1.5-0.5B-Chat-q0f16-MLC
> [2024-05-29 23:35:17] INFO auto_config.py:115: Found model configuration: dist/models/Qwen1.5-0.5B-Chat/config.json
> [2024-05-29 23:35:20] INFO auto_device.py:79: Found device: cuda:0
> [2024-05-29 23:35:21] INFO auto_device.py:88: Not found device: rocm:0
> [2024-05-29 23:35:22] INFO auto_device.py:88: Not found device: metal:0
> [2024-05-29 23:35:22] INFO auto_device.py:88: Not found device: vulkan:0
> [2024-05-29 23:35:23] INFO auto_device.py:88: Not found device: opencl:0
> [2024-05-29 23:35:23] INFO auto_device.py:35: Using device: cuda:0
> [2024-05-29 23:35:23] INFO auto_weight.py:70: Finding weights in: dist/models/Qwen1.5-0.5B-Chat
> [2024-05-29 23:35:23] INFO auto_weight.py:136: Not found Huggingface PyTorch
> [2024-05-29 23:35:23] INFO auto_weight.py:143: Found source weight format: huggingface-safetensor. Source configuration: dist/models/Qwen1.5-0.5B-Chat/model.safetensors.index.json
> [2024-05-29 23:35:23] INFO auto_weight.py:106: Using source weight configuration: dist/models/Qwen1.5-0.5B-Chat/model.safetensors.index.json. Use `--source` to override.
> [2024-05-29 23:35:23] INFO auto_weight.py:110: Using source weight format: huggingface-safetensor. Use `--source-format` to override.
> [2024-05-29 23:35:23] INFO auto_config.py:153: Found model type: qwen2. Use `--model-type` to override.
> Weight conversion with arguments:
>   --config          dist/models/Qwen1.5-0.5B-Chat/config.json
>   --quantization    NoQuantize(name='q0f16', kind='no-quant', model_dtype='float16')
>   --model-type      qwen2
>   --device          cuda:0
>   --source          dist/models/Qwen1.5-0.5B-Chat/model.safetensors.index.json
>   --source-format   huggingface-safetensor
>   --output          dist/Qwen1.5-0.5B-Chat-q0f16-MLC
> [2024-05-29 23:35:23] INFO qwen2_model.py:48: context_window_size not found in config.json. Falling back to max_position_embeddings (32768)
> [2024-05-29 23:35:23] INFO qwen2_model.py:65: prefill_chunk_size defaults to 2048
> Start storing to cache dist/Qwen1.5-0.5B-Chat-q0f16-MLC
> [2024-05-29 23:35:25] INFO huggingface_loader.py:184: Loading HF parameters from: dist/models/Qwen1.5-0.5B-Chat/model.safetensors
> [2024-05-29 23:35:27] INFO huggingface_loader.py:174: [Not quantized] Parameter: "lm_head.weight", shape: (151936, 1024), dtype: float16
> [2024-05-29 23:35:30] INFO huggingface_loader.py:174: [Not quantized] Parameter: "model.embed_tokens.weight", shape: (151936, 1024), dtype: float16
> [2024-05-29 23:35:32] INFO huggingface_loader.py:174: [Not quantized] Parameter: "model.layers.0.input_layernorm.weight", shape: (1024,), dtype: float16
> [2024-05-29 23:35:32] INFO huggingface_loader.py:174: [Not quantized] Parameter: "model.layers.0.mlp.down_proj.weight", shape: (1024, 2816), dtype: float16
> [2024-05-29 23:35:32] INFO huggingface_loader.py:174: [Not quantized] Parameter: "model.layers.0.mlp.gate_up_proj.weight", shape: (5632, 1024), dtype: float16
> [2024-05-29 23:35:32] INFO huggingface_loader.py:174: [Not quantized] Parameter: "model.layers.0.post_attention_layernorm.weight", shape: (1024,), dtype: float16
> ```
> 
> Above is just part of it which shows that weight can be converted successfully and the parameter `lm_head.weight` do exist, which I think is not a naming error issue. So I think you'd better to download the model from huggingface and try it again.
> 
> Besides, we indeed do not upload `Qwen1.5-0.5B-chat` model to our mlc-ai huggingface repository. Therefore, I have uploaded the model with four distinct quantized version just now. And I think that's another way if you want to try this model.

Hi @tlopex, thank reply. The model I downloaded directly from huggingface is fine. But when I finetune [Qwen1.5-0.5B-Chat](https://huggingface.co/Qwen/Qwen1.5-0.5B-Chat) and then convert it, the above error will be occurred. There will be no error when finetuning on [Qwen1.5-1.8B-Chat](https://huggingface.co/Qwen/Qwen1.5-1.8B-Chat). if you have other ideas？

**Comment by tqchen** [comment]
likely when you fine-tune, you need to know where is your lm_head, it may be under different name, or if your fine-tune did not save the weights that were originally in the model, and you need to recombine it

**Comment by canluhuang** [comment]
> likely when you fine-tune, you need to know where is your lm_head, it may be under different name, or if your fine-tune did not save the weights that were originally in the model(and it did not fine-tune), and you need to recombine it

Thanks for your advice. This problem also occurs in qwen2 and I upgraded to the latest version of mlc to fix it.

**Comment by MrRace** [comment]
@tqchen  @tlopex  When performing model weight conversion on the Qwen2 model, this error also occurs.
```
mlc-ai-nightly-cu122                     0.15.dev404
mlc-llm-nightly-cu122                    0.1.dev1362
```

**Comment by JLake310** [comment]
I've got the same error, and I resolved it by saving the model as a .bin file instead of using safetensors.
I'm not sure this would be the solution, but it worked for some reason.

```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen2-1.5B-Instruct",
    torch_dtype=torch.float16
)

tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2-1.5B-Instruct")
model.save_pretrained("Qwen2-1.5B-Instruct", safe_serialization=False)
tokenizer.save_pretrained('Qwen2-1.5B-Instruct')
```
