### ISSUE TITLE
Cannot find RedPajama-INCITE-Chat-3B-v1-q4f16_0-iphone.tar

### ISSUE THREAD

**Issue by VnykBabyshki** [mlc-ai/mlc-llm#246]
This happens after running `./prepare_libs.sh`. I'm using RedPajama as my model, I'm using vicuna, that I have in the dist directory (vicuna-v1-7b-q3f16_0)
```
Install the project...
-- Install configuration: "Release"
-- Installing: /Users/vnykbabyshki/Downloads/mlc-llm/ios/build/lib/libmlc_llm.a
-- Installing: /Users/vnykbabyshki/Downloads/mlc-llm/ios/build/lib/libtokenizers_cpp.a
-- Installing: /Users/vnykbabyshki/Downloads/mlc-llm/ios/build/lib/libsentencepiece.a
-- Installing: /Users/vnykbabyshki/Downloads/mlc-llm/ios/build/lib/libtvm_runtime.a
-- Up-to-date: /Users/vnykbabyshki/Downloads/mlc-llm/ios/build/lib/libtokenizers_c.a
+ cd ..
+ rm -rf build/tvm_home
+ ln -s /Users/vnykbabyshki/envnew/lib/python3.10/site-packages/tvm build/tvm_home
+ python prepare_model_lib.py
Traceback (most recent call last):
  File "/Users/vnykbabyshki/Downloads/mlc-llm/ios/prepare_model_lib.py", line 23, in <module>
    main()
  File "/Users/vnykbabyshki/Downloads/mlc-llm/ios/prepare_model_lib.py", line 15, in main
    raise RuntimeError(f"Cannot find {path}")
RuntimeError: Cannot find /Users/vnykbabyshki/Downloads/mlc-llm/dist/RedPajama-INCITE-Chat-3B-v1-q4f16_0/RedPajama-INCITE-Chat-3B-v1-q4f16_0-iphone.tar
```

**Comment by tqchen** [comment]
You need to edit the MLCChat/app-config.json model_libs section to include libs you intend to build

**Comment by VnykBabyshki** [comment]
Thanks. Inside the MLCChat/app-config.json I've removed `RedPajama-INCITE-Chat-3B-v1-q4f16_0` from `model_libs` array and now there is only a `vicuna-v1-7b-q3f16_0`. It works.
