### ISSUE TITLE
执行mlc_chat指令时总是报错

### ISSUE THREAD

**Issue by lmee** [mlc-ai/mlc-llm#2471]
帮忙解答下，感谢
Traceback (most recent call last):
  File "/opt/miniconda3/envs/torch-gpu/bin/mlc_chat", line 33, in <module>
    sys.exit(load_entry_point('mlc-chat', 'console_scripts', 'mlc_chat')())
  File "/opt/miniconda3/envs/torch-gpu/bin/mlc_chat", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/miniconda3/envs/torch-gpu/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/opt/miniconda3/envs/torch-gpu/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/lijieer/projects/github/mlc-MiniCPM/python/mlc_chat/__init__.py", line 5, in <module>
    from .chat_module import ChatConfig, ChatModule, ConvConfig, GenerationConfig
  File "/Users/lijieer/projects/github/mlc-MiniCPM/python/mlc_chat/chat_module.py", line 20, in <module>
    from . import base as _
  File "/Users/lijieer/projects/github/mlc-MiniCPM/python/mlc_chat/base.py", line 28, in <module>
    _LIB, _LIB_PATH = _load_mlc_llm_lib()
  File "/Users/lijieer/projects/github/mlc-MiniCPM/python/mlc_chat/base.py", line 23, in _load_mlc_llm_lib
    return ctypes.CDLL(lib_path[0]), lib_path[0]
  File "/opt/miniconda3/envs/torch-gpu/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/lijieer/projects/github/mlc-MiniCPM/build/libmlc_llm_module.dylib, 0x0006): Symbol not found: __ZN3tvm7runtime7NDArray10CreateViewENS0_10ShapeTupleE10DLDataType
  Referenced from: <AAC658F1-71A4-37A1-B3B5-7467487A3792> /Users/lijieer/projects/github/mlc-MiniCPM/build/libmlc_llm_module.dylib
  Expected in:     <F4C8FCF7-EC05-347C-A094-DB27FFC7A03A> /opt/miniconda3/envs/torch-gpu/lib/python3.9/site-packages/tvm/libtvm.dylib

**Comment by Hzfengsy** [comment]
Please update to the latest TVM and MLC commit and rebuild everything. This issue happens when you are using mismatched TVM and MLC versions.

**Comment by Hzfengsy** [comment]
BTW, we have already renamed `mlc_chat` into `mlc_llm`. It looks like you are using a really old version of MLC-LLM, please try upgrading. Also, please send issue to the related project If you are using any downstream project (e.g. mlc-MiniCPM)

**Comment by lmee** [comment]
ok , thanks a lot
