### ISSUE TITLE
exe "mlc_llm package" error

### ISSUE THREAD

**Issue by lmee** [mlc-ai/mlc-llm#2491]
I have recomplied some times ,but always report the follow erros,pls help to support

rustc 1.77.2 (25ef9e3d8 2024-04-09) -->rust environment

    --> /Users/lijieer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.203/src/private/ser.rs:1335:9
     |
1335 |         Ok(())
     |         ^^ not found in this scope

error: could not compile `serde` (lib) due to 6742 previous errors
make[3]: *** [mlc_llm/tokenizers/aarch64-linux-android/release/libtokenizers_c.a] Error 101
make[2]: *** [mlc_llm/tokenizers/CMakeFiles/tokenizers_c.dir/all] Error 2
make[1]: *** [CMakeFiles/tvm4j_runtime_packed.dir/rule] Error 2
make: *** [tvm4j_runtime_packed] Error 2
Traceback (most recent call last):
  File "/Users/lijieer/projects/github/mlc-llm/android/mlc4j/prepare_libs.py", line 117, in <module>
    main(parsed.mlc_llm_source_dir)
  File "/Users/lijieer/projects/github/mlc-llm/android/mlc4j/prepare_libs.py", line 100, in main
    run_cmake_build()
  File "/Users/lijieer/projects/github/mlc-llm/android/mlc4j/prepare_libs.py", line 65, in run_cmake_build
    subprocess.run(cmd, check=True, env=os.environ)
  File "/opt/miniconda3/envs/mlc-chat-venv/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'tvm4j_runtime_packed', '--config', 'release', '-j8']' returned non-zero exit status 2.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/miniconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/mlc_llm/__main__.py", line 64, in <module>
    main()
  File "/opt/miniconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/mlc_llm/__main__.py", line 53, in main
    cli.main(sys.argv[2:])
  File "/opt/miniconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/mlc_llm/cli/package.py", line 64, in main
    package(
  File "/opt/miniconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/mlc_llm/interface/package.py", line 361, in package
    build_android_binding(mlc_llm_source_dir, output)
  File "/opt/miniconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/mlc_llm/interface/package.py", line 275, in build_android_binding
    subprocess.run([sys.executable, mlc4j_path / "prepare_libs.py"], check=True, env=os.environ)
  File "/opt/miniconda3/envs/mlc-chat-venv/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/miniconda3/envs/mlc-chat-venv/bin/python', PosixPath('/Users/lijieer/projects/github/mlc-llm/android/mlc4j/prepare_libs.py')]' returned non-zero exit status 1.

**Comment by tqchen** [comment]
this seems to be a rust issue, not sure if it is due to rust versions, unfortunatelt i cannot reproduce locally

**Comment by ponytaill** [comment]
I got the same errors. Weird.

**Comment by ponytaill** [comment]
Hi, I figured it out. You need to downgrade the version of rustc to 1.75.0.
Use `rustup install 1.75` and then `rustup default 1.75-x86_64-unknown-linux-gnu`

**Comment by lmee** [comment]
> @lmee Hi, I figured it out. You need to downgrade the version of rustc to 1.75.0. Use `rustup install 1.75` and then `rustup default 1.75-x86_64-unknown-linux-gnu`

it works ,thanks a lot :)
