### ISSUE TITLE
run mlc_llm package  ValueError: Git clone failed with return code 128: None. The command was

### ISSUE THREAD

**Issue by panghongtao** [mlc-ai/mlc-llm#2501]
I have mlc_llm and tvm installed.What do I need to do after installing these two plug-ins? I want to run it on Android. I execute the **mlc_llm package** in the mlc-llm-main\android\MLCChat directory. This error occurred.Do I need to execute this command? Or generate the apk file directly?

[2024-06-04 17:14:32] INFO package.py:327: MLC LLM HOME: "E:\project\mlc-llm-main"
[2024-06-04 17:14:32] INFO package.py:28: Clean up all directories under "dist\bundle"
[2024-06-04 17:14:32] INFO jit.py:43: MLC_JIT_POLICY = ON. Can be one of: ON, OFF, REDO, READONLY
[2024-06-04 17:14:32] INFO download_cache.py:227: Downloading model from HuggingFace: HF://mlc-ai/CodeQwen1.5-7B
[2024-06-04 17:14:32] INFO download_cache.py:29: MLC_DOWNLOAD_CACHE_POLICY = ON. Can be one of: ON, OFF, REDO, READONLY
[2024-06-04 17:14:32] INFO download_cache.py:56: [Git] Cloning https://huggingface.co/mlc-ai/CodeQwen1.5-7B.git to D:\Users\W9057210.ADC\AppData\Local\Temp\tmpge2z_c3l\tmp
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\mlc_llm\support\download_cache.py", line 57, in git_clone
    subprocess.run(
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'clone', 'https://huggingface.co/mlc-ai/CodeQwen1.5-7B.git', '.tmp']' returned non-zero exit status 128.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\anaconda3\Scripts\mlc_llm.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\anaconda3\Lib\site-packages\mlc_llm\__main__.py", line 53, in main
    cli.main(sys.argv[2:])
  File "C:\ProgramData\anaconda3\Lib\site-packages\mlc_llm\cli\package.py", line 64, in main
    package(
  File "C:\ProgramData\anaconda3\Lib\site-packages\mlc_llm\interface\package.py", line 351, in package
    model_lib_path_for_prepare_libs = build_model_library(
                                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\mlc_llm\interface\package.py", line 73, in build_model_library
    model_path = download_cache.get_or_download_model(model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\mlc_llm\support\download_cache.py", line 228, in get_or_download_model
    model_path = download_and_cache_mlc_weights(model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\mlc_llm\support\download_cache.py", line 180, in download_and_cache_mlc_weights
    git_clone(git_url, tmp_dir, ignore_lfs=True)
  File "C:\ProgramData\anaconda3\Lib\site-packages\mlc_llm\support\download_cache.py", line 70, in git_clone
    raise ValueError(
ValueError: Git clone failed with return code 128: None. The command was: ['git', 'clone', 'https://huggingface.co/mlc-ai/CodeQwen1.5-7B.git', '.tmp']

**Comment by MasterJH5574** [comment]
Thank you @panghongtao for the question. From the log you share, it looks like you are using model "https://huggingface.co/mlc-ai/CodeQwen1.5-7B.git" in your `mlc-package-config.json`, while as of now we don't have the CodeQwen model in https://huggingface.co/mlc-ai.

You can try to use other models whose converted weights are available in https://huggingface.co/mlc-ai. Or if you want to use the CodeQwen model now, you can follow this “Build Your Own Model” section to convert weight and upload to HuggingFace https://llm.mlc.ai/docs/deploy/ios.html#bring-your-own-model (p.s. this page is for iOS but the “Build Your Own Model” section works well for Android).

**Comment by panghongtao** [comment]
> Thank you @panghongtao for the question. From the log you share, it looks like you are using model "https://huggingface.co/mlc-ai/CodeQwen1.5-7B.git" in your `mlc-package-config.json`, while as of now we don't have the CodeQwen model in https://huggingface.co/mlc-ai.
> 
> You can try to use other models whose converted weights are available in https://huggingface.co/mlc-ai. Or if you want to use the CodeQwen model now, you can follow this “Build Your Own Model” section to convert weight and upload to HuggingFace https://llm.mlc.ai/docs/deploy/ios.html#bring-your-own-model (p.s. this page is for iOS but the “Build Your Own Model” section works well for Android).

Thank you for your reply. I've found this issue. I don't have this bug anymore

**Comment by MasterJH5574** [comment]
Thanks for confirming!

**Comment by djimdba** [comment]
Hi @MasterJH5574 i have the same problème, can you explain more how you fixed it please ?
Thank in advance.

**Comment by panghongtao** [comment]
> Hi @MasterJH5574 i have the same problème, can you explain more how you fixed it please ? Thank in advance.

I think this model must be available in https://hf-mirror.com/mlc-ai before it can be used. Or you can edit a new model and upload it to mlc-ai. I saw in the introduction of IOS how to upload the model

**Comment by MasterJH5574** [comment]
@djimdba Yes what @panghongtao mentions is right. You can use the models already in https://huggingface.co/mlc-ai, or follow https://llm.mlc.ai/docs/compilation/convert_weights.html this page and upload to your own HuggingFace if the model you run not yet delivered in https://huggingface.co/mlc-ai.

**Comment by gejian-iscas** [comment]
Is it possible that the network environment in China prevents me from downloading the model in Huggingface and reports an error code 128? How can I solve this error?
