### ISSUE TITLE
mlc_llm package is ERROR: returned non-zero exit status[Bug] 

### ISSUE THREAD

**Issue by panghongtao** [mlc-ai/mlc-llm#2511]
## 🐛 Bug

I am running on the Android platform Qwen-7b-chat-q4f161-mlc This model

## To Reproduce

1. add rust1.78
2. conda activate myName
3. python -m pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly mlc-ai-nightly
4. git clone https://github.com/mlc-ai/mlc-llm.git
    cd mlc-llm
    git submodule update --init --recursive
    cd android
5. add NDK 
    ANDROID_NDK: %HOME%/AppData/Local/Android/Sdk/ndk/25.2.9519653
    TVM_NDK_CC: %ANDROID_NDK%/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android24
6. mlc_package 

MyErrorLog:
[2024-06-05 18:01:16] INFO package.py:327: MLC LLM HOME: "E:\project\mlc-llm-main"
[2024-06-05 18:01:16] INFO package.py:28: Clean up all directories under "dist\bundle"
[2024-06-05 18:01:16] INFO jit.py:43: MLC_JIT_POLICY = ON. Can be one of: ON, OFF, REDO, READONLY
[2024-06-05 18:01:16] INFO download_cache.py:227: Downloading model from HuggingFace: HF://mlc-ai/Qwen-7B-Chat-q4f16_1-MLC
[2024-06-05 18:01:16] INFO download_cache.py:29: MLC_DOWNLOAD_CACHE_POLICY = ON. Can be one of: ON, OFF, REDO, READONLY
[2024-06-05 18:01:16] INFO download_cache.py:166: Weights already downloaded: D:\Users\W9057210.ADC\AppData\Local\mlc_llm\model_weights\hf\mlc-ai\Qwen-7B-Chat-q4f16_1-MLC
[2024-06-05 18:01:16] INFO package.py:81: Model lib is not specified for model "Qwen-7B-Chat-q4f16_1-MLC". Now jit compile the model library.
[2024-06-05 18:01:16] INFO jit.py:160: Using cached model lib: D:\Users\W9057210.ADC\AppData\Local\mlc_llm\model_lib\e28f0896e747de1e51f09c8055e9061c.tar
[2024-06-05 18:01:16] INFO package.py:154: Dump the app config below to "dist\bundle\mlc-app-config.json":
{
  "model_list": [
    {
      "model_id": "Qwen-7B-Chat-q4f16_1-MLC",
      "model_lib": "qwen_q4f16_1_eab54620bed8dc427ee39dcd5a262599",
      "model_url": "https://huggingface.co/mlc-ai/Qwen-7B-Chat-q4f16_1-MLC",
      "estimated_vram_bytes": 3000000000
    }
  ]
}
[2024-06-05 18:01:16] INFO package.py:211: Creating lib from ['D:\\Users\\W9057210.ADC\\AppData\\Local\\mlc_llm\\model_lib\\e28f0896e747de1e51f09c8055e9061c.tar']
[2024-06-05 18:01:16] INFO package.py:212: Validating the library dist\lib\libmodel_android.a
[2024-06-05 18:01:16] INFO package.py:213: List of available model libs packaged: ['qwen_q4f16_1_eab54620bed8dc427ee39dcd5a262599'], if we have '-' in the model_lib string, it will be turned into '_'
[2024-06-05 18:01:16] INFO package.py:256: Validation pass
[2024-06-05 18:01:16] INFO package.py:270: Moving "dist\lib\libmodel_android.a" to "build\lib\libmodel_android.a"
[2024-06-05 18:01:16] INFO package.py:274: Building mlc4j
info: component 'rust-std' for target 'aarch64-linux-android' is up to date
[2024-06-05 18:01:18] INFO prepare_libs.py:90: Entering "E:\project\mlc-llm-main\android\MLCChat\build" for MLC LLM and tvm4j build.
[2024-06-05 18:01:18] INFO prepare_libs.py:94: Set TVM_SOURCE_DIR to "E:\project\mlc-llm-main\3rdparty\tvm"
[2024-06-05 18:01:18] INFO prepare_libs.py:22: Running cmake
[2024-06-05 18:01:18] INFO prepare_libs.py:48: Using ninja in windows, make sure you installed ninja in conda
-- The C compiler identification is Clang 14.0.7
-- The CXX compiler identification is Clang 14.0.7
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/Users/W9057210.ADC/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Users/W9057210.ADC/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at E:/project/mlc-llm-main/android/MLCChat/build/config.cmake:1 (set):
  Syntax error in cmake code at

    E:/project/mlc-llm-main/android/MLCChat/build/config.cmake:1

  when parsing string

    ${E:\project\mlc-llm-main\3rdparty\tvm}

  Invalid character (':') in a variable name: 'E'
Call Stack (most recent call first):
  E:/project/mlc-llm-main/CMakeLists.txt:12 (include)

-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "E:\project\mlc-llm-main\android\mlc4j\prepare_libs.py", line 117, in <module>
    main(parsed.mlc_llm_source_dir)
  File "E:\project\mlc-llm-main\android\mlc4j\prepare_libs.py", line 99, in main
    run_cmake(mlc_llm_source_dir / "android" / "mlc4j")
  File "E:\project\mlc-llm-main\android\mlc4j\prepare_libs.py", line 50, in run_cmake
    subprocess.run(cmd, check=True, env=os.environ)
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', 'E:\\project\\mlc-llm-main\\android\\mlc4j', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=D:\\Users\\W9057210.ADC\\AppData\\Local\\Android\\Sdk\\ndk\\25.2.9519653\\build\\cmake\\android.toolchain.cmake', '-DCMAKE_INSTALL_PREFIX=.', '-DCMAKE_CXX_FLAGS="-O3"', '-DANDROID_ABI=arm64-v8a', '-DANDROID_NATIVE_API_LEVEL=android-24', '-DANDROID_PLATFORM=android-24', '-DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ON', '-DANDROID_STL=c++_static', '-DUSE_HEXAGON_SDK=OFF', '-DMLC_LLM_INSTALL_STATIC_LIB=ON', '-DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON', '-DUSE_OPENCL=ON', '-DUSE_OPENCL_ENABLE_HOST_PTR=ON', '-DUSE_CUSTOM_LOGGING=ON', '-G', 'Ninja']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Scripts\mlc_llm.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\site-packages\mlc_llm\__main__.py", line 53, in main
    cli.main(sys.argv[2:])
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\site-packages\mlc_llm\cli\package.py", line 64, in main
    package(
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\site-packages\mlc_llm\interface\package.py", line 361, in package
    build_android_binding(mlc_llm_source_dir, output)
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\site-packages\mlc_llm\interface\package.py", line 275, in build_android_binding
    subprocess.run([sys.executable, mlc4j_path / "prepare_libs.py"], check=True, env=os.environ)
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\ProgramData\\anaconda3\\envs\\mlc-panghongtao\\python.exe', WindowsPath('E:/project/mlc-llm-main/android/mlc4j/prepare_libs.py')]' returned non-zero exit status 1.

**Comment by tqchen** [comment]
can you print out the code in E:/project/mlc-llm-main/android/MLCChat/build/config.cmake:1 and see what is the content there

**Comment by panghongtao** [comment]
> can you print out the code in E:/project/mlc-llm-main/android/MLCChat/build/config.cmake:1 and see what is the content there

just have this context:
------------------------------------------------------------------------

set(TVM_SOURCE_DIR ${E:\project\mlc-llm-main\3rdparty\tvm})

-------------------------------------------------------------------------

Does this mean that my TVM Settings are wrong?

**Comment by PhilCuriosity** [comment]
> > can you print out the code in E:/project/mlc-llm-main/android/MLCChat/build/config.cmake:1 and see what is the content there
> 
> @tqchen just have this context:
> 
> set(TVM_SOURCE_DIR ${E:\project\mlc-llm-main\3rdparty\tvm})
> 
> Does this mean that my TVM Settings are wrong?
> 
> This directory E:\project\mlc-llm-main\3rdparty\tvm no have file

You need to execute a command first to download tvm and other dependencies.
`cd mlc-llmgit submodule update --init --recursive 
 `

**Comment by PhilCuriosity** [comment]
> can you print out the code in E:/project/mlc-llm-main/android/MLCChat/build/config.cmake:1 and see what is the content there

I also encountered a similar error on windows, as follows
set TVM_SOURCE_DIR=..\\..\3rdparty\tvm
```
CMake Error at E:/CCode/mlc-llm/android/MLCChat/build/config.cmake:1 (set):
  Syntax error in cmake code at

    E:/CCode/mlc-llm/android/MLCChat/build/config.cmake:1

  when parsing string

    ${..\..\3rdparty\tvm}

  Invalid character escape '\3'.
Call Stack (most recent call first):
  E:/CCode/mlc-llm/CMakeLists.txt:12 (include)

```
set TVM_SOURCE_DIR= ../../3rdparty/tvm
```
-- TVM_SOURCE_DIR: ../../3rdparty/tvm
CMake Error at E:/CCode/mlc-llm/CMakeLists.txt:65 (add_subdirectory):
  add_subdirectory given source "../../3rdparty/tvm" which is not an existing
  directory.
```

**Comment by panghongtao** [comment]
> > can you print out the code in E:/project/mlc-llm-main/android/MLCChat/build/config.cmake:1 and see what is the content there
> 
> I also encountered a similar error on windows, as follows set TVM_SOURCE_DIR=..\..\3rdparty\tvm
> 
> ```
> CMake Error at E:/CCode/mlc-llm/android/MLCChat/build/config.cmake:1 (set):
>   Syntax error in cmake code at
> 
>     E:/CCode/mlc-llm/android/MLCChat/build/config.cmake:1
> 
>   when parsing string
> 
>     ${..\..\3rdparty\tvm}
> 
>   Invalid character escape '\3'.
> Call Stack (most recent call first):
>   E:/CCode/mlc-llm/CMakeLists.txt:12 (include)
> ```
> 
> set TVM_SOURCE_DIR= ../../3rdparty/tvm
> 
> ```
> -- TVM_SOURCE_DIR: ../../3rdparty/tvm
> CMake Error at E:/CCode/mlc-llm/CMakeLists.txt:65 (add_subdirectory):
>   add_subdirectory given source "../../3rdparty/tvm" which is not an existing
>   directory.
> ```

Hi PhilCuriosity。I've modified my code the way you did. Now I have the same problem as you. About tvm in Windows 10 path error, have you resolved? Is there a way to do that?

**Comment by PhilCuriosity** [comment]
Sorry, I'm not sure how the mlc-llm command works, and I haven't solved the problem yet.

**Comment by panghongtao** [comment]
> Sorry, I'm not sure how the mlc-llm command works, and I haven't solved the problem yet.

update mlc_llm code.This issue has been fixed. set TVM_SOURCE_DIR E:/project/mlc-llm/3rdparty/tvm  this format

**Comment by tqchen** [comment]
Glad it works out

**Comment by PhilCuriosity** [comment]
That worked. Thank you.
