### ISSUE TITLE
[Bug] TVM_SOURCE_DIR In Windows 10. In the identification path is error

### ISSUE THREAD

**Issue by panghongtao** [mlc-ai/mlc-llm#2536]
## 🐛 Bug

TVM_SOURCE_DIR  Is there an error in this parameter setting? I try two paths and get the same error. Is there a special setting for this parameter in Windows 10?

## To Reproduce

**set TVM_SOURCE_DIR E:/project/mlc-llm/3rdparty/tvm**

[2024-06-07 10:59:06] INFO prepare_libs.py:48: Using ninja in windows, make sure you installed ninja in conda
CMake Error at E:/project/mlc-llm/android/MLCChat/build/config.cmake:1 (set):
  Syntax error in cmake code at

    E:/project/mlc-llm/android/MLCChat/build/config.cmake:1

  when parsing string

    ${E:/project/mlc-llm/3rdparty/tvm}

  Invalid character (':') in a variable name: 'E'
Call Stack (most recent call first):
  E:/project/mlc-llm/CMakeLists.txt:12 (include)

-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "E:\project\mlc-llm\android\mlc4j\prepare_libs.py", line 117, in <module>
    main(parsed.mlc_llm_source_dir)
  File "E:\project\mlc-llm\android\mlc4j\prepare_libs.py", line 99, in main
    run_cmake(mlc_llm_source_dir / "android" / "mlc4j")
  File "E:\project\mlc-llm\android\mlc4j\prepare_libs.py", line 50, in run_cmake
    subprocess.run(cmd, check=True, env=os.environ)
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', 'E:\\project\\mlc-llm\\android\\mlc4j', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=D:\\Users\\W9057210.ADC\\AppData\\Local\\Android\\Sdk\\ndk\\25.2.9519653\\build\\cmake\\android.toolchain.cmake', '-DCMAKE_INSTALL_PREFIX=.', '-DCMAKE_CXX_FLAGS="-O3"', '-DANDROID_ABI=arm64-v8a', '-DANDROID_NATIVE_API_LEVEL=android-24', '-DANDROID_PLATFORM=android-24', '-DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ON', '-DANDROID_STL=c++_static', '-DUSE_HEXAGON_SDK=OFF', '-DMLC_LLM_INSTALL_STATIC_LIB=ON', '-DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON', '-DUSE_OPENCL=ON', '-DUSE_OPENCL_ENABLE_HOST_PTR=ON', '-DUSE_CUSTOM_LOGGING=ON', '-G', 'Ninja']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Scripts\mlc_llm.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\site-packages\mlc_llm\__main__.py", line 53, in main
    cli.main(sys.argv[2:])
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\site-packages\mlc_llm\cli\package.py", line 64, in main
    package(
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\site-packages\mlc_llm\interface\package.py", line 361, in package
    build_android_binding(mlc_llm_source_dir, output)
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\site-packages\mlc_llm\interface\package.py", line 275, in build_android_binding
    subprocess.run([sys.executable, mlc4j_path / "prepare_libs.py"], check=True, env=os.environ)
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,

**set TVM_SOURCE_DIR E:\project\mlc-llm\3rdparty\tvm**

[2024-06-07 11:13:04] INFO prepare_libs.py:48: Using ninja in windows, make sure you installed ninja in conda
CMake Error at E:/project/mlc-llm/android/MLCChat/build/config.cmake:1 (set):
  Syntax error in cmake code at

    E:/project/mlc-llm/android/MLCChat/build/config.cmake:1

  when parsing string

    ${E:\project\mlc-llm\3rdparty\tvm}

  Invalid character (':') in a variable name: 'E'
Call Stack (most recent call first):
  E:/project/mlc-llm/CMakeLists.txt:12 (include)

-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "E:\project\mlc-llm\android\mlc4j\prepare_libs.py", line 117, in <module>
    main(parsed.mlc_llm_source_dir)
  File "E:\project\mlc-llm\android\mlc4j\prepare_libs.py", line 99, in main
    run_cmake(mlc_llm_source_dir / "android" / "mlc4j")
  File "E:\project\mlc-llm\android\mlc4j\prepare_libs.py", line 50, in run_cmake
    subprocess.run(cmd, check=True, env=os.environ)
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', 'E:\\project\\mlc-llm\\android\\mlc4j', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=D:\\Users\\W9057210.ADC\\AppData\\Local\\Android\\Sdk\\ndk\\25.2.9519653\\build\\cmake\\android.toolchain.cmake', '-DCMAKE_INSTALL_PREFIX=.', '-DCMAKE_CXX_FLAGS="-O3"', '-DANDROID_ABI=arm64-v8a', '-DANDROID_NATIVE_API_LEVEL=android-24', '-DANDROID_PLATFORM=android-24', '-DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ON', '-DANDROID_STL=c++_static', '-DUSE_HEXAGON_SDK=OFF', '-DMLC_LLM_INSTALL_STATIC_LIB=ON', '-DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON', '-DUSE_OPENCL=ON', '-DUSE_OPENCL_ENABLE_HOST_PTR=ON', '-DUSE_CUSTOM_LOGGING=ON', '-G', 'Ninja']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Scripts\mlc_llm.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\site-packages\mlc_llm\__main__.py", line 53, in main
    cli.main(sys.argv[2:])
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\site-packages\mlc_llm\cli\package.py", line 64, in main
    package(
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\site-packages\mlc_llm\interface\package.py", line 361, in package
    build_android_binding(mlc_llm_source_dir, output)
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\site-packages\mlc_llm\interface\package.py", line 275, in build_android_binding
    subprocess.run([sys.executable, mlc4j_path / "prepare_libs.py"], check=True, env=os.environ)
  File "C:\ProgramData\anaconda3\envs\mlc-panghongtao\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,

**Comment by MasterJH5574** [comment]
Hi @panghongtao, we just merged a patch in #2538. Could you fetch and check out the latest main branch, and see if this can resolve the issue you reported?

**Comment by panghongtao** [comment]
> Hi @panghongtao, we just merged a patch in #2538. Could you fetch and check out the latest main branch, and see if this can resolve the issue you reported?

I have tried. The problem has been solved. In Windows 10 you need to change the path format

if set TVM_SOURCE_DIR E:/project/mlc-llm/3rdparty\tvm/  

go on execue

but if set TVM_SOURCE_DIR E:\project\mlc-llm\3rdparty\tvm\ 

CMake Error at E:/project/mlc-llm/android/MLCChat/build/config.cmake:1 (set):
  Syntax error in cmake code at

    E:/project/mlc-llm/android/MLCChat/build/config.cmake:1

  when parsing string

    E:\project\mlc-llm\3rdparty\tvm

  Invalid character escape '\p'.
Call Stack (most recent call first):
  E:/project/mlc-llm/CMakeLists.txt:12 (include)
