### ISSUE TITLE
[Question] Is there a way to compute ppl of models in MLC-LLM?

### ISSUE THREAD

**Issue by ponytaill** [mlc-ai/mlc-llm#2554]
## ❓ General Questions

Hi, I wonder if there is a way to compute ppl of llms in MLC-LLM. Thanks for any help.

**Comment by MasterJH5574** [comment]
Thank you for the question. We support the full set of OpenAI API, including `logprob`. So you may leverage the logprob output to calculate the perplexity. Here is some reference from OpenAI that might be related https://cookbook.openai.com/examples/using_logprobs#5-calculating-perplexity.

**Comment by ponytaill** [comment]
> Thank you for the question. We support the full set of OpenAI API, including `logprob`. So you may leverage the logprob output to calculate the perplexity. Here is some reference from OpenAI that might be related https://cookbook.openai.com/examples/using_logprobs#5-calculating-perplexity.

Hi, @MasterJH5574  I followed the tutorial and wrote the following code and ran it, but got error.
`from mlc_llm import MLCEngine
from openai import OpenAI
from math import exp
import numpy as np
import os
# Create engine
# model = "HF://mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC"
model = "./dist/qwen2-MLC"
engine = MLCEngine(model)

prompt = "What is love?"
API_RESPONSE = engine.chat.completions.create(
    messages=[{"role": "user", "content": prompt}],
    model=model,
    logprobs=True,
    stream=False,
)
print(API_RESPONSE)
engine.terminate()`
The output is following:
[2024-06-13 15:00:19] INFO auto_device.py:88: Not found device: cuda:0
[2024-06-13 15:00:21] INFO auto_device.py:88: Not found device: rocm:0
[2024-06-13 15:00:22] INFO auto_device.py:88: Not found device: metal:0
[2024-06-13 15:00:24] INFO auto_device.py:79: Found device: vulkan:0
[2024-06-13 15:00:25] INFO auto_device.py:88: Not found device: opencl:0
[2024-06-13 15:00:25] INFO auto_device.py:35: Using device: vulkan:0
[2024-06-13 15:00:25] INFO jit.py:43: MLC_JIT_POLICY = ON. Can be one of: ON, OFF, REDO, READONLY
[2024-06-13 15:00:25] INFO jit.py:160: Using cached model lib: /home/shi/.cache/mlc_llm/model_lib/dc2779a21ab9b30a7ec2f85a29b5e45e.so
[2024-06-13 15:00:25] INFO engine_base.py:168: The selected engine mode is local. We choose small max batch size and KV cache capacity to use less GPU memory.
[2024-06-13 15:00:25] INFO engine_base.py:193: If you don't have concurrent requests and only use the engine interactively, please select mode "interactive".
[2024-06-13 15:00:25] INFO engine_base.py:198: If you have high concurrent requests and want to maximize the GPU memory utilization, please select mode "server".
[15:00:25] /workspace/mlc-llm/cpp/serve/config.cc:649: Under mode "local", max batch size will be set to 4, max KV cache token capacity will be set to 768, prefill chunk size will be set to 768. 
[15:00:25] /workspace/mlc-llm/cpp/serve/config.cc:649: Under mode "interactive", max batch size will be set to 1, max KV cache token capacity will be set to 768, prefill chunk size will be set to 768. 
[15:00:25] /workspace/mlc-llm/cpp/serve/config.cc:649: Under mode "server", max batch size will be set to 80, max KV cache token capacity will be set to 61440, prefill chunk size will be set to 768. 
[15:00:25] /workspace/mlc-llm/cpp/serve/config.cc:729: The actual engine mode is "local". So max batch size is 4, max KV cache token capacity is 768, prefill chunk size is 768.
[15:00:25] /workspace/mlc-llm/cpp/serve/config.cc:734: Estimated total single GPU memory usage: 1405.491 MB (Parameters: 332.533 MB. KVCache: 126.101 MB. Temporary buffer: 946.857 MB). The actual usage might be slightly larger than the estimated number.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/shi/anaconda3/envs/newmlc/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/shi/anaconda3/envs/newmlc/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/home/shi/anaconda3/envs/newmlc/lib/python3.10/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/workspace/mlc-llm/cpp/serve/threaded_engine.cc", line 169, in mlc::llm::serve::ThreadedEngineImpl::RunBackgroundLoop()
  File "/workspace/mlc-llm/cpp/serve/engine.cc", line 613, in mlc::llm::serve::EngineImpl::Step()
  File "/workspace/mlc-llm/cpp/serve/engine_actions/action_commons.cc", line 178, in mlc::llm::serve::ActionStepPostProcess(tvm::runtime::Array<mlc::llm::serve::Request, void>, mlc::llm::serve::EngineState, tvm::runtime::Array<mlc::llm::serve::Model, void>, mlc::llm::Tokenizer const&, tvm::runtime::TypedPackedFunc<void (tvm::runtime::Array<mlc::llm::serve::RequestStreamOutput, void>)>, long, tvm::runtime::Optional<mlc::llm::serve::EventTraceRecorder>)
  File "/workspace/mlc-llm/cpp/serve/request_state.cc", line 137, in mlc::llm::serve::RequestStateEntryNode::GetReturnTokenIds(mlc::llm::Tokenizer const&, long)
  File "/workspace/mlc-llm/cpp/tokenizers/streamer.cc", line 193, in mlc::llm::StopStrHandlerObj::Put(int)
tvm.error.InternalError: Traceback (most recent call last):
  4: mlc::llm::serve::ThreadedEngineImpl::RunBackgroundLoop()
        at /workspace/mlc-llm/cpp/serve/threaded_engine.cc:169
  3: mlc::llm::serve::EngineImpl::Step()
        at /workspace/mlc-llm/cpp/serve/engine.cc:613
  2: mlc::llm::serve::ActionStepPostProcess(tvm::runtime::Array<mlc::llm::serve::Request, void>, mlc::llm::serve::EngineState, tvm::runtime::Array<mlc::llm::serve::Model, void>, mlc::llm::Tokenizer const&, tvm::runtime::TypedPackedFunc<void (tvm::runtime::Array<mlc::llm::serve::RequestStreamOutput, void>)>, long, tvm::runtime::Optional<mlc::llm::serve::EventTraceRecorder>)
        at /workspace/mlc-llm/cpp/serve/engine_actions/action_commons.cc:178
  1: mlc::llm::serve::RequestStateEntryNode::GetReturnTokenIds(mlc::llm::Tokenizer const&, long)
        at /workspace/mlc-llm/cpp/serve/request_state.cc:137
  0: mlc::llm::StopStrHandlerObj::Put(int)
        at /workspace/mlc-llm/cpp/tokenizers/streamer.cc:193
  File "/workspace/mlc-llm/cpp/tokenizers/streamer.cc", line 193
InternalError: Check failed: token_id < static_cast<int>(token_table_.size()) (151935 vs. 151646) : 

It seems like caused by too many output tokens? I've tried to bring up prompt questions that expect a short answer, such as "Does one plus one equal two?" I can get normal output with no errors.

**Comment by MasterJH5574** [comment]
@ponytaill Sorry for the late reply. We fixed a Qwen issue on June 7 in this commit https://github.com/mlc-ai/mlc-llm/commit/208642d372e721c9f7157a6b2a13bd1f94b7361c. Just wondering if your mlc-llm package is installed before June 7? If that's the case, you may upgrade to the latest nightly package and try again.

**Comment by ponytaill** [comment]
> @ponytaill Sorry for the late reply. We fixed a Qwen issue on June 7 in this commit [208642d](https://github.com/mlc-ai/mlc-llm/commit/208642d372e721c9f7157a6b2a13bd1f94b7361c). Just wondering if your mlc-llm package is installed before June 7? If that's the case, you may upgrade to the latest nightly package and try again.

Thanks. Either way, the problem is solved.
