### ISSUE TITLE
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

### ISSUE THREAD

**Issue by Karwei0** [mlc-ai/mlc-llm#2582]
## 🐛 Bug

when I execute the command 

`mlc_chat_cli --model Llama-2-7b-chat-hf-q4f16_1 --model-lib-path D:\chat\dist\prebuilt\lib\Llama-2-7b-chat-hf\Llama-2-7b-chat-hf-q4f16_1-vulkan.so`

there was a problem:

~~~
Use MLC config: "D:\\chat\\dist\\prebuilt\\Llama-2-7b-chat-hf-q4f16_1\\mlc-chat-config.json"
Use model weights: "D:\\chat\\dist\\prebuilt\\Llama-2-7b-chat-hf-q4f16_1\\ndarray-cache.json"
Use model library: "D:\\chat\\dist\\prebuilt\\lib\\Llama-2-7b-chat-hf\\Llama-2-7b-chat-hf-q4f16_1-vulkan.so"
You can use the following special commands:
  /help               print the special commands
  /exit               quit the cli
  /stats              print out the latest stats (token/sec)
  /reset              restart a fresh chat
  /reload [model]  reload model `model` from disk, or reload the current model if `model` is not specified

Loading model...
[10:38:03] C:\Miniconda\envs\mlc-llm-build\conda-bld\mlc-chat-cli-nightly-package_1706850403301\work\cpp\llm_chat.cc:526: InternalError: Check failed: (config["conv_template"].is<std::string>()) is false:
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.
~~~

how can I solve it

**Comment by Hzfengsy** [comment]
`mlc_chat_cli` API is pretty old, please reinstall/upgrade your package :)

**Comment by Karwei0** [comment]
OK，thank you.  There are so many guidance online. So should I use `mlc_llm` instead of `mlc_chat_cli`;
However there was another problem which has puzzled me for a long time when I use `mlc_llm`
~~~
(mlc-chat-venv) D:\chat>mlc_llm --model Llama-2-7b-chat-hf-q4f16_1 --model-lib-path D:\chat\dist\prebuilt\lib\Llama-2-7b-chat-hf\Llama-2-7b-chat-hf-q4f16_1-vulkan.so
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\anaconda3\Scripts\mlc_llm.exe\__main__.py", line 4, in <module>
  File "D:\anaconda3\Lib\site-packages\mlc_llm\__init__.py", line 6, in <module>
    from . import protocol, serve
  File "D:\anaconda3\Lib\site-packages\mlc_llm\serve\__init__.py", line 4, in <module>
    from .. import base
  File "D:\anaconda3\Lib\site-packages\mlc_llm\base.py", line 7, in <module>
    import tvm
  File "D:\anaconda3\Lib\site-packages\tvm\__init__.py", line 26, in <module>
    from ._ffi.base import TVMError, __version__, _RUNTIME_ONLY
  File "D:\anaconda3\Lib\site-packages\tvm\_ffi\__init__.py", line 28, in <module>
    from .base import register_error
  File "D:\anaconda3\Lib\site-packages\tvm\_ffi\base.py", line 78, in <module>
    _LIB, _LIB_NAME = _load_lib()
                      ^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\tvm\_ffi\base.py", line 64, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 1114] 动态链接库(DLL)初始化例程失败。
~~~

"动态链接库(DLL)初始化例程失败" I can't find something relevant guidance . Can you give me some advice?

**Comment by Hzfengsy** [comment]
All prebuilt libraries are built for Linux only. 

We recommend to follow our latest tutorial: https://llm.mlc.ai/docs/get_started/quick_start.html

**Comment by Karwei0** [comment]
It is a sad story. I've tried countless time in these days.
But thank you all the same.
