### ISSUE TITLE
[Bug] AttributeError: 'NoneType' object has no attribute 'device_type'

### ISSUE THREAD

**Issue by haohenggang** [mlc-ai/mlc-llm#2627]
## 🐛 Bug
 (mlc-chat-venv) hhg@dell:~/mlc-llm$ mlc_llm convert_weight ./dist/models/Qwen1.5-1.8B-Chat --model-type qwen2 --device auto --quantization q4f16_1 --source-format huggingface-safetensor -o dist/qwen1.5-1.8b-q4f16_1-MLC
[2024-07-05 22:44:32] INFO auto_config.py:116: Found model configuration: dist/models/Qwen1.5-1.8B-Chat/config.json
[2024-07-05 22:44:34] INFO auto_device.py:88: Not found device: cuda:0
[2024-07-05 22:44:36] INFO auto_device.py:88: Not found device: rocm:0
[2024-07-05 22:44:39] INFO auto_device.py:88: Not found device: metal:0
[2024-07-05 22:44:41] INFO auto_device.py:88: Not found device: vulkan:0
[2024-07-05 22:44:43] INFO auto_device.py:88: Not found device: opencl:0
[2024-07-05 22:44:43] INFO auto_device.py:33: Not found: No available device detected
[2024-07-05 22:44:43] INFO auto_weight.py:71: Finding weights in: dist/models/Qwen1.5-1.8B-Chat
[2024-07-05 22:44:43] INFO auto_weight.py:144: Found source weight format: huggingface-safetensor. Source configuration: dist/models/Qwen1.5-1.8B-Chat/model.safetensors.index.json
[2024-07-05 22:44:43] INFO auto_config.py:154: Found model type: qwen2. Use `--model-type` to override.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/hhg/mlc-llm/python/mlc_llm/__main__.py", line 64, in <module>
    main()
  File "/home/hhg/mlc-llm/python/mlc_llm/__main__.py", line 37, in main
    cli.main(sys.argv[2:])
  File "/home/hhg/mlc-llm/python/mlc_llm/cli/convert_weight.py", line 88, in main
    convert_weight(
  File "/home/hhg/mlc-llm/python/mlc_llm/interface/convert_weight.py", line 180, in convert_weight
    args.display()
  File "/home/hhg/mlc-llm/python/mlc_llm/interface/convert_weight.py", line 49, in display
    print(f"  {bold('--device'):<25} {_device_to_str(self.device)}", file=out)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hhg/mlc-llm/python/mlc_llm/interface/convert_weight.py", line 42, in _device_to_str
    return f"{Device.MASK2STR[device.device_type]}:{device.device_id}"
                              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'device_type'

nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0

hhg@dell:~/mlc-llm$ nvidia-smi
Fri Jul  5 22:48:33 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla P100-PCIE-16GB           Off |   00000000:01:00.0 Off |                    0 |
| N/A   41C    P0             26W /  250W |       7MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1074      G   /usr/lib/xorg/Xorg                              4MiB |
+-----------------------------------------------------------------------------------------+

## Environment
conda create -n mlc-chat-venv -c conda-forge \
    "cmake>=3.24" \
    rust \
    git \
    python=3.11
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0

# enter the build environment
conda activate mlc-chat-venv

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source):
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by MasterJH5574** [comment]
Hi @haohenggang, as the logger suggested, no device is found
```
[2024-07-05 22:44:34] INFO auto_device.py:88: Not found device: cuda:0
[2024-07-05 22:44:36] INFO auto_device.py:88: Not found device: rocm:0
[2024-07-05 22:44:39] INFO auto_device.py:88: Not found device: metal:0
[2024-07-05 22:44:41] INFO auto_device.py:88: Not found device: vulkan:0
[2024-07-05 22:44:43] INFO auto_device.py:88: Not found device: opencl:0
[2024-07-05 22:44:43] INFO auto_device.py:33: Not found: No available device detected
```

May I ask which device did you use?

**Comment by haohenggang** [comment]
> Hi @haohenggang, as the logger suggested, no device is found
> 
> ```
> [2024-07-05 22:44:34] INFO auto_device.py:88: Not found device: cuda:0
> [2024-07-05 22:44:36] INFO auto_device.py:88: Not found device: rocm:0
> [2024-07-05 22:44:39] INFO auto_device.py:88: Not found device: metal:0
> [2024-07-05 22:44:41] INFO auto_device.py:88: Not found device: vulkan:0
> [2024-07-05 22:44:43] INFO auto_device.py:88: Not found device: opencl:0
> [2024-07-05 22:44:43] INFO auto_device.py:33: Not found: No available device detected
> ```
> 
> May I ask which device did you use?

I have add cuda in build tvm unity,and that has ok

**Comment by haohenggang** [comment]
I have add cuda in build tvm unity,and that has ok

**Comment by clvlc** [comment]
> I have add cuda in build tvm unity,and that has ok

I got the same problem, but my torch can find cuda.
`>>> print(torch.cuda.is_available())
True
>>> print(torch.cuda.get_device_name(0))
NVIDIA GeForce GTX 1050
>>> print(torch.cuda.current_device())
0
>>> print(torch.cuda.device_count())
1
>>> exit()`
Could you please explain in detail how to solve this problem?
