### ISSUE TITLE
[Bug] TVMError: InternalError: Cannot find PackedFunc runtime.disco.allreduce in either Relax VM kernel library

### ISSUE THREAD

**Issue by limin05030** [mlc-ai/mlc-llm#2638]
## 🐛 Bug
When I was compiling an Android app and running it, there was a crash:
```
FATAL EXCEPTION: Thread-4
Process: ai.mlc.mlcchat, PID: 11743
org.apache.tvm.Base$TVMError: InternalError: Check failed: (func.defined()) is false: Error: Cannot find PackedFunc runtime.disco.allreduce in either Relax VM kernel library, or in TVM runtime PackedFunc registry, or in global Relax functions of the VM executable
Stack trace:
File "/home/ll/MLC/Llama-2-7b-chat-hf/mlc-llm/android/mlc4j/../../3rdparty/tvm/src/runtime/relax_vm/vm.cc", line 705
                                                    
    at org.apache.tvm.Base.checkCall(Base.java:173)
    at org.apache.tvm.Function.invoke(Function.java:130)
    ...
```

I am using `Llama-2-7b-chat-hf` and the main steps are as follows:

step 1. convert weight and generate config:
```
$ mlc_llm convert_weight \
    ./dist/models/Llama-2-7b-chat-hf/ \
    --quantization q4f16_1 \
    -o dist/Llama-2-7b-chat-hf-q4f16_1-MLC
```
```
$ mlc_llm gen_config \
    ./dist/models/Llama-2-7b-chat-hf/ \
    --quantization q4f16_1 \
    --conv-template llama-2 \
    --context-window-size 768 \
    --tensor-parallel-shard 2 \
    -o dist/Llama-2-7b-chat-hf-q4f16_1-MLC/
```
```
$ cat dist/Llama-2-7b-chat-hf-q4f16_1-MLC/mlc-chat-config.json:
{
  "version": "0.1.0",
  "model_type": "llama",
  "quantization": "q4f16_1",
  "model_config": {
    "hidden_size": 4096,
    "intermediate_size": 11008,
    "num_attention_heads": 32,
    "num_hidden_layers": 32,
    "rms_norm_eps": 1e-05,
    "vocab_size": 32000,
    "position_embedding_base": 10000,
    "context_window_size": 768,
    "prefill_chunk_size": 768,
    "num_key_value_heads": 32,
    "head_dim": 128,
    "tensor_parallel_shards": 2,
    "max_batch_size": 80
  },
  "vocab_size": 32000,
  "context_window_size": 768,
  "sliding_window_size": -1,
  "prefill_chunk_size": 768,
  "attention_sink_size": -1,
  "tensor_parallel_shards": 2,
  "temperature": 0.6,
  "presence_penalty": 0.0,
  "frequency_penalty": 0.0,
  "repetition_penalty": 1.0,
  "top_p": 0.9,
  "tokenizer_files": [
    "tokenizer.model",
    "tokenizer.json",
    "tokenizer_config.json"
  ],
  "tokenizer_info": {
    "token_postproc_method": "byte_fallback",
    "prepend_space_in_encode": true,
    "strip_space_in_decode": true
  },
  "conv_template": {
    "name": "llama-2",
    "system_template": "[INST] <<SYS>>\n{system_message}\n<</SYS>>\n\n",
    "system_message": "You are a helpful, respectful and honest assistant.",
    "system_prefix_token_ids": [
      1
    ],
    "add_role_after_system_message": false,
    "roles": {
      "user": "<s>[INST]",
      "assistant": "[/INST]",
      "tool": "[INST]"
    },
    "role_templates": {
      "user": "{user_message}",
      "assistant": "{assistant_message}",
      "tool": "{tool_message}"
    },
    "messages": [],
    "seps": [
      " ",
      " </s>"
    ],
    "role_content_sep": " ",
    "role_empty_sep": " ",
    "stop_str": [
      "[INST]"
    ],
    "stop_token_ids": [
      2
    ],
    "function_string": "",
    "use_function_calling": false
  },
  "pad_token_id": 0,
  "bos_token_id": 1,
  "eos_token_id": 2
}
```

step 2. build apk and install it:
```
$cat mlc-llm/android/MLCChat/mlc-package-config.json:
{
    "device": "android",
    "model_list": [
        {
            "model": "../../dist/Llama-2-7b-chat-hf-q4f16_1-MLC",
            "estimated_vram_bytes": 4679979417,
            "model_id": "Llama-2-7b-chat-hf-q4f16_1-MLC",
            "bundle_weight": true,
            "overrides": {
                "context_window_size": 768,
                "prefill_chunk_size": 256
            }
        }
    ]
}
```

```
$ cd mlc-llm/android/MLCChat
$ mlc_llm package
$ <compile apk using studio>
$ python bundle_weight.py --apk-path app/build/outputs/apk/debug/app-debug.apk
```

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): **Android**
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): **Ubuntu**
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): **Pixel 5**
 - How you installed MLC-LLM (`conda`, source): **python -m pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly-cu122 mlc-ai-nightly-cu122**
 - How you installed TVM-Unity (`pip`, source): **python -m pip install --pre -U -f https://mlc.ai/wheels mlc-ai-nightly-cu122**
 - Python version (e.g. 3.10): **3.11**
 - GPU driver version (if applicable): **(`nvidia-smi`)  NVIDIA-SMI 555.42.06      Driver Version: 555.42.06      CUDA Version: 12.5**
 - CUDA/cuDNN version (if applicable): **(`nvcc --version`)  Cuda compilation tools, release 12.2, V12.2.140**
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
``` 
USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
TVM_DEBUG_WITH_ABI_CHANGE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU:
CUDA_VERSION: 12.2
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: ON
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM:
USE_OPENCL_GTEST: /path/to/opencl/gtest
TVM_LOG_BEFORE_THROW: OFF
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_MSCCL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --ignore-libllvm --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: ON
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: f5f048bbd71513f087799f987019e3931f68a6d9
USE_VULKAN: ON
USE_RUST_EXT: OFF
USE_CUTLASS: ON
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2024-06-03 09:18:53 -0400
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: ON
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 15.0.7
USE_MRVL: OFF
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: OFF
USE_BNNS: OFF
USE_FLASHINFER: ON
USE_CUBLAS: ON
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION:
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /opt/rh/gcc-toolset-11/root/usr/bin/c++
HIDE_PRIVATE_SYMBOLS: ON
```

**Comment by tqchen** [comment]
Android do not support tensor parallel. So please avoid specify tensor parallel shards. Please follow the Android sdk to use mlc LLM package
