### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/2y/nd0wwb5s7c5flc4d0dm8124m0000gp/T/tmpzqysjxlt/tmp/ndarray-cache.json'[Question] 

### ISSUE THREAD

**Issue by Foursheepsir** [mlc-ai/mlc-llm#2656]
## ❓ General Questions

Hi, when I run 'mlc_llm package', there is a weird issue. I tried to debug but no progress yet. Could anyone help me on that? Many thanks! (os: macOS, model: MiniCPM-V-2 downloaded from huggingface: https://huggingface.co/openbmb/MiniCPM-V-2/tree/main) 

[2024-07-14 17:02:20] INFO download_cache.py:95: [Git LFS] Downloading tokenizer.model
100%|██████████████████████████████████████████| 10/10 [29:06<00:00, 174.67s/it]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/danieldd/Desktop/mlc-llm/python/mlc_llm/__main__.py", line 64, in <module>
    main()
  File "/Users/danieldd/Desktop/mlc-llm/python/mlc_llm/__main__.py", line 53, in main
    cli.main(sys.argv[2:])
  File "/Users/danieldd/Desktop/mlc-llm/python/mlc_llm/cli/package.py", line 64, in main
    package(
  File "/Users/danieldd/Desktop/mlc-llm/python/mlc_llm/interface/package.py", line 351, in package
    model_lib_path_for_prepare_libs = build_model_library(
                                      ^^^^^^^^^^^^^^^^^^^^
  File "/Users/danieldd/Desktop/mlc-llm/python/mlc_llm/interface/package.py", line 73, in build_model_library
    model_path = download_cache.get_or_download_model(model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danieldd/Desktop/mlc-llm/python/mlc_llm/support/download_cache.py", line 228, in get_or_download_model
    model_path = download_and_cache_mlc_weights(model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danieldd/Desktop/mlc-llm/python/mlc_llm/support/download_cache.py", line 183, in download_and_cache_mlc_weights
    with (tmp_dir / "ndarray-cache.json").open(encoding="utf-8") as in_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danieldd/miniconda3/envs/mlc-chat-venv/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/2y/nd0wwb5s7c5flc4d0dm8124m0000gp/T/tmpzqysjxlt/tmp/ndarray-cache.json'

**Comment by Hzfengsy** [comment]
`mlc_llm package` requires the repo in MLC format, while the given model is the original HF model. Please try to convert to MLC weight via `mlc_llm convert` and then try `package` cmd
