### ISSUE TITLE
[Bug] gemma init crash: AttentionKVCache expected 19 arguments but 18 were provided

### ISSUE THREAD

**Issue by Regenhardt** [mlc-ai/mlc-llm#2752]
## 🐛 Bug

Initializing a chat with gemma-2b, the process crashes and displays a stacktrace in the chat.

## To Reproduce

1. Unless previously done, download gemma-2b.
2. Start a chat with gemma-2b.
3. Wait.
4. Error message appears:

```
MLCChat failed

Stack trace:
org.apache.tvm.Base$TVMError: TVMError: Function vm.builtin.paged_attention_kv_cache_create_reduced(0: runtime.ShapeTuple, 1: int64_t, 2: int64_t, 3: int64_t, 4: int64_t, 5: int, 6: double, 7: double, 8: runtime.NDArray, 9: runtime.PackedFunc, 10: runtime.PackedFunc, 11: runtime.PackedFunc, 12: runtime.PackedFunc, 13: runtime.PackedFunc, 14: runtime.PackedFunc, 15: runtime.PackedFunc, 16: runtime.PackedFunc, 17: runtime.PackedFunc, 18: runtime.PackedFunc) -> relax.vm.AttentionKVCache expects 19 arguments, but 18 were provided.
Stack trace:
  File "/Users/kartik/mlc/tvm/include/tvm/runtime/packed_func.h", line 1908

 at org.apache.tvm.Base.checkCall([Base.java:173](https://base.java:173/))
 at org.apache.tvm.Function.invoke([Function.java:130](https://function.java:130/))
 at ai.mlc.mlcllm.ChatModule.reload([ChatModule.java:46](https://chatmodule.java:46/))
 at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:648)
 at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:646)
 at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:548)
 at ai.mlc.mlcchat.AppViewModel$ChatState.mainReloadChat$lambda$3(AppViewModel.kt:646)
 at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$CXL6v4mjTu_Sr5Pk2zFDcus0R-8(Unknown Source:0)
 at ai.mlc.mlcchat.AppViewModel$ChatState$$[ExternalSyntheticLambda2.run](https://externalsyntheticlambda2.run/)(Unknown Source:8)
 at java.util.concurrent.Executors$[RunnableAdapter.call](https://runnableadapter.call/)([Executors.java:462](https://executors.java:462/))
 at [java.util.concurrent.FutureTask.run](https://java.util.concurrent.futuretask.run/)([FutureTask.java:266](https://futuretask.java:266/))
 at java.util.concurrent.ThreadPoolExecutor.runWorker([ThreadPoolExecutor.java:1167](https://threadpoolexecutor.java:1167/))
 at java.util.concurrent.ThreadPoolExecutor$[Worker.run](https://worker.run/)([ThreadPoolExecutor.java:641](https://threadpoolexecutor.java:641/))
 at [java.lang.Thread.run](https://java.lang.thread.run/)([Thread.java:919](https://thread.java:919/))


Error message:
TVMError: Function vm.builtin.paged_attention_kv_cache_create_reduced(0: runtime.ShapeTuple, 1: int64_t, 2: int64_t, 3: int64_t, 4: int64_t, 5: int, 6: double, 7: double, 8: runtime.NDArray, 9: runtime.PackedFunc, 10: runtime.PackedFunc, 11: runtime.PackedFunc, 12: runtime.PackedFunc, 13: runtime.PackedFunc, 14: runtime.PackedFunc, 15: runtime.PackedFunc, 16: runtime.PackedFunc, 17: runtime.PackedFunc, 18: runtime.PackedFunc) -> relax.vm.AttentionKVCache expects 19 arguments, but 18 were provided.
Stack trace:
  File "/Users/kartik/mlc/tvm/include/tvm/runtime/packed_func.h", line 1908
```

## Expected behavior

Model should be initialized to work with the chat. Chat should work.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Android 10
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): Sony Xperia XZ3 (H8416)
 - How you installed MLC-LLM (`conda`, source): APK download from docs website
 - How you installed TVM-Unity (`pip`, source): No idea...I just hope its included in the APK?
 - Python version (e.g. 3.10):  Uhhh this is an android app.
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

My phone has 4GB RAM, maybe it's that? I'd expect a different error though, or a complete app crash.

**Comment by MasterJH5574** [comment]
Thank you @Regenhardt for reporting. We are aware of this and are looking into it. Will report back and update the apk when it's fixed.

**Comment by gfvvz** [comment]
Similar issue meet for llama3.1, which report the error below:
TVMError: Function flashinfer.attention_kernel_prefill_with_ragged_kv_cache_begin_forward(0: DLTensor*, 1: DLTensor*, 2: int64_t, 3: int64_t, 4: int64_t, 5: int64_t, 6: void*) -> void expects 7 arguments, but 8 were provided.

**Comment by mengshyu** [comment]
Hi @Regenhardt, @gfvvz, I have verified on Samsung S23 and it works well,  could you uninstall MLCChat first and reinstall it to see if the issue still exists?

there is a simulator issue, and fixed by reinstalling app #2753

**Comment by Regenhardt** [comment]
Reinstalled the app, downloaded Gemma model, started chat, same error message appeared.

**Comment by miklosakos** [comment]
Same error message happens on a Google Pixel 7 running Android 15 Beta with RedPajama.
![Screenshot_20240811-043511.png](https://github.com/user-attachments/assets/38414d60-7da5-4733-80c3-a3d7008fe057)

**Comment by miklosakos** [comment]
Same with Mistral.
![Screenshot_20240811-044752.png](https://github.com/user-attachments/assets/3b696cf4-f219-4cc5-a200-12ee567cec3b)

**Comment by gfvvz** [comment]
@mengshyu , I do not use APK, just use command line in Ubuntu20.04, and before I upgrade the mlc-llm code base, the same model works.

**Comment by mengshyu** [comment]
Hi @gfvvz, It could be used the cached model library, please refer https://github.com/mlc-ai/mlc-llm/issues/2777#issuecomment-2304890962 for more details.
