### ISSUE TITLE
[Bug] The sequence only has length 202, while the length of pop is 304 which exceeds the whole sequence length.

### ISSUE THREAD

**Issue by mynameiskeen** [mlc-ai/mlc-llm#2766]
## 🐛 Bug

Running Qwen2-7B-Instruct with quantization q4f16_1 encountered error "TVMError: Check failed: n <= it->second.seq_length (304 vs. 202) : The sequence only has length 202, while the length of pop is 304 which exceeds the whole sequence length." when performing benchmark with llmperf with 50 concurrent users.

## To Reproduce

1. Run Qwen2-7B-Instruct with quantization q4f16_1, with parameters:
```bash
python -m mlc_llm serve Qwen2-7B-Instruct-mlc-q4f16-1 --model-lib Qwen2-7B-Instruct-mlc-q4f16-1/Qwen2-7B-Instruct-mlc-q4f16-1-cuda.so --mode server --overrides max_total_seq_length=16384;gpu_memory_utilization=0.9 --host 0.0.0.0 --port 8010
```
2. Perform benchmark with llmperf with below command:
```bash
python token_benchmark_ray.py --model Qwen2-7B-Instruct-mlc-q4f16-1 --mean-input-tokens 50 --stddev-input-tokens 0 --mean-output-tokens 150 --stddev-output-tokens 0 --max-num-completed-requests 500 --timeout 3600 --num-concurrent-requests 50 --results-dir "result_outputs" --llm-api openai --additional-sampling-params 
```
3. When concurrent requests were 5/10/20, it worked fine, but with concurrent 50, it raised error 
```
TVMError: Check failed: n <= it->second.seq_length (304 vs. 202) : The sequence only has length 202, while the length of pop is 304 which exceeds the whole sequence length.
```

4. After error raised, the mlc_llm process hung, need to kill it with "kill -9"

```
INFO:     127.0.0.1:33758 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:33760 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:39734 - "POST /v1/chat/completions HTTP/1.1" 200 OK
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/data/miniconda3/envs/mlc-llm/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/data/miniconda3/envs/mlc-llm/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 339, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 270, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 259, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 185, in tvm._ffi._cy3.core.CHECK_CALL
  File "/data/miniconda3/envs/mlc-llm/lib/python3.10/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/workspace/mlc-llm/cpp/serve/threaded_engine.cc", line 182, in mlc::llm::serve::ThreadedEngineImpl::RunBackgroundLoop()
  File "/workspace/mlc-llm/cpp/serve/engine.cc", line 650, in mlc::llm::serve::EngineImpl::Step()
  File "/workspace/mlc-llm/cpp/serve/engine_actions/new_request_prefill.cc", line 45, in mlc::llm::serve::NewRequestPrefillActionObj::Step(mlc::llm::serve::EngineState)
  File "/workspace/mlc-llm/cpp/serve/engine_actions/new_request_prefill.cc", line 325, in mlc::llm::serve::NewRequestPrefillActionObj::MatchPrefixCache(mlc::llm::serve::EngineState, mlc::llm::serve::BatchPrefillBaseActionObj::PrefillInput*)
  File "/workspace/mlc-llm/cpp/serve/model.cc", line 663, in mlc::llm::serve::ModelImpl::PopNFromKVCache(long, int)
tvm._ffi.base.TVMError: Traceback (most recent call last):
  7: mlc::llm::serve::ThreadedEngineImpl::RunBackgroundLoop()
        at /workspace/mlc-llm/cpp/serve/threaded_engine.cc:182
  6: mlc::llm::serve::EngineImpl::Step()
        at /workspace/mlc-llm/cpp/serve/engine.cc:650
  5: mlc::llm::serve::NewRequestPrefillActionObj::Step(mlc::llm::serve::EngineState)
        at /workspace/mlc-llm/cpp/serve/engine_actions/new_request_prefill.cc:45
  4: mlc::llm::serve::NewRequestPrefillActionObj::MatchPrefixCache(mlc::llm::serve::EngineState, mlc::llm::serve::BatchPrefillBaseActionObj::PrefillInput*)
        at /workspace/mlc-llm/cpp/serve/engine_actions/new_request_prefill.cc:325
  3: mlc::llm::serve::ModelImpl::PopNFromKVCache(long, int)
        at /workspace/mlc-llm/cpp/serve/model.cc:663
  2: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<void (tvm::runtime::relax_vm::KVState, long, int)>::AssignTypedLambda<tvm::runtime::Registry::set_body_method<tvm::runtime::relax_vm::KVState, tvm::runtime::relax_vm::KVStateObj, void, long, int, void>(void (tvm::runtime::relax_vm::KVStateObj::*)(long, int))::{lambda(tvm::runtime::relax_vm::KVState, long, int)#1}>(tvm::runtime::Registry::set_body_method<tvm::runtime::relax_vm::KVState, tvm::runtime::relax_vm::KVStateObj, void, long, int, void>(void (tvm::runtime::relax_vm::KVStateObj::*)(long, int))::{lambda(tvm::runtime::relax_vm::KVState, long, int)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  1: tvm::runtime::relax_vm::PagedAttentionKVCacheObj::PopN(long, int)
  0: _ZN3tvm7runtime6deta
  File "/workspace/tvm/src/runtime/relax_vm/paged_kv_cache.cc", line 1387
TVMError: Check failed: n <= it->second.seq_length (304 vs. 202) : The sequence only has length 202, while the length of pop is 304 which exceeds the whole sequence length.
[2024-08-07 01:27:48] INFO engine.py:1402: request chatcmpl-99a992860ac04fd5a7333b434ce40747 cancelled
INFO:     127.0.0.1:52260 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
INFO:     127.0.0.1:52274 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
INFO:     127.0.0.1:52282 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
```
## Expected behavior

Working as normal

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu 22.04
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) A100 PCIe 80GB
 - How you installed MLC-LLM (`conda`, source): conda pip install 
 - How you installed TVM-Unity (`pip`, source): pip install
 - Python version (e.g. 3.10): 3.10
 - GPU driver version (if applicable):555.42.06
 - CUDA/cuDNN version (if applicable): 12.5
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by MasterJH5574** [comment]
Hi @mynameiskeen, sorry for the delayed response. This issue is likely gone in the latest prebuilt packages. We'll appreciate if you would like to try again, and are happy to help if it persists.
