### ISSUE TITLE
[Bug]  crash when init qwen2 model

### ISSUE THREAD

**Issue by jfduma** [mlc-ai/mlc-llm#2787]
## 🐛 Bug

FATAL EXCEPTION: Thread-4
                 Process: ai.mlc.mlcchat, PID: 31622
                 org.apache.tvm.Base$TVMError: ValueError: Check failed: (f != nullptr) is false: Cannot find function mlc.multi_gpu.SendFromLastGroupToWorker0
                 Stack trace:
                   File "/Users/jiangfeng/work/mlc-llm/cpp/serve/function_table.cc", line 139
                 
                 	at org.apache.tvm.Base.checkCall(Base.java:173)
                 	at org.apache.tvm.Function.invoke(Function.java:130)
                 	at ai.mlc.mlcllm.JSONFFIEngine.runBackgroundLoop(JSONFFIEngine.java:64)
                 	at ai.mlc.mlcllm.MLCEngine$backgroundWorker$1.invoke(MLCEngine.kt:42)
                 	at ai.mlc.mlcllm.MLCEngine$backgroundWorker$1.invoke(MLCEngine.kt:40)
                 	at ai.mlc.mlcllm.BackgroundWorker$start$1.invoke(MLCEngine.kt:19)
                 	at ai.mlc.mlcllm.BackgroundWorker$start$1.invoke(MLCEngine.kt:18)
                 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

1. init a model like qwen2

In the function_table.cc file, there is an attempt to look up the mlc.multi_gpu.SendFromLastGroupToWorker0 function. This function is registered in the multi_gpu/build.cc file but is wrapped in #ifndef MLC_SINGLE_GPU_ONLY. However, the mlc4j/CMakeFiles.txt defines target_compile_definitions(mlc_llm_objs PUBLIC MLC_SINGLE_GPU_ONLY), which prevents the registration of this function, leading to the initialization failure.

**Comment by SamuraiBUPT** [comment]
Got the same problem here.

**Comment by HHH16** [comment]
I also encountered this problem.

**Comment by KAIWEILIUCC** [comment]
I Got the same issue

**Comment by MasterJH5574** [comment]
Apologize for the late response. This issue is fixed in https://github.com/mlc-ai/mlc-llm/pull/2807. Please pull the check out main branch and try again. Thanks!
