### ISSUE TITLE
[Question]   libtvm4j.so missing when run in phone

### ISSUE THREAD

**Issue by bglu3ca3AlbertoMajlqbewski** [mlc-ai/mlc-llm#2805]
## ❓ General Questions

1. I download this version
git clone -b docs_typo_mlc_chat --single-branch https://github.com/mlc-ai/mlc-llm.git 
2. in dir mlc-llm/android/MLCChat
    run command:  mlc_llm package   
    there is no error
3. Run apk in phone and report error
    Attempting to load libtvm4j.so
[WARN] Couldn't find native library tvm4j.

4. Here is log 
-------------------------------------------------------------------------------------------------------------------------------
Compat change id reported: 237531167; UID 10291; state: DISABLED
FramePredict init: false
init success
registerContentObserver fail
init cloud whiteList failed
Access denied finding property "ro.vendor.display.iris_x7.support"
type=1400 audit(0.0:12674): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=507 scontext=u:r:untrusted_app_32:s0:c35,c257,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0 app=ai.mlc.mlcchat
hardware acceleration = true, forceHwAccelerated = false
[a0b9b2d ai.mlc.mlcchat/ai.mlc.mlcchat.MainActivity#4251](this:0xb4000076c7664a50,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'a0b9b2d ai.mlc.mlcchat/ai.mlc.mlcchat.MainActivity#4251'
applied 1 plugins for [ai.mlc.mlcchat]:
plugin 1: [libMEOW_gift.so]:
Method java.lang.Object androidx.compose.runtime.snapshots.SnapshotStateMap.mutate(kotlin.jvm.functions.Function1) failed lock verification and will run slower.
Common causes for lock verification issues are non-optimized dex code
and incorrect proguard optimizations.
Method void androidx.compose.runtime.snapshots.SnapshotStateMap.update(kotlin.jvm.functions.Function1) failed lock verification and will run slower.
Method boolean androidx.compose.runtime.snapshots.SnapshotStateMap.removeIf$runtime_release(kotlin.jvm.functions.Function1) failed lock verification and will run slower.
Method boolean androidx.compose.runtime.snapshots.SnapshotStateList.conditionalUpdate(kotlin.jvm.functions.Function1) failed lock verification and will run slower.
Method java.lang.Object androidx.compose.runtime.snapshots.SnapshotStateList.mutate(kotlin.jvm.functions.Function1) failed lock verification and will run slower.
Method void androidx.compose.runtime.snapshots.SnapshotStateList.update(kotlin.jvm.functions.Function1) failed lock verification and will run slower.
Try loading tvm4j from native path.
Try loading tvm4j-linux-x86_64 from native path.
[WARN] TVM native library not found in path. Copying native library from the archive. Consider installing the library somewhere in the path (for Windows: PATH, for Linux: LD_LIBRARY_PATH), or specifying by Java cmd option -Djava.library.path=[lib path].
Attempting to load libtvm4j.so
[WARN] Couldn't find native library tvm4j.
java.lang.UnsatisfiedLinkError: Couldn't find the resource libtvm4j.so
at org.apache.tvm.NativeLibraryLoader.extractResourceFileToTempDir(NativeLibraryLoader.java:127)
at org.apache.tvm.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:87)
at org.apache.tvm.Base.<clinit>(Base.java:73)
at org.apache.tvm.Function.listGlobalFuncNames(Function.java:52)
at org.apache.tvm.Function.getFunction(Function.java:38)
at ai.mlc.mlcllm.JSONFFIEngine.<init>(JSONFFIEngine.java:24)
at ai.mlc.mlcllm.MLCEngine.<init>(MLCEngine.kt:33)
at ai.mlc.mlcchat.AppViewModel$ChatState.<init>(AppViewModel.kt:508)
at ai.mlc.mlcchat.AppViewModel.<init>(AppViewModel.kt:30)
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:314)
at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:306)
at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:280)
at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
at androidx.lifecycle.viewmodel.compose.ViewModelKt.get(ViewModel.kt:215)
at androidx.lifecycle.viewmodel.compose.ViewModelKt.viewModel(ViewModel.kt:156)
at ai.mlc.mlcchat.NavViewKt.NavView(NavView.kt:29)
at ai.mlc.mlcchat.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:24)
at ai.mlc.mlcchat.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:23)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
at androidx.compose.material3.TextKt.ProvideTextStyle(Text.kt:360)
at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:81)
at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:80)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
at androidx.compose.material3.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:73)
at ai.mlc.mlcchat.ui.theme.ThemeKt.MLCChatTheme(Theme.kt:102)
at ai.mlc.mlcchat.ComposableSingletons$MainActivityKt$lambda-2$1.invoke(MainActivity.kt:23)
at ai.mlc.mlcchat.ComposableSingletons$MainActivityKt$lambda-2$1.invoke(MainActivity.kt:22)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:132)
at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:114)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(Surface.kt:111)
at ai.mlc.mlcchat.ComposableSingletons$MainActivityKt$lambda-3$1.invoke(MainActivity.kt:19)
at ai.mlc.mlcchat.ComposableSingletons$MainActivityKt$lambda-3$1.invoke(MainActivity.kt:18)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:428)
at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:194)
at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:123)
at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:122)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:114)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:156)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:155)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:155)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:140)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3373)
at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3363)
at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3363)
at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3298)
at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:587)
at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:966)
at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1099)
at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:181)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1174)
at android.view.View.dispatchAttachedToWindow(View.java:22375)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3605)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3612)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3631)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3052)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10606)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1768)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1777)
at android.view.Choreographer.doCallbacks(Choreographer.java:1247)
at android.view.Choreographer.doFrame(Choreographer.java:1114)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1731)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:222)
at android.os.Looper.loop(Looper.java:314)
at android.app.ActivityThread.main(ActivityThread.java:8786)

2024-08-14 17:26:16.264 10348-10348 System.err ai.mlc.mlcchat W at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1090)
Try to load tvm4j (runtime packed version) ...
libtvm4j loads successfully.
[ai.mlc.mlcchat/ai.mlc.mlcchat.MainActivity#4252](this:0xb4000076c7714a50,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'ai.mlc.mlcchat/ai.mlc.mlcchat.MainActivity#4252'
[](id:286c00000000,api:0,p:-1,c:10348) connect: controlledByApp=false
meow new tls: 0xb400007c90b78000
applied 1 plugins for [ai.mlc.mlcchat]:
plugin 1: [libMEOW_gift.so]:
vri.reportNextDraw android.view.ViewRootImpl.performTraversals:4443 android.view.ViewRootImpl.doTraversal:3052 android.view.ViewRootImpl$TraversalRunnable.run:10606 android.view.Choreographer$CallbackRecord.run:1768 android.view.Choreographer$CallbackRecord.run:1777
vri.Setup new sync=wmsSync-VRI[MainActivity]#0
Unable to match the desired swap behavior.
makeCurrent grContext:0xb400007c90de39a0 reset mTextureAvailable
MiuiProcessManagerServiceStub setSchedFifo

5.  #340 report same Question
https://github.com/mlc-ai/mlc-llm/issues/340[ bug ](https://github.com/mlc-ai/mlc-llm/issues?q=libtvm4j.so+label%3Abug)java / android
#340

thanks~

**Comment by bglu3ca3AlbertoMajlqbewski** [comment]
I also check mlc_llm package result， no libtvm4j.so
(mlc-chat-cpm2) lenovo@lenovo-LEGION-REN9000K-34IRZ:/sda/xj/mlc-llm/android/MLCChat$ find ./ -iname "libtvm4j*.so"
./dist/lib/mlc4j/output/arm64-v8a/libtvm4j_runtime_packed.so
./dist/lib/mlc4j/build/intermediates/library_jni/debug/jni/arm64-v8a/libtvm4j_runtime_packed.so
./dist/lib/mlc4j/build/intermediates/merged_jni_libs/debug/out/arm64-v8a/libtvm4j_runtime_packed.so
./dist/lib/mlc4j/build/intermediates/merged_native_libs/debug/out/lib/arm64-v8a/libtvm4j_runtime_packed.so
./app/build/intermediates/stripped_native_libs/debug/out/lib/arm64-v8a/libtvm4j_runtime_packed.so
./app/build/intermediates/merged_native_libs/debug/out/lib/arm64-v8a/libtvm4j_runtime_packed.so
./build/output/arm64-v8a/libtvm4j_runtime_packed.so
./build/libtvm4j_runtime_packed.so

**Comment by tqchen** [comment]
there is no need to link ` libtvm4j.so` in android, instead the app loads libtvm4j_runtime_packed.so, which effectively support the runtime feature needed
