### ISSUE TITLE
[Question] Does MLC support AWQ quantization method to quantize Qwen2-7B-Instruct

### ISSUE THREAD

**Issue by Moxoo** [mlc-ai/mlc-llm#2806]
## ❓ General Questions

I try to quantize qwne2 using q4f16_autoawq but get this error:
```
mlc_llm convert_weight /Qwen2-7B-Instruct/ --quantization q4f16_autoawq -o /Qwen2-7B-Instruct-q4f16_autoawq-MLC

Traceback (most recent call last):
  File "/home/NLP/anaconda3/envs/mlc-chat-venv/bin/mlc_llm", line 33, in <module>
    sys.exit(load_entry_point('mlc-llm', 'console_scripts', 'mlc_llm')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxu/mlc-llm/python/mlc_llm/__main__.py", line 37, in main
    cli.main(sys.argv[2:])
  File "/home/maxu/mlc-llm/python/mlc_llm/cli/convert_weight.py", line 88, in main
    convert_weight(
  File "/home/maxu/mlc-llm/python/mlc_llm/interface/convert_weight.py", line 181, in convert_weight
    _convert_args(args)
  File "/home/maxu/mlc-llm/python/mlc_llm/interface/convert_weight.py", line 68, in _convert_args
    model, quantize_map = args.model.quantize[args.quantization.kind](
                          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'awq'
```

**Comment by Geministudents** [comment]
Is this problem solved?
