### ISSUE TITLE
[Question] tvmc run InternalError  (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

### ISSUE THREAD

**Issue by irischang710** [mlc-ai/mlc-llm#2819]
## ❓ General Questions

Followed the steps in the tutorial, failed when running the following command:
(mlc-venv) <username>@MacBook-Air-3 mlc_workspace % tvmc run \
--inputs imagenet_cat.npz \
--output predictions.npz \
resnet50-v2-7-tvm.tar
[17:11:48] /Users/<username>/projects/mlc_workspace/tvm/src/runtime/logging.cc:390: TVM_LOG_DEBUG enables VLOG statements in 'ir/transform.cc' up to level 1
[17:11:48] /Users/<username>/projects/mlc_workspace/tvm/src/runtime/logging.cc:390: TVM_LOG_DEBUG enables VLOG statements in 'relay/ir/transform.cc' up to level 1
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlc-venv/bin/tvmc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/<username>/projects/mlc_workspace/tvm/python/tvm/driver/tvmc/main.py", line 118, in main
    sys.exit(_main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/<username>/projects/mlc_workspace/tvm/python/tvm/driver/tvmc/main.py", line 106, in _main
    return args.func(args)
           ^^^^^^^^^^^^^^^
  File "/Users/<username>/projects/mlc_workspace/tvm/python/tvm/driver/tvmc/runner.py", line 282, in drive_run
    result = run_module(
             ^^^^^^^^^^^
  File "/Users/<username>/projects/mlc_workspace/tvm/python/tvm/driver/tvmc/runner.py", line 589, in run_module
    lib = session.load_module(tvmc_package.lib_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<username>/projects/mlc_workspace/tvm/python/tvm/rpc/client.py", line 178, in load_module
    return _ffi_api.LoadRemoteModule(self._sess, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<username>/projects/mlc_workspace/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 245, in __call__
    raise_last_ffi_error()
  File "/Users/<username>/projects/mlc_workspace/tvm/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/Users/<username>/projects/mlc_workspace/tvm/python/tvm/rpc/server.py", line 81, in load_module
    m = _load_module(path)
        ^^^^^^^^^^^^^^^^^^
  File "/Users/<username>/projects/mlc_workspace/tvm/python/tvm/runtime/module.py", line 699, in load_module
    return _ffi_api.ModuleLoadFromFile(path, fmt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<username>/projects/mlc_workspace/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 245, in __call__
    raise_last_ffi_error()
  File "/Users/<username>/projects/mlc_workspace/tvm/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm.error.InternalError: Traceback (most recent call last):
  File "/Users/<username>/projects/mlc_workspace/tvm/src/runtime/dso_library.cc", line 125
InternalError: Check failed: (lib_handle_ != nullptr) is false: Failed to load dynamic shared library /private/var/folders/y6/fc5zw1js53q0pmq6th2wxt0xrsshqz/T/tmpucyrn47y/mod.so dlopen(/private/var/folders/y6/fc5zw1js53q0pmq6th2wxt0xrsshqz/T/tmpucyrn47y/mod.so, 0x0005): tried: '/private/var/folders/y6/fc5zw1js53q0pmq6th2wxt0xrsshqz/T/tmpucyrn47y/mod.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/y6/fc5zw1js53q0pmq6th2wxt0xrsshqz/T/tmpucyrn47y/mod.so' (no such file), '/private/var/folders/y6/fc5zw1js53q0pmq6th2wxt0xrsshqz/T/tmpucyrn47y/mod.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

Could you advise how to fix this?

**Comment by Hzfengsy** [comment]
the issue is not related to this project, please turn to [Apache TVM](https://github.com/apache/tvm)
