### ISSUE TITLE
[Question] multiple GPUs

### ISSUE THREAD

**Issue by HTTP404Not-Found** [mlc-ai/mlc-llm#2838]
## ❓ General Questions
I cannot run CLI with Multi-GPU
gpu:w7800*4

command :mlc_llm serve HF://mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC --overrides "tensor_parallel_shards=3" --mode server

--- --- --- log --- --- ---
[2024-08-22 19:13:41] INFO auto_device.py:88: Not found device: cuda:0
[2024-08-22 19:13:44] INFO auto_device.py:79: Found device: rocm:0
[2024-08-22 19:13:44] INFO auto_device.py:79: Found device: rocm:1
[2024-08-22 19:13:44] INFO auto_device.py:79: Found device: rocm:2
[2024-08-22 19:13:44] INFO auto_device.py:79: Found device: rocm:3
[2024-08-22 19:13:45] INFO auto_device.py:88: Not found device: metal:0
[2024-08-22 19:13:45] INFO auto_device.py:79: Found device: vulkan:0
[2024-08-22 19:13:45] INFO auto_device.py:79: Found device: vulkan:1
[2024-08-22 19:13:45] INFO auto_device.py:79: Found device: vulkan:2
[2024-08-22 19:13:45] INFO auto_device.py:79: Found device: vulkan:3
[2024-08-22 19:13:45] INFO auto_device.py:79: Found device: vulkan:4
[2024-08-22 19:13:46] INFO auto_device.py:88: Not found device: opencl:0
[2024-08-22 19:13:46] INFO auto_device.py:35: Using device: rocm:0
[2024-08-22 19:13:46] INFO download_cache.py:227: Downloading model from HuggingFace: HF://mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC
[2024-08-22 19:13:46] INFO download_cache.py:29: MLC_DOWNLOAD_CACHE_POLICY = ON. Can be one of: ON, OFF, REDO, READONLY
[2024-08-22 19:13:46] INFO download_cache.py:166: Weights already downloaded: /root/.cache/mlc_llm/model_weights/hf/mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC
[2024-08-22 19:13:46] INFO jit.py:43: MLC_JIT_POLICY = ON. Can be one of: ON, OFF, REDO, READONLY
[2024-08-22 19:13:46] INFO jit.py:118: Compiling using commands below:
[2024-08-22 19:13:46] INFO jit.py:119: /root/anaconda3/envs/mlc-prebuilt/bin/python -m mlc_llm compile /root/.cache/mlc_llm/model_weights/hf/mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC --opt 'flashinfer=1;cublas_gemm=1;faster_transformer=0;cudagraph=1;cutlass=1;ipc_allreduce_strategy=NONE' --overrides tensor_parallel_shards=3 --device rocm:0 --output /tmp/tmpvyexztrs/lib.so
[2024-08-22 19:13:47] INFO auto_config.py:70: Found model configuration: /root/.cache/mlc_llm/model_weights/hf/mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC/mlc-chat-config.json
[2024-08-22 19:13:47] INFO auto_target.py:84: Detecting target device: rocm:0
[2024-08-22 19:13:47] INFO auto_target.py:86: Found target: {"thread_warp_size": 32, "mtriple": "amdgcn-amd-amdhsa-hcc", "max_threads_per_block": 1024, "max_num_threads": 256, "kind": "rocm", "max_shared_memory_per_block": 65536, "tag": "", "mcpu": "gfx1100", "keys": ["rocm", "gpu"]}
[2024-08-22 19:13:47] INFO auto_target.py:103: Found host LLVM triple: x86_64-unknown-linux-gnu
[2024-08-22 19:13:47] INFO auto_target.py:104: Found host LLVM CPU: znver4
[2024-08-22 19:13:47] INFO auto_config.py:154: Found model type: llama. Use `--model-type` to override.
Compiling with arguments:
  --config          LlamaConfig(hidden_size=4096, intermediate_size=14336, num_attention_heads=32, num_hidden_layers=32, rms_norm_eps=1e-05, vocab_size=128256, tie_word_embeddings=False, position_embedding_base=500000.0, rope_scaling=None, context_window_size=8192, prefill_chunk_size=2048, num_key_value_heads=8, head_dim=128, tensor_parallel_shards=1, max_batch_size=80, kwargs={})
  --quantization    GroupQuantize(name='q4f16_1', kind='group-quant', group_size=32, quantize_dtype='int4', storage_dtype='uint32', model_dtype='float16', linear_weight_layout='NK', quantize_embedding=True, quantize_final_fc=True, num_elem_per_storage=8, num_storage_per_group=4, max_int_value=7, tensor_parallel_shards=0)
  --model-type      llama
  --target          {"thread_warp_size": 32, "host": {"mtriple": "x86_64-unknown-linux-gnu", "tag": "", "kind": "llvm", "mcpu": "znver4", "keys": ["cpu"]}, "mtriple": "amdgcn-amd-amdhsa-hcc", "max_threads_per_block": 1024, "max_num_threads": 256, "kind": "rocm", "max_shared_memory_per_block": 65536, "tag": "", "mcpu": "gfx1100", "keys": ["rocm", "gpu"]}
  --opt             flashinfer=0;cublas_gemm=0;faster_transformer=0;cudagraph=0;cutlass=0;ipc_allreduce_strategy=NONE
  --system-lib-prefix ""
  --output          /tmp/tmpvyexztrs/lib.so
  --overrides       context_window_size=None;sliding_window_size=None;prefill_chunk_size=None;attention_sink_size=None;max_batch_size=None;tensor_parallel_shards=3
[2024-08-22 19:13:47] INFO config.py:107: Overriding tensor_parallel_shards from 1 to 3
[2024-08-22 19:13:47] INFO compile.py:127: Creating model from: LlamaConfig(hidden_size=4096, intermediate_size=14336, num_attention_heads=32, num_hidden_layers=32, rms_norm_eps=1e-05, vocab_size=128256, tie_word_embeddings=False, position_embedding_base=500000.0, rope_scaling=None, context_window_size=8192, prefill_chunk_size=2048, num_key_value_heads=8, head_dim=128, tensor_parallel_shards=1, max_batch_size=80, kwargs={})
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/__main__.py", line 64, in <module>
    main()
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/__main__.py", line 33, in main
    cli.main(sys.argv[2:])
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/cli/compile.py", line 129, in main
    compile(
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/interface/compile.py", line 229, in compile
    _compile(args, model_config)
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/interface/compile.py", line 143, in _compile
    model, _ = args.model.quantize[args.quantization.kind](model_config, args.quantization)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/model/llama/llama_quantization.py", line 25, in group_quant
    model: nn.Module = LlamaForCasualLM(model_config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/model/llama/llama_model.py", line 223, in __init__
    self.model = LlamaModel(config)
                 ^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/model/llama/llama_model.py", line 209, in __init__
    [LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)]
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/model/llama/llama_model.py", line 209, in <listcomp>
    [LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)]
     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/model/llama/llama_model.py", line 169, in __init__
    self.self_attn = LlamaAttention(config)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/model/llama/llama_model.py", line 139, in __init__
    config.num_key_value_heads % config.tensor_parallel_shards == 0
AssertionError: num_kv_heads(8) must be divisible by tensor_parallel_shards
Traceback (most recent call last):
  File "/root/anaconda3/envs/mlc-prebuilt/bin/mlc_llm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/__main__.py", line 49, in main
    cli.main(sys.argv[2:])
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/cli/serve.py", line 188, in main
    serve(
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/interface/serve.py", line 53, in serve
    async_engine = engine.AsyncMLCEngine(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/serve/engine.py", line 904, in __init__
    super().__init__(
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/serve/engine_base.py", line 589, in __init__
    ) = _process_model_args(models, device, engine_config)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/serve/engine_base.py", line 170, in _process_model_args
    model_args: List[Tuple[str, str]] = [_convert_model_info(model) for model in models]
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/serve/engine_base.py", line 170, in <listcomp>
    model_args: List[Tuple[str, str]] = [_convert_model_info(model) for model in models]
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/serve/engine_base.py", line 163, in _convert_model_info
    model_lib = jit.jit(
                ^^^^^^^^
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/interface/jit.py", line 164, in jit
    _run_jit(
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/interface/jit.py", line 124, in _run_jit
    raise RuntimeError("Cannot find compilation output, compilation failed")
RuntimeError: Cannot find compilation output, compilation failed
Exception ignored in: <function MLCEngineBase.__del__ at 0x712e6e182f20>
Traceback (most recent call last):
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/serve/engine_base.py", line 653, in __del__
    self.terminate()
  File "/root/anaconda3/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/serve/engine_base.py", line 660, in terminate
    self._ffi["exit_background_loop"]()
    ^^^^^^^^^
AttributeError: 'AsyncMLCEngine' object has no attribute '_ffi'

**Comment by loredunk** [comment]
how do you fix it?
