### ISSUE TITLE
[Question] Build on Android 32bit device 'armeabi-v7a' 

### ISSUE THREAD

**Issue by cjhelloviewing** [mlc-ai/mlc-llm#2864]
## ❓ General Questions

When checking the Android demo app and Build Android App from Source, only 'arm64-v8a' is supported.

I wonder if it is possible to build the 'mlc_llm package' a and the app so that it can run on the 'armeabi-v7a' Android device.

**Comment by Kaneki-x** [comment]
@cjhelloviewing maybe you can modify `-DANDROID_ABI=arm64-v8a` code in  '/android/mlc4j/prepare_libs.py' and try 'mlc_llm package' again

**Comment by cjhelloviewing** [comment]
@Kaneki-x Thank you. I changed it according to the information you provided and built it.
An error occurred during the build, so I contacted you to check if the build method was wrong.

Error 
`
...
error[E0463]: can't find crate for `core`
  |
  = note: the `armv7-linux-androideabi` target may not be installed
  = help: consider downloading the target with `rustup target add armv7-linux-androideabi`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `memchr` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `crossbeam-utils` (lib) due to 1 previous error
error: could not compile `libc` (lib) due to 1 previous error
...
`
->  rustup target add armv7-linux-androideabi
The above error was resolved with the following execution, but the following error occurred.

Error 
`
error occurred: Failed to find tool. Is `armv7-linux-androideabi24-clang` installed?

make: *** [tvm4j_runtime_packed] Error 2
Traceback (most recent call last):
  File "/Users/khkang80/zproject/mlc-llm/android/mlc4j/prepare_libs.py", line 120, in <module>
    main(parsed.mlc_llm_source_dir)
  File "/Users/khkang80/zproject/mlc-llm/android/mlc4j/prepare_libs.py", line 103, in main
    run_cmake_build()
  File "/Users/khkang80/zproject/mlc-llm/android/mlc4j/prepare_libs.py", line 66, in run_cmake_build
    subprocess.run(cmd, check=True, env=os.environ)
  File "/Users/khkang80/opt/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'tvm4j_runtime_packed', '--config', 'release', '-j10']' returned non-zero exit status 2.
Traceback (most recent call last):
  File "/Users/khkang80/opt/anaconda3/bin/mlc_llm", line 8, in <module>
    sys.exit(main())
  File "/Users/khkang80/opt/anaconda3/lib/python3.9/site-packages/mlc_llm/__main__.py", line 53, in main
    cli.main(sys.argv[2:])
  File "/Users/khkang80/opt/anaconda3/lib/python3.9/site-packages/mlc_llm/cli/package.py", line 64, in main
    package(
  File "/Users/khkang80/opt/anaconda3/lib/python3.9/site-packages/mlc_llm/interface/package.py", line 361, in package
    build_android_binding(mlc_llm_source_dir, output)
  File "/Users/khkang80/opt/anaconda3/lib/python3.9/site-packages/mlc_llm/interface/package.py", line 275, in build_android_binding
    subprocess.run([sys.executable, mlc4j_path / "prepare_libs.py"], check=True, env=os.environ)
  File "/Users/khkang80/opt/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/khkang80/opt/anaconda3/bin/python', PosixPath('/Users/khkang80/zproject/mlc-llm/android/mlc4j/prepare_libs.py')]' returned non-zero exit status 1.
`

When checking mlc-llm/3rdparty/tokenizers-cpp/CMakeLists.txt, it is as follows (line 45)
`
  elseif (ANDROID_ABI STREQUAL "armeabi-v7a")
    set(TOKENIZERS_CPP_CARGO_TARGET armv7-linux-androideabi)
`

There is no `armv7-linux-androideabi24-clang` in Android NDK (Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin).

I need help.

**Comment by Kaneki-x** [comment]
I think it should be an NDK-related configuration issue. You can check the following section to see if it needs to be adjusted to the corresponding clang, as well as other configurations related to NDK cross-compilation.
<img width="774" alt="Microsoft Edge 2024-09-02 23 10 21" src="https://github.com/user-attachments/assets/708135ec-df64-4bbc-bea4-83eefc44d248">

**Comment by cjhelloviewing** [comment]
@Kaneki-x  Thamks.
I tried 'mlc_llm package' by changing it as follows.

TVM_NDK_CC patch 
<img width="696" alt="스크린샷 2024-09-03 오전 11 16 37" src="https://github.com/user-attachments/assets/8ffd2a26-6059-4a47-b001-b5a66943e55a">
mlc-llm/android/mlc4j/prepare_libs.py 34line
<img width="307" alt="스크린샷 2024-09-03 오전 11 17 01" src="https://github.com/user-attachments/assets/05b6db0a-b4de-48d5-8208-f7417c779561">
mlc-llm/3rdparty/tokenizers-cpp/CMakeLists.txt 46line
<img width="495" alt="스크린샷 2024-09-03 오전 11 17 24" src="https://github.com/user-attachments/assets/284e906e-1347-424a-b343-b4a53a9ed787">

The following error occurs during build
----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
Consolidate compiler generated dependencies of target sentencepiece-static
Consolidate compiler generated dependencies of target mlc_llm_objs
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/Users/khkang80/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rustc - --crate-name ___ --print=file-names --target armv7a-linux-androideabi --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: Error loading target specification: Could not find specification for target "armv7a-linux-androideabi". Run `rustc --print target-list` for a list of built-in targets

Consolidate compiler generated dependencies of target tvm_runtime_objs
make[3]: *** [mlc_llm/tokenizers/armv7a-linux-androideabi/release/libtokenizers_c.a] Error 101
make[2]: *** [mlc_llm/tokenizers/CMakeFiles/tokenizers_c.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 37%] Built target sentencepiece-static
[ 62%] Built target mlc_llm_objs
[100%] Built target tvm_runtime_objs
make[1]: *** [CMakeFiles/tvm4j_runtime_packed.dir/rule] Error 2
make: *** [tvm4j_runtime_packed] Error 2
Traceback (most recent call last):
  File "/Users/khkang80/zproject/mlc-llm/android/mlc4j/prepare_libs.py", line 121, in <module>
    main(parsed.mlc_llm_source_dir)
  File "/Users/khkang80/zproject/mlc-llm/android/mlc4j/prepare_libs.py", line 104, in main
    run_cmake_build()
  File "/Users/khkang80/zproject/mlc-llm/android/mlc4j/prepare_libs.py", line 67, in run_cmake_build
    subprocess.run(cmd, check=True, env=os.environ)
  File "/Users/khkang80/opt/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'tvm4j_runtime_packed', '--config', 'release', '-j10']' returned non-zero exit status 2.
Traceback (most recent call last):
  File "/Users/khkang80/opt/anaconda3/bin/mlc_llm", line 8, in <module>
    sys.exit(main())
  File "/Users/khkang80/opt/anaconda3/lib/python3.9/site-packages/mlc_llm/__main__.py", line 53, in main
    cli.main(sys.argv[2:])
  File "/Users/khkang80/opt/anaconda3/lib/python3.9/site-packages/mlc_llm/cli/package.py", line 64, in main
    package(
  File "/Users/khkang80/opt/anaconda3/lib/python3.9/site-packages/mlc_llm/interface/package.py", line 361, in package
    build_android_binding(mlc_llm_source_dir, output)
  File "/Users/khkang80/opt/anaconda3/lib/python3.9/site-packages/mlc_llm/interface/package.py", line 275, in build_android_binding
    subprocess.run([sys.executable, mlc4j_path / "prepare_libs.py"], check=True, env=os.environ)
  File "/Users/khkang80/opt/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/khkang80/opt/anaconda3/bin/python', PosixPath('/Users/khkang80/zproject/mlc-llm/android/mlc4j/prepare_libs.py')]' returned non-zero exit status 1.
----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----

'rustc' is installed normally and can be run from cmd.

**Comment by cjhelloviewing** [comment]
@Kaneki-x 
I tried to build by changing NDK path and Clang name.
I got compatibility issue as below.
I am asking if you can help me.

--- --- --- --- --- 
1. TVM_NDK_CC="$ANDROID_NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7-linux-androideabi24-clang"
2. armv7a-linux-androideabi24-clang -> armv7-linux-androideabi24-clang
--- --- --- --- --- error --- --- --- --- --- 
[100%] Linking CXX shared library libtvm4j_runtime_packed.so
ld.lld: error: lib/libmodel_android.a(lib0.o) is incompatible with armelf_linux_eabi
ld.lld: error: lib/libmodel_android.a(phi3_q4f16_1_2a9ab7c8fc39c689e5b1983391f85ffd_devc.o) is incompatible with armelf_linux_eabi
ld.lld: error: lib/libmodel_android.a(qwen2_q4f16_1_2e221f430380225c03990ad24c3d030e_devc.o) is incompatible with armelf_linux_eabi
ld.lld: error: lib/libmodel_android.a(lib0.o) is incompatible with armelf_linux_eabi
ld.lld: error: lib/libmodel_android.a(gemma2_q4f16_1_5cc7dbd3ae3d1040984d9720b2d7b7d4_devc.o) is incompatible with armelf_linux_eabi
ld.lld: error: lib/libmodel_android.a(lib0.o) is incompatible with armelf_linux_eabi
ld.lld: error: lib/libmodel_android.a(llama_q3f16_1_25bcdc17395bc7aaad0b7f761dc55b85_devc.o) is incompatible with armelf_linux_eabi
ld.lld: error: lib/libmodel_android.a(lib0.o) is incompatible with armelf_linux_eabi
ld.lld: error: lib/libmodel_android.a(mistral_q4f16_1_c2cba77a6def4dd52f7e20b5d8576ab5_devc.o) is incompatible with armelf_linux_eabi
ld.lld: error: lib/libmodel_android.a(lib0.o) is incompatible with armelf_linux_eabi
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libtvm4j_runtime_packed.so] Error 1
make[2]: *** [CMakeFiles/tvm4j_runtime_packed.dir/all] Error 2
make[1]: *** [CMakeFiles/tvm4j_runtime_packed.dir/rule] Error 2
make: *** [tvm4j_runtime_packed] Error 2

**Comment by SwordFishKe** [comment]
> @Kaneki-x I tried to build by changing NDK path and Clang name. I got compatibility issue as below. I am asking if you can help me.
> 
> 1. TVM_NDK_CC="$ANDROID_NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7-linux-androideabi24-clang"
> 2. armv7a-linux-androideabi24-clang -> armv7-linux-androideabi24-clang
>    --- --- --- --- --- error --- --- --- --- ---
>    [100%] Linking CXX shared library libtvm4j_runtime_packed.so
>    ld.lld: error: lib/libmodel_android.a(lib0.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(phi3_q4f16_1_2a9ab7c8fc39c689e5b1983391f85ffd_devc.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(qwen2_q4f16_1_2e221f430380225c03990ad24c3d030e_devc.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(lib0.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(gemma2_q4f16_1_5cc7dbd3ae3d1040984d9720b2d7b7d4_devc.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(lib0.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(llama_q3f16_1_25bcdc17395bc7aaad0b7f761dc55b85_devc.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(lib0.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(mistral_q4f16_1_c2cba77a6def4dd52f7e20b5d8576ab5_devc.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(lib0.o) is incompatible with armelf_linux_eabi
>    clang++: error: linker command failed with exit code 1 (use -v to see invocation)
>    make[3]: *** [libtvm4j_runtime_packed.so] Error 1
>    make[2]: *** [CMakeFiles/tvm4j_runtime_packed.dir/all] Error 2
>    make[1]: *** [CMakeFiles/tvm4j_runtime_packed.dir/rule] Error 2
>    make: *** [tvm4j_runtime_packed] Error 2


i get the same error,  @cjhelloviewing Have you found a solution

**Comment by SwordFishKe** [comment]
mark

**Comment by BennyWang1007** [comment]
S

> [@Kaneki-x](https://github.com/Kaneki-x) I tried to build by changing NDK path and Clang name. I got compatibility issue as below. I am asking if you can help me.
> 
> 1. TVM_NDK_CC="$ANDROID_NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7-linux-androideabi24-clang"
> 2. armv7a-linux-androideabi24-clang -> armv7-linux-androideabi24-clang
>    --- --- --- --- --- error --- --- --- --- ---
>    [100%] Linking CXX shared library libtvm4j_runtime_packed.so
>    ld.lld: error: lib/libmodel_android.a(lib0.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(phi3_q4f16_1_2a9ab7c8fc39c689e5b1983391f85ffd_devc.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(qwen2_q4f16_1_2e221f430380225c03990ad24c3d030e_devc.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(lib0.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(gemma2_q4f16_1_5cc7dbd3ae3d1040984d9720b2d7b7d4_devc.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(lib0.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(llama_q3f16_1_25bcdc17395bc7aaad0b7f761dc55b85_devc.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(lib0.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(mistral_q4f16_1_c2cba77a6def4dd52f7e20b5d8576ab5_devc.o) is incompatible with armelf_linux_eabi
>    ld.lld: error: lib/libmodel_android.a(lib0.o) is incompatible with armelf_linux_eabi
>    clang++: error: linker command failed with exit code 1 (use -v to see invocation)
>    make[3]: *** [libtvm4j_runtime_packed.so] Error 1
>    make[2]: *** [CMakeFiles/tvm4j_runtime_packed.dir/all] Error 2
>    make[1]: *** [CMakeFiles/tvm4j_runtime_packed.dir/rule] Error 2
>    make: *** [tvm4j_runtime_packed] Error 2

Same here, waiting for a solution
