### ISSUE TITLE
[Bug] TVM installation fails on Windows machines

### ISSUE THREAD

**Issue by fabiomatricardi** [mlc-ai/mlc-llm#2870]
## 🐛 Bug

`OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed`

Tested also with conda... same issues

Followed installation process according to the documentation
OS Windows 11
PC: Lenovo Legion with 

## To Reproduce
Created venv with Python 3.11
installed
pip install clang zstd
pip install --pre -U -f https://mlc.ai/wheels mlc-ai-nightly

Run the test code to verify TVM installation
python -c "import tvm; print(tvm.__file__)"

results:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\llmMlc-test\venv\Lib\site-packages\tvm\__init__.py", line 26, in <module>
    from ._ffi.base import TVMError, __version__, _RUNTIME_ONLY
  File "D:\llmMlc-test\venv\Lib\site-packages\tvm\_ffi\__init__.py", line 28, in <module>
    from .base import register_error
  File "D:\llmMlc-test\venv\Lib\site-packages\tvm\_ffi\base.py", line 78, in <module>
    _LIB, _LIB_NAME = _load_lib()
                      ^^^^^^^^^^^
  File "D:\llmMlc-test\venv\Lib\site-packages\tvm\_ffi\base.py", line 64, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed
```

1.
1.
1.

## Environment

 - Platform: Vulkanand CUDA
 - Operating system: Windows 11
 - Device: Lenovo Legion with NVidia GeForce RTX 2060
 - How you installed MLC-LLM (`conda`, source): venv and pip
 - How you installed TVM-Unity (`pip`, source): venv and pip
 - Python version (e.g. 3.10):  3.11
 - GPU driver version (if applicable):  NVIDIA-SMI 560.76
 - CUDA/cuDNN version (if applicable): CUDA 12.6
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.76                 Driver Version: 560.76         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   37C    P0             18W /   65W |       0MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

**Comment by AMKCode** [comment]
Hi, we tried reproducing it on a Windows 11 machine with CUDA 12.6 (RTX 3050 Ti) and we couldn't reproduce the bug. We don't yet support CUDA for Windows.

**Comment by MasterJH5574** [comment]
MLC works through Vulkan on Windows for now, so it's likely not a CUDA issue here. It might be some other issue causing the library load failure.
