### ISSUE TITLE
[Question] OSError: libnvrtc.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by 545771889a** [mlc-ai/mlc-llm#2888]
when i try to run script in pycharm, i got an error OSError: libnvrtc.so.12: cannot open shared object file: No such file or directory,but when i run script in terminal, it worked. why?
here is my script:

from mlc_llm import MLCEngine
from mlc_llm.serve.config import EngineConfig

# Create engine
model = "/home/energize/myfile/llama-70b/llama-recipes/model/llama3-70b_mlc"
engine = MLCEngine(
    model,
    engine_config=EngineConfig(tensor_parallel_shards=2),
)

# Run chat completion in OpenAI API.
for response in engine.chat.completions.create(
    messages=[{"role": "user", "content": "What is the meaning of life?"}],
    model=model,
    stream=True,
):
    for choice in response.choices:
        print(choice.delta.content, end="", flush=True)
print("\n")

engine.terminate()

Traceback (most recent call last):
  File "/home/energize/myfile/llama-70b/llama-recipes/recipes/quickstart/inference/local_inference/my_inference.py", line 1, in <module>
    from mlc_llm import MLCEngine
  File "/home/energize/myfile/python_env/mlc-llm/lib/python3.12/site-packages/mlc_llm/__init__.py", line 6, in <module>
    from tvm import register_func
  File "/home/energize/myfile/python_env/mlc-llm/lib/python3.12/site-packages/tvm/__init__.py", line 26, in <module>
    from ._ffi.base import TVMError, __version__, _RUNTIME_ONLY
  File "/home/energize/myfile/python_env/mlc-llm/lib/python3.12/site-packages/tvm/_ffi/__init__.py", line 28, in <module>
    from .base import register_error
  File "/home/energize/myfile/python_env/mlc-llm/lib/python3.12/site-packages/tvm/_ffi/base.py", line 78, in <module>
    _LIB, _LIB_NAME = _load_lib()
                      ^^^^^^^^^^^
  File "/home/energize/myfile/python_env/mlc-llm/lib/python3.12/site-packages/tvm/_ffi/base.py", line 64, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/energize/miniconda3/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libnvrtc.so.12: cannot open shared object file: No such file or directory

Process finished with exit code 1

**Comment by MasterJH5574** [comment]
`libnvrtc.so` is the runtime compilation library for CUDA C++. I guess it might be that PyCharm's library load configuration does not include the directory where this library is in, and thus it is not loaded when you run mlc. You may want to check PyCharm for related issues.
