### ISSUE TITLE
[Question] InternalError: Check failed: type_code_ == kTVMPackedFuncHandle (0 vs. 10) : expected FunctionHandle but got int

### ISSUE THREAD

**Issue by JustANoob903** [mlc-ai/mlc-llm#2889]
## ❓ General Questions

Hello, I have followed the instructions to install OpenCL, MLCLM, TVM-Unity, and other dependencies, but when I tried to run mlc_LLm chat Llama-7b-chat-hf-q4f16_1, it reported an error :  

> InternalError: Check failed: type_code_ == kTVMPackedFuncHandle (0 vs. 10) : expected FunctionHandle but got int

How can I fix it？

**Comment by JustANoob903** [comment]
i run it on orangepi

**Comment by MasterJH5574** [comment]
Please check related issues https://github.com/mlc-ai/mlc-llm/issues/2882, https://github.com/mlc-ai/mlc-llm/issues/2884.

**Comment by JustANoob903** [comment]
> Please check related issues #2882, #2884.

hello.I have pulled the latest source code and rebuilt it,but this issue still exists.Here is the detailed error message:

```
  File "/home/orangepi/tvm_unity/src/runtime/relax_vm/paged_kv_cache.cc", line 2683, in operator()
    PackedFunc f_attention_prefill_with_tree_mask_paged_kv = args[21];
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
tvm.error.InternalError: Traceback (most recent call last):
  12: mlc::llm::serve::ThreadedEngineImpl::RunBackgroundLoop()
        at /home/orangepi/mlc-llm/cpp/serve/threaded_engine.cc:169
  11: mlc::llm::serve::ThreadedEngineImpl::EngineReloadImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
        at /home/orangepi/mlc-llm/cpp/serve/threaded_engine.cc:282
  10: mlc::llm::serve::Engine::Create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DLDevice, tvm::runtime::TypedPackedFunc<void (tvm::runtime::Array<mlc::llm::serve::RequestStreamOutput, void>)>, tvm::runtime::Optional<mlc::llm::serve::EventTraceRecorder>)
        at /home/orangepi/mlc-llm/cpp/serve/engine.cc:913
  9: mlc::llm::serve::EngineImpl::Create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DLDevice, tvm::runtime::TypedPackedFunc<void (tvm::runtime::Array<mlc::llm::serve::RequestStreamOutput, void>)>, tvm::runtime::Optional<mlc::llm::serve::EventTraceRecorder>)
        at /home/orangepi/mlc-llm/cpp/serve/engine.cc:376
  8: mlc::llm::serve::ModelImpl::CreateKVCache(int, int, long, long, int)
        at /home/orangepi/mlc-llm/cpp/serve/model.cc:692
  7: operator()
        at /home/orangepi/tvm_unity/src/runtime/relax_vm/vm.cc:978
  6: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
        at /home/orangepi/tvm_unity/src/runtime/relax_vm/vm.cc:558
  5: operator()
        at /home/orangepi/tvm_unity/src/runtime/relax_vm/vm.cc:632
  4: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
        at /home/orangepi/tvm_unity/src/runtime/relax_vm/vm.cc:703
  3: tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
        at /home/orangepi/tvm_unity/src/runtime/relax_vm/vm.cc:828
  2: tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
        at /home/orangepi/tvm_unity/src/runtime/relax_vm/vm.cc:781
  1: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
        at /home/orangepi/tvm_unity/src/runtime/relax_vm/vm.cc:540
  0: operator()
        at /home/orangepi/tvm_unity/src/runtime/relax_vm/paged_kv_cache.cc:2683
  File "/home/orangepi/tvm_unity/include/tvm/runtime/packed_func.h", line 649
InternalError: Check failed: type_code_ == kTVMPackedFuncHandle (0 vs. 10) : expected FunctionHandle but got int
```
