### ISSUE TITLE
[Question] running on wsl2?

### ISSUE THREAD

**Issue by BlindDeveloper** [mlc-ai/mlc-llm#2893]
Hello, how to run mlc llm on wsl2 using cpu?
I was try mlc_llmchatHF://mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC
But get error.
 Please provide me with a command that I can copy the error text with my mouse or arrow keys, I can't do that because I'm using a screen reader.

**Comment by puzzle9** [comment]
use gpu is ok
cpu have error

```
(ai) ➜  mlc-ai python -c "import tvm; print(tvm.__file__)"
/opt/conda/envs/ai/lib/python3.12/site-packages/tvm/__init__.py
(ai) ➜  mlc-ai mlc_llm chat HF://mlc-ai/Phi-3.5-mini-instruct-q4f16_1-MLC
[2024-09-11 19:56:10] INFO auto_device.py:88: Not found device: cuda:0
[2024-09-11 19:56:11] INFO auto_device.py:88: Not found device: rocm:0
[2024-09-11 19:56:12] INFO auto_device.py:88: Not found device: metal:0
[2024-09-11 19:56:14] INFO auto_device.py:88: Not found device: vulkan:0
[2024-09-11 19:56:15] INFO auto_device.py:88: Not found device: opencl:0
[2024-09-11 19:56:15] INFO auto_device.py:33: Not found: No available device detected
Traceback (most recent call last):
  File "/opt/conda/envs/ai/bin/mlc_llm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/ai/lib/python3.12/site-packages/mlc_llm/__main__.py", line 45, in main
    cli.main(sys.argv[2:])
  File "/opt/conda/envs/ai/lib/python3.12/site-packages/mlc_llm/cli/chat.py", line 36, in main
    chat(
  File "/opt/conda/envs/ai/lib/python3.12/site-packages/mlc_llm/interface/chat.py", line 285, in chat
    JSONFFIEngine(
  File "/opt/conda/envs/ai/lib/python3.12/site-packages/mlc_llm/json_ffi/engine.py", line 231, in __init__
    assert isinstance(device, tvm.runtime.Device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by BlindDeveloper** [comment]
@puzzle9  could you provide command for running on gpu?

**Comment by BlindDeveloper** [comment]
@puzzle9  
Today tryed run on windows, and get error, looks like package isn't executable.
If you have intel integrated videocard, could you test on it?

**Comment by puzzle9** [comment]
> @puzzle9 Today tryed run on windows, and get error, looks like package isn't executable. If you have intel integrated videocard, could you test on it?

Sorry, I don't have an Intel graphics card
