### ISSUE TITLE
Problems encountered while doing Android SDK

### ISSUE THREAD

**Issue by whyshifht** [mlc-ai/mlc-llm#2986]
When I was building the Android SDK according to the official documentation, the 'mlc_llm package' command had difficulty downloading the model and always timed out for the connection, hoping to get some help:[2024-10-18 13:02:37] INFO download_cache.py:56: [Git] Cloning https://huggingface.co/mlc-ai/Phi-3.5-mini-instruct-q4f16_0-MLC.git to /tmp/tmpq5b54u16/tmp
Traceback (most recent call last):
  File "/home/root2/conda2/envs/mlc-prebuilt/lib/python3.11/site-packages/mlc_llm/support/download_cache.py", line 57, in git_clone
    subprocess.run(
  File "/home/root2/conda2/envs/mlc-prebuilt/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'clone', 'https://huggingface.co/mlc-ai/Phi-3.5-mini-instruct-q4f16_0-MLC.git', '.tmp']' returned non-zero exit status 128.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/root2/conda2/envs/mlc-prebuilt/bin/mlc_llm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/root2/conda2/envs/mlc-prebuilt/lib/py

**Comment by nihalgeorge01** [comment]
Hi, looks like the git clone seems to fail, but I can't reproduce this on our end
Could you try separately (in any directory, just to test the git clone) the following and see if it works? 
```
$ git clone https://huggingface.co/mlc-ai/Phi-3.5-mini-instruct-q4f16_0-MLC.git
```

**Comment by Lanssi** [comment]
@whyshifht Hi! Did you open the proxy for the network problem? Or mayby you can change the proxy node? Or maybe you can try the huggingface mirror and use the following instruction `HF_ENDPOINT=https://hf-mirror.com mlc_llm package` instead of `mlc_llm package`.
