### ISSUE TITLE
[Bug] Sending images with large dimensions into vision models will break TVM

### ISSUE THREAD

**Issue by Neet-Nestor** [mlc-ai/mlc-llm#3044]
## 🐛 Bug

When I send images with large dimensions into the engine, it throws error from TVM. For example, I'm using Phi-3.5-vision-instruct models:

1. an image of size 4030x2707:
```
/Users/neet/code/mlc-llm/3rdparty/tvm/src/runtime/ndarray.cc:213: Check failed: relative_byte_offset + view_size <= curr_size (32727630 vs. 518400) : ValueError: View with shape [1, 2707, 4030, 3] and datatype uint8 would have a size of 32727630 bytes.  This would occupy bytes 0 <= i_byte < 32727630 within the backing array.  However, the NDArray being viewed only contains 518400 bytes (shape = [1, 360, 480, 3], dtype= uint8).
```
 
2. an image of size 2166x1700:
```
libc++abi: terminating due to uncaught exception of type tvm::runtime::InternalError: [23:07:43] /Users/neet/code/mlc-llm/3rdparty/tvm/src/runtime/ndarray.cc:213: Check failed: relative_byte_offset + view_size <= curr_size (11046600 vs. 1017846) : ValueError: View with shape [1, 1700, 2166, 3] and datatype uint8 would have a size of 11046600 bytes.  This would occupy bytes 0 <= i_byte < 11046600 within the backing array.  However, the NDArray being viewed only contains 1017846 bytes (shape = [1, 618, 549, 3], dtype= uint8).
```

## To Reproduce

1. Send images in large dimensions to the backend in base64 format via `jsonFFIEngine.chatCompletion(jsonRequest, requestID: requestID)` 

## Expected behavior

The engine should not throw errors.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): iOS app through the SDK
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): MacOS
 - How you installed MLC-LLM (`conda`, source): yes
 - How you installed TVM-Unity (`pip`, source): yes

**Comment by Chris611** [comment]
I have the same issue on Ubuntu 24.04. Using openai API with mlc_llm serve of phi-3.5-vision.  Compiled from source

**Comment by Chris611** [comment]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 339, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 270, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 259, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 185, in tvm._ffi._cy3.core.CHECK_CALL
  File "/home/chris/AI/mlc-llm-cuda/lib/python3.12/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/workspace/mlc-llm/cpp/serve/threaded_engine.cc", line 182, in mlc::llm::serve::ThreadedEngineImpl::RunBackgroundLoop()
  File "/workspace/mlc-llm/cpp/serve/engine.cc", line 594, in mlc::llm::serve::EngineImpl::Step()
  File "/workspace/mlc-llm/cpp/serve/engine_actions/new_request_prefill.cc", line 119, in mlc::llm::serve::NewRequestPrefillActionObj::Step(mlc::llm::serve::EngineState)
  File "/workspace/mlc-llm/cpp/serve/data.cc", line 96, in mlc::llm::serve::ImageDataNode::GetEmbedding(mlc::llm::serve::Model, tvm::runtime::ObjectRef*, int) const
  File "/workspace/mlc-llm/cpp/serve/model.cc", line 116, in mlc::llm::serve::ModelImpl::ImageEmbed(tvm::runtime::NDArray const&, tvm::runtime::ObjectRef*, int)
  File "/workspace/mlc-llm/cpp/serve/function_table.cc", line 320, in mlc::llm::serve::FunctionTable::CopyToWorker0(tvm::runtime::NDArray const&, tvm::runtime::String, tvm::runtime::ShapeTuple, bool)
ValueError: Traceback (most recent call last):
  7: mlc::llm::serve::ThreadedEngineImpl::RunBackgroundLoop()
        at /workspace/mlc-llm/cpp/serve/threaded_engine.cc:182
  6: mlc::llm::serve::EngineImpl::Step()
        at /workspace/mlc-llm/cpp/serve/engine.cc:594
  5: mlc::llm::serve::NewRequestPrefillActionObj::Step(mlc::llm::serve::EngineState)
        at /workspace/mlc-llm/cpp/serve/engine_actions/new_request_prefill.cc:119
  4: mlc::llm::serve::ImageDataNode::GetEmbedding(mlc::llm::serve::Model, tvm::runtime::ObjectRef*, int) const
        at /workspace/mlc-llm/cpp/serve/data.cc:96
  3: mlc::llm::serve::ModelImpl::ImageEmbed(tvm::runtime::NDArray const&, tvm::runtime::ObjectRef*, int)
        at /workspace/mlc-llm/cpp/serve/model.cc:116
  2: mlc::llm::serve::FunctionTable::CopyToWorker0(tvm::runtime::NDArray const&, tvm::runtime::String, tvm::runtime::ShapeTuple, bool)
        at /workspace/mlc-llm/cpp/serve/function_table.cc:320
  1: tvm::runtime::NDArray::CreateView(tvm::runtime::ShapeTuple, DLDataType, unsigned long)
  0: _ZN3tvm7runtime6deta
  File "/workspace/tvm/src/runtime/ndarray.cc", line 213
ValueError: Check failed: relative_byte_offset + view_size <= curr_size (4320000 vs. 2260800) : View with shape [1, 1200, 1200, 3] and datatype uint8 would have a size of 4320000 bytes.  This would occupy bytes 0 <= i_byte < 4320000 within the backing array.  However, the NDArray being viewed only contains 2260800 bytes (shape = [1, 628, 1200, 3], dtype= uint8).

```

**Comment by Chris611** [comment]
And it only goes wrong if the second image is larger than the first image.

**Comment by mengshyu** [comment]
Hi @Neet-Nestor and @Chris611 , I fixed it in #3082 , could you try it again, thanks.
