### ISSUE TITLE
[Bug] Phi-3 model compile error

### ISSUE THREAD

**Issue by arashno** [mlc-ai/mlc-llm#3076]
## 🐛 Bug

Here is the error when I try to compile the phi-3 model:

> (mlcllm) [oan1pi@rng-dl01-w018:/fs/scratch/rb_bd_dlp_rng-dl01_cr_AIM_employees/oan1pi] $  cd /fs/scratch/rb_bd_dlp_rng-dl01_cr_AIM_employees/oan1pi ; /usr/bin/env /home/oan1pi/.conda/envs/mlcllm/bin/python /home/oan1pi/.vscode-server/extensions/ms-python.debugpy-2024.14.0/bundled/libs/debugpy/adapter/../../debugpy/launcher 35655 -- /fs/scratch/rb_bd_dlp_rng-dl01_cr_AIM_employees/oan1pi/mlcllm_conversion/compile.py mlcllm_conversion/Phi-3-mini-4k-instruct/config.json -o compiled --quantization q4f16_1 
> flashinfer is not supported on CUDA arch < 80
> Compiling with arguments:
>   --config          Phi3Config(model_type='phi3', hidden_size=3072, vocab_size=32064, num_hidden_layers=32, num_attention_heads=32, intermediate_size=8192, rms_norm_eps=1e-05, num_key_value_heads=32, max_position_embeddings=4096, position_embedding_base=10000.0, rope_scaling=None, original_max_position_embeddings=4096, context_window_size=4096, prefill_chunk_size=4096, head_dim=96, tensor_parallel_shards=1, max_batch_size=1, kwargs={})
>   --quantization    GroupQuantize(name='q4f16_1', kind='group-quant', group_size=32, quantize_dtype='int4', storage_dtype='uint32', model_dtype='float16', linear_weight_layout='NK', quantize_embedding=True, quantize_final_fc=True, num_elem_per_storage=8, num_storage_per_group=4, max_int_value=7, tensor_parallel_shards=0)
>   --model-type      phi3
>   --target          {"thread_warp_size": runtime.BoxInt(32), "host": {"mtriple": "x86_64-redhat-linux-gnu", "tag": "", "kind": "llvm", "mcpu": "skylake-avx512", "keys": ["cpu"]}, "arch": "sm_70", "max_threads_per_block": runtime.BoxInt(1024), "libs": ["thrust"], "max_num_threads": runtime.BoxInt(1024), "kind": "cuda", "max_shared_memory_per_block": runtime.BoxInt(49152), "tag": "", "keys": ["cuda", "gpu"]}
>   --opt             flashinfer=0;cublas_gemm=0;faster_transformer=0;cudagraph=1;cutlass=1;ipc_allreduce_strategy=AUTO
>   --system-lib-prefix ""
>   --output          compiled
>   --overrides       context_window_size=None;sliding_window_size=None;prefill_chunk_size=None;attention_sink_size=None;max_batch_size=None;tensor_parallel_shards=None;pipeline_parallel_stages=None;disaggregation=None
> Unknown output suffix: . Assuming shared library.
> Traceback (most recent call last):
>   File "/home/oan1pi/.conda/envs/mlcllm/lib/python3.11/runpy.py", line 198, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/oan1pi/.conda/envs/mlcllm/lib/python3.11/runpy.py", line 88, in _run_code
>     exec(code, run_globals)
>   File "/home/oan1pi/.vscode-server/extensions/ms-python.debugpy-2024.14.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
>     cli.main()
>   File "/home/oan1pi/.vscode-server/extensions/ms-python.debugpy-2024.14.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
>     run()
>   File "/home/oan1pi/.vscode-server/extensions/ms-python.debugpy-2024.14.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
>     runpy.run_path(target, run_name="__main__")
>   File "/home/oan1pi/.vscode-server/extensions/ms-python.debugpy-2024.14.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
>     return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/oan1pi/.vscode-server/extensions/ms-python.debugpy-2024.14.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
>     _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
>   File "/home/oan1pi/.vscode-server/extensions/ms-python.debugpy-2024.14.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
>     exec(code, run_globals)
>   File "/fs/scratch/rb_bd_dlp_rng-dl01_cr_AIM_employees/oan1pi/mlcllm_conversion/compile.py", line 142, in <module>
>     main()
>   File "/fs/scratch/rb_bd_dlp_rng-dl01_cr_AIM_employees/oan1pi/mlcllm_conversion/compile.py", line 129, in main
>     compile(
>   File "/home/oan1pi/.conda/envs/mlcllm/lib/python3.11/site-packages/mlc_llm/interface/compile.py", line 244, in compile
>     _compile(args, model_config)
>   File "/home/oan1pi/.conda/envs/mlcllm/lib/python3.11/site-packages/mlc_llm/interface/compile.py", line 189, in _compile
>     args.build_func(
>   File "/home/oan1pi/.conda/envs/mlcllm/lib/python3.11/site-packages/mlc_llm/support/auto_target.py", line 301, in build
>     relax.build(
>   File "/home/oan1pi/.conda/envs/mlcllm/lib/python3.11/site-packages/tvm/relax/vm_build.py", line 347, in build
>     mod = pipeline(mod)
>           ^^^^^^^^^^^^^
>   File "/home/oan1pi/.conda/envs/mlcllm/lib/python3.11/site-packages/tvm/ir/transform.py", line 238, in __call__
>     return _ffi_transform_api.RunPass(self, mod)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "tvm/_ffi/_cython/./packed_func.pxi", line 339, in tvm._ffi._cy3.core.PackedFuncBase.__call__
>   File "tvm/_ffi/_cython/./packed_func.pxi", line 270, in tvm._ffi._cy3.core.FuncCall
>   File "tvm/_ffi/_cython/./packed_func.pxi", line 259, in tvm._ffi._cy3.core.FuncCall3
>   File "tvm/_ffi/_cython/./base.pxi", line 185, in tvm._ffi._cy3.core.CHECK_CALL
>   File "/home/oan1pi/.conda/envs/mlcllm/lib/python3.11/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
>     raise py_err
>   File "tvm/_ffi/_cython/./packed_func.pxi", line 56, in tvm._ffi._cy3.core.tvm_callback
>   File "/home/oan1pi/.conda/envs/mlcllm/lib/python3.11/site-packages/mlc_llm/compiler_pass/pipeline.py", line 188, in _pipeline
>     mod = seq(mod)
>           ^^^^^^^^
>   File "/home/oan1pi/.conda/envs/mlcllm/lib/python3.11/site-packages/tvm/ir/transform.py", line 238, in __call__
>     return _ffi_transform_api.RunPass(self, mod)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "tvm/_ffi/_cython/./packed_func.pxi", line 339, in tvm._ffi._cy3.core.PackedFuncBase.__call__
>   File "tvm/_ffi/_cython/./packed_func.pxi", line 270, in tvm._ffi._cy3.core.FuncCall
>   File "tvm/_ffi/_cython/./packed_func.pxi", line 259, in tvm._ffi._cy3.core.FuncCall3
>   File "tvm/_ffi/_cython/./base.pxi", line 185, in tvm._ffi._cy3.core.CHECK_CALL
>   File "tvm/_ffi/_cython/./packed_func.pxi", line 56, in tvm._ffi._cy3.core.tvm_callback
>   File "/home/oan1pi/.conda/envs/mlcllm/lib/python3.11/site-packages/tvm/ir/transform.py", line 307, in _pass_func
>     return inst.transform_module(mod, ctx)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/oan1pi/.conda/envs/mlcllm/lib/python3.11/site-packages/mlc_llm/compiler_pass/dispatch_kv_cache_creation.py", line 108, in transform_module
>     self.create_tir_paged_kv_cache(bb, kwargs)
>   File "/home/oan1pi/.conda/envs/mlcllm/lib/python3.11/site-packages/mlc_llm/compiler_pass/dispatch_kv_cache_creation.py", line 147, in create_tir_paged_kv_cache
>     cache = kv_cache.TIRPagedKVCache(target=self.target, **kwargs)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: TIRPagedKVCache.__init__() got an unexpected keyword argument 'enable_disaggregation'
> [00:43:10] /workspace/tvm/src/relax/ir/block_builder.cc:65: Warning: BlockBuilder destroyed with remaining blocks!
> 

## To Reproduce

1. I downloaded the phi-3 model from https://huggingface.co/microsoft/Phi-3-mini-4k-instruct
2- I ran `mlc_llm compile Phi-3-mini-4k-instruct -o compiled --quantization q4f16_1`

## Expected behavior

As far as I know, mlc_llm supports phi-3 model and the model I downloaded is the standard phi-3 model.
So, I expect the above instruction works without any issue.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Linux Fedora
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): CPU
 - How you installed MLC-LLM (`conda`, source): pip
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10): 3.11.11
 - GPU driver version (if applicable): 560.35.03 
 - CUDA/cuDNN version (if applicable): 12.4.0
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 -USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
TVM_DEBUG_WITH_ABI_CHANGE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU: 
CUDA_VERSION: 12.3
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_OPENCL_EXTN_QCOM: NOT-FOUND
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_THRUST: ON
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: 
USE_OPENCL_GTEST: /path/to/opencl/gtest
TVM_LOG_BEFORE_THROW: OFF
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_MSCCL: OFF
USE_NNAPI_RUNTIME: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --ignore-libllvm --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: ON
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: fb765b633bc0d208d406a134df32c957760a5241
USE_VULKAN: ON
USE_RUST_EXT: OFF
USE_CUTLASS: ON
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2024-12-15 07:25:01 -0500
USE_HIPBLAS: OFF
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: ON
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 18.1.8
USE_MRVL: OFF
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
USE_NNAPI_CODEGEN: OFF
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: OFF
USE_BNNS: OFF
USE_FLASHINFER: ON
USE_CUBLAS: ON
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_NVSHMEM: /workspace/nvshmem
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION: 
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /opt/rh/gcc-toolset-11/root/usr/bin/c++
HIDE_PRIVATE_SYMBOLS: ON
 - Any other relevant information:

**Comment by arashno** [comment]
The issue occurred because I was using the nightly version of MLC LLM while having the stable version of the MLC-AI package installed. This caused the problem. After reinstalling the nightly version of the MLC-AI package, everything works fine now.
