### ISSUE TITLE
 android apk crashed 

### ISSUE THREAD

**Issue by yyr2011** [mlc-ai/mlc-llm#308]
Android MLCChat crashed on start

---  error message:

FATAL EXCEPTION: pool-2-thread-1
Process: ai.mlc.mlcchat, PID: 4697
java.lang.RuntimeException: java.io.FileNotFoundException: https://huggingface.co/mlc-ai/demo-vicuna-v1-7b-int4/resolve/main/float16/params_shard_7.bin
	at ai.mlc.mlcchat.Downloader.lambda$download$0$ai-mlc-mlcchat-Downloader(Downloader.java:98)

--- apk file :

https://github.com/mlc-ai/binary-mlc-llm-libs/raw/main/mlc-chat.apk

**Comment by tobrun** [comment]
Same for me, underling reason is that the files got moved from:
 
- https://huggingface.co/mlc-ai/demo-vicuna-v1-7b-int4/resolve/main/float16/params_shard_7.bin

to 

- https://huggingface.co/mlc-ai/demo-vicuna-v1-7b-int4/resolve/main/params_shard_7.bin

Through this commit:
 - https://huggingface.co/mlc-ai/demo-vicuna-v1-7b-int4/commit/6ed41fe48c0979b7c1951885de21dcd93c1cddb1

**Comment by Ricardo-Riley** [comment]
now have new version apk  ， https://github.com/mlc-ai/binary-mlc-llm-libs/raw/main/mlc-chat.apk   	33.3 MB (35,003,075 字节)，can you run ？

**Comment by joooogle** [comment]
it didn't work on my device too. runtime exception log :
FATAL EXCEPTION: main
                                                                                                    Process: ai.mlc.mlcchat, PID: 18049
                                                                                                    java.lang.IllegalArgumentException: Failed requirement.
                                                                                                    	at ai.mlc.mlcchat.AppViewModel$ChatState.requestReloadChat(AppViewModel.kt:401)
                                                                                                    	at ai.mlc.mlcchat.AppViewModel$ModelState.startChat(AppViewModel.kt:337)
                                                                                                    	at ai.mlc.mlcchat.StartViewKt$ModelView$1$1$3.invoke(StartView.kt:191)
                                                                                                    	at ai.mlc.mlcchat.StartViewKt$ModelView$1$1$3.invoke(StartView.kt:189)
                                                                                                    	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke-k-4lQ0M(Clickable.kt:167)
                                                                                                    	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke(Clickable.kt:156)
                                                                                                    	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:566)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:456)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:469)
                                                                                                    	at androidx.compose.ui.node.BackwardsCompatNode.onPointerEvent-H0pRuoY(BackwardsCompatNode.kt:374)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:314)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
                                                                                                    	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:183)
                                                                                                    	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:102)
                                                                                                    	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:98)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1361)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1307)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1246)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3326)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2987)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3326)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2987)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3326)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2987)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3326)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2987)
                                                                                                    	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:846)
                                                                                                    	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:2065)
2023-06-09 12:26:50.092 18049-18049 AndroidRuntime          ai.mlc.mlcchat                       E  	at android.app.Activity.dispatchTouchEvent(Activity.java:4388)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:771)
                                                                                                    	at android.view.View.dispatchPointerEvent(View.java:15112)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7915)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7649)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7043)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7100)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7066)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7248)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7074)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7305)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7047)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7100)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7066)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7074)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7047)
                                                                                                    	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10482)
                                                                                                    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10384)
                                                                                                    	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10337)
                                                                                                    	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10729)
                                                                                                    	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:310)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:374)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:163)
                                                                                                    	at android.os.Looper.loop(Looper.java:293)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9596)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)

**Comment by remixer-dec** [comment]
Just tried the fresh apk, RedPajama works great, but Vicuna crashes 
<summary>log</summary>
<details><pre>
ABI: 'arm64'
Timestamp: 2023-06-12 01:50:02+0400
pid: 26662, tid: 26764, name: pool-2-thread-1  >>> ai.mlc.mlcchat <<<
uid: 10596
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'terminating with uncaught exception of type tvm::runtime::InternalError: [01:50:01] /Users/houbohan/relax/include/tvm/runtime/device_api.h:291: unknown type =0
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.
'
    x0  0000000000000000  x1  000000000000688c  x2  0000000000000006  x3  0000007d6d671870
    x4  fefefefefefeff09  x5  fefefefefefeff09  x6  fefefefefefeff09  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  c665a0e21aefbced  x10 0000000000000000  x11 ffffffc0fffffbdf
    x12 0000000000000001  x13 0000000064864189  x14 00377aeb392731f5  x15 00007ea81ce9db27
    x16 0000007e624c9948  x17 0000007e624a8390  x18 0000000000007d00  x19 0000000000006826
    x20 000000000000688c  x21 00000000ffffffff  x22 0000007d6d6719a0  x23 0000007d6d6719e0
    x24 0000007d6d671ac0  x25 0000007d6d671a08  x26 0000000000000000  x27 0000000000000004
    x28 0000007d6f1ef6e1  x29 0000007d6d6718f0
    lr  0000007e6245baa0  sp  0000007d6d671850  pc  0000007e6245bacc  pst 0000000000000000

backtrace:
      #00 pc 0000000000089acc  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: a790cdbd8e44ea8a90802da343cb82ce)
      #01 pc 00000000016b9368  /data/app/~~VMVJl0btAI7T28_fNb6RwQ==/ai.mlc.mlcchat-I8wnJvwadB5qFBVlW-4ocA==/base.apk!libtvm4j_runtime_packed.so (offset 0x936000) (BuildId: 38facf65d1453768160efa5c7c703882086c0887)

</pre></details>

**Comment by cyx-6** [comment]
Sorry for replying late. Please try new [apk](https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/mlc-chat.apk). And vicuna has been deprecated.
