### ISSUE TITLE
[Bug] Model compilation via "build.py" fails with "cannot import name 'contrib' from partially initialized module 'tvm.relax.backend'"

### ISSUE THREAD

**Issue by pgagarinov** [mlc-ai/mlc-llm#311]
## 🐛 Bug

I tried to run the example from https://github.com/mlc-ai/mlc-llm#hugging-face-url but it failed with the following error
```
❯ python build.py --hf-path=databricks/dolly-v2-3b
Traceback (most recent call last):
  File "/Users/peter/_Git/_GPT/mlc-llm/build.py", line 10, in <module>
    from tvm import relax
  File "/Users/peter/micromamba/envs/mlc-llm-env/lib/python3.11/site-packages/tvm/relax/__init__.py", line 98, in <module>
    from . import backend
  File "/Users/peter/micromamba/envs/mlc-llm-env/lib/python3.11/site-packages/tvm/relax/backend/__init__.py", line 19, in <module>
    from . import contrib
ImportError: cannot import name 'contrib' from partially initialized module 'tvm.relax.backend' (most likely due to a circular import) (/Users/peter/micromamba/envs/mlc-llm-env/lib/python3.11/site-packages/tvm/relax/backend/__init__.py)
```

## To Reproduce

```
# Create a new conda environment and install dependencies
conda create -n mlc-llm-env python
conda activate mlc-llm-env
pip install torch transformers # Install PyTorch and Hugging Face transformers
pip install -I mlc_ai_nightly -f https://mlc.ai/wheels # Install TVM

# Install Git and Git-LFS if you haven't already.
# They are used for downloading the model weights from Hugging Face.
conda install git git-lfs
git lfs install

# Clone the MLC LLM repo
git clone --recursive https://github.com/mlc-ai/mlc-llm.git
cd mlc-llm

# Create the local build directory and compile the model
# This will automatically download the parameters, tokenizer, and config from Hugging Face
python build.py --hf-path=databricks/dolly-v2-3b
```

## Expected behavior

I expected that the model becomes available at  `dist/dolly-v2-3b-q3f16_0`

## Environment

 - Platform: Apple M2 Max, Metal
 - Operating system: MacOs Venturan 13.4
 - Device: Macbook Pro 16 M2 Max 32GB
 - How you installed MLC-LLM (`conda`, source) : `git clone --recursive https://github.com/mlc-ai/mlc-llm.git`
 - How you installed TVM-Unity (`pip`, source): `pip install -I mlc_ai_nightly -f https://mlc.ai/wheels`
 - Python version: `3.11`
 - GPU driver version (if applicable): 
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
```
USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
CUDA_VERSION: NOT-FOUND
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM:
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_LLVM: llvm-config --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: b67c0eaa74919de719fc6a6c2ae774c0cf403d20
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2023-06-03 00:14:52 -0700
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: ON
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 15.0.7
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: OFF
USE_BNNS: OFF
USE_CUBLAS: OFF
USE_METAL: ON
USE_MICRO_STANDALONE_RUNTIME: ON
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: ON
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION:
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /Library/Developer/CommandLineTools/usr/bin/c++
HIDE_PRIVATE_SYMBOLS: ON
```
 - Any other relevant information:

**Comment by lorentz-wu** [comment]
I have same problem

**Comment by gowthaml15** [comment]
I am also facing this problem

**Comment by czczycz** [comment]
Same problem. There is no module `contrib` in `tvm.relax.backend`.

**Comment by Cursky** [comment]
Same problem,how to do?

**Comment by junrushao** [comment]
https://github.com/mlc-ai/relax/pull/244

**Comment by appleguy** [comment]
Any way to apply that fix locally? I encountered this problem as well. Was hoping to try out MPS performance on a M1 Max 64GB to decide whether to order the just-announced Mac Pro :)
