### ISSUE TITLE
[Bug] SyntaxError: invalid syntax！

### ISSUE THREAD

**Issue by sleepwalker2017** [mlc-ai/mlc-llm#313]
commit 0933e95ab062febc76cdee10530f0c9c6d098c67 (HEAD -> main, origin/main, origin/HEAD)

```
python tests/chat.py --local-id vicuna-v1-7b-q3f16_0
Traceback (most recent call last):
  File "tests/chat.py", line 14, in <module>
    from mlc_llm.conversation import SeparatorStyle, compute_skip_echo_len, conv_templates
  File "/data/codes/mlc-llm/mlc_llm/conversation.py", line 351
    conv_templates = {
    ^
SyntaxError: invalid syntax
```

**Comment by junrushao** [comment]
`tests/chat.py` is legacy code that we should get rid of. https://github.com/mlc-ai/mlc-llm/pull/322
