### ISSUE TITLE
crashed after installed on vivo x90 Pro [Bug] 

### ISSUE THREAD

**Issue by CheneyJeme** [mlc-ai/mlc-llm#321]
## 🐛 Bug

1. install the mlc-chat.apk on vivo x90 Pro
2. open mlc-chat, and crashed. Retry and crash again.
3. restarting the phone and restarting mlc-chat can't help.

## Environment

vivo x90 Pro:
OS	Android 13, Funtouch 13 (Global), OriginOS 3 (China)
Chipset	Mediatek Dimensity 9200 (4 nm)
CPU	Octa-core (1x3.05 GHz Cortex-X3 & 3x2.85 GHz Cortex-A715 & 4x1.80 GHz Cortex-A510)
GPU	Immortalis-G715 MC11
RAM 8G

**Comment by chen20021014** [comment]
added the bug two day

**Comment by jiacheo** [comment]
same problem here on `Huawei Mate40 Pro`.  I use `adb logcat | grep 'ai.mlc.mlcchat' -C 100` to find some exceptions logs.
may be it could help for diagnosising the issue.

```
  3847  3937 E AndroidRuntime: Process: ai.mlc.mlcchat, PID: 3847
  3847  3937 E AndroidRuntime: java.lang.RuntimeException: java.io.FileNotFoundException: https://huggingface.co/mlc-ai/demo-vicuna-v1-7b-int4/resolve/main/float16/params_shard_7.bin
  3847  3937 E AndroidRuntime: 	at ai.mlc.mlcchat.Downloader.lambda$download$0$ai-mlc-mlcchat-Downloader(Downloader.java:98)
  3847  3937 E AndroidRuntime: 	at ai.mlc.mlcchat.Downloader$$ExternalSyntheticLambda0.run(Unknown Source:2)
  3847  3937 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  3847  3937 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  3847  3937 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:930)
  3847  3937 E AndroidRuntime: Caused by: java.io.FileNotFoundException: https://huggingface.co/mlc-ai/demo-vicuna-v1-7b-int4/resolve/main/float16/params_shard_7.bin
  3847  3937 E AndroidRuntime: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
  3847  3937 E AndroidRuntime: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
  3847  3937 E AndroidRuntime: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
  3847  3937 E AndroidRuntime: 	at java.net.URL.openStream(URL.java:1072)
  3847  3937 E AndroidRuntime: 	at ai.mlc.mlcchat.Downloader.lambda$download$0$ai-mlc-mlcchat-Downloader(Downloader.java:81)
  3847  3937 E AndroidRuntime: 	... 4 more

```

**Comment by tqchen** [comment]
Closing for now. Please check the latest apk
