### ISSUE TITLE
[Question] No module named 'tvm'

### ISSUE THREAD

**Issue by realcarlos** [mlc-ai/mlc-llm#330]
## ❓ General Questions
python3 build.py --hf-path=ethzanalytics/RedPajama-INCITE-Chat-3B-v1-GPTQ-4bit-128g
Traceback (most recent call last):
  File "/Users/xxx/mlc-llm/build.py", line 8, in <module>
    import tvm
ModuleNotFoundError: No module named 'tvm'

and I have already installed tvm by:

python3 -m pip install tvm

**Comment by sudeepag** [comment]
Could you remove `tvm` and try to install it using `pip install -I mlc_ai_nightly -f https://mlc.ai/wheels`?

**Comment by junrushao** [comment]
Please refer to this doc for TVM installation: https://mlc.ai/mlc-llm/docs/install/tvm.html

**Comment by IgnacioTechie** [comment]
Same error here.

Per the instructions I run to confirm tvm install:

python -c "import tvm; print(tvm.__file__)"
/home/nacho/.local/lib/python3.11/site-packages/tvm/__init__.py

python -c "import tvm; print(tvm._ffi.base._LIB)"
<CDLL '/home/nacho/.local/lib/python3.11/site-packages/tvm/libtvm.so', handle 5574d7b12920 at 0x7f5101cd6150>

Then:

mlc_llm_build --help

Traceback (most recent call last):
  File "/home/nacho/.local/bin/mlc_llm_build", line 5, in <module>
    from mlc_llm.build import main
  File "/home/nacho/.local/pipx/venvs/mlc-llm/lib/python3.11/site-packages/mlc_llm/__init__.py", line 1, in <module>
    from . import dispatch
  File "/home/nacho/.local/pipx/venvs/mlc-llm/lib/python3.11/site-packages/mlc_llm/dispatch/__init__.py", line 1, in <module>
    from .dispatch_tir_operator import DispatchTIROperator
  File "/home/nacho/.local/pipx/venvs/mlc-llm/lib/python3.11/site-packages/mlc_llm/dispatch/dispatch_tir_operator.py", line 2, in <module>
    import tvm
ModuleNotFoundError: No module named 'tvm'

**Comment by IgnacioTechie** [comment]
This worked for me:
`pip install --pre mlc-ai-nightly -f https://mlc.ai/wheels`

**Comment by EntropyGenerator** [comment]
Same issue when building mlc-ai from source. Solved by building tvm. (I have vulkan problem when using prebuild package.)

**Comment by ykz9527** [comment]
you can exec:
export PYTHONPATH=$PYTHONPATH:/your-path/mlc-llm/3rdparty/tvm/python/
