### ISSUE TITLE
[Doc] (+/- bugs) (Compilation from source) - python bindings installation issue on Mac

### ISSUE THREAD

**Issue by cryolite-ai** [mlc-ai/mlc-llm#402]
## 📚 Documentation
Trying to follow the ['compilation from source' details section](https://mlc.ai/mlc-llm/docs/install/tvm.html) - running into an issue which suggests that python setup may not be respecting conda environment - may be as simple as the original conda not explicitly indicating a python version(!)

### Bug
Having followed instructions and compiled `libtvm.dylib libtvm_runtime.dylib` I was attempting, on a Mac running recent OS, with Xcode etc installed, using the `(tvm-build-venv)` conda environment (which had apparently successfully configured following earlier instructions) I `cd`'d into the python/ directory and tried to do the python bindings installation but ended up with the following:

```
(tvm-build-venv) python % python setup.py install
zsh: command not found: python
```
odd, I'll try it with python3..
```
(tvm-build-venv) python % python3 setup.py install
Use git describe based version 0.12.dev1094+gbd5ee5888
WARNING: Cython is not installed, will compile without cython module
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/Library/Python'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Library/Python/3.9/site-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).
```
ok, this looks like the setup.py is trying to install stuff into a system library and not the conda environment?? 

The conda environment earlier installed doesn't include cython:
```
(tvm-build-venv) python % conda list
# packages in environment at /Users/ai/miniconda3/envs/tvm-build-venv:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.19.1               hb547adb_0    conda-forge
ca-certificates           2023.5.7             hf0a4a13_0    conda-forge
cmake                     3.26.4               hc0af03a_0    conda-forge
curl                      8.1.2                h912dcd9_0    conda-forge
expat                     2.5.0                hb7217d7_1    conda-forge
gettext                   0.21.1               h0186832_0    conda-forge
git                       2.41.0          pl5321h46e2b6d_0    conda-forge
icu                       72.1                 he12128b_0    conda-forge
krb5                      1.20.1               h69eda48_0    conda-forge
libcurl                   8.1.2                h912dcd9_0    conda-forge
libcxx                    16.0.5               h4653b0c_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libllvm16                 16.0.5               he79909e_0    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libuv                     1.44.2               he4db4b2_0    conda-forge
libxml2                   2.11.4               he3bdae6_0    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
llvm-tools                16.0.5               he79909e_0    conda-forge
llvmdev                   16.0.5               h504e6bf_0    conda-forge
ncurses                   6.4                  h7ea286d_0    conda-forge
openssl                   3.1.1                h53f4e23_1    conda-forge
pcre2                     10.40                hb34f9b4_0    conda-forge
perl                      5.32.1          2_h9b22ae9_perl5    conda-forge
rhash                     1.4.3                he4db4b2_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
zlib                      1.2.13               h53f4e23_5    conda-forge
zstd                      1.5.2                hf913c23_6    conda-forge
``` 

Doing `pip3 install cython` resulted in:

```
Defaulting to user installation because normal site-packages is not writeable
Collecting cython
  Downloading Cython-0.29.35-py2.py3-none-any.whl (988 kB)
     |████████████████████████████████| 988 kB 5.0 MB/s 
Installing collected packages: cython
  WARNING: The scripts cygdb, cython and cythonize are installed in '/Users/ai/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed cython-0.29.35
WARNING: You are using pip version 21.2.4; however, version 23.1.2 is available.
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.
```
which again suggests that something about the installation is not respecting the environment.. so, I uninstalled the cython package and installed it again this time with `pip3 install cython --prefix=/Users/ai/miniconda3/envs/tvm-build-venv` and `which cython` had it in the conda environment's folder..

but attempting to run `python setup.py install` from the `tvm-unity/python/` subdirectory of the git-cloned mlc-ai/relax repo (which is what the mlc-ai/mlc-llm installation instructions indicate should be used at present) still runs into problems.

Looking into things further, and checking the above carefully, it seems that the original conda environment setup specified in https://mlc.ai/mlc-llm/docs/install/tvm.html doesn't define a python version.. which might be good :-)

Manually performing `conda install python` seems to have resolved some issues, but still some issues..

```
(tvm-build-venv) python % python setup.py install 
Use git describe based version 0.12.dev1094+gbd5ee5888
Traceback (most recent call last):
  File "/Users/ai/Projects/tvm-unity/python/setup.py", line 202, in <module>
    shutil.copy(path, os.path.join(CURRENT_DIR, "tvm"))
  File "/Users/ai/miniconda3/envs/tvm-build-venv/lib/python3.11/shutil.py", line 419, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/ai/miniconda3/envs/tvm-build-venv/lib/python3.11/shutil.py", line 236, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/Users/ai/Projects/tvm-unity/python/tvm/libtvm.dylib' and '/Users/ai/Projects/tvm-unity/python/tvm/libtvm.dylib' are the same file
```

**Comment by junrushao** [comment]
In fact your build is successful, but only installation fails. The reason you failed is that "python" is not installed in your conda environment according to your error message:

```
zsh: command not found: python
```

And likely the `python3` you tried comes from the other different environment, which might be the cause of subsequent mess-ups :-(

I added some documentation on post-build installation: https://mlc.ai/mlc-llm/docs/install/tvm.html#id4. Would you mind trying it out in a clean conda environment? Thanks a lot!

**Comment by junrushao** [comment]
I also added stronger words saying you usually don't have to build TVM yourself :-)

**Comment by junrushao** [comment]
The doc should be much clearer now. Please circle back if it still doesn't work
