### ISSUE TITLE
[Bug] The "send" button is not working for Android app  

### ISSUE THREAD

**Issue by lixiangnlp** [mlc-ai/mlc-llm#566]
I installed the Android app on my Xiaomi 11 Ultra with MIUI 14. I find the "send" button is grey and not working. And the app crashed with the following error info.

java.lang.IllegalArgumentException: Failed requirement.
	at ai.mlc.mlcchat.AppViewModel$ChatState.requestReloadChat(AppViewModel.kt:401)
	at ai.mlc.mlcchat.AppViewModel$ModelState.startChat(AppViewModel.kt:337)
	at ai.mlc.mlcchat.StartViewKt$ModelView$1$1$3.invoke(StartView.kt:191)
	at ai.mlc.mlcchat.StartViewKt$ModelView$1$1$3.invoke(StartView.kt:189)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke-k-4lQ0M(Clickable.kt:167)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke(Clickable.kt:156)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:566)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:456)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:469)
	at androidx.compose.ui.node.BackwardsCompatNode.onPointerEvent-H0pRuoY(BackwardsCompatNode.kt:374)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:314)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:183)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:102)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:98)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1361)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1307)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1246)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3132)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3132)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3132)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3132)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:571)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1899)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4403)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:529)
	at android.view.View.dispatchPointerEvent(View.java:15334)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6964)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6751)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6170)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6227)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6193)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6358)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6201)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6415)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6174)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6227)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6193)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6201)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6174)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9312)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9263)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9231)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9451)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:292)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:341)
	at android.os.Looper.loopOnce(Looper.java:168)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@2e8740b, androidx.compose.runtime.BroadcastFrameClock@bd6f2e8, StandaloneCoroutine{Cancelling}@ff84d01, AndroidUiDispatcher@3f547a6]

**Comment by Hzfengsy** [comment]
cc @cyx-6

**Comment by tsaizehua** [comment]
I also encountered the same problem. I successfully downloaded 'vicuna-v1-7b-q4f16_0.'. After clicking on the dialog box on the right, an 'initialize' toast flashed. After that, there was no prompt, and the send button was unavailable. The android system is '5.15.41-android13-8-gb5e953e9df35'.

**Comment by willswordh** [comment]
Same issue. It seems that MLC team hasn't solved the issue yet.

**Comment by ceasarXuu** [comment]
My iPhone can run normally, but I tried two different Android phones but they couldn’t initialize and 「send」.

**Comment by suoko** [comment]
Its kind of random. I confirm the send button is not usually available, but sometimes it becomes available. Cannot reproduce though
