### ISSUE TITLE
[Feature Request] Support compilation of weights stored in .safetensors files

### ISSUE THREAD

**Issue by gsuuon** [mlc-ai/mlc-llm#585]
## 🚀 Feature
Support the [safetensors](https://github.com/huggingface/safetensors) format

## Motivation
Quite a few models (especially ones quantized via AutoGPTQ) are distributed in .safetensors. 

## Alternatives
Not having safetensors support

## Additional context
[Here](https://github.com/huggingface/safetensors#yet-another-format-) are some good reasons for why safetensors

**Comment by CharlieRuan0130** [comment]
Hi @gsuuon, `.safetensors` now should be supported after the latest #627; let us know if there is any issue. Thanks!

**Comment by gsuuon** [comment]
Hi @CharlieRuan0130 , thanks for adding this! I wasn't able to get this to work with an AutoGPTQ'd .safetensors model (https://huggingface.co/TheBloke/Llama-2-13B-chat-GPTQ).

I think this approach makes an assumption about the model name being 'model.safetensors'. If I just rename the model to 'model.safetensors' AutoGPTQ complains about not being able to find the model when I run `python3 -m mlc_llm.build --target cuda --quantization autogptq_llama_q4f16_0 --use-safetensors --model Llama-2-13B-chat-GPTQ`:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/gsuuon/mlc-llm/mlc_llm/build.py", line 13, in <module>
    main()
  File "/home/gsuuon/mlc-llm/mlc_llm/build.py", line 10, in main
    core.build_model_from_args(parsed_args)
  File "/home/gsuuon/mlc-llm/mlc_llm/core.py", line 410, in build_model_from_args
    mod, param_manager, params = llama.get_model(args, config)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gsuuon/mlc-llm/mlc_llm/relax_model/llama.py", line 944, in get_model
    param_list = args.quantization.load_quantized_params(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gsuuon/mlc-llm/mlc_llm/quantization/quantization.py", line 218, in load_quantized_params
    return self._load_quantized_params_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gsuuon/mlc-llm/mlc_llm/quantization/autogptq_quantization.py", line 30, in load_autogptq_params
    model = AutoGPTQForCausalLM.from_quantized(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gsuuon/miniconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/auto_gptq/modeling/auto.py", line 94, in from_quantized
    return quant_func(
           ^^^^^^^^^^^
  File "/home/gsuuon/miniconda3/envs/mlc-chat-venv/lib/python3.11/site-packages/auto_gptq/modeling/_base.py", line 714, in from_quantized
    raise FileNotFoundError(f"Could not find model in {model_name_or_path}")

```

So I make this change to pass through our assumed base name:

```diff
diff --git a/mlc_llm/quantization/autogptq_quantization.py b/mlc_llm/quantization/autogptq_quantization.py
index 0adc172..0cebcee 100644
--- a/mlc_llm/quantization/autogptq_quantization.py
+++ b/mlc_llm/quantization/autogptq_quantization.py
@@ -28,7 +28,7 @@ def load_autogptq_params(
     from auto_gptq import AutoGPTQForCausalLM

     model = AutoGPTQForCausalLM.from_quantized(
-        model_path, use_safetensors=use_safetensors
+        model_path, use_safetensors=use_safetensors, model_basename="model"
     ).cpu()
     param_dict = model.state_dict()
     for pidx, pname in pidx2pname.items():
```
But then I get:
```
(mlc-chat-venv) gsuuon@fullerene:~/mlc-llm$ python3 -m mlc_llm.build --target cuda --quantization autogptq_llama_q4f16_0 --use-safetensors --model Llama-2-13B-chat-GPTQ
Using path "dist/models/Llama-2-13B-chat-GPTQ" for model "Llama-2-13B-chat-GPTQ"
Database paths: ['log_db/vicuna-v1-7b', 'log_db/dolly-v2-3b', 'log_db/redpajama-3b-q4f32', 'log_db/redpajama-3b-q4f16', 'log_db/rwkv-raven-1b5', 'log_db/rwkv-raven-7b', 'log_db/rwkv-raven-3b']
Target configured: cuda -keys=cuda,gpu -arch=sm_86 -max_num_threads=1024 -thread_warp_size=32
The safetensors archive passed at dist/models/Llama-2-13B-chat-GPTQ/model.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/gsuuon/mlc-llm/mlc_llm/build.py", line 13, in <module>
    main()
  File "/home/gsuuon/mlc-llm/mlc_llm/build.py", line 10, in main
    core.build_model_from_args(parsed_args)
  File "/home/gsuuon/mlc-llm/mlc_llm/core.py", line 410, in build_model_from_args
    mod, param_manager, params = llama.get_model(args, config)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gsuuon/mlc-llm/mlc_llm/relax_model/llama.py", line 944, in get_model
    param_list = args.quantization.load_quantized_params(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gsuuon/mlc-llm/mlc_llm/quantization/quantization.py", line 218, in load_quantized_params
    return self._load_quantized_params_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gsuuon/mlc-llm/mlc_llm/quantization/autogptq_quantization.py", line 38, in load_autogptq_params
    np_array = param_dict[pname].numpy()
               ~~~~~~~~~~^^^^^^^
KeyError: 'model.model.layers.0.self_attn.q_proj.qweight'
```

If I run `python3 -m mlc_llm.build --target cuda --quantization q4f16_1 --use-safetensors --model Llama-2-13B-chat-GPTQ` I just get
```
Using path "dist/models/Llama-2-13B-chat-GPTQ" for model "Llama-2-13B-chat-GPTQ"
Database paths: ['log_db/vicuna-v1-7b', 'log_db/dolly-v2-3b', 'log_db/redpajama-3b-q4f32', 'log_db/redpajama-3b-q4f16', 'log_db/rwkv-raven-1b5', 'log_db/rwkv-raven-7b', 'log_db/rwkv-raven-3b']
Target configured: cuda -keys=cuda,gpu -arch=sm_86 -max_num_threads=1024 -thread_warp_size=32
Automatically using target for weight quantization: cuda -keys=cuda,gpu -arch=sm_86 -max_num_threads=1024 -max_shared_memory_per_block=49152 -max_threads_per_block=1024 -registers_per_block=65536 -thread_warp_size=32
Start computing and quantizing weights... This may take a while.
/home/gsuuon/mlc-llm/mlc_llm/relax_model/llama.py:909: RuntimeWarning: overflow encountered in cast
  return [(torch_pname, torch_param.astype(dtype))]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/gsuuon/mlc-llm/mlc_llm/build.py", line 13, in <module>
    main()
  File "/home/gsuuon/mlc-llm/mlc_llm/build.py", line 10, in main
    core.build_model_from_args(parsed_args)
  File "/home/gsuuon/mlc-llm/mlc_llm/core.py", line 425, in build_model_from_args
    new_params = utils.convert_weights(param_manager, params, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gsuuon/mlc-llm/mlc_llm/utils.py", line 181, in convert_weights
    vm["transform_params"]()
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
KeyError: 'Traceback (most recent call last):\n  6: TVMFuncCall\n  5: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)\n  4: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::relax_vm::VirtualMachineImpl::GetClosureInternal(tvm::runtime::String const&, bool)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)\n  3: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)\n  2: tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()\n  1: tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)\n  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<TVMFuncCreateFromCFunc::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) [clone .cold]\n  File "tvm/_ffi/_cython/./packed_func.pxi", line 56, in tvm._ffi._cy3.core.tvm_callback\n  File "/home/gsuuon/mlc-llm/mlc_llm/relax_model/param_manager.py", line 583, in get_item\n    [cached_torch_params[torch_pname] for torch_pname in torch_pnames],\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/gsuuon/mlc-llm/mlc_llm/relax_model/param_manager.py", line 583, in <listcomp>\n    [cached_torch_params[torch_pname] for torch_pname in torch_pnames],\n     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\nKeyError: \'model.layers.0.self_attn.q_proj.weight\''

```

The warning ```The safetensors archive passed at dist/models/Llama-2-13B-chat-GPTQ/model.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.``` could indicate that the model needs to be packaged differently?

I'm not sure if this should be a separate issue, but [this](https://github.com/mlc-ai/mlc-llm/blob/487b028d91245bd2650191a05a59b55170bcb7b8/mlc_llm/relax_model/param_manager.py#L833) could glob for a `.safetensors` file instead of hardcoding the file name to make it easier to directly consume some of the models available on huggingface.
