### ISSUE TITLE
[Bug] build llama using rocm

### ISSUE THREAD

**Issue by Cydia2018** [mlc-ai/mlc-llm#632]
## 🐛 Bug

Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/mlc/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xxx/anaconda3/envs/mlc/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/relay/xxx/workspace/mlc-llm/mlc_llm/build.py", line 13, in <module>
    main()
  File "/home/xxx/workspace/mlc-llm/mlc_llm/build.py", line 10, in main
    core.build_model_from_args(parsed_args)
  File "/home/xxx/workspace/mlc-llm/mlc_llm/core.py", line 425, in build_model_from_args
    new_params = utils.convert_weights(param_manager, params, args)
  File "/home/xxx/workspace/mlc-llm/mlc_llm/utils.py", line 181, in convert_weights
    vm = relax.vm.VirtualMachine(ex, device)
  File "/home/xxx/tvm-unity/python/tvm/runtime/relax_vm.py", line 81, in __init__
    rt_mod = rt_mod.jit()
  File "/home/xxx/tvm-unity/python/tvm/relax/vm_build.py", line 89, in jit
    not_runnable_list = self.mod._collect_from_import_tree(_not_runnable)
  File "/home/xxx/tvm-unity/python/tvm/runtime/module.py", line 431, in _collect_from_import_tree
    assert (
AssertionError: Module hip should be either dso exportable or binary serializable.

I have build tvm on ROCm, however, when building llama model, there is above problem. I want to know whether it is caused by the imperfect support of rocm？

**Comment by Hzfengsy** [comment]
Thanks for reporting it. ROCm is an important backend and it's on our roadmap. However, there are no available devices in our team. We may work on it as soon as ROCm is supported on AMD desktop cards (likely Q4 said by rocm team)

Meanwhile, you are warmly welcome if you could help contribute ROCm support to MLC-LLM

**Comment by tqchen** [comment]
Thanks for the suggestion, opening a tracking issue for this https://github.com/mlc-ai/mlc-llm/issues/644

**Comment by junrushao** [comment]
Should be fixed via #644
