### ISSUE TITLE
mlc_llm.build ModuleNotFoundError: No module named 'pytest'

### ISSUE THREAD

**Issue by esmeetu** [mlc-ai/mlc-llm#813]
## To Reproduce

1.python -m mlc_llm.build --model ../chatglm2-6b --target metal --quantization q4f16_1

```
Using path "../chatglm2-6b" for model "chatglm2-6b"
[09:58:30] /Users/catalyst/Workspace/mlc-ai-package-self-runner/_work/package/package/tvm/src/runtime/metal/metal_device_api.mm:167: Intializing Metal device 0, name=Apple M1 Pro
Host CPU dection:
  Target triple: arm64-apple-darwin22.5.0
  Process triple: arm64-apple-darwin22.5.0
  Host CPU: apple-m1
Target configured: metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32
Host CPU dection:
  Target triple: arm64-apple-darwin22.5.0
  Process triple: arm64-apple-darwin22.5.0
  Host CPU: apple-m1
Automatically using target for weight quantization: metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32
Start computing and quantizing weights... This may take a while.
Finish computing and quantizing weights.
Total param size: 3.2713050842285156 GB
Start storing to cache dist/chatglm2-6b-q4f16_1/params
[0313/0313] saving param_312
All finished, 88 total shards committed, record saved to dist/chatglm2-6b-q4f16_1/params/ndarray-cache.json
Finish exporting chat config to dist/chatglm2-6b-q4f16_1/params/mlc-chat-config.json
[09:58:55] /Users/catalyst/Workspace/mlc-ai-package-self-runner/_work/package/package/tvm/include/tvm/topi/transform.h:1076: Warning: Fast mode segfaults when there are out-of-bounds indices. Make sure input indices are in bound
[09:58:56] /Users/catalyst/Workspace/mlc-ai-package-self-runner/_work/package/package/tvm/include/tvm/topi/transform.h:1076: Warning: Fast mode segfaults when there are out-of-bounds indices. Make sure input indices are in bound
Save a cached module to dist/chatglm2-6b-q4f16_1/mod_cache_before_build.pkl.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlc/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlc/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/roy/mlc-llm/mlc_llm/build.py", line 13, in <module>
    main()
  File "/Users/roy/mlc-llm/mlc_llm/build.py", line 10, in main
    core.build_model_from_args(parsed_args)
  File "/Users/roy/mlc-llm/mlc_llm/core.py", line 590, in build_model_from_args
    build(mod, args)
  File "/Users/roy/mlc-llm/mlc_llm/core.py", line 473, in build
    utils.debug_dump_benchmark_script(
  File "/Users/roy/mlc-llm/mlc_llm/utils.py", line 108, in debug_dump_benchmark_script
    from tvm.dlight.benchmark import extract_all_func_info_from_relax
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlc/lib/python3.9/site-packages/tvm/dlight/benchmark/__init__.py", line 18, in <module>
    from .bench import benchmark, benchmark_prim_func, benchmark_relax_func
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlc/lib/python3.9/site-packages/tvm/dlight/benchmark/bench.py", line 28, in <module>
    from tvm.testing import rpc_run
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlc/lib/python3.9/site-packages/tvm/testing/__init__.py", line 47, in <module>
    from .utils import *
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlc/lib/python3.9/site-packages/tvm/testing/utils.py", line 85, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

## Expected behavior

build success

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Metal
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): MacOS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): Mac
 - How you installed MLC-LLM (`conda`, source): source(master)
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.9
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

`pip install pytest` works

**Comment by Hzfengsy** [comment]
Thanks for the report, should be improved in https://github.com/mlc-ai/mlc-llm/pull/814

**Comment by junrushao** [comment]
CC: @zxybazh
