### ISSUE TITLE
Runing mlc-llm python code on windows fail

### ISSUE THREAD

**Issue by lucasjinreal** [mlc-ai/mlc-llm#82]
Hi, tried to run python (gen my self), got some errors:

```
Check failed: (it != self_->idx_sub_.end()) is false:
```

I built tvm unity branch it import correctly, but runtime error when run `python .\tests\chat.py`

Full traceback:

```
Traceback (most recent call last):
  File "E:\codes\ai\aichat\mlc-llm\tests\chat.py", line 13, in <module>
    from mlc_llm import utils
  File "e:\codes\ai\aichat\mlc-llm\mlc_llm\__init__.py", line 2, in <module>
    from . import transform
  File "e:\codes\ai\aichat\mlc-llm\mlc_llm\transform\__init__.py", line 1, in <module>
    from .dispatch_tir_operator import DispatchTIROperator
  File "e:\codes\ai\aichat\mlc-llm\mlc_llm\transform\dispatch_tir_operator.py", line 6371, in <module>
    get_dict_key(fused_min_max_triu_te_broadcast_to): fused_min_max_triu_te_broadcast_to_sch_func(),
  File "e:\codes\ai\aichat\mlc-llm\mlc_llm\transform\dispatch_tir_operator.py", line 30, in fused_min_max_triu_te_broadcast_to_sch_func
    sch.reverse_compute_inline(b0)
  File "e:\codes\libs\tvm\python\tvm\tir\schedule\_type_checker.py", line 339, in wrap
    return func(*args, **kwargs)
  File "e:\codes\libs\tvm\python\tvm\tir\schedule\schedule.py", line 2218, in reverse_compute_inline
    _ffi_api.ScheduleReverseComputeInline(self, block)  # type: ignore # pylint: disable=no-member
  File "e:\codes\libs\tvm\python\tvm\_ffi\_ctypes\packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  File "E:\codes\libs\tvm\src\tir\schedule\primitive\compute_inline.cc", line 537
TVMError:
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (it != self_->idx_sub_.end()) is false:
```

Any help here?

**Comment by yzh119** [comment]
Some of the functionalities for dynamic shape have not been upstreamed yet, please use the [relax repo](https://github.com/mlc-ai/relax) for now.

**Comment by junrushao** [comment]
Yep please use this repo: https://github.com/mlc-ai/relax
