### ISSUE TITLE
[Bug] How to Compile a Custom LLM to iPhone

### ISSUE THREAD

**Issue by llSourcell** [mlc-ai/mlc-llm#878]
## 🐛 Bug

Hello MLC Team! I'm loving this project, thank you for your efforts. I'm trying to compile any 3 billion parameter model from the Open LLM leaderboard, but can't get any of them to work. I'm using an M1 apple silicon macbook. I was able to successfully compile Llama and redpajama like everyone else. I'm lookign to do this for other models. Any ideas? Should i start learning Relay and start writing my own relay code? or is this a simple parameter flag fix im not getting? 

## To Reproduce

1. git clone https://github.com/mlc-ai/mlc-llm.git
2. cd mlc-llm 
3. mkdir -p dist/prebuilt
4. git clone https://github.com/mlc-ai/binary-mlc-llm-libs.git dist/prebuilt/lib
5. git submodule update --init --recursive 
6. Cd ./iOS
7. python3 -m mlc_llm.build --hf-path=Aspik101/WizardVicuna-Uncensored-3B-instruct-PL-lora_unload --target iphone --max-seq-len 768 --quantization q3f16_1

Step 7 is the only step that matters here. 

I've tried each combination of quantization parameters available in the MLC LLM library, they all throw different errors. Here is the error from above line 7

```
(base) sirajraval@Sirajs-MBP-2 mlc-llm % python3 -m mlc_llm.build --hf-path=Aspik101/WizardVicuna-Uncensored-3B-instruct-PL-lora_unload --target iphone --max-seq-len 768 --quantization q3f16_1
Weights exist at dist/models/WizardVicuna-Uncensored-3B-instruct-PL-lora_unload, skipping download.
Using path "dist/models/WizardVicuna-Uncensored-3B-instruct-PL-lora_unload" for model "WizardVicuna-Uncensored-3B-instruct-PL-lora_unload"
Target configured: metal -keys=metal,gpu -libs=iphoneos -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=256 -thread_warp_size=1
Load cached module from dist/WizardVicuna-Uncensored-3B-instruct-PL-lora_unload-q3f16_1/mod_cache_before_build.pkl and skip tracing. You can use --use-cache=0 to retrace
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/sirajraval/Desktop/sep6_transformers/mlc-llm/mlc_llm/build.py", line 13, in <module>
    main()
  File "/Users/sirajraval/Desktop/sep6_transformers/mlc-llm/mlc_llm/build.py", line 10, in main
    core.build_model_from_args(parsed_args)
  File "/Users/sirajraval/Desktop/sep6_transformers/mlc-llm/mlc_llm/core.py", line 600, in build_model_from_args
    build(mod, args)
  File "/Users/sirajraval/Desktop/sep6_transformers/mlc-llm/mlc_llm/core.py", line 500, in build
    mod_deploy = dl.ApplyDefaultSchedule(  # pylint: disable=not-callable
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sirajraval/anaconda3/lib/python3.11/site-packages/tvm/ir/transform.py", line 238, in __call__
    return _ffi_transform_api.RunPass(self, mod)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm.tir.schedule.schedule.ScheduleError: Traceback (most recent call last):
  File "tvm/_ffi/_cython/./packed_func.pxi", line 56, in tvm._ffi._cy3.core.tvm_callback
  File "/Users/sirajraval/anaconda3/lib/python3.11/site-packages/tvm/ir/transform.py", line 307, in _pass_func
    return inst.transform_module(mod, ctx)
  File "/Users/sirajraval/anaconda3/lib/python3.11/site-packages/tvm/dlight/base/transform.py", line 64, in transform_module
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    sch = _apply_rules(func, target, self.rules, tunable=False)
  File "/Users/sirajraval/anaconda3/lib/python3.11/site-packages/tvm/dlight/base/transform.py", line 80, in _apply_rules
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    space = rule.apply(func, target, tunable)
  File "/Users/sirajraval/anaconda3/lib/python3.11/site-packages/tvm/dlight/gpu/reduction.py", line 102, in apply
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    self._sch_inner_spatial(sch, target, block, c_factor, epilogue)
  File "/Users/sirajraval/anaconda3/lib/python3.11/site-packages/tvm/dlight/gpu/reduction.py", line 225, in _sch_inner_spatial
    sch.bind(s, "threadIdx.x")
  File "/Users/sirajraval/anaconda3/lib/python3.11/site-packages/tvm/tir/schedule/_type_checker.py", line 340, in wrap
    return func(*args, **kwargs)
  File "/Users/sirajraval/anaconda3/lib/python3.11/site-packages/tvm/tir/schedule/schedule.py", line 1173, in bind
           ^^^^^^^^^^^^^^^^^^^^^
    _ffi_api.ScheduleBind(self, loop, thread_axis)  # type: ignore # pylint: disable=no-member
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
ScheduleError: An error occurred in the schedule primitive 'bind'.
The IR with diagnostic is:
# from tvm.script import ir as I
# from tvm.script import tir as T

@I.ir_module
class Module:
    @T.prim_func(private=True)
    def main(var_A: T.handle, var_B: T.handle, var_matmul: T.handle):
        T.func_attr({"tir.noalias": T.bool(True)})
        n = T.int64()
        A = T.match_buffer(var_A, (T.int64(1), T.int64(32), T.int64(1), n), "float16")
        B = T.match_buffer(var_B, (T.int64(1), T.int64(32), n, T.int64(100)), "float16")
        matmul = T.match_buffer(var_matmul, (T.int64(1), T.int64(32), T.int64(1), T.int64(100)), "float16")
        with T.block("root"):
            T.reads()
            T.writes()
            matmul_rf_local = T.alloc_buffer((T.int64(16), T.int64(1), T.int64(32), T.int64(1), T.int64(100)), "float16", scope="local")
            for ax0_ax1_fused_0 in T.thread_binding(T.int64(200), thread="blockIdx.x"):
                for ax0_ax1_fused_1 in T.thread_binding(T.int64(16), thread="threadIdx.x"):
                    for ax2_fused_1 in T.thread_binding(T.int64(16), thread="threadIdx.y"):
                        with T.block("matmul_rf_init"):
                            vax2_fused_1 = T.axis.spatial(T.int64(16), ax2_fused_1)
                            v0 = T.axis.spatial(T.int64(32), (ax0_ax1_fused_0 * T.int64(16) + ax0_ax1_fused_1) // T.int64(100))
                            v1 = T.axis.spatial(T.int64(100), (ax0_ax1_fused_0 * T.int64(16) + ax0_ax1_fused_1) % T.int64(100))
                            T.reads()
                            T.writes(matmul_rf_local[vax2_fused_1, T.int64(0), v0, T.int64(0), v1])
                            matmul_rf_local[vax2_fused_1, T.int64(0), v0, T.int64(0), v1] = T.float16(0)
                        for ax2_fused_0 in range((n + T.int64(15)) // T.int64(16)):
                            for u in range(1):
                                with T.block("matmul_rf_update"):
                                    vax2_fused_1 = T.axis.spatial(T.int64(16), ax2_fused_1)
                                    v0 = T.axis.spatial(T.int64(32), (ax0_ax1_fused_0 * T.int64(16) + ax0_ax1_fused_1) // T.int64(100))
                                    v1 = T.axis.spatial(T.int64(100), (ax0_ax1_fused_0 * T.int64(16) + ax0_ax1_fused_1) % T.int64(100))
                                    vax2_fused_0 = T.axis.reduce((n + T.int64(15)) // T.int64(16), ax2_fused_0)
                                    T.where(ax2_fused_0 * T.int64(16) + ax2_fused_1 < n)
                                    T.reads(matmul_rf_local[vax2_fused_1, T.int64(0), v0, T.int64(0), v1], A[T.int64(0), v0, T.int64(0), vax2_fused_0 * T.int64(16) + vax2_fused_1], B[T.int64(0), v0, vax2_fused_0 * T.int64(16) + vax2_fused_1, v1])
                                    T.writes(matmul_rf_local[vax2_fused_1, T.int64(0), v0, T.int64(0), v1])
                                    matmul_rf_local[vax2_fused_1, T.int64(0), v0, T.int64(0), v1] = matmul_rf_local[vax2_fused_1, T.int64(0), v0, T.int64(0), v1] + A[T.int64(0), v0, T.int64(0), vax2_fused_0 * T.int64(16) + vax2_fused_1] * B[T.int64(0), v0, vax2_fused_0 * T.int64(16) + vax2_fused_1, v1]
                # tir.For#0
                for ax1_ax2_fused in range((ax0_ax1_fused_0 * T.int64(16) % T.int64(100) + T.int64(15)) // T.int64(100) * T.int64(100) + T.int64(100)):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    for ax0 in range(T.int64(16)):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        # tir.Block#1
                        with T.block("matmul"):
                        ^^^^^^^^^^^^^^^^^^^^^^^
                            vax2_fused_1 = T.axis.reduce(T.int64(16), ax0)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            v0 = T.axis.spatial(T.int64(32), ax0_ax1_fused_0 * T.int64(16) // T.int64(100) + ax1_ax2_fused // T.int64(100))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            v1 = T.axis.spatial(T.int64(100), ax1_ax2_fused % T.int64(100))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            T.reads(matmul_rf_local[vax2_fused_1, T.int64(0), v0, T.int64(0), v1])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            T.writes(matmul[T.int64(0), v0, T.int64(0), v1])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            with T.init():
                            ^^^^^^^^^^^^^^
                                matmul[T.int64(0), v0, T.int64(0), v1] = T.float16(0)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            matmul[T.int64(0), v0, T.int64(0), v1] = matmul[T.int64(0), v0, T.int64(0), v1] + matmul_rf_local[vax2_fused_1, T.int64(0), v0, T.int64(0), v1]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error message: The queried subtree root tir.For#0 in SRef tree does not have compact dataflow, because its child block tir.Block#1 on SRef tree is neither a local complete block nor a local reduction block.
It violates condition #1 as a local complete block.
Definition of a local complete block:
1) All block vars are data parallel
2) Local Dominant: the block is the only writer of its output, dominating the reader of its output buffers under a given subtree
3) No overlap between the buffers the block reads and writes
It violates condition #2 as a local reduction block.
Definition of a reduction block:
1) The block has the `init` statement
2) All the block bindings are quasi-affine expressions
3) All block vars are either data parallel block vars or reduction block vars
4) Local Dominant: the block is the only writer of its output, dominating the reader of its output buffers under a given subtree
5) The reduction block vars are not used to index the output buffers

(base) sirajraval@Sirajs-MBP-2 mlc-llm % python3 -m mlc_llm.build --hf-path=Aspik101/WizardVicuna-Uncensored-3B-instruct-PL-lora_unload --target iphone --max-seq-len 768 --quantization q3f16_1


## Expected behavior

Output of a compiled iphone .tar binary  that i can run on device locally


Any help is appreciated! Thank you

**Comment by Hzfengsy** [comment]
Looks like this model arch is not supported now :-(

**Comment by MasterJH5574** [comment]
Hi @llSourcell, reading the error message, it is the matmul function not handled properly. Given the model is llama-structured, I suppose it can work seamlessly with MLC LLM. If you would like to try compile the model again with `--debug-dump` enabled, we are happy to look into issue with the dumped log files if it persists.

**Comment by MasterJH5574** [comment]
Closed for now. You are welcome to reopen the issue or open a new issue if there are further problems.
