### ISSUE TITLE
[Question] "import tvm" error in python

### ISSUE THREAD

**Issue by weizhenhuan** [mlc-ai/mlc-llm#915]
I compile the mlc-llm from source successfully. To install tvm python, I cd to 3rdparth/tvm and execute "python setup.py install". And then I got this picture, it shows that I install it successfully.
![image](https://github.com/mlc-ai/mlc-llm/assets/55399998/d1cd73e6-e45c-4fab-a1a2-1b3bfcb33830)

But when I run "import tvm" in python, it reports an error like this. I have set the environment variable TVM_HOME. I google it but still cannot solve it. Can you help me?

>>> import tvm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/weizhenhuan/miniconda3/envs/tvm/lib/python3.11/site-packages/tvm-0.12.dev1574+g631f37b6b-py3.11-linux-x86_64.egg/tvm/__init__.py", line 33, in <module>
    from .runtime.object import Object
  File "/home/weizhenhuan/miniconda3/envs/tvm/lib/python3.11/site-packages/tvm-0.12.dev1574+g631f37b6b-py3.11-linux-x86_64.egg/tvm/runtime/__init__.py", line 22, in <module>
    from .object_path import ObjectPath, ObjectPathPair
  File "/home/weizhenhuan/miniconda3/envs/tvm/lib/python3.11/site-packages/tvm-0.12.dev1574+g631f37b6b-py3.11-linux-x86_64.egg/tvm/runtime/object_path.py", line 43, in <module>
    @tvm._ffi.register_object("ObjectPath")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weizhenhuan/miniconda3/envs/tvm/lib/python3.11/site-packages/tvm-0.12.dev1574+g631f37b6b-py3.11-linux-x86_64.egg/tvm/_ffi/registry.py", line 69, in register
    check_call(_LIB.TVMObjectTypeKey2Index(c_str(object_name), ctypes.byref(tidx)))
  File "/home/weizhenhuan/miniconda3/envs/tvm/lib/python3.11/site-packages/tvm-0.12.dev1574+g631f37b6b-py3.11-linux-x86_64.egg/tvm/_ffi/base.py", line 491, in check_call
    raise_last_ffi_error()
  File "/home/weizhenhuan/miniconda3/envs/tvm/lib/python3.11/site-packages/tvm-0.12.dev1574+g631f37b6b-py3.11-linux-x86_64.egg/tvm/_ffi/base.py", line 476, in raise_last_ffi_error
    raise py_err
tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (3) /home/weizhenhuan/miniconda3/envs/tvm/bin/libtvm.so(TVMObjectTypeKey2Index+0x5c) [0x7facd224dc1c]
  [bt] (2) /home/weizhenhuan/miniconda3/envs/tvm/bin/libtvm.so(tvm::runtime::Object::TypeKey2Index(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x220) [0x7facd224db90]
  [bt] (1) /home/weizhenhuan/miniconda3/envs/tvm/bin/libtvm.so(tvm::runtime::detail::LogFatal::Entry::Finalize()+0x3d) [0x7facd21d6c9d]
  [bt] (0) /home/weizhenhuan/miniconda3/envs/tvm/bin/libtvm.so(tvm::runtime::Backtrace[abi:cxx11]()+0x2c) [0x7facd223170c]
  File "/home/weizhenhuan/code/mlc-llm/3rdparty/tvm/src/runtime/object.cc", line 165
InternalError: Check failed: (it != type_key2index_.end()) is false: Cannot find type ObjectPath. Did you forget to register the node by TVM_REGISTER_NODE_TYPE ?

**Comment by junrushao** [comment]
Please follow the tutorial to install TVM Unity: https://mlc.ai/mlc-llm/docs/install/tvm.html

**Comment by weizhenhuan** [comment]
when compiling the mlc-llm from source, it also has compiled the tvm repo, which is "relax" repo. The link you provide is also to compile the "tvm-unity" repo, which is also "relax" repo. What's  the difference?

**Comment by loonyma** [comment]
I encountered the same issue. The point is tvm compile configture, Make sure of below setting.

echo "set(CMAKE_BUILD_TYPE RelWithDebInfo)" >> config.cmake
# LLVM is a must dependency
echo "set(USE_LLVM \"llvm-config --ignore-libllvm --link-static\")" >> config.cmake
echo "set(HIDE_PRIVATE_SYMBOLS ON)" >> config.cmake

**Comment by zhaoA** [comment]
> when compiling the mlc-llm from source, it also has compiled the tvm repo, which is "relax" repo. The link you provide is also to compile the "tvm-unity" repo, which is also "relax" repo. What's the difference?

I think they are the same. In the mlc-llm folder, in order to reduce complication time, the compilation option BUILD_DUMMY_LIBTVM is open. May that is the reason.
