### ISSUE TITLE
[Bug] Failed to build when the models downloaded manually instead of git clone

### ISSUE THREAD

**Issue by zuramai** [mlc-ai/mlc-llm#924]
## To Reproduce

1. Clone the huggingface model without the LFS files
2. Download the LFS files with different downloader
3. Run the build command:

```
python3 build.py --model ../models/Nous-Hermes-llama-2-7b --target webgpu 
```

Error messages:
```
Using path "../models/Nous-Hermes-llama-2-7b" for model "Nous-Hermes-llama-2-7b"
Target configured: webgpu -keys=webgpu,gpu -max_num_threads=256
[11:04:38] /Users/catalyst/Workspace/mlc-ai-package-self-runner/_work/package/package/tvm/src/runtime/metal/metal_device_api.mm:167: Intializing Metal device 0, name=Apple M2 Pro
Host CPU dection:
  Target triple: arm64-apple-darwin22.3.0
  Process triple: arm64-apple-darwin22.3.0
  Host CPU: apple-m1
Automatically using target for weight quantization: metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32
[11:04:38] /Users/catalyst/Workspace/mlc-ai-package-self-runner/_work/package/package/tvm/src/relax/ir/block_builder.cc:64: Warning: BlockBuilder destroyed with remaining blocks!
Traceback (most recent call last):
  File "/Users/zuramai/Code/LLM/mlc-llm/build.py", line 4, in <module>
    main()
  File "/Users/zuramai/Code/LLM/mlc-llm/mlc_llm/build.py", line 10, in main
    core.build_model_from_args(parsed_args)
  File "/Users/zuramai/Code/LLM/mlc-llm/mlc_llm/core.py", line 611, in build_model_from_args
    new_params = utils.convert_weights(param_manager, params, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zuramai/Code/LLM/mlc-llm/mlc_llm/utils.py", line 254, in convert_weights
    ex = relax.build(mod_transform, target=target)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tvm/relax/vm_build.py", line 321, in build
    new_mod = seq(mod)
              ^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tvm/ir/transform.py", line 238, in __call__
    return _ffi_transform_api.RunPass(self, mod)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm.error.InternalError: Traceback (most recent call last):
  File "/Users/catalyst/Workspace/mlc-ai-package-self-runner/_work/package/package/tvm/src/relax/backend/vm/vm_shape_lower.cc", line 360
InternalError: Check failed: (slot->value_computed) is false: PrimExpr T.int64(4) * v * T.int64(512) has not been computed
```

## Expected behavior

Expected to have the build successful

## Environment

 - Platform: WebGPU
 - Operating system: MacOS
 - Device: Mac M2 Pro
 - How you installed MLC-LLM: Yes
 - How you installed TVM-Unity (`pip`, source): Yes
 - Python version: 3.11.5
 - GPU driver version (if applicable): 
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): Yes
 - Any other relevant information:

## Additional context

I tried cloning the repository and it build successfully. But when I download it manually, it's not working.

**Comment by MasterJH5574** [comment]
Hi @zuramai, thanks for reporting. This looks quite interesting and we’d like to take a look. To help myself better understand, 
I wonder how the LFS files are downloaded (through which downloader, for example), and after downloading, where you put the downloaded LFS files? After having these information I can try to reproduce the issue.

On the other hand, could you make sure you are at the latest commit of mlc-llm? We fixed some issue of `InternalError: Check failed: (slot->value_computed) is false: PrimExpr T.int64(4) * v * T.int64(512) has not been computed` one week ago. Please let us know if the issue persists after updating to the latest commit.

**Comment by zuramai** [comment]
Thank you for the response @MasterJH5574

Apparently, the cause of this error is not because downloading via another downloader, I tried to build the model through downloading the model directly using `--hf-path` is also result in this error.

Command:
```
 python3 build.py --hf-path meta-llama/Llama-2-7b-chat-hf --target webgpu
```

I am using the latest commit of mlc-llm. This works in some model, but not in other models. It supposed to be fixed in https://github.com/apache/tvm/pull/14606 but it still does not work for me although I'm using the latest commit

Error:
```
> python3 build.py --hf-path meta-llama/Llama-2-7b-chat-hf --target webgpu
Updated Git hooks.
Git LFS initialized.
Cloning into 'dist/models/Llama-2-7b-chat-hf'...
remote: Enumerating objects: 79, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 79 (delta 32), reused 0 (delta 0), pack-reused 15
Unpacking objects: 100% (79/79), 978.36 KiB | 804.00 KiB/s, done.
Downloading model-00001-of-00002.safetensors (10 GB)
Downloading model-00002-of-00002.safetensors (3.5 GB)
Downloading pytorch_model-00001-of-00002.bin (10 GB)s
Downloading pytorch_model-00002-of-00002.bin (3.5 GB)
Filtering content: 100% (5/5), 9.10 GiB | 254.00 KiB/s, done.
Downloaded weights to dist/models/Llama-2-7b-chat-hf
Using path "dist/models/Llama-2-7b-chat-hf" for model "Llama-2-7b-chat-hf"
Target configured: webgpu -keys=webgpu,gpu -max_num_threads=256
[09:01:25] /Users/catalyst/Workspace/mlc-ai-package-self-runner/_work/package/package/tvm/src/runtime/metal/metal_device_api.mm:167: Intializing Metal device 0, name=Apple M2 Pro
Host CPU dection:
  Target triple: arm64-apple-darwin22.3.0
  Process triple: arm64-apple-darwin22.3.0
  Host CPU: apple-m1
Automatically using target for weight quantization: metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32
[09:01:26] /Users/catalyst/Workspace/mlc-ai-package-self-runner/_work/package/package/tvm/src/relax/ir/block_builder.cc:64: Warning: BlockBuilder destroyed with remaining blocks!
Traceback (most recent call last):
  File "/Users/zuramai/Code/LLM/mlc-llm/build.py", line 4, in <module>
    main()
  File "/Users/zuramai/Code/LLM/mlc-llm/mlc_llm/build.py", line 10, in main
    core.build_model_from_args(parsed_args)
  File "/Users/zuramai/Code/LLM/mlc-llm/mlc_llm/core.py", line 611, in build_model_from_args
    new_params = utils.convert_weights(param_manager, params, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zuramai/Code/LLM/mlc-llm/mlc_llm/utils.py", line 254, in convert_weights
    ex = relax.build(mod_transform, target=target)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tvm/relax/vm_build.py", line 321, in build
    new_mod = seq(mod)
              ^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tvm/ir/transform.py", line 238, in __call__
    return _ffi_transform_api.RunPass(self, mod)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm.error.InternalError: Traceback (most recent call last):
  File "/Users/catalyst/Workspace/mlc-ai-package-self-runner/_work/package/package/tvm/src/relax/backend/vm/vm_shape_lower.cc", line 360
InternalError: Check failed: (slot->value_computed) is false: PrimExpr T.int64(4) * v * T.int64(512) has not been computed
```

**Comment by MasterJH5574** [comment]
Sorry @zuramai I tried for a few times and was not able to reproduce the issue. Here is the log when I run the command
```
~/Workspace/mlc-llm @5a4db2ee *2 ❯ python3 build.py --hf-path meta-llama/Llama-2-7b-chat-hf --target webgpu
Updated Git hooks.
Git LFS initialized.
Cloning into 'dist/models/Llama-2-7b-chat-hf'...
Username for 'https://huggingface.co': ruihanglai
Password for 'https://ruihanglai@huggingface.co':
remote: Enumerating objects: 79, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 79 (delta 32), reused 0 (delta 0), pack-reused 15
Unpacking objects: 100% (79/79), 978.36 KiB | 8.08 MiB/s, done.
Username for 'https://huggingface.co': ruihanglai
Password for 'https://ruihanglai@huggingface.co':
Filtering content: 100% (5/5), 9.10 GiB | 31.00 MiB/s, done.
Downloaded weights to dist/models/Llama-2-7b-chat-hf
Using path "dist/models/Llama-2-7b-chat-hf" for model "Llama-2-7b-chat-hf"
Target configured: webgpu -keys=webgpu,gpu -max_num_threads=256
Load cached module from dist/Llama-2-7b-chat-hf-q4f16_1/mod_cache_before_build.pkl and skip tracing. You can use --use-cache=0 to retrace
[16:09:09] /Users/ruihang-macstudio/Workspace/tvm/src/target/llvm/codegen_llvm.cc:185: Warning: Set native vector bits to be 128 for wasm32
Finish exporting to dist/Llama-2-7b-chat-hf-q4f16_1/Llama-2-7b-chat-hf-q4f16_1-webgpu.wasm
```

Could you check if the TVM Unity you installed through pip is also the latest? I am not sure if this is a factor here. You can use `pip install --pre --force-reinstall mlc-ai-nightly mlc-chat-nightly -f https://mlc.ai/wheels` to update TVM Unity.

**Comment by zuramai** [comment]
Thank you, @MasterJH5574. The reinstall command you providing is working.

```
pip install --pre --force-reinstall mlc-ai-nightly mlc-chat-nightly -f https://mlc.ai/wheels
```
