### ISSUE TITLE
[Question] Chatglm-6b is not supported yet?

### ISSUE THREAD

**Issue by wangxu569** [mlc-ai/mlc-llm#928]
## ❓ General Questions

Using path "dist/models/chatglm-6b" for model "chatglm-6b"
Target configured: cuda -keys=cuda,gpu -arch=sm_86 -max_num_threads=1024 -max_shared_memory_per_block=49152 -max_threads_per_block=1024 -registers_per_block=65536 -thread_warp_size=32
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/test/mlc-llm/mlc_llm/build.py", line 13, in <module>
    main()
  File "/home/test/mlc-llm/mlc_llm/build.py", line 10, in main
    core.build_model_from_args(parsed_args)
  File "/home/test/mlc-llm/mlc_llm/core.py", line 602, in build_model_from_args
    mod, param_manager, params, model_config = chatglm.get_model(args, config)
  File "/home/test/mlc-llm/mlc_llm/relax_model/chatglm.py", line 834, in get_model
    raise ValueError(f"Unsupported model {model}")
ValueError: Unsupported model chatglm-6b

compile cmd:  python3 -m mlc_llm.build --model chatglm-6b --target cuda --quantization q4f16_1

**Comment by davidpissarra** [comment]
As of #624, MLC supports the latest version of ChatGLM, the [ChatGLM2](https://huggingface.co/THUDM/chatglm2-6b). The first version is not supported due to slight differences in the architecture.
