### ISSUE TITLE
[Bug] convert LLama2-13b TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by KiwiHana** [mlc-ai/mlc-llm#932]
NV3060 6GB
cuda12.1

```
$ python build.py --model ../Llama-2-13b-chat-hf --target c
uda --quantization q4f16_1 --artifact-path "./dist_13b" --use-cache 0 --max-seq-len 512

Using path "../llama-2-13b-chat-hf" for model "llama-2-13b-chat-hf"
Target configured: cuda -keys=cuda,gpu -arch=sm_86 -max_num_threads=1024 -max_shared_memory_per_block=49152 -max_threads_per_block=1024 -registers_per_block=65536 -thread_warp_size=32
Automatically using target for weight quantization: cuda -keys=cuda,gpu -arch=sm_86 -max_num_threads=1024 -max_shared_memory_per_block=49152 -max_threads_per_block=1024 -registers_per_block=65536 -thread_warp_size=32
Start computing and quantizing weights... This may take a while.
Traceback (most recent call last):
  File "/mnt/c/kiwi/llm/llama2/mlc-llm/build.py", line 4, in <module>
    main()
  File "/mnt/c/kiwi/llm/llama2/mlc-llm/mlc_llm/build.py", line 10, in main
    core.build_model_from_args(parsed_args)
  File "/mnt/c/kiwi/llm/llama2/mlc-llm/mlc_llm/core.py", line 611, in build_model_from_args
    new_params = utils.convert_weights(param_manager, params, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/kiwi/llm/llama2/mlc-llm/mlc_llm/utils.py", line 257, in convert_weights
    vm["transform_params"]()
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/home/kiwi/miniconda3/envs/mlc-py11/lib/python3.11/site-packages/tvm/_ffi/base.py", line 476, in raise_last_ffi_error
    raise py_err
  File "tvm/_ffi/_cython/./packed_func.pxi", line 56, in tvm._ffi._cy3.core.tvm_callback
  File "/mnt/c/kiwi/llm/llama2/mlc-llm/mlc_llm/relax_model/param_manager.py", line 560, in get_item
    cached_relax_params[i] = self.f_compute_relax_param(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/kiwi/llm/llama2/mlc-llm/mlc_llm/relax_model/llama.py", line 950, in f_compute_relax_param
    assert k.shape == (kv_heads * head_dim, hidden_size)
                       ~~~~~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by junrushao** [comment]
I think you are using the old Llama1 instead of Llama2. In this case, the field `num_key_value_heads` is not available in `config.json`, leading to this issue. A fix: https://github.com/mlc-ai/mlc-llm/pull/933

**Comment by KiwiHana** [comment]
> I think you are using the old Llama1 instead of Llama2. In this case, the field `num_key_value_heads` is not available in `config.json`, leading to this issue. A fix: #933

Model download from https://huggingface.co/meta-llama/Llama-2-13b-chat-hf
Does MLC support this model?

**Comment by junrushao** [comment]
Can you check if the fix works for you?

**Comment by KiwiHana** [comment]
Yes, it work!
