### ISSUE TITLE
[Bug] using q4f16_ft quantization results in `Check failed: (!block_stack_.empty()) is false: no block is being built`

### ISSUE THREAD

**Issue by dusty-nv** [mlc-ai/mlc-llm#937]
## 🐛 Bug

Unable to run q4f16_ft quantization on any llama models.   CUTLASS is enabled in the build.  Is there a proper way to use it?

## To Reproduce

```
python3 -m mlc_llm.build --model Llama-2-7b-chat-hf --target cuda --quantization q4f16_ft

Using path "dist/models/Llama-2-7b-chat-hf" for model "Llama-2-7b-chat-hf"
Target configured: cuda -keys=cuda,gpu -arch=sm_87 -max_num_threads=1024 -max_shared_memory_per_block=49152 -max_threads_per_block=1024 -registers_per_block=65536 -thread_warp_size=32
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mlc_llm/build.py", line 13, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/mlc_llm/build.py", line 10, in main
    core.build_model_from_args(parsed_args)
  File "/usr/local/lib/python3.8/dist-packages/mlc_llm/core.py", line 638, in build_model_from_args
    mod = mod_transform_before_build(mod, param_manager, args, model_config)
  File "/usr/local/lib/python3.8/dist-packages/mlc_llm/core.py", line 370, in mod_transform_before_build
    mod = param_manager.transform_dequantize(mod)
  File "/usr/local/lib/python3.8/dist-packages/mlc_llm/relax_model/param_manager.py", line 366, in transform_dequantize
    "params", self.get_quantized_param_info(gv.name_hint)
  File "/usr/local/lib/python3.8/dist-packages/mlc_llm/relax_model/param_manager.py", line 429, in get_quantized_param_info
    quantized_data = bb.normalize(f_quantize(bb, provided_tensor_vars))
  File "/usr/local/lib/python3.8/dist-packages/mlc_llm/quantization/ft_rowwise_quantization.py", line 40, in f_quantize
    encoded_data = bb.emit_te(
  File "/usr/local/lib/python3.8/dist-packages/tvm/relax/block_builder.py", line 525, in emit_te
    return self.emit(self.call_te(func, *args, **kwargs), name_hint=name_hint)
  File "/usr/local/lib/python3.8/dist-packages/tvm/relax/block_builder.py", line 308, in emit
    return _ffi_api.BlockBuilderEmit(self, expr, name_hint)  # type: ignore
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/usr/local/lib/python3.8/dist-packages/tvm/_ffi/base.py", line 476, in raise_last_ffi_error
    raise py_err
tvm.error.InternalError: Traceback (most recent call last):
  [bt] (5) /usr/local/lib/python3.8/dist-packages/tvm/libtvm.so(TVMFuncCall+0x64) [0xffff85cc44b4]
  [bt] (4) /usr/local/lib/python3.8/dist-packages/tvm/libtvm.so(+0x1719fb4) [0xffff84104fb4]
  [bt] (3) /usr/local/lib/python3.8/dist-packages/tvm/libtvm.so(tvm::relax::BlockBuilderImpl::Emit(tvm::RelayExpr, tvm::runtime::String)+0xc8) [0xffff84111350]
  [bt] (2) /usr/local/lib/python3.8/dist-packages/tvm/libtvm.so(+0x17173fc) [0xffff841023fc]
  [bt] (1) /usr/local/lib/python3.8/dist-packages/tvm/libtvm.so(tvm::runtime::detail::LogFatal::Entry::Finalize()+0x78) [0xffff839f7588]
  [bt] (0) /usr/local/lib/python3.8/dist-packages/tvm/libtvm.so(tvm::runtime::Backtrace[abi:cxx11]()+0x30) [0xffff85d08530]
  File "/opt/mlc-llm/3rdparty/tvm/src/relax/ir/block_builder.cc", line 321
InternalError: Check failed: (!block_stack_.empty()) is false: no block is being built
```

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):  CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):  Ubuntu 20.04
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)   Jetson AGX Orin
 - How you installed MLC-LLM (`conda`, source):  source
 - How you installed TVM-Unity (`pip`, source):  source
 - Python version (e.g. 3.10):  3.8
 - GPU driver version (if applicable):  JetPack 5.1.2
 - CUDA/cuDNN version (if applicable):  CUDA 11.4
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):  `631f37b6bf8b101d16ecc55de7e6a749a3588570`
 - Any other relevant information:

## Additional context

I am hoping that using FasterTransformer has additional performance optimizations

**Comment by junrushao** [comment]
FasterTransformer is slower than our default approach actually, at least on the hardwares we tested (3090Ti, 4090 and A100) :)

**Comment by junrushao** [comment]
Perhaps @masahi could take a look

**Comment by dusty-nv** [comment]
Aha okay, thanks @junrushao , good to know!   I will not get hung up on it and continue using q4f16_1 quantization.

**Comment by masahi** [comment]
It will be fixed by https://github.com/mlc-ai/mlc-llm/pull/917

**Comment by MasterJH5574** [comment]
#917 is merged. Please check if the issue persists, thanks!
