### ISSUE TITLE
[Bug] Llama-2-7b-chat-hf-q4f16_1-vulkan.so: invalid ELF header

### ISSUE THREAD

**Issue by KiwiHana** [mlc-ai/mlc-llm#948]
```
$ python benchmark.py
Traceback (most recent call last):
  File "/home/mlc-llm/benchmark.py", line 3, in <module>
    cm = ChatModule(model="./dist/Llama-2-7b-chat-hf-q4f16_1/params/", lib_path="./dist/Llama-2-7b-chat-hf-q4f16_1/Llama-2-7b-chat-hf-q4f16_1-vulkan.so")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a770/miniconda3/envs/mlc-llm/lib/python3.11/site-packages/mlc_chat/chat_module.py", line 603, in __init__
    self._reload(self.lib_path, self.model_path, user_chat_config_json_str)
  File "/home/a770/miniconda3/envs/mlc-llm/lib/python3.11/site-packages/mlc_chat/chat_module.py", line 784, in _reload
    self._reload_func(lib, model_path, app_config_json)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/home/a770/miniconda3/envs/mlc-llm/lib/python3.11/site-packages/tvm/_ffi/base.py", line 476, in raise_last_ffi_error
    raise py_err
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 1175, in mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 475, in mlc::llm::LLMChat::Reload(tvm::runtime::String, tvm::runtime::String, tvm::runtime::String)
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 182, in Init
tvm.error.InternalError: Traceback (most recent call last):
  7: mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
        at /workspace/mlc-llm/cpp/llm_chat.cc:1175
  6: mlc::llm::LLMChat::Reload(tvm::runtime::String, tvm::runtime::String, tvm::runtime::String)
        at /workspace/mlc-llm/cpp/llm_chat.cc:475
  5: Init
        at /workspace/mlc-llm/cpp/llm_chat.cc:182
  4: tvm::runtime::Module::LoadFromFile(tvm::runtime::String const&, tvm::runtime::String const&)
  3: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::__mk_TVM0::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::__mk_TVM0, tvm::runtime::TVMRetValue)
  2: tvm::runtime::CreateDSOLibraryObject(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
  1: tvm::runtime::DSOLibrary::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  0: _ZN3tvm7runtime6deta
  File "/workspace/tvm/src/runtime/dso_library.cc", line 125
InternalError: Check failed: (lib_handle_ != nullptr) is false: Failed to load dynamic shared library ./dist/Llama-2-7b-chat-hf-q4f16_1/Llama-2-7b-chat-hf-q4f16_1-vulkan.so ./dist/Llama-2-7b-chat-hf-q4f16_1/Llama-2-7b-chat-hf-q4f16_1-vulkan.so: invalid ELF header
```

**Comment by junrushao** [comment]
"invalid ELF header" is pretty indicative of what is happening under the hood - for example, it happens most when you are loading an x86 shared library on an ARM machine, or an ARM shared library on an x86 machine. Could you share more info on how you obtained `Llama-2-7b-chat-hf-q4f16_1-vulkan.so` and which architecture your hardware is>

**Comment by KiwiHana** [comment]
> "invalid ELF header" is pretty indicative of what is happening under the hood - for example, it happens most when you are loading an x86 shared library on an ARM machine, or an ARM shared library on an x86 machine. Could you share more info on how you obtained `Llama-2-7b-chat-hf-q4f16_1-vulkan.so` and which architecture your CPU is?

Hi Junru, I obtained `Llama-2-7b-chat-hf-q4f16_1-vulkan.so` from https://github.com/mlc-ai/binary-mlc-llm-libs
My CPU is ADL 12700, DGPU is Arc A770

**Comment by KiwiHana** [comment]
Hi Junru, I use this command to compile, but get error.

```
$ python build.py --model /LLM/Llama-2-7b-chat-hf/ --target vulkan --quantization q4f16_1 --artifact-path "./dist" --use-cache 0 --max-seq-len 1024
Using path "/LLM/Llama-2-7b-chat-hf" for model "Llama-2-7b-chat-hf"
Target configured: vulkan -keys=vulkan,gpu -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=256 -supports_16bit_buffer=1 -supports_8bit_buffer=1 -supports_float16=1 -supports_float32=1 -supports_int16=1 -supports_int32=1 -supports_int8=1 -supports_storage_buffer_storage_class=1 -thread_warp_size=1
Automatically using target for weight quantization: vulkan -keys=vulkan,gpu -max_num_threads=256 -max_shared_memory_per_block=65536 -max_threads_per_block=1024 -supports_16bit_buffer=1 -supports_float16=1 -supports_float32=1 -supports_int16=1 -supports_int32=1 -supports_int8=1 -thread_warp_size=1
Traceback (most recent call last):
  File "/home/a770/Downloads/kiwi/mlc-llm/build.py", line 4, in <module>
    main()
  File "/home/a770/Downloads/kiwi/mlc-llm/mlc_llm/build.py", line 10, in main
    core.build_model_from_args(parsed_args)
  File "/home/a770/Downloads/kiwi/mlc-llm/mlc_llm/core.py", line 616, in build_model_from_args
    new_params = utils.convert_weights(param_manager, params, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a770/Downloads/kiwi/mlc-llm/mlc_llm/utils.py", line 254, in convert_weights
    ex = relax.build(mod_transform, target=target)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a770/miniconda3/envs/mlc-llm/lib/python3.11/site-packages/tvm/relax/vm_build.py", line 338, in build
    return _vmlink(builder, target, tir_mod, ext_libs, params, system_lib=system_lib)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a770/miniconda3/envs/mlc-llm/lib/python3.11/site-packages/tvm/relax/vm_build.py", line 242, in _vmlink
    lib = tvm.build(
          ^^^^^^^^^^
  File "/home/a770/miniconda3/envs/mlc-llm/lib/python3.11/site-packages/tvm/driver/build_module.py", line 281, in build
    rt_mod_host = _driver_ffi.tir_to_runtime(annotated_mods, target_host)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/home/a770/miniconda3/envs/mlc-llm/lib/python3.11/site-packages/tvm/_ffi/base.py", line 476, in raise_last_ffi_error
    raise py_err
tvm.error.InternalError: Traceback (most recent call last):
  10: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::runtime::Module (tvm::runtime::Map<tvm::Target, tvm::IRModule, void, void> const&, tvm::Target)>::AssignTypedLambda<tvm::__mk_TVM22::{lambda(tvm::runtime::Map<tvm::Target, tvm::IRModule, void, void> const&, tvm::Target)#1}>(tvm::__mk_TVM22::{lambda(tvm::runtime::Map<tvm::Target, tvm::IRModule, void, void> const&, tvm::Target)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::runtime::TVMRetValue)
  9: tvm::TIRToRuntime(tvm::runtime::Map<tvm::Target, tvm::IRModule, void, void> const&, tvm::Target const&)
  8: tvm::codegen::Build(tvm::IRModule, tvm::Target)
  7: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::runtime::Module (tvm::IRModule, tvm::Target)>::AssignTypedLambda<tvm::codegen::__mk_TVM0::{lambda(tvm::IRModule, tvm::Target)#1}>(tvm::codegen::__mk_TVM0::{lambda(tvm::IRModule, tvm::Target)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::runtime::TVMRetValue)
  6: tvm::codegen::BuildSPIRV(tvm::IRModule, tvm::Target)
  5: tvm::codegen::LowerToSPIRV[abi:cxx11](tvm::IRModule, tvm::Target)
  4: tvm::codegen::CodeGenSPIRV::BuildFunction(tvm::tir::PrimFunc const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  3: tvm::codegen::spirv::IRBuilder::GetSType(tvm::runtime::DataType const&, unsigned int, unsigned int)
  2: tvm::codegen::spirv::IRBuilder::DeclareType(tvm::runtime::DataType const&, unsigned int, unsigned int)
  1: tvm::codegen::spirv::IRBuilder::AddCapabilityFor(tvm::runtime::DataType const&)
  0: _ZN3tvm7runtime6deta
  File "/workspace/tvm/src/target/spirv/ir_builder.cc", line 556
InternalError: Check failed: (spirv_support_.supports_int64) is false: Vulkan target does not support Int64 capability.  If your device supports 64-bit int operations, please either add -supports_int64=1 to the target, or query all device parameters by adding -from_device=0.
```

**Comment by junrushao** [comment]
This is an issue that we are using int64 as integer types in most of the cases, which may or may not be well supported by Vulkan. I just submitted a fix for Index dGPU and let me know if it works for you: https://github.com/mlc-ai/mlc-llm/pull/950.

**Comment by KiwiHana** [comment]
> This is an issue that we are using int64 as integer types in most of the cases, which may or may not be well supported by Vulkan. I just submitted a fix for Index dGPU and let me know if it works for you: #950.

Yes, it work! Thanks🙂
