### ISSUE TITLE
[Bug] Disco breaks with custom `repetition_penalty`

### ISSUE THREAD

**Issue by sunggg** [mlc-ai/mlc-llm#976]
## 🐛 Bug

Faced the following error when using `repetition_penalty=1.6` with `num_shards=2`. This error did not occur with `num_shards=1`. 

## To Reproduce

1. Build your model with `num_shard=2`
2. Run the following script with custom `repetition_penalty`.
``` 
from mlc_chat import ChatModule
from mlc_chat.chat_module import ChatConfig
cm = ChatModule(model="codellama-34b-instruct-hf-s2q0f16", chat_config=ChatConfig(
                    repetition_penalty = 1.6
                ))

output = cm.benchmark_generate("What's the meaning of life?", generate_length=256)
```
3. Meet the error
```
Traceback (most recent call last):
  File "examples/python/benchmark.py", line 12, in <module>
    output = cm.benchmark_generate("What's the meaning of life?", generate_length=256)
  File "/home/spark/mlc-llm/python/mlc_chat/chat_module.py", line 767, in benchmark_generate
    self._prefill(prompt)
  File "/home/spark/mlc-llm/python/mlc_chat/chat_module.py", line 808, in _prefill
    self._prefill_func(input, decode_next_token, place_in_prompt.value)
  File "/home/spark/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "/home/spark/tvm/python/tvm/_ffi/base.py", line 476, in raise_last_ffi_error
    raise py_err
  File "/home/spark/mlc-llm/cpp/llm_chat.cc", line 1254, in mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#5}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
    GetChat()->PrefillStep(args[0], true, args[1], place_in_prompt);
  File "/home/spark/mlc-llm/cpp/llm_chat.cc", line 781, in mlc::llm::LLMChat::PrefillStep(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool, mlc::llm::PlaceInPrompt)
    NDArray logits_on_device = this->ForwardTokens(prompt_tokens, new_seq_len);
  File "/home/spark/mlc-llm/cpp/llm_chat.cc", line 1007, in mlc::llm::LLMChat::ForwardTokens(std::vector<int, std::allocator<int> >, long)
    ret = ft_.prefill_func_(input_data, cur_pos_shape, kv_cache_, params_);
tvm._ffi.base.TVMError: Traceback (most recent call last):
  8: mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#5}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
        at /home/spark/mlc-llm/cpp/llm_chat.cc:1254
  7: mlc::llm::LLMChat::PrefillStep(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool, mlc::llm::PlaceInPrompt)
        at /home/spark/mlc-llm/cpp/llm_chat.cc:781
  6: mlc::llm::LLMChat::ForwardTokens(std::vector<int, std::allocator<int> >, long)
        at /home/spark/mlc-llm/cpp/llm_chat.cc:1007
  5: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  4: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::relax_vm::VirtualMachineImpl::GetClosureInternal(tvm::runtime::String const&, bool)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  3: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
  2: tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
  1: tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
  0: tvm::runtime::relax_vm::MatchShape(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  File "/home/spark/tvm/src/runtime/relax_vm/builtin.cc", line 101
RuntimeError: Check failed: input_shape[i] == reg (10240 vs. 5120) : ErrorContext(fn=prefill, loc=param[3], param=params, annotation=R.Tuple(R.Tensor((v, 8192), dtype="float16"), R.Tensor((5120, 8192), dtype="float16"), R.Tensor((8192, 4096), dtype="float16"), R.Tensor((22016, 8192), dtype="float16"),
```

## Expected behavior

Run without error. 

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu 20.04.5 LTS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): A100
 - How you installed MLC-LLM (`conda`, source): source. commit `5a4db2ee9be3713a0035d7a677f9e4cbc10cb15b`
 - How you installed TVM-Unity (`pip`, source): source. tvm unity commit `9fd45741e818ad0fa41bd0305fc1552c29649976`
 - Python version (e.g. 3.10): `Python 3.8.17`
 - GPU driver version (if applicable): `525.105.17`
 - CUDA/cuDNN version (if applicable): `cuda_11.8.r11.8/`
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
```
USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU: OFF
CUDA_VERSION: 11.8
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: OFF
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: ON
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: ON
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: 9fd45741e818ad0fa41bd0305fc1552c29649976
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: ON
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2023-09-20 09:45:33 -0400
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: ON
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 10.0.0
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: none
USE_BNNS: OFF
USE_CUBLAS: ON
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION: 
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /usr/bin/c++
HIDE_PRIVATE_SYMBOLS: OFF
```
 - Any other relevant information:

**Comment by jinhongyii** [comment]
fixed in #1002
