### ISSUE TITLE
wsl build vicuna failed and throw mismatch_cast  error

### ISSUE THREAD

**Issue by shuyaoyimei** [mlc-ai/mlc-llm#98]
env:
```
os: win11 sub system wsl2 ubuntu
ram:64G
swap:24g
model:vicuna-v1-7b
tvm-backend:relax
```
build code:
```python3 build.py --model vicuna-v1-7b --dtype float16 --target auto --quantization-mode int3 --quantization-sym --quantization-storage-nbit 16 --max-seq-len 768```
error:
```
File "build.py", line 271, in <module>
    mod = mod_transform_before_build(mod, params, ARGS)
  File "build.py", line 219, in mod_transform_before_build
    new_params = utils.transform_params(mod_transform, model_params)
  File "~/mlc-llm/mlc_llm/utils.py", line 107, in transform_params
    res = vm[transform_func_name](model_params)
  File "~/relax/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  6: TVMFuncCall
  5: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  4: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::relax_vm::VirtualMachineImpl::GetClosureInternal(tvm::runtime::String const&, bool)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  3: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
  2: tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
  1: tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
  0: tvm::runtime::relax_vm::MatchShape(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  File "~/relax/src/runtime/relax_vm/builtin.cc", line 101
RuntimeError: Check failed: input_shape[i] == reg (32001 vs. 32000) : ErrorContext(fn=encoding_transform_params, loc=param[0], param=params, annotation=R.Tuple(**some shape info** )  match_cast error,  shape[0] mismatch to specified constant
```

I have located the error to a specific function called `Rewrite` within the `vm_shape_lower` class in the `relax` source code. 
The error seems to be caused by an `input` shape that doesn't match the expected shape within the `match_todos` variable. 
However, I'm having trouble understanding how the `input` is getting into `match_todos`. 
Has anyone faced a similar issue before or could suggest any debugging tips?

**Comment by junrushao** [comment]
Thanks for reporting this issue though!
